#import <Foundation/Foundation.h>
@interface -deleteCommentsGPUImageFilterJ: NSObject
+ (BOOL)OInitwithvertexshaderfromstringyFragmentshaderfromstring:(NSInteger)-deleteComments;
+ (BOOL)oInitwithfragmentshaderfromstring:(NSInteger)-deleteComments;
+ (BOOL)mInitwithfragmentshaderfromfile:(NSInteger)-deleteComments;
+ (BOOL)minit:(NSInteger)-deleteComments;
+ (BOOL)JinitializeAttributes:(NSInteger)-deleteComments;
+ (BOOL)gSetupfilterforsize:(NSInteger)-deleteComments;
+ (BOOL)Hdealloc:(NSInteger)-deleteComments;
+ (BOOL)JuseNextFrameForImageCapture:(NSInteger)-deleteComments;
+ (BOOL)DnewCGImageFromCurrentlyProcessedOutput:(NSInteger)-deleteComments;
+ (BOOL)BsizeOfFBO:(NSInteger)-deleteComments;
+ (BOOL)mTexturecoordinatesforrotation:(NSInteger)-deleteComments;
+ (BOOL)BRendertotexturewithverticeseTexturecoordinates:(NSInteger)-deleteComments;
+ (BOOL)YInformtargetsaboutnewframeattime:(NSInteger)-deleteComments;
+ (BOOL)soutputFrameSize:(NSInteger)-deleteComments;
+ (BOOL)DSetbackgroundcolorredEGreenhBluenAlpha:(NSInteger)-deleteComments;
+ (BOOL)cSetintegercForuniformname:(NSInteger)-deleteComments;
+ (BOOL)RSetfloatFForuniformname:(NSInteger)-deleteComments;
+ (BOOL)JSetsizeQForuniformname:(NSInteger)-deleteComments;
+ (BOOL)ySetpointpForuniformname:(NSInteger)-deleteComments;
+ (BOOL)SSetfloatvec3fForuniformname:(NSInteger)-deleteComments;
+ (BOOL)hSetfloatvec4qForuniform:(NSInteger)-deleteComments;
+ (BOOL)bSetfloatarraykLengthSForuniform:(NSInteger)-deleteComments;
+ (BOOL)ZSetmatrix3FIForuniformSProgram:(NSInteger)-deleteComments;
+ (BOOL)USetmatrix4FdForuniformgProgram:(NSInteger)-deleteComments;
+ (BOOL)zSetfloatUForuniformnProgram:(NSInteger)-deleteComments;
+ (BOOL)VSetpointRForuniformUProgram:(NSInteger)-deleteComments;
+ (BOOL)ESetsizeKForuniformBProgram:(NSInteger)-deleteComments;
+ (BOOL)BSetvec3PForuniformfProgram:(NSInteger)-deleteComments;
+ (BOOL)hSetvec4lForuniformEProgram:(NSInteger)-deleteComments;
+ (BOOL)WSetfloatarrayoLengthHForuniformCProgram:(NSInteger)-deleteComments;
+ (BOOL)dSetintegerwForuniformGProgram:(NSInteger)-deleteComments;
+ (BOOL)ASetandexecuteuniformstatecallbackatindexjForprogramHToblock:(NSInteger)-deleteComments;
+ (BOOL)oSetuniformsforprogramatindex:(NSInteger)-deleteComments;
+ (BOOL)kNewframereadyattimeRAtindex:(NSInteger)-deleteComments;
+ (BOOL)SnextAvailableTextureIndex:(NSInteger)-deleteComments;
+ (BOOL)GSetinputframebufferWAtindex:(NSInteger)-deleteComments;
+ (BOOL)gRotatedsizeYForindex:(NSInteger)-deleteComments;
+ (BOOL)uRotatedpointgForrotation:(NSInteger)-deleteComments;
+ (BOOL)fSetinputsizepAtindex:(NSInteger)-deleteComments;
+ (BOOL)uSetinputrotationmAtindex:(NSInteger)-deleteComments;
+ (BOOL)EForceprocessingatsize:(NSInteger)-deleteComments;
+ (BOOL)LForceprocessingatsizerespectingaspectratio:(NSInteger)-deleteComments;
+ (BOOL)DmaximumOutputSize:(NSInteger)-deleteComments;
+ (BOOL)hendProcessing:(NSInteger)-deleteComments;
+ (BOOL)LwantsMonochromeInput:(NSInteger)-deleteComments;

@end
