#import <Foundation/Foundation.h>
@interface -deleteCommentsGPUImageFilteru: NSObject
+ (BOOL)lInitwithvertexshaderfromstringiFragmentshaderfromstring:(NSInteger)-deleteComments;
+ (BOOL)sInitwithfragmentshaderfromstring:(NSInteger)-deleteComments;
+ (BOOL)LInitwithfragmentshaderfromfile:(NSInteger)-deleteComments;
+ (BOOL)uinit:(NSInteger)-deleteComments;
+ (BOOL)cinitializeAttributes:(NSInteger)-deleteComments;
+ (BOOL)ySetupfilterforsize:(NSInteger)-deleteComments;
+ (BOOL)rdealloc:(NSInteger)-deleteComments;
+ (BOOL)LuseNextFrameForImageCapture:(NSInteger)-deleteComments;
+ (BOOL)rnewCGImageFromCurrentlyProcessedOutput:(NSInteger)-deleteComments;
+ (BOOL)ssizeOfFBO:(NSInteger)-deleteComments;
+ (BOOL)fTexturecoordinatesforrotation:(NSInteger)-deleteComments;
+ (BOOL)TRendertotexturewithverticestTexturecoordinates:(NSInteger)-deleteComments;
+ (BOOL)wInformtargetsaboutnewframeattime:(NSInteger)-deleteComments;
+ (BOOL)VoutputFrameSize:(NSInteger)-deleteComments;
+ (BOOL)WSetbackgroundcolorredPGreeniBlueUAlpha:(NSInteger)-deleteComments;
+ (BOOL)rSetintegerJForuniformname:(NSInteger)-deleteComments;
+ (BOOL)TSetfloatGForuniformname:(NSInteger)-deleteComments;
+ (BOOL)nSetsizeaForuniformname:(NSInteger)-deleteComments;
+ (BOOL)gSetpointOForuniformname:(NSInteger)-deleteComments;
+ (BOOL)LSetfloatvec3sForuniformname:(NSInteger)-deleteComments;
+ (BOOL)QSetfloatvec4CForuniform:(NSInteger)-deleteComments;
+ (BOOL)ESetfloatarrayhLengthaForuniform:(NSInteger)-deleteComments;
+ (BOOL)YSetmatrix3FvForuniformPProgram:(NSInteger)-deleteComments;
+ (BOOL)ISetmatrix4FIForuniformPProgram:(NSInteger)-deleteComments;
+ (BOOL)qSetfloatNForuniformPProgram:(NSInteger)-deleteComments;
+ (BOOL)wSetpointMForuniformaProgram:(NSInteger)-deleteComments;
+ (BOOL)ISetsizeTForuniformjProgram:(NSInteger)-deleteComments;
+ (BOOL)SSetvec3kForuniformRProgram:(NSInteger)-deleteComments;
+ (BOOL)JSetvec4zForuniformbProgram:(NSInteger)-deleteComments;
+ (BOOL)mSetfloatarrayQLengthrForuniformNProgram:(NSInteger)-deleteComments;
+ (BOOL)oSetintegerdForuniformbProgram:(NSInteger)-deleteComments;
+ (BOOL)RSetandexecuteuniformstatecallbackatindexFForprogramJToblock:(NSInteger)-deleteComments;
+ (BOOL)XSetuniformsforprogramatindex:(NSInteger)-deleteComments;
+ (BOOL)XNewframereadyattimeVAtindex:(NSInteger)-deleteComments;
+ (BOOL)LnextAvailableTextureIndex:(NSInteger)-deleteComments;
+ (BOOL)KSetinputframebufferCAtindex:(NSInteger)-deleteComments;
+ (BOOL)KRotatedsizeEForindex:(NSInteger)-deleteComments;
+ (BOOL)iRotatedpointqForrotation:(NSInteger)-deleteComments;
+ (BOOL)fSetinputsizeOAtindex:(NSInteger)-deleteComments;
+ (BOOL)KSetinputrotationpAtindex:(NSInteger)-deleteComments;
+ (BOOL)sForceprocessingatsize:(NSInteger)-deleteComments;
+ (BOOL)dForceprocessingatsizerespectingaspectratio:(NSInteger)-deleteComments;
+ (BOOL)GmaximumOutputSize:(NSInteger)-deleteComments;
+ (BOOL)XendProcessing:(NSInteger)-deleteComments;
+ (BOOL)jwantsMonochromeInput:(NSInteger)-deleteComments;

@end
