#import <Foundation/Foundation.h>
@interface -deleteCommentsGPUImageFilterK: NSObject
+ (BOOL)EInitwithvertexshaderfromstringfragmentshaderfromstringbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)uInitwithfragmentshaderfromstringbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)pInitwithfragmentshaderfromfilebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)iInitbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)iInitializeattributesbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)xSetupfilterforsizebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)VDeallocbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)wUsenextframeforimagecapturebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)vNewcgimagefromcurrentlyprocessedoutputbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)nSizeoffbobmbmbm:(NSInteger)-deleteComments;
+ (BOOL)aTexturecoordinatesforrotationbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)kRendertotexturewithverticestexturecoordinatesbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)qInformtargetsaboutnewframeattimebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)COutputframesizebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)bSetbackgroundcolorredgreenbluealphabmbmbm:(NSInteger)-deleteComments;
+ (BOOL)VSetintegerforuniformnamebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)vSetfloatforuniformnamebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)YSetsizeforuniformnamebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)uSetpointforuniformnamebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)NSetfloatvec3Foruniformnamebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)YSetfloatvec4Foruniformbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)DSetfloatarraylengthforuniformbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)NSetmatrix3Fforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)cSetmatrix4Fforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)USetfloatforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)JSetpointforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)DSetsizeforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)xSetvec3Foruniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)kSetvec4Foruniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)ISetfloatarraylengthforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)BSetintegerforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)SSetandexecuteuniformstatecallbackatindexforprogramtoblockbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)BSetuniformsforprogramatindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)dNewframereadyattimeatindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)oNextavailabletextureindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)zSetinputframebufferatindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)IRotatedsizeforindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)KRotatedpointforrotationbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)vSetinputsizeatindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)sSetinputrotationatindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)qForceprocessingatsizebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)nForceprocessingatsizerespectingaspectratiobmbmbm:(NSInteger)-deleteComments;
+ (BOOL)KMaximumoutputsizebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)YEndprocessingbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)lWantsmonochromeinputbmbmbm:(NSInteger)-deleteComments;

@end
