#import <Foundation/Foundation.h>
@interface -deleteCommentsGPUImageFilterN: NSObject
+ (BOOL)hInitwithvertexshaderfromstringfragmentshaderfromstringbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)eInitwithfragmentshaderfromstringbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)uInitwithfragmentshaderfromfilebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)zInitbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)kInitializeattributesbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)uSetupfilterforsizebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)EDeallocbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)PUsenextframeforimagecapturebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)pNewcgimagefromcurrentlyprocessedoutputbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)sSizeoffbobmbmbm:(NSInteger)-deleteComments;
+ (BOOL)ZTexturecoordinatesforrotationbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)tRendertotexturewithverticestexturecoordinatesbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)hInformtargetsaboutnewframeattimebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)TOutputframesizebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)GSetbackgroundcolorredgreenbluealphabmbmbm:(NSInteger)-deleteComments;
+ (BOOL)kSetintegerforuniformnamebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)ESetfloatforuniformnamebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)qSetsizeforuniformnamebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)vSetpointforuniformnamebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)OSetfloatvec3Foruniformnamebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)ASetfloatvec4Foruniformbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)ISetfloatarraylengthforuniformbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)sSetmatrix3Fforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)bSetmatrix4Fforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)KSetfloatforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)hSetpointforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)JSetsizeforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)JSetvec3Foruniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)oSetvec4Foruniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)OSetfloatarraylengthforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)KSetintegerforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)HSetandexecuteuniformstatecallbackatindexforprogramtoblockbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)rSetuniformsforprogramatindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)lNewframereadyattimeatindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)VNextavailabletextureindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)eSetinputframebufferatindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)VRotatedsizeforindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)QRotatedpointforrotationbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)BSetinputsizeatindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)hSetinputrotationatindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)oForceprocessingatsizebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)kForceprocessingatsizerespectingaspectratiobmbmbm:(NSInteger)-deleteComments;
+ (BOOL)qMaximumoutputsizebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)nEndprocessingbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)XWantsmonochromeinputbmbmbm:(NSInteger)-deleteComments;

@end
