#import <Foundation/Foundation.h>
@interface -deleteCommentsBMGPUImageFilterNI: NSObject
+ (BOOL)ZVinitwithvertexshaderfromstringfragmentshaderfromstringbm:(NSInteger)-deleteComments;
+ (BOOL)PYinitwithfragmentshaderfromstringbm:(NSInteger)-deleteComments;
+ (BOOL)EDinitwithfragmentshaderfromfilebm:(NSInteger)-deleteComments;
+ (BOOL)WKinitbm:(NSInteger)-deleteComments;
+ (BOOL)kSinitializeattributesbm:(NSInteger)-deleteComments;
+ (BOOL)tEsetupfilterforsizebm:(NSInteger)-deleteComments;
+ (BOOL)hZdeallocbm:(NSInteger)-deleteComments;
+ (BOOL)SJusenextframeforimagecapturebm:(NSInteger)-deleteComments;
+ (BOOL)eDnewcgimagefromcurrentlyprocessedoutputbm:(NSInteger)-deleteComments;
+ (BOOL)NCsizeoffbobm:(NSInteger)-deleteComments;
+ (BOOL)mDtexturecoordinatesforrotationbm:(NSInteger)-deleteComments;
+ (BOOL)fVrendertotexturewithverticestexturecoordinatesbm:(NSInteger)-deleteComments;
+ (BOOL)uOinformtargetsaboutnewframeattimebm:(NSInteger)-deleteComments;
+ (BOOL)QGoutputframesizebm:(NSInteger)-deleteComments;
+ (BOOL)vTsetbackgroundcolorredgreenbluealphabm:(NSInteger)-deleteComments;
+ (BOOL)UTsetintegerforuniformnamebm:(NSInteger)-deleteComments;
+ (BOOL)KWsetfloatforuniformnamebm:(NSInteger)-deleteComments;
+ (BOOL)XIsetsizeforuniformnamebm:(NSInteger)-deleteComments;
+ (BOOL)DVsetpointforuniformnamebm:(NSInteger)-deleteComments;
+ (BOOL)lVsetfloatvec3Foruniformnamebm:(NSInteger)-deleteComments;
+ (BOOL)UFsetfloatvec4Foruniformbm:(NSInteger)-deleteComments;
+ (BOOL)YKsetfloatarraylengthforuniformbm:(NSInteger)-deleteComments;
+ (BOOL)yIsetmatrix3Fforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)lPsetmatrix4Fforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)xAsetfloatforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)xFsetpointforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)kGsetsizeforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)ZXsetvec3Foruniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)PPsetvec4Foruniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)ZGsetfloatarraylengthforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)aIsetintegerforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)yHsetandexecuteuniformstatecallbackatindexforprogramtoblockbm:(NSInteger)-deleteComments;
+ (BOOL)ENsetuniformsforprogramatindexbm:(NSInteger)-deleteComments;
+ (BOOL)uXnewframereadyattimeatindexbm:(NSInteger)-deleteComments;
+ (BOOL)vSnextavailabletextureindexbm:(NSInteger)-deleteComments;
+ (BOOL)fJsetinputframebufferatindexbm:(NSInteger)-deleteComments;
+ (BOOL)VNrotatedsizeforindexbm:(NSInteger)-deleteComments;
+ (BOOL)PZrotatedpointforrotationbm:(NSInteger)-deleteComments;
+ (BOOL)JSsetinputsizeatindexbm:(NSInteger)-deleteComments;
+ (BOOL)GVsetinputrotationatindexbm:(NSInteger)-deleteComments;
+ (BOOL)AVforceprocessingatsizebm:(NSInteger)-deleteComments;
+ (BOOL)EQforceprocessingatsizerespectingaspectratiobm:(NSInteger)-deleteComments;
+ (BOOL)oYmaximumoutputsizebm:(NSInteger)-deleteComments;
+ (BOOL)dBendprocessingbm:(NSInteger)-deleteComments;
+ (BOOL)YPwantsmonochromeinputbm:(NSInteger)-deleteComments;

@end
