#import <Foundation/Foundation.h>
@interface -deleteCommentsGPUImageFilterD: NSObject
+ (BOOL)QInitwithvertexshaderfromstringPFragmentshaderfromstring:(NSInteger)-deleteComments;
+ (BOOL)vInitwithfragmentshaderfromstring:(NSInteger)-deleteComments;
+ (BOOL)KInitwithfragmentshaderfromfile:(NSInteger)-deleteComments;
+ (BOOL)Iinit:(NSInteger)-deleteComments;
+ (BOOL)ninitializeAttributes:(NSInteger)-deleteComments;
+ (BOOL)SSetupfilterforsize:(NSInteger)-deleteComments;
+ (BOOL)sdealloc:(NSInteger)-deleteComments;
+ (BOOL)JuseNextFrameForImageCapture:(NSInteger)-deleteComments;
+ (BOOL)fnewCGImageFromCurrentlyProcessedOutput:(NSInteger)-deleteComments;
+ (BOOL)xsizeOfFBO:(NSInteger)-deleteComments;
+ (BOOL)YTexturecoordinatesforrotation:(NSInteger)-deleteComments;
+ (BOOL)VRendertotexturewithverticespTexturecoordinates:(NSInteger)-deleteComments;
+ (BOOL)tInformtargetsaboutnewframeattime:(NSInteger)-deleteComments;
+ (BOOL)EoutputFrameSize:(NSInteger)-deleteComments;
+ (BOOL)YSetbackgroundcolorredeGreenZBluehAlpha:(NSInteger)-deleteComments;
+ (BOOL)ASetintegerrForuniformname:(NSInteger)-deleteComments;
+ (BOOL)rSetfloatwForuniformname:(NSInteger)-deleteComments;
+ (BOOL)tSetsizePForuniformname:(NSInteger)-deleteComments;
+ (BOOL)LSetpointBForuniformname:(NSInteger)-deleteComments;
+ (BOOL)bSetfloatvec3gForuniformname:(NSInteger)-deleteComments;
+ (BOOL)nSetfloatvec4bForuniform:(NSInteger)-deleteComments;
+ (BOOL)QSetfloatarrayzLengthwForuniform:(NSInteger)-deleteComments;
+ (BOOL)SSetmatrix3FMForuniformWProgram:(NSInteger)-deleteComments;
+ (BOOL)ISetmatrix4FNForuniformoProgram:(NSInteger)-deleteComments;
+ (BOOL)pSetfloatVForuniformAProgram:(NSInteger)-deleteComments;
+ (BOOL)uSetpointWForuniformTProgram:(NSInteger)-deleteComments;
+ (BOOL)pSetsizeoForuniformuProgram:(NSInteger)-deleteComments;
+ (BOOL)ASetvec3YForuniformYProgram:(NSInteger)-deleteComments;
+ (BOOL)JSetvec4oForuniformiProgram:(NSInteger)-deleteComments;
+ (BOOL)SSetfloatarraylLengthKForuniformBProgram:(NSInteger)-deleteComments;
+ (BOOL)MSetintegerLForuniformyProgram:(NSInteger)-deleteComments;
+ (BOOL)bSetandexecuteuniformstatecallbackatindexDForprogramrToblock:(NSInteger)-deleteComments;
+ (BOOL)YSetuniformsforprogramatindex:(NSInteger)-deleteComments;
+ (BOOL)GNewframereadyattimekAtindex:(NSInteger)-deleteComments;
+ (BOOL)UnextAvailableTextureIndex:(NSInteger)-deleteComments;
+ (BOOL)oSetinputframebuffercAtindex:(NSInteger)-deleteComments;
+ (BOOL)bRotatedsizeqForindex:(NSInteger)-deleteComments;
+ (BOOL)TRotatedpointrForrotation:(NSInteger)-deleteComments;
+ (BOOL)vSetinputsizeuAtindex:(NSInteger)-deleteComments;
+ (BOOL)GSetinputrotationrAtindex:(NSInteger)-deleteComments;
+ (BOOL)XForceprocessingatsize:(NSInteger)-deleteComments;
+ (BOOL)WForceprocessingatsizerespectingaspectratio:(NSInteger)-deleteComments;
+ (BOOL)hmaximumOutputSize:(NSInteger)-deleteComments;
+ (BOOL)wendProcessing:(NSInteger)-deleteComments;
+ (BOOL)GwantsMonochromeInput:(NSInteger)-deleteComments;

@end
