#import <Foundation/Foundation.h>
@interface -deleteCommentsNSDataZ: NSObject
+ (BOOL)kmd2String:(NSInteger)-deleteComments;
+ (BOOL)pmd2Data:(NSInteger)-deleteComments;
+ (BOOL)fmd4String:(NSInteger)-deleteComments;
+ (BOOL)bmd4Data:(NSInteger)-deleteComments;
+ (BOOL)nmd5String:(NSInteger)-deleteComments;
+ (BOOL)kmd5Data:(NSInteger)-deleteComments;
+ (BOOL)zsha1String:(NSInteger)-deleteComments;
+ (BOOL)nsha1Data:(NSInteger)-deleteComments;
+ (BOOL)Ssha224String:(NSInteger)-deleteComments;
+ (BOOL)Psha224Data:(NSInteger)-deleteComments;
+ (BOOL)ysha256String:(NSInteger)-deleteComments;
+ (BOOL)Gsha256Data:(NSInteger)-deleteComments;
+ (BOOL)Zsha384String:(NSInteger)-deleteComments;
+ (BOOL)tsha384Data:(NSInteger)-deleteComments;
+ (BOOL)dsha512String:(NSInteger)-deleteComments;
+ (BOOL)hsha512Data:(NSInteger)-deleteComments;
+ (BOOL)JHmacstringusingalgpWithkey:(NSInteger)-deleteComments;
+ (BOOL)vHmacdatausingalgCWithkey:(NSInteger)-deleteComments;
+ (BOOL)XHmacmd5Stringwithkey:(NSInteger)-deleteComments;
+ (BOOL)oHmacmd5Datawithkey:(NSInteger)-deleteComments;
+ (BOOL)ZHmacsha1Stringwithkey:(NSInteger)-deleteComments;
+ (BOOL)wHmacsha1Datawithkey:(NSInteger)-deleteComments;
+ (BOOL)XHmacsha224Stringwithkey:(NSInteger)-deleteComments;
+ (BOOL)mHmacsha224Datawithkey:(NSInteger)-deleteComments;
+ (BOOL)KHmacsha256Stringwithkey:(NSInteger)-deleteComments;
+ (BOOL)SHmacsha256Datawithkey:(NSInteger)-deleteComments;
+ (BOOL)vHmacsha384Stringwithkey:(NSInteger)-deleteComments;
+ (BOOL)NHmacsha384Datawithkey:(NSInteger)-deleteComments;
+ (BOOL)uHmacsha512Stringwithkey:(NSInteger)-deleteComments;
+ (BOOL)gHmacsha512Datawithkey:(NSInteger)-deleteComments;
+ (BOOL)Wcrc32String:(NSInteger)-deleteComments;
+ (BOOL)Dcrc32:(NSInteger)-deleteComments;
+ (BOOL)qAes256EncryptwithkeyhIv:(NSInteger)-deleteComments;
+ (BOOL)nAes256DecryptwithkeyHIv:(NSInteger)-deleteComments;
+ (BOOL)rutf8String:(NSInteger)-deleteComments;
+ (BOOL)qhexString:(NSInteger)-deleteComments;
+ (BOOL)NDatawithhexstring:(NSInteger)-deleteComments;
+ (BOOL)Fbase64EncodedString:(NSInteger)-deleteComments;
+ (BOOL)vDatawithbase64Encodedstring:(NSInteger)-deleteComments;
+ (BOOL)YjsonValueDecoded:(NSInteger)-deleteComments;
+ (BOOL)dgzipInflate:(NSInteger)-deleteComments;
+ (BOOL)JgzipDeflate:(NSInteger)-deleteComments;
+ (BOOL)dzlibInflate:(NSInteger)-deleteComments;
+ (BOOL)DzlibDeflate:(NSInteger)-deleteComments;
+ (BOOL)ZDatanamed:(NSInteger)-deleteComments;

@end
