#import <Foundation/Foundation.h>
@interface -deleteCommentsBMBMGPUImageFiltermfk: NSObject
+ (BOOL)uUjinitwithvertexshaderfromstringfragmentshaderfromstringbm:(NSInteger)-deleteComments;
+ (BOOL)PXpinitwithfragmentshaderfromstringbm:(NSInteger)-deleteComments;
+ (BOOL)KOlinitwithfragmentshaderfromfilebm:(NSInteger)-deleteComments;
+ (BOOL)XIfinitbm:(NSInteger)-deleteComments;
+ (BOOL)PVhinitializeattributesbm:(NSInteger)-deleteComments;
+ (BOOL)GBlsetupfilterforsizebm:(NSInteger)-deleteComments;
+ (BOOL)DPpdeallocbm:(NSInteger)-deleteComments;
+ (BOOL)oUousenextframeforimagecapturebm:(NSInteger)-deleteComments;
+ (BOOL)ZGnnewcgimagefromcurrentlyprocessedoutputbm:(NSInteger)-deleteComments;
+ (BOOL)oXesizeoffbobm:(NSInteger)-deleteComments;
+ (BOOL)jXwtexturecoordinatesforrotationbm:(NSInteger)-deleteComments;
+ (BOOL)GTorendertotexturewithverticestexturecoordinatesbm:(NSInteger)-deleteComments;
+ (BOOL)dDqinformtargetsaboutnewframeattimebm:(NSInteger)-deleteComments;
+ (BOOL)CVyoutputframesizebm:(NSInteger)-deleteComments;
+ (BOOL)mFzsetbackgroundcolorredgreenbluealphabm:(NSInteger)-deleteComments;
+ (BOOL)SCcsetintegerforuniformnamebm:(NSInteger)-deleteComments;
+ (BOOL)xTqsetfloatforuniformnamebm:(NSInteger)-deleteComments;
+ (BOOL)xQdsetsizeforuniformnamebm:(NSInteger)-deleteComments;
+ (BOOL)LOzsetpointforuniformnamebm:(NSInteger)-deleteComments;
+ (BOOL)dJgsetfloatvec3Foruniformnamebm:(NSInteger)-deleteComments;
+ (BOOL)BJmsetfloatvec4Foruniformbm:(NSInteger)-deleteComments;
+ (BOOL)ZUxsetfloatarraylengthforuniformbm:(NSInteger)-deleteComments;
+ (BOOL)qPhsetmatrix3Fforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)oNwsetmatrix4Fforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)xRusetfloatforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)HBbsetpointforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)NZtsetsizeforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)IRjsetvec3Foruniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)tVrsetvec4Foruniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)JEesetfloatarraylengthforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)MHfsetintegerforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)YGpsetandexecuteuniformstatecallbackatindexforprogramtoblockbm:(NSInteger)-deleteComments;
+ (BOOL)SVssetuniformsforprogramatindexbm:(NSInteger)-deleteComments;
+ (BOOL)rDjnewframereadyattimeatindexbm:(NSInteger)-deleteComments;
+ (BOOL)GRnnextavailabletextureindexbm:(NSInteger)-deleteComments;
+ (BOOL)HUusetinputframebufferatindexbm:(NSInteger)-deleteComments;
+ (BOOL)wQdrotatedsizeforindexbm:(NSInteger)-deleteComments;
+ (BOOL)uTrrotatedpointforrotationbm:(NSInteger)-deleteComments;
+ (BOOL)vMwsetinputsizeatindexbm:(NSInteger)-deleteComments;
+ (BOOL)tMtsetinputrotationatindexbm:(NSInteger)-deleteComments;
+ (BOOL)COkforceprocessingatsizebm:(NSInteger)-deleteComments;
+ (BOOL)bHoforceprocessingatsizerespectingaspectratiobm:(NSInteger)-deleteComments;
+ (BOOL)pHwmaximumoutputsizebm:(NSInteger)-deleteComments;
+ (BOOL)sObendprocessingbm:(NSInteger)-deleteComments;
+ (BOOL)lTmwantsmonochromeinputbm:(NSInteger)-deleteComments;

@end
