#import <Foundation/Foundation.h>
@interface -deleteCommentsBMBMGPUImageFiltermuf: NSObject
+ (BOOL)EIjinitwithvertexshaderfromstringfragmentshaderfromstringbmbm:(NSInteger)-deleteComments;
+ (BOOL)hEpinitwithfragmentshaderfromstringbmbm:(NSInteger)-deleteComments;
+ (BOOL)QAlinitwithfragmentshaderfromfilebmbm:(NSInteger)-deleteComments;
+ (BOOL)nVfinitbmbm:(NSInteger)-deleteComments;
+ (BOOL)iGhinitializeattributesbmbm:(NSInteger)-deleteComments;
+ (BOOL)FVlsetupfilterforsizebmbm:(NSInteger)-deleteComments;
+ (BOOL)jBpdeallocbmbm:(NSInteger)-deleteComments;
+ (BOOL)ELousenextframeforimagecapturebmbm:(NSInteger)-deleteComments;
+ (BOOL)eLnnewcgimagefromcurrentlyprocessedoutputbmbm:(NSInteger)-deleteComments;
+ (BOOL)FQesizeoffbobmbm:(NSInteger)-deleteComments;
+ (BOOL)XYwtexturecoordinatesforrotationbmbm:(NSInteger)-deleteComments;
+ (BOOL)GDorendertotexturewithverticestexturecoordinatesbmbm:(NSInteger)-deleteComments;
+ (BOOL)MPqinformtargetsaboutnewframeattimebmbm:(NSInteger)-deleteComments;
+ (BOOL)THyoutputframesizebmbm:(NSInteger)-deleteComments;
+ (BOOL)GEzsetbackgroundcolorredgreenbluealphabmbm:(NSInteger)-deleteComments;
+ (BOOL)FZcsetintegerforuniformnamebmbm:(NSInteger)-deleteComments;
+ (BOOL)QHqsetfloatforuniformnamebmbm:(NSInteger)-deleteComments;
+ (BOOL)qLdsetsizeforuniformnamebmbm:(NSInteger)-deleteComments;
+ (BOOL)cCzsetpointforuniformnamebmbm:(NSInteger)-deleteComments;
+ (BOOL)YCgsetfloatvec3Foruniformnamebmbm:(NSInteger)-deleteComments;
+ (BOOL)GXmsetfloatvec4Foruniformbmbm:(NSInteger)-deleteComments;
+ (BOOL)SAxsetfloatarraylengthforuniformbmbm:(NSInteger)-deleteComments;
+ (BOOL)BZhsetmatrix3Fforuniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)CRwsetmatrix4Fforuniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)iFusetfloatforuniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)eUbsetpointforuniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)wBtsetsizeforuniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)fGjsetvec3Foruniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)vUrsetvec4Foruniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)oKesetfloatarraylengthforuniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)qJfsetintegerforuniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)EJpsetandexecuteuniformstatecallbackatindexforprogramtoblockbmbm:(NSInteger)-deleteComments;
+ (BOOL)PXssetuniformsforprogramatindexbmbm:(NSInteger)-deleteComments;
+ (BOOL)wSjnewframereadyattimeatindexbmbm:(NSInteger)-deleteComments;
+ (BOOL)sSnnextavailabletextureindexbmbm:(NSInteger)-deleteComments;
+ (BOOL)jHusetinputframebufferatindexbmbm:(NSInteger)-deleteComments;
+ (BOOL)cMdrotatedsizeforindexbmbm:(NSInteger)-deleteComments;
+ (BOOL)cWrrotatedpointforrotationbmbm:(NSInteger)-deleteComments;
+ (BOOL)HCwsetinputsizeatindexbmbm:(NSInteger)-deleteComments;
+ (BOOL)WStsetinputrotationatindexbmbm:(NSInteger)-deleteComments;
+ (BOOL)wDkforceprocessingatsizebmbm:(NSInteger)-deleteComments;
+ (BOOL)mYoforceprocessingatsizerespectingaspectratiobmbm:(NSInteger)-deleteComments;
+ (BOOL)zGwmaximumoutputsizebmbm:(NSInteger)-deleteComments;
+ (BOOL)zYbendprocessingbmbm:(NSInteger)-deleteComments;
+ (BOOL)sOmwantsmonochromeinputbmbm:(NSInteger)-deleteComments;

@end
