#import <Foundation/Foundation.h>
@interface -deleteCommentsBMBMVIMVideoPlayervRY: NSObject
+ (BOOL)FMadealloc:(NSInteger)-deleteComments;
+ (BOOL)ZHkinit:(NSInteger)-deleteComments;
+ (BOOL)CHgsetupplayer:(NSInteger)-deleteComments;
+ (BOOL)TBksetupaudiosession:(NSInteger)-deleteComments;
+ (BOOL)KOsseturl:(NSInteger)-deleteComments;
+ (BOOL)VKysetplayeritem:(NSInteger)-deleteComments;
+ (BOOL)IPnsetasset:(NSInteger)-deleteComments;
+ (BOOL)JOqsetmuted:(NSInteger)-deleteComments;
+ (BOOL)MPeismuted:(NSInteger)-deleteComments;
+ (BOOL)YBmplay:(NSInteger)-deleteComments;
+ (BOOL)bWipause:(NSInteger)-deleteComments;
+ (BOOL)wVnseektotime:(NSInteger)-deleteComments;
+ (BOOL)JUfreset:(NSInteger)-deleteComments;
+ (BOOL)WTmenableairplay:(NSInteger)-deleteComments;
+ (BOOL)rZzdisableairplay:(NSInteger)-deleteComments;
+ (BOOL)MKrisairplayenabled:(NSInteger)-deleteComments;
+ (BOOL)yGastartscrubbing:(NSInteger)-deleteComments;
+ (BOOL)QVzscrub:(NSInteger)-deleteComments;
+ (BOOL)DDpstopscrubbing:(NSInteger)-deleteComments;
+ (BOOL)MMzenabletimeupdates:(NSInteger)-deleteComments;
+ (BOOL)gUvdisabletimeupdates:(NSInteger)-deleteComments;
+ (BOOL)rSqsetvolume:(NSInteger)-deleteComments;
+ (BOOL)SBgcancelfadevolume:(NSInteger)-deleteComments;
+ (BOOL)ZOifadeinvolume:(NSInteger)-deleteComments;
+ (BOOL)dSvfadeoutvolume:(NSInteger)-deleteComments;
+ (BOOL)lYsreportunabletocreateplayeritem:(NSInteger)-deleteComments;
+ (BOOL)KSkresetplayeritemifnecessary:(NSInteger)-deleteComments;
+ (BOOL)ZLhprepareplayeritem:(NSInteger)-deleteComments;
+ (BOOL)qYprestart:(NSInteger)-deleteComments;
+ (BOOL)gCiisatendtime:(NSInteger)-deleteComments;
+ (BOOL)bMncalcloadedduration:(NSInteger)-deleteComments;
+ (BOOL)wAzaddplayerobservers:(NSInteger)-deleteComments;
+ (BOOL)LKjremoveplayerobservers:(NSInteger)-deleteComments;
+ (BOOL)oZzaddplayeritemobservers:(NSInteger)-deleteComments;
+ (BOOL)ETpremoveplayeritemobservers:(NSInteger)-deleteComments;
+ (BOOL)SVgaddtimeobserver:(NSInteger)-deleteComments;
+ (BOOL)FLvremovetimeobserver:(NSInteger)-deleteComments;
+ (BOOL)uJgobservevalueforkeypathtofobjectdchangeecontext:(NSInteger)-deleteComments;
+ (BOOL)wReplayeritemdidplaytoendtime:(NSInteger)-deleteComments;

@end
