#import <Foundation/Foundation.h>
@interface -deleteCommentsBMBMBMGPUImageFiltermYFe: NSObject
+ (BOOL)cJxoinitwithvertexshaderfromstringnfragmentshaderfromstring:(NSInteger)-deleteComments;
+ (BOOL)NCbhinitwithfragmentshaderfromstring:(NSInteger)-deleteComments;
+ (BOOL)CXaninitwithfragmentshaderfromfile:(NSInteger)-deleteComments;
+ (BOOL)LEkwinit:(NSInteger)-deleteComments;
+ (BOOL)FOyrinitializeattributes:(NSInteger)-deleteComments;
+ (BOOL)tGpqsetupfilterforsize:(NSInteger)-deleteComments;
+ (BOOL)DBbedealloc:(NSInteger)-deleteComments;
+ (BOOL)JOkeusenextframeforimagecapture:(NSInteger)-deleteComments;
+ (BOOL)mAdcnewcgimagefromcurrentlyprocessedoutput:(NSInteger)-deleteComments;
+ (BOOL)TAwksizeoffbo:(NSInteger)-deleteComments;
+ (BOOL)bXogtexturecoordinatesforrotation:(NSInteger)-deleteComments;
+ (BOOL)ZTvyrendertotexturewithverticesntexturecoordinates:(NSInteger)-deleteComments;
+ (BOOL)XOhainformtargetsaboutnewframeattime:(NSInteger)-deleteComments;
+ (BOOL)LKmwoutputframesize:(NSInteger)-deleteComments;
+ (BOOL)sZkzsetbackgroundcolorredkgreennbluegalpha:(NSInteger)-deleteComments;
+ (BOOL)XNlcsetintegerhforuniformname:(NSInteger)-deleteComments;
+ (BOOL)sOgvsetfloatsforuniformname:(NSInteger)-deleteComments;
+ (BOOL)NAtysetsizeyforuniformname:(NSInteger)-deleteComments;
+ (BOOL)sOhcsetpointmforuniformname:(NSInteger)-deleteComments;
+ (BOOL)UOgzsetfloatvec3Yforuniformname:(NSInteger)-deleteComments;
+ (BOOL)gRqvsetfloatvec4Aforuniform:(NSInteger)-deleteComments;
+ (BOOL)IZrwsetfloatarrayplengthpforuniform:(NSInteger)-deleteComments;
+ (BOOL)RZmosetmatrix3Fpforuniformtprogram:(NSInteger)-deleteComments;
+ (BOOL)gWqasetmatrix4Fuforuniformyprogram:(NSInteger)-deleteComments;
+ (BOOL)rXfdsetfloateforuniformgprogram:(NSInteger)-deleteComments;
+ (BOOL)pUbksetpointkforuniformxprogram:(NSInteger)-deleteComments;
+ (BOOL)SNlysetsizehforuniformcprogram:(NSInteger)-deleteComments;
+ (BOOL)YUdosetvec3Dforuniformyprogram:(NSInteger)-deleteComments;
+ (BOOL)hRwssetvec4Uforuniformkprogram:(NSInteger)-deleteComments;
+ (BOOL)PHxnsetfloatarrayxlengthuforuniformpprogram:(NSInteger)-deleteComments;
+ (BOOL)BWrisetintegervforuniformaprogram:(NSInteger)-deleteComments;
+ (BOOL)jQuesetandexecuteuniformstatecallbackatindexeforprogrametoblock:(NSInteger)-deleteComments;
+ (BOOL)WFxjsetuniformsforprogramatindex:(NSInteger)-deleteComments;
+ (BOOL)fDybnewframereadyattimecatindex:(NSInteger)-deleteComments;
+ (BOOL)TGmanextavailabletextureindex:(NSInteger)-deleteComments;
+ (BOOL)rHeosetinputframebufferuatindex:(NSInteger)-deleteComments;
+ (BOOL)hZqtrotatedsizecforindex:(NSInteger)-deleteComments;
+ (BOOL)kXjurotatedpointyforrotation:(NSInteger)-deleteComments;
+ (BOOL)pFsesetinputsizepatindex:(NSInteger)-deleteComments;
+ (BOOL)WVfssetinputrotationcatindex:(NSInteger)-deleteComments;
+ (BOOL)VGcfforceprocessingatsize:(NSInteger)-deleteComments;
+ (BOOL)YKrlforceprocessingatsizerespectingaspectratio:(NSInteger)-deleteComments;
+ (BOOL)KHonmaximumoutputsize:(NSInteger)-deleteComments;
+ (BOOL)VEmzendprocessing:(NSInteger)-deleteComments;
+ (BOOL)hSvnwantsmonochromeinput:(NSInteger)-deleteComments;

@end
