#import <Foundation/Foundation.h>
@interface -deleteCommentsBMBMGPUImageFilteryTj: NSObject
+ (BOOL)pTtinitwithvertexshaderfromstringefragmentshaderfromstring:(NSInteger)-deleteComments;
+ (BOOL)sZiinitwithfragmentshaderfromstring:(NSInteger)-deleteComments;
+ (BOOL)fIkinitwithfragmentshaderfromfile:(NSInteger)-deleteComments;
+ (BOOL)xBcinit:(NSInteger)-deleteComments;
+ (BOOL)FRsinitializeattributes:(NSInteger)-deleteComments;
+ (BOOL)cOxsetupfilterforsize:(NSInteger)-deleteComments;
+ (BOOL)vQjdealloc:(NSInteger)-deleteComments;
+ (BOOL)ZUhusenextframeforimagecapture:(NSInteger)-deleteComments;
+ (BOOL)jZhnewcgimagefromcurrentlyprocessedoutput:(NSInteger)-deleteComments;
+ (BOOL)NDasizeoffbo:(NSInteger)-deleteComments;
+ (BOOL)CDjtexturecoordinatesforrotation:(NSInteger)-deleteComments;
+ (BOOL)zKgrendertotexturewithverticesstexturecoordinates:(NSInteger)-deleteComments;
+ (BOOL)KLxinformtargetsaboutnewframeattime:(NSInteger)-deleteComments;
+ (BOOL)gAyoutputframesize:(NSInteger)-deleteComments;
+ (BOOL)YKosetbackgroundcolorredkgreenablueealpha:(NSInteger)-deleteComments;
+ (BOOL)pCbsetintegeriforuniformname:(NSInteger)-deleteComments;
+ (BOOL)CZysetfloatxforuniformname:(NSInteger)-deleteComments;
+ (BOOL)iUgsetsizejforuniformname:(NSInteger)-deleteComments;
+ (BOOL)IOrsetpointeforuniformname:(NSInteger)-deleteComments;
+ (BOOL)jJusetfloatvec3Fforuniformname:(NSInteger)-deleteComments;
+ (BOOL)NExsetfloatvec4Yforuniform:(NSInteger)-deleteComments;
+ (BOOL)sRysetfloatarrayslengthvforuniform:(NSInteger)-deleteComments;
+ (BOOL)GHnsetmatrix3Fpforuniformrprogram:(NSInteger)-deleteComments;
+ (BOOL)yIbsetmatrix4Feforuniformoprogram:(NSInteger)-deleteComments;
+ (BOOL)jEusetfloattforuniformpprogram:(NSInteger)-deleteComments;
+ (BOOL)xZxsetpointlforuniformbprogram:(NSInteger)-deleteComments;
+ (BOOL)pNqsetsizetforuniformlprogram:(NSInteger)-deleteComments;
+ (BOOL)FZbsetvec3Yforuniformjprogram:(NSInteger)-deleteComments;
+ (BOOL)zFjsetvec4Hforuniformyprogram:(NSInteger)-deleteComments;
+ (BOOL)vJcsetfloatarrayclengthtforuniformjprogram:(NSInteger)-deleteComments;
+ (BOOL)aZisetintegercforuniformoprogram:(NSInteger)-deleteComments;
+ (BOOL)sEjsetandexecuteuniformstatecallbackatindexeforprogramgtoblock:(NSInteger)-deleteComments;
+ (BOOL)GQhsetuniformsforprogramatindex:(NSInteger)-deleteComments;
+ (BOOL)VHhnewframereadyattimezatindex:(NSInteger)-deleteComments;
+ (BOOL)pObnextavailabletextureindex:(NSInteger)-deleteComments;
+ (BOOL)CYjsetinputframebufferoatindex:(NSInteger)-deleteComments;
+ (BOOL)KXyrotatedsizeeforindex:(NSInteger)-deleteComments;
+ (BOOL)vVdrotatedpointhforrotation:(NSInteger)-deleteComments;
+ (BOOL)MRnsetinputsizeaatindex:(NSInteger)-deleteComments;
+ (BOOL)qMusetinputrotationjatindex:(NSInteger)-deleteComments;
+ (BOOL)cDyforceprocessingatsize:(NSInteger)-deleteComments;
+ (BOOL)hAhforceprocessingatsizerespectingaspectratio:(NSInteger)-deleteComments;
+ (BOOL)lRpmaximumoutputsize:(NSInteger)-deleteComments;
+ (BOOL)FBhendprocessing:(NSInteger)-deleteComments;
+ (BOOL)dZiwantsmonochromeinput:(NSInteger)-deleteComments;

@end
