#import <Foundation/Foundation.h>
@interface -deleteCommentsNSDataM: NSObject
+ (BOOL)ymd2String:(NSInteger)-deleteComments;
+ (BOOL)Fmd2Data:(NSInteger)-deleteComments;
+ (BOOL)vmd4String:(NSInteger)-deleteComments;
+ (BOOL)nmd4Data:(NSInteger)-deleteComments;
+ (BOOL)wmd5String:(NSInteger)-deleteComments;
+ (BOOL)emd5Data:(NSInteger)-deleteComments;
+ (BOOL)Wsha1String:(NSInteger)-deleteComments;
+ (BOOL)Osha1Data:(NSInteger)-deleteComments;
+ (BOOL)Isha224String:(NSInteger)-deleteComments;
+ (BOOL)Csha224Data:(NSInteger)-deleteComments;
+ (BOOL)msha256String:(NSInteger)-deleteComments;
+ (BOOL)bsha256Data:(NSInteger)-deleteComments;
+ (BOOL)gsha384String:(NSInteger)-deleteComments;
+ (BOOL)Usha384Data:(NSInteger)-deleteComments;
+ (BOOL)Ksha512String:(NSInteger)-deleteComments;
+ (BOOL)Qsha512Data:(NSInteger)-deleteComments;
+ (BOOL)qHmacstringusingalgGWithkey:(NSInteger)-deleteComments;
+ (BOOL)SHmacdatausingalgcWithkey:(NSInteger)-deleteComments;
+ (BOOL)nHmacmd5Stringwithkey:(NSInteger)-deleteComments;
+ (BOOL)aHmacmd5Datawithkey:(NSInteger)-deleteComments;
+ (BOOL)pHmacsha1Stringwithkey:(NSInteger)-deleteComments;
+ (BOOL)OHmacsha1Datawithkey:(NSInteger)-deleteComments;
+ (BOOL)vHmacsha224Stringwithkey:(NSInteger)-deleteComments;
+ (BOOL)jHmacsha224Datawithkey:(NSInteger)-deleteComments;
+ (BOOL)jHmacsha256Stringwithkey:(NSInteger)-deleteComments;
+ (BOOL)VHmacsha256Datawithkey:(NSInteger)-deleteComments;
+ (BOOL)nHmacsha384Stringwithkey:(NSInteger)-deleteComments;
+ (BOOL)cHmacsha384Datawithkey:(NSInteger)-deleteComments;
+ (BOOL)rHmacsha512Stringwithkey:(NSInteger)-deleteComments;
+ (BOOL)yHmacsha512Datawithkey:(NSInteger)-deleteComments;
+ (BOOL)Ycrc32String:(NSInteger)-deleteComments;
+ (BOOL)Ucrc32:(NSInteger)-deleteComments;
+ (BOOL)zAes256EncryptwithkeyLIv:(NSInteger)-deleteComments;
+ (BOOL)CAes256DecryptwithkeyuIv:(NSInteger)-deleteComments;
+ (BOOL)Zutf8String:(NSInteger)-deleteComments;
+ (BOOL)xhexString:(NSInteger)-deleteComments;
+ (BOOL)JDatawithhexstring:(NSInteger)-deleteComments;
+ (BOOL)vbase64EncodedString:(NSInteger)-deleteComments;
+ (BOOL)ZDatawithbase64Encodedstring:(NSInteger)-deleteComments;
+ (BOOL)FjsonValueDecoded:(NSInteger)-deleteComments;
+ (BOOL)dgzipInflate:(NSInteger)-deleteComments;
+ (BOOL)tgzipDeflate:(NSInteger)-deleteComments;
+ (BOOL)QzlibInflate:(NSInteger)-deleteComments;
+ (BOOL)yzlibDeflate:(NSInteger)-deleteComments;
+ (BOOL)MDatanamed:(NSInteger)-deleteComments;

@end
