#import <Foundation/Foundation.h>
@interface -deleteCommentsBMGPUImageFilterms: NSObject
+ (BOOL)gJinitwithvertexshaderfromstringfragmentshaderfromstringbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)jPinitwithfragmentshaderfromstringbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)aLinitwithfragmentshaderfromfilebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)rFinitbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)CHinitializeattributesbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)zLsetupfilterforsizebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)rPdeallocbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)nOusenextframeforimagecapturebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)rNnewcgimagefromcurrentlyprocessedoutputbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)GEsizeoffbobmbmbm:(NSInteger)-deleteComments;
+ (BOOL)yWtexturecoordinatesforrotationbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)YOrendertotexturewithverticestexturecoordinatesbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)zQinformtargetsaboutnewframeattimebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)eYoutputframesizebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)hZsetbackgroundcolorredgreenbluealphabmbmbm:(NSInteger)-deleteComments;
+ (BOOL)SCsetintegerforuniformnamebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)xQsetfloatforuniformnamebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)SDsetsizeforuniformnamebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)SZsetpointforuniformnamebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)RGsetfloatvec3Foruniformnamebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)rMsetfloatvec4Foruniformbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)DXsetfloatarraylengthforuniformbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)xHsetmatrix3Fforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)FWsetmatrix4Fforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)HUsetfloatforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)IBsetpointforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)yTsetsizeforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)yJsetvec3Foruniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)FRsetvec4Foruniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)GEsetfloatarraylengthforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)QFsetintegerforuniformprogrambmbmbm:(NSInteger)-deleteComments;
+ (BOOL)NPsetandexecuteuniformstatecallbackatindexforprogramtoblockbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)LSsetuniformsforprogramatindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)tJnewframereadyattimeatindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)WNnextavailabletextureindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)cUsetinputframebufferatindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)LDrotatedsizeforindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)ZRrotatedpointforrotationbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)YWsetinputsizeatindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)TTsetinputrotationatindexbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)pKforceprocessingatsizebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)SOforceprocessingatsizerespectingaspectratiobmbmbm:(NSInteger)-deleteComments;
+ (BOOL)oWmaximumoutputsizebmbmbm:(NSInteger)-deleteComments;
+ (BOOL)VBendprocessingbmbmbm:(NSInteger)-deleteComments;
+ (BOOL)MMwantsmonochromeinputbmbmbm:(NSInteger)-deleteComments;

@end
