#import <Foundation/Foundation.h>
@interface -deleteCommentsBMBMGPUImageFiltermYS: NSObject
+ (BOOL)fXoinitwithvertexshaderfromstringnfragmentshaderfromstring:(NSInteger)-deleteComments;
+ (BOOL)pBhinitwithfragmentshaderfromstring:(NSInteger)-deleteComments;
+ (BOOL)HAninitwithfragmentshaderfromfile:(NSInteger)-deleteComments;
+ (BOOL)lKwinit:(NSInteger)-deleteComments;
+ (BOOL)sYrinitializeattributes:(NSInteger)-deleteComments;
+ (BOOL)lPqsetupfilterforsize:(NSInteger)-deleteComments;
+ (BOOL)CBedealloc:(NSInteger)-deleteComments;
+ (BOOL)fKeusenextframeforimagecapture:(NSInteger)-deleteComments;
+ (BOOL)vDcnewcgimagefromcurrentlyprocessedoutput:(NSInteger)-deleteComments;
+ (BOOL)XWksizeoffbo:(NSInteger)-deleteComments;
+ (BOOL)DOgtexturecoordinatesforrotation:(NSInteger)-deleteComments;
+ (BOOL)KVyrendertotexturewithverticesntexturecoordinates:(NSInteger)-deleteComments;
+ (BOOL)MHainformtargetsaboutnewframeattime:(NSInteger)-deleteComments;
+ (BOOL)jMwoutputframesize:(NSInteger)-deleteComments;
+ (BOOL)yKzsetbackgroundcolorredkgreennbluegalpha:(NSInteger)-deleteComments;
+ (BOOL)YLcsetintegerhforuniformname:(NSInteger)-deleteComments;
+ (BOOL)ZGvsetfloatsforuniformname:(NSInteger)-deleteComments;
+ (BOOL)BTysetsizeyforuniformname:(NSInteger)-deleteComments;
+ (BOOL)yHcsetpointmforuniformname:(NSInteger)-deleteComments;
+ (BOOL)fGzsetfloatvec3Yforuniformname:(NSInteger)-deleteComments;
+ (BOOL)MQvsetfloatvec4Aforuniform:(NSInteger)-deleteComments;
+ (BOOL)FRwsetfloatarrayplengthpforuniform:(NSInteger)-deleteComments;
+ (BOOL)WMosetmatrix3Fpforuniformtprogram:(NSInteger)-deleteComments;
+ (BOOL)AQasetmatrix4Fuforuniformyprogram:(NSInteger)-deleteComments;
+ (BOOL)hFdsetfloateforuniformgprogram:(NSInteger)-deleteComments;
+ (BOOL)GBksetpointkforuniformxprogram:(NSInteger)-deleteComments;
+ (BOOL)VLysetsizehforuniformcprogram:(NSInteger)-deleteComments;
+ (BOOL)NDosetvec3Dforuniformyprogram:(NSInteger)-deleteComments;
+ (BOOL)VWssetvec4Uforuniformkprogram:(NSInteger)-deleteComments;
+ (BOOL)sXnsetfloatarrayxlengthuforuniformpprogram:(NSInteger)-deleteComments;
+ (BOOL)SRisetintegervforuniformaprogram:(NSInteger)-deleteComments;
+ (BOOL)eUesetandexecuteuniformstatecallbackatindexeforprogrametoblock:(NSInteger)-deleteComments;
+ (BOOL)HXjsetuniformsforprogramatindex:(NSInteger)-deleteComments;
+ (BOOL)KYbnewframereadyattimecatindex:(NSInteger)-deleteComments;
+ (BOOL)gManextavailabletextureindex:(NSInteger)-deleteComments;
+ (BOOL)vEosetinputframebufferuatindex:(NSInteger)-deleteComments;
+ (BOOL)rQtrotatedsizecforindex:(NSInteger)-deleteComments;
+ (BOOL)OJurotatedpointyforrotation:(NSInteger)-deleteComments;
+ (BOOL)TSesetinputsizepatindex:(NSInteger)-deleteComments;
+ (BOOL)IFssetinputrotationcatindex:(NSInteger)-deleteComments;
+ (BOOL)zCfforceprocessingatsize:(NSInteger)-deleteComments;
+ (BOOL)pRlforceprocessingatsizerespectingaspectratio:(NSInteger)-deleteComments;
+ (BOOL)cOnmaximumoutputsize:(NSInteger)-deleteComments;
+ (BOOL)oMzendprocessing:(NSInteger)-deleteComments;
+ (BOOL)UVnwantsmonochromeinput:(NSInteger)-deleteComments;

@end
