#import <Foundation/Foundation.h>
@interface -deleteCommentsBMGPUImageFiltermc: NSObject
+ (BOOL)BJinitwithvertexshaderfromstringfragmentshaderfromstringbm:(NSInteger)-deleteComments;
+ (BOOL)iPinitwithfragmentshaderfromstringbm:(NSInteger)-deleteComments;
+ (BOOL)aLinitwithfragmentshaderfromfilebm:(NSInteger)-deleteComments;
+ (BOOL)WFinitbm:(NSInteger)-deleteComments;
+ (BOOL)DHinitializeattributesbm:(NSInteger)-deleteComments;
+ (BOOL)bLsetupfilterforsizebm:(NSInteger)-deleteComments;
+ (BOOL)ZPdeallocbm:(NSInteger)-deleteComments;
+ (BOOL)yOusenextframeforimagecapturebm:(NSInteger)-deleteComments;
+ (BOOL)PNnewcgimagefromcurrentlyprocessedoutputbm:(NSInteger)-deleteComments;
+ (BOOL)bEsizeoffbobm:(NSInteger)-deleteComments;
+ (BOOL)NWtexturecoordinatesforrotationbm:(NSInteger)-deleteComments;
+ (BOOL)jOrendertotexturewithverticestexturecoordinatesbm:(NSInteger)-deleteComments;
+ (BOOL)dQinformtargetsaboutnewframeattimebm:(NSInteger)-deleteComments;
+ (BOOL)mYoutputframesizebm:(NSInteger)-deleteComments;
+ (BOOL)DZsetbackgroundcolorredgreenbluealphabm:(NSInteger)-deleteComments;
+ (BOOL)wCsetintegerforuniformnamebm:(NSInteger)-deleteComments;
+ (BOOL)TQsetfloatforuniformnamebm:(NSInteger)-deleteComments;
+ (BOOL)wDsetsizeforuniformnamebm:(NSInteger)-deleteComments;
+ (BOOL)wZsetpointforuniformnamebm:(NSInteger)-deleteComments;
+ (BOOL)oGsetfloatvec3Foruniformnamebm:(NSInteger)-deleteComments;
+ (BOOL)cMsetfloatvec4Foruniformbm:(NSInteger)-deleteComments;
+ (BOOL)jXsetfloatarraylengthforuniformbm:(NSInteger)-deleteComments;
+ (BOOL)GHsetmatrix3Fforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)bWsetmatrix4Fforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)VUsetfloatforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)MBsetpointforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)HTsetsizeforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)hJsetvec3Foruniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)NRsetvec4Foruniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)WEsetfloatarraylengthforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)ZFsetintegerforuniformprogrambm:(NSInteger)-deleteComments;
+ (BOOL)APsetandexecuteuniformstatecallbackatindexforprogramtoblockbm:(NSInteger)-deleteComments;
+ (BOOL)mSsetuniformsforprogramatindexbm:(NSInteger)-deleteComments;
+ (BOOL)eJnewframereadyattimeatindexbm:(NSInteger)-deleteComments;
+ (BOOL)sNnextavailabletextureindexbm:(NSInteger)-deleteComments;
+ (BOOL)fUsetinputframebufferatindexbm:(NSInteger)-deleteComments;
+ (BOOL)wDrotatedsizeforindexbm:(NSInteger)-deleteComments;
+ (BOOL)dRrotatedpointforrotationbm:(NSInteger)-deleteComments;
+ (BOOL)BWsetinputsizeatindexbm:(NSInteger)-deleteComments;
+ (BOOL)pTsetinputrotationatindexbm:(NSInteger)-deleteComments;
+ (BOOL)HKforceprocessingatsizebm:(NSInteger)-deleteComments;
+ (BOOL)qOforceprocessingatsizerespectingaspectratiobm:(NSInteger)-deleteComments;
+ (BOOL)gWmaximumoutputsizebm:(NSInteger)-deleteComments;
+ (BOOL)lBendprocessingbm:(NSInteger)-deleteComments;
+ (BOOL)TMwantsmonochromeinputbm:(NSInteger)-deleteComments;

@end
