#import <Foundation/Foundation.h>
@interface -deleteCommentsBMVIMVideoPlayervY: NSObject
+ (BOOL)JAdealloc:(NSInteger)-deleteComments;
+ (BOOL)KKinit:(NSInteger)-deleteComments;
+ (BOOL)nGsetupplayer:(NSInteger)-deleteComments;
+ (BOOL)uKsetupaudiosession:(NSInteger)-deleteComments;
+ (BOOL)wSseturl:(NSInteger)-deleteComments;
+ (BOOL)yYsetplayeritem:(NSInteger)-deleteComments;
+ (BOOL)XNsetasset:(NSInteger)-deleteComments;
+ (BOOL)aQsetmuted:(NSInteger)-deleteComments;
+ (BOOL)kEismuted:(NSInteger)-deleteComments;
+ (BOOL)FMplay:(NSInteger)-deleteComments;
+ (BOOL)iIpause:(NSInteger)-deleteComments;
+ (BOOL)uNseektotime:(NSInteger)-deleteComments;
+ (BOOL)HFreset:(NSInteger)-deleteComments;
+ (BOOL)wMenableairplay:(NSInteger)-deleteComments;
+ (BOOL)XZdisableairplay:(NSInteger)-deleteComments;
+ (BOOL)ERisairplayenabled:(NSInteger)-deleteComments;
+ (BOOL)PAstartscrubbing:(NSInteger)-deleteComments;
+ (BOOL)eZscrub:(NSInteger)-deleteComments;
+ (BOOL)HPstopscrubbing:(NSInteger)-deleteComments;
+ (BOOL)nZenabletimeupdates:(NSInteger)-deleteComments;
+ (BOOL)oVdisabletimeupdates:(NSInteger)-deleteComments;
+ (BOOL)KQsetvolume:(NSInteger)-deleteComments;
+ (BOOL)KGcancelfadevolume:(NSInteger)-deleteComments;
+ (BOOL)LIfadeinvolume:(NSInteger)-deleteComments;
+ (BOOL)yVfadeoutvolume:(NSInteger)-deleteComments;
+ (BOOL)ySreportunabletocreateplayeritem:(NSInteger)-deleteComments;
+ (BOOL)zKresetplayeritemifnecessary:(NSInteger)-deleteComments;
+ (BOOL)THprepareplayeritem:(NSInteger)-deleteComments;
+ (BOOL)dPrestart:(NSInteger)-deleteComments;
+ (BOOL)XIisatendtime:(NSInteger)-deleteComments;
+ (BOOL)iNcalcloadedduration:(NSInteger)-deleteComments;
+ (BOOL)JZaddplayerobservers:(NSInteger)-deleteComments;
+ (BOOL)pJremoveplayerobservers:(NSInteger)-deleteComments;
+ (BOOL)AZaddplayeritemobservers:(NSInteger)-deleteComments;
+ (BOOL)PPremoveplayeritemobservers:(NSInteger)-deleteComments;
+ (BOOL)fGaddtimeobserver:(NSInteger)-deleteComments;
+ (BOOL)oVremovetimeobserver:(NSInteger)-deleteComments;
+ (BOOL)SGobservevalueforkeypathtofobjectdchangeecontext:(NSInteger)-deleteComments;
+ (BOOL)iEplayeritemdidplaytoendtime:(NSInteger)-deleteComments;

@end
