#import <Foundation/Foundation.h>
@interface -deleteCommentsBMGPUImageFilterHk: NSObject
+ (BOOL)jUinitwithvertexshaderfromstringfragmentshaderfromstringbmbm:(NSInteger)-deleteComments;
+ (BOOL)mVinitwithfragmentshaderfromstringbmbm:(NSInteger)-deleteComments;
+ (BOOL)BMinitwithfragmentshaderfromfilebmbm:(NSInteger)-deleteComments;
+ (BOOL)fSinitbmbm:(NSInteger)-deleteComments;
+ (BOOL)SYinitializeattributesbmbm:(NSInteger)-deleteComments;
+ (BOOL)UZsetupfilterforsizebmbm:(NSInteger)-deleteComments;
+ (BOOL)cBdeallocbmbm:(NSInteger)-deleteComments;
+ (BOOL)NLusenextframeforimagecapturebmbm:(NSInteger)-deleteComments;
+ (BOOL)uUnewcgimagefromcurrentlyprocessedoutputbmbm:(NSInteger)-deleteComments;
+ (BOOL)CBsizeoffbobmbm:(NSInteger)-deleteComments;
+ (BOOL)EYtexturecoordinatesforrotationbmbm:(NSInteger)-deleteComments;
+ (BOOL)aIrendertotexturewithverticestexturecoordinatesbmbm:(NSInteger)-deleteComments;
+ (BOOL)HMinformtargetsaboutnewframeattimebmbm:(NSInteger)-deleteComments;
+ (BOOL)CWoutputframesizebmbm:(NSInteger)-deleteComments;
+ (BOOL)THsetbackgroundcolorredgreenbluealphabmbm:(NSInteger)-deleteComments;
+ (BOOL)UAsetintegerforuniformnamebmbm:(NSInteger)-deleteComments;
+ (BOOL)MEsetfloatforuniformnamebmbm:(NSInteger)-deleteComments;
+ (BOOL)sLsetsizeforuniformnamebmbm:(NSInteger)-deleteComments;
+ (BOOL)nEsetpointforuniformnamebmbm:(NSInteger)-deleteComments;
+ (BOOL)fFsetfloatvec3Foruniformnamebmbm:(NSInteger)-deleteComments;
+ (BOOL)RSsetfloatvec4Foruniformbmbm:(NSInteger)-deleteComments;
+ (BOOL)CUsetfloatarraylengthforuniformbmbm:(NSInteger)-deleteComments;
+ (BOOL)fFsetmatrix3Fforuniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)mCsetmatrix4Fforuniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)eNsetfloatforuniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)XPsetpointforuniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)VQsetsizeforuniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)SEsetvec3Foruniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)aMsetvec4Foruniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)DPsetfloatarraylengthforuniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)DNsetintegerforuniformprogrambmbm:(NSInteger)-deleteComments;
+ (BOOL)yMsetandexecuteuniformstatecallbackatindexforprogramtoblockbmbm:(NSInteger)-deleteComments;
+ (BOOL)NLsetuniformsforprogramatindexbmbm:(NSInteger)-deleteComments;
+ (BOOL)NDnewframereadyattimeatindexbmbm:(NSInteger)-deleteComments;
+ (BOOL)YCnextavailabletextureindexbmbm:(NSInteger)-deleteComments;
+ (BOOL)TWsetinputframebufferatindexbmbm:(NSInteger)-deleteComments;
+ (BOOL)fWrotatedsizeforindexbmbm:(NSInteger)-deleteComments;
+ (BOOL)zOrotatedpointforrotationbmbm:(NSInteger)-deleteComments;
+ (BOOL)yMsetinputsizeatindexbmbm:(NSInteger)-deleteComments;
+ (BOOL)LRsetinputrotationatindexbmbm:(NSInteger)-deleteComments;
+ (BOOL)RUforceprocessingatsizebmbm:(NSInteger)-deleteComments;
+ (BOOL)HFforceprocessingatsizerespectingaspectratiobmbm:(NSInteger)-deleteComments;
+ (BOOL)nImaximumoutputsizebmbm:(NSInteger)-deleteComments;
+ (BOOL)ABendprocessingbmbm:(NSInteger)-deleteComments;
+ (BOOL)XJwantsmonochromeinputbmbm:(NSInteger)-deleteComments;

@end
