#import <Foundation/Foundation.h>
@interface BMBMGPUImageFiltermu: NSObject
+ (BOOL)IJinitwithvertexshaderfromstringfragmentshaderfromstringbmbm:(NSInteger)BM;
+ (BOOL)EPinitwithfragmentshaderfromstringbmbm:(NSInteger)BM;
+ (BOOL)aLinitwithfragmentshaderfromfilebmbm:(NSInteger)BM;
+ (BOOL)vFinitbmbm:(NSInteger)BM;
+ (BOOL)gHinitializeattributesbmbm:(NSInteger)BM;
+ (BOOL)vLsetupfilterforsizebmbm:(NSInteger)BM;
+ (BOOL)BPdeallocbmbm:(NSInteger)BM;
+ (BOOL)lOusenextframeforimagecapturebmbm:(NSInteger)BM;
+ (BOOL)LNnewcgimagefromcurrentlyprocessedoutputbmbm:(NSInteger)BM;
+ (BOOL)qEsizeoffbobmbm:(NSInteger)BM;
+ (BOOL)YWtexturecoordinatesforrotationbmbm:(NSInteger)BM;
+ (BOOL)DOrendertotexturewithverticestexturecoordinatesbmbm:(NSInteger)BM;
+ (BOOL)pQinformtargetsaboutnewframeattimebmbm:(NSInteger)BM;
+ (BOOL)HYoutputframesizebmbm:(NSInteger)BM;
+ (BOOL)EZsetbackgroundcolorredgreenbluealphabmbm:(NSInteger)BM;
+ (BOOL)ZCsetintegerforuniformnamebmbm:(NSInteger)BM;
+ (BOOL)HQsetfloatforuniformnamebmbm:(NSInteger)BM;
+ (BOOL)LDsetsizeforuniformnamebmbm:(NSInteger)BM;
+ (BOOL)CZsetpointforuniformnamebmbm:(NSInteger)BM;
+ (BOOL)cGsetfloatvec3Foruniformnamebmbm:(NSInteger)BM;
+ (BOOL)xMsetfloatvec4Foruniformbmbm:(NSInteger)BM;
+ (BOOL)aXsetfloatarraylengthforuniformbmbm:(NSInteger)BM;
+ (BOOL)ZHsetmatrix3Fforuniformprogrambmbm:(NSInteger)BM;
+ (BOOL)rWsetmatrix4Fforuniformprogrambmbm:(NSInteger)BM;
+ (BOOL)fUsetfloatforuniformprogrambmbm:(NSInteger)BM;
+ (BOOL)UBsetpointforuniformprogrambmbm:(NSInteger)BM;
+ (BOOL)BTsetsizeforuniformprogrambmbm:(NSInteger)BM;
+ (BOOL)GJsetvec3Foruniformprogrambmbm:(NSInteger)BM;
+ (BOOL)uRsetvec4Foruniformprogrambmbm:(NSInteger)BM;
+ (BOOL)kEsetfloatarraylengthforuniformprogrambmbm:(NSInteger)BM;
+ (BOOL)JFsetintegerforuniformprogrambmbm:(NSInteger)BM;
+ (BOOL)jPsetandexecuteuniformstatecallbackatindexforprogramtoblockbmbm:(NSInteger)BM;
+ (BOOL)XSsetuniformsforprogramatindexbmbm:(NSInteger)BM;
+ (BOOL)sJnewframereadyattimeatindexbmbm:(NSInteger)BM;
+ (BOOL)sNnextavailabletextureindexbmbm:(NSInteger)BM;
+ (BOOL)hUsetinputframebufferatindexbmbm:(NSInteger)BM;
+ (BOOL)mDrotatedsizeforindexbmbm:(NSInteger)BM;
+ (BOOL)wRrotatedpointforrotationbmbm:(NSInteger)BM;
+ (BOOL)cWsetinputsizeatindexbmbm:(NSInteger)BM;
+ (BOOL)sTsetinputrotationatindexbmbm:(NSInteger)BM;
+ (BOOL)DKforceprocessingatsizebmbm:(NSInteger)BM;
+ (BOOL)yOforceprocessingatsizerespectingaspectratiobmbm:(NSInteger)BM;
+ (BOOL)GWmaximumoutputsizebmbm:(NSInteger)BM;
+ (BOOL)YBendprocessingbmbm:(NSInteger)BM;
+ (BOOL)OMwantsmonochromeinputbmbm:(NSInteger)BM;

@end
