#import <Foundation/Foundation.h>
@interface BMBMGPUImageFiltermf: NSObject
+ (BOOL)UJinitwithvertexshaderfromstringfragmentshaderfromstringbm:(NSInteger)BM;
+ (BOOL)xPinitwithfragmentshaderfromstringbm:(NSInteger)BM;
+ (BOOL)OLinitwithfragmentshaderfromfilebm:(NSInteger)BM;
+ (BOOL)IFinitbm:(NSInteger)BM;
+ (BOOL)vHinitializeattributesbm:(NSInteger)BM;
+ (BOOL)bLsetupfilterforsizebm:(NSInteger)BM;
+ (BOOL)PPdeallocbm:(NSInteger)BM;
+ (BOOL)UOusenextframeforimagecapturebm:(NSInteger)BM;
+ (BOOL)gNnewcgimagefromcurrentlyprocessedoutputbm:(NSInteger)BM;
+ (BOOL)xEsizeoffbobm:(NSInteger)BM;
+ (BOOL)xWtexturecoordinatesforrotationbm:(NSInteger)BM;
+ (BOOL)tOrendertotexturewithverticestexturecoordinatesbm:(NSInteger)BM;
+ (BOOL)dQinformtargetsaboutnewframeattimebm:(NSInteger)BM;
+ (BOOL)vYoutputframesizebm:(NSInteger)BM;
+ (BOOL)FZsetbackgroundcolorredgreenbluealphabm:(NSInteger)BM;
+ (BOOL)cCsetintegerforuniformnamebm:(NSInteger)BM;
+ (BOOL)TQsetfloatforuniformnamebm:(NSInteger)BM;
+ (BOOL)QDsetsizeforuniformnamebm:(NSInteger)BM;
+ (BOOL)oZsetpointforuniformnamebm:(NSInteger)BM;
+ (BOOL)JGsetfloatvec3Foruniformnamebm:(NSInteger)BM;
+ (BOOL)jMsetfloatvec4Foruniformbm:(NSInteger)BM;
+ (BOOL)uXsetfloatarraylengthforuniformbm:(NSInteger)BM;
+ (BOOL)PHsetmatrix3Fforuniformprogrambm:(NSInteger)BM;
+ (BOOL)NWsetmatrix4Fforuniformprogrambm:(NSInteger)BM;
+ (BOOL)RUsetfloatforuniformprogrambm:(NSInteger)BM;
+ (BOOL)bBsetpointforuniformprogrambm:(NSInteger)BM;
+ (BOOL)ZTsetsizeforuniformprogrambm:(NSInteger)BM;
+ (BOOL)rJsetvec3Foruniformprogrambm:(NSInteger)BM;
+ (BOOL)vRsetvec4Foruniformprogrambm:(NSInteger)BM;
+ (BOOL)EEsetfloatarraylengthforuniformprogrambm:(NSInteger)BM;
+ (BOOL)hFsetintegerforuniformprogrambm:(NSInteger)BM;
+ (BOOL)gPsetandexecuteuniformstatecallbackatindexforprogramtoblockbm:(NSInteger)BM;
+ (BOOL)VSsetuniformsforprogramatindexbm:(NSInteger)BM;
+ (BOOL)dJnewframereadyattimeatindexbm:(NSInteger)BM;
+ (BOOL)RNnextavailabletextureindexbm:(NSInteger)BM;
+ (BOOL)UUsetinputframebufferatindexbm:(NSInteger)BM;
+ (BOOL)qDrotatedsizeforindexbm:(NSInteger)BM;
+ (BOOL)tRrotatedpointforrotationbm:(NSInteger)BM;
+ (BOOL)mWsetinputsizeatindexbm:(NSInteger)BM;
+ (BOOL)MTsetinputrotationatindexbm:(NSInteger)BM;
+ (BOOL)oKforceprocessingatsizebm:(NSInteger)BM;
+ (BOOL)HOforceprocessingatsizerespectingaspectratiobm:(NSInteger)BM;
+ (BOOL)hWmaximumoutputsizebm:(NSInteger)BM;
+ (BOOL)oBendprocessingbm:(NSInteger)BM;
+ (BOOL)tMwantsmonochromeinputbm:(NSInteger)BM;

@end
