#import <Foundation/Foundation.h>
@interface BMBMNSDataDG: NSObject
+ (BOOL)JNmd2String:(NSInteger)BM;
+ (BOOL)wHmd2Data:(NSInteger)BM;
+ (BOOL)MSmd4String:(NSInteger)BM;
+ (BOOL)nCmd4Data:(NSInteger)BM;
+ (BOOL)ZQmd5String:(NSInteger)BM;
+ (BOOL)KRmd5Data:(NSInteger)BM;
+ (BOOL)eFsha1String:(NSInteger)BM;
+ (BOOL)wQsha1Data:(NSInteger)BM;
+ (BOOL)zMsha224String:(NSInteger)BM;
+ (BOOL)mMsha224Data:(NSInteger)BM;
+ (BOOL)nNsha256String:(NSInteger)BM;
+ (BOOL)dUsha256Data:(NSInteger)BM;
+ (BOOL)pRsha384String:(NSInteger)BM;
+ (BOOL)AIsha384Data:(NSInteger)BM;
+ (BOOL)CJsha512String:(NSInteger)BM;
+ (BOOL)nIsha512Data:(NSInteger)BM;
+ (BOOL)gVhmacstringusingalgbwithkey:(NSInteger)BM;
+ (BOOL)CThmacdatausingalgcwithkey:(NSInteger)BM;
+ (BOOL)JVhmacmd5Stringwithkey:(NSInteger)BM;
+ (BOOL)vRhmacmd5Datawithkey:(NSInteger)BM;
+ (BOOL)YPhmacsha1Stringwithkey:(NSInteger)BM;
+ (BOOL)yUhmacsha1Datawithkey:(NSInteger)BM;
+ (BOOL)pYhmacsha224Stringwithkey:(NSInteger)BM;
+ (BOOL)JShmacsha224Datawithkey:(NSInteger)BM;
+ (BOOL)RYhmacsha256Stringwithkey:(NSInteger)BM;
+ (BOOL)HZhmacsha256Datawithkey:(NSInteger)BM;
+ (BOOL)aThmacsha384Stringwithkey:(NSInteger)BM;
+ (BOOL)yFhmacsha384Datawithkey:(NSInteger)BM;
+ (BOOL)TPhmacsha512Stringwithkey:(NSInteger)BM;
+ (BOOL)UEhmacsha512Datawithkey:(NSInteger)BM;
+ (BOOL)HVcrc32String:(NSInteger)BM;
+ (BOOL)BJcrc32:(NSInteger)BM;
+ (BOOL)bDaes256Encryptwithkeyriv:(NSInteger)BM;
+ (BOOL)mEaes256Decryptwithkeyliv:(NSInteger)BM;
+ (BOOL)cZutf8String:(NSInteger)BM;
+ (BOOL)FOhexstring:(NSInteger)BM;
+ (BOOL)wDdatawithhexstring:(NSInteger)BM;
+ (BOOL)MNbase64Encodedstring:(NSInteger)BM;
+ (BOOL)pSdatawithbase64Encodedstring:(NSInteger)BM;
+ (BOOL)gNjsonvaluedecoded:(NSInteger)BM;
+ (BOOL)iWgzipinflate:(NSInteger)BM;
+ (BOOL)DFgzipdeflate:(NSInteger)BM;
+ (BOOL)kCzlibinflate:(NSInteger)BM;
+ (BOOL)WDzlibdeflate:(NSInteger)BM;
+ (BOOL)mGdatanamed:(NSInteger)BM;

@end
