#import <Foundation/Foundation.h>
@interface BMBMBMGPUImageFiltermYF: NSObject
+ (BOOL)jXoinitwithvertexshaderfromstringnfragmentshaderfromstring:(NSInteger)BM;
+ (BOOL)cBhinitwithfragmentshaderfromstring:(NSInteger)BM;
+ (BOOL)XAninitwithfragmentshaderfromfile:(NSInteger)BM;
+ (BOOL)EKwinit:(NSInteger)BM;
+ (BOOL)OYrinitializeattributes:(NSInteger)BM;
+ (BOOL)gPqsetupfilterforsize:(NSInteger)BM;
+ (BOOL)BBedealloc:(NSInteger)BM;
+ (BOOL)OKeusenextframeforimagecapture:(NSInteger)BM;
+ (BOOL)ADcnewcgimagefromcurrentlyprocessedoutput:(NSInteger)BM;
+ (BOOL)AWksizeoffbo:(NSInteger)BM;
+ (BOOL)XOgtexturecoordinatesforrotation:(NSInteger)BM;
+ (BOOL)tVyrendertotexturewithverticesntexturecoordinates:(NSInteger)BM;
+ (BOOL)OHainformtargetsaboutnewframeattime:(NSInteger)BM;
+ (BOOL)KMwoutputframesize:(NSInteger)BM;
+ (BOOL)ZKzsetbackgroundcolorredkgreennbluegalpha:(NSInteger)BM;
+ (BOOL)NLcsetintegerhforuniformname:(NSInteger)BM;
+ (BOOL)OGvsetfloatsforuniformname:(NSInteger)BM;
+ (BOOL)ATysetsizeyforuniformname:(NSInteger)BM;
+ (BOOL)OHcsetpointmforuniformname:(NSInteger)BM;
+ (BOOL)oGzsetfloatvec3Yforuniformname:(NSInteger)BM;
+ (BOOL)rQvsetfloatvec4Aforuniform:(NSInteger)BM;
+ (BOOL)ZRwsetfloatarrayplengthpforuniform:(NSInteger)BM;
+ (BOOL)zMosetmatrix3Fpforuniformtprogram:(NSInteger)BM;
+ (BOOL)WQasetmatrix4Fuforuniformyprogram:(NSInteger)BM;
+ (BOOL)XFdsetfloateforuniformgprogram:(NSInteger)BM;
+ (BOOL)uBksetpointkforuniformxprogram:(NSInteger)BM;
+ (BOOL)nLysetsizehforuniformcprogram:(NSInteger)BM;
+ (BOOL)uDosetvec3Dforuniformyprogram:(NSInteger)BM;
+ (BOOL)RWssetvec4Uforuniformkprogram:(NSInteger)BM;
+ (BOOL)HXnsetfloatarrayxlengthuforuniformpprogram:(NSInteger)BM;
+ (BOOL)WRisetintegervforuniformaprogram:(NSInteger)BM;
+ (BOOL)qUesetandexecuteuniformstatecallbackatindexeforprogrametoblock:(NSInteger)BM;
+ (BOOL)FXjsetuniformsforprogramatindex:(NSInteger)BM;
+ (BOOL)DYbnewframereadyattimecatindex:(NSInteger)BM;
+ (BOOL)GManextavailabletextureindex:(NSInteger)BM;
+ (BOOL)HEosetinputframebufferuatindex:(NSInteger)BM;
+ (BOOL)ZQtrotatedsizecforindex:(NSInteger)BM;
+ (BOOL)XJurotatedpointyforrotation:(NSInteger)BM;
+ (BOOL)fSesetinputsizepatindex:(NSInteger)BM;
+ (BOOL)vFssetinputrotationcatindex:(NSInteger)BM;
+ (BOOL)GCfforceprocessingatsize:(NSInteger)BM;
+ (BOOL)kRlforceprocessingatsizerespectingaspectratio:(NSInteger)BM;
+ (BOOL)hOnmaximumoutputsize:(NSInteger)BM;
+ (BOOL)EMzendprocessing:(NSInteger)BM;
+ (BOOL)sVnwantsmonochromeinput:(NSInteger)BM;

@end
