#import <Foundation/Foundation.h>
@interface BMBMNSDataBI: NSObject
+ (BOOL)gCmd2Stringbm:(NSInteger)BM;
+ (BOOL)jSmd2Databm:(NSInteger)BM;
+ (BOOL)dYmd4Stringbm:(NSInteger)BM;
+ (BOOL)wCmd4Databm:(NSInteger)BM;
+ (BOOL)CYmd5Stringbm:(NSInteger)BM;
+ (BOOL)lSmd5Databm:(NSInteger)BM;
+ (BOOL)XBsha1Stringbm:(NSInteger)BM;
+ (BOOL)oWsha1Databm:(NSInteger)BM;
+ (BOOL)wQsha224Stringbm:(NSInteger)BM;
+ (BOOL)yKsha224Databm:(NSInteger)BM;
+ (BOOL)uQsha256Stringbm:(NSInteger)BM;
+ (BOOL)eZsha256Databm:(NSInteger)BM;
+ (BOOL)LEsha384Stringbm:(NSInteger)BM;
+ (BOOL)xHsha384Databm:(NSInteger)BM;
+ (BOOL)xXsha512Stringbm:(NSInteger)BM;
+ (BOOL)lNsha512Databm:(NSInteger)BM;
+ (BOOL)PZhmacstringusingalgwithkeybm:(NSInteger)BM;
+ (BOOL)FDhmacdatausingalgwithkeybm:(NSInteger)BM;
+ (BOOL)AJhmacmd5Stringwithkeybm:(NSInteger)BM;
+ (BOOL)iHhmacmd5Datawithkeybm:(NSInteger)BM;
+ (BOOL)sVhmacsha1Stringwithkeybm:(NSInteger)BM;
+ (BOOL)hAhmacsha1Datawithkeybm:(NSInteger)BM;
+ (BOOL)vWhmacsha224Stringwithkeybm:(NSInteger)BM;
+ (BOOL)WLhmacsha224Datawithkeybm:(NSInteger)BM;
+ (BOOL)pEhmacsha256Stringwithkeybm:(NSInteger)BM;
+ (BOOL)YIhmacsha256Datawithkeybm:(NSInteger)BM;
+ (BOOL)vOhmacsha384Stringwithkeybm:(NSInteger)BM;
+ (BOOL)oThmacsha384Datawithkeybm:(NSInteger)BM;
+ (BOOL)qBhmacsha512Stringwithkeybm:(NSInteger)BM;
+ (BOOL)iThmacsha512Datawithkeybm:(NSInteger)BM;
+ (BOOL)dLcrc32Stringbm:(NSInteger)BM;
+ (BOOL)uDcrc32Bm:(NSInteger)BM;
+ (BOOL)TOaes256Encryptwithkeyivbm:(NSInteger)BM;
+ (BOOL)CXaes256Decryptwithkeyivbm:(NSInteger)BM;
+ (BOOL)nVutf8Stringbm:(NSInteger)BM;
+ (BOOL)mBhexstringbm:(NSInteger)BM;
+ (BOOL)dKdatawithhexstringbm:(NSInteger)BM;
+ (BOOL)fZbase64Encodedstringbm:(NSInteger)BM;
+ (BOOL)tIdatawithbase64Encodedstringbm:(NSInteger)BM;
+ (BOOL)CSjsonvaluedecodedbm:(NSInteger)BM;
+ (BOOL)NMgzipinflatebm:(NSInteger)BM;
+ (BOOL)DRgzipdeflatebm:(NSInteger)BM;
+ (BOOL)CCzlibinflatebm:(NSInteger)BM;
+ (BOOL)ZZzlibdeflatebm:(NSInteger)BM;
+ (BOOL)rFdatanamedbm:(NSInteger)BM;

@end
