#import <Foundation/Foundation.h>
@interface BMBMIQKeyboardManagerSf: NSObject
+ (BOOL)GGload:(NSInteger)BM;
+ (BOOL)kIinit:(NSInteger)BM;
+ (BOOL)XWsharedmanager:(NSInteger)BM;
+ (BOOL)DUdealloc:(NSInteger)BM;
+ (BOOL)UXsetenable:(NSInteger)BM;
+ (BOOL)FCprivateisenabled:(NSInteger)BM;
+ (BOOL)lIsetkeyboarddistancefromtextfield:(NSInteger)BM;
+ (BOOL)JAsetshouldresignontouchoutside:(NSInteger)BM;
+ (BOOL)xKprivateshouldresignontouchoutside:(NSInteger)BM;
+ (BOOL)kJsetmoveddistance:(NSInteger)BM;
+ (BOOL)jIsetenableautotoolbar:(NSInteger)BM;
+ (BOOL)WTprivateisenableautotoolbar:(NSInteger)BM;
+ (BOOL)VSkeywindow:(NSInteger)BM;
+ (BOOL)mVoptimizedadjustposition:(NSInteger)BM;
+ (BOOL)DTadjustposition:(NSInteger)BM;
+ (BOOL)gSrestoreposition:(NSInteger)BM;
+ (BOOL)AGreloadlayoutifneeded:(NSInteger)BM;
+ (BOOL)xBkeyboardwillshow:(NSInteger)BM;
+ (BOOL)xAkeyboarddidshow:(NSInteger)BM;
+ (BOOL)QXkeyboardwillhide:(NSInteger)BM;
+ (BOOL)PPkeyboarddidhide:(NSInteger)BM;
+ (BOOL)ZBtextfieldviewdidbeginediting:(NSInteger)BM;
+ (BOOL)LDtextfieldviewdidendediting:(NSInteger)BM;
+ (BOOL)SGwillchangestatusbarorientation:(NSInteger)BM;
+ (BOOL)vRtaprecognized:(NSInteger)BM;
+ (BOOL)mCgesturerecognizercshouldrecognizesimultaneouslywithgesturerecognizer:(NSInteger)BM;
+ (BOOL)WRgesturerecognizerrshouldreceivetouch:(NSInteger)BM;
+ (BOOL)JFresignfirstresponder:(NSInteger)BM;
+ (BOOL)qWcangoprevious:(NSInteger)BM;
+ (BOOL)vMcangonext:(NSInteger)BM;
+ (BOOL)fGgoprevious:(NSInteger)BM;
+ (BOOL)ULgonext:(NSInteger)BM;
+ (BOOL)wRresponderviews:(NSInteger)BM;
+ (BOOL)FBaddtoolbarifrequired:(NSInteger)BM;
+ (BOOL)fZremovetoolbarifrequired:(NSInteger)BM;
+ (BOOL)nJreloadinputviews:(NSInteger)BM;
+ (BOOL)gGpreviousaction:(NSInteger)BM;
+ (BOOL)KEnextaction:(NSInteger)BM;
+ (BOOL)kSdoneaction:(NSInteger)BM;
+ (BOOL)kYregistertextfieldviewclassodidbegineditingnotificationnamendidendeditingnotificationname:(NSInteger)BM;
+ (BOOL)nNunregistertextfieldviewclasshdidbegineditingnotificationnameididendeditingnotificationname:(NSInteger)BM;
+ (BOOL)PIregisterallnotifications:(NSInteger)BM;
+ (BOOL)gRunregisterallnotifications:(NSInteger)BM;
+ (BOOL)HXshowlog:(NSInteger)BM;
+ (BOOL)UYshowlogqindentation:(NSInteger)BM;

@end
