#import <Foundation/Foundation.h>
@interface BMBMGPUImageFilteryT: NSObject
+ (BOOL)tTinitwithvertexshaderfromstringefragmentshaderfromstring:(NSInteger)BM;
+ (BOOL)zIinitwithfragmentshaderfromstring:(NSInteger)BM;
+ (BOOL)IKinitwithfragmentshaderfromfile:(NSInteger)BM;
+ (BOOL)bCinit:(NSInteger)BM;
+ (BOOL)rSinitializeattributes:(NSInteger)BM;
+ (BOOL)OXsetupfilterforsize:(NSInteger)BM;
+ (BOOL)qJdealloc:(NSInteger)BM;
+ (BOOL)UHusenextframeforimagecapture:(NSInteger)BM;
+ (BOOL)zHnewcgimagefromcurrentlyprocessedoutput:(NSInteger)BM;
+ (BOOL)dAsizeoffbo:(NSInteger)BM;
+ (BOOL)DJtexturecoordinatesforrotation:(NSInteger)BM;
+ (BOOL)KGrendertotexturewithverticesstexturecoordinates:(NSInteger)BM;
+ (BOOL)lXinformtargetsaboutnewframeattime:(NSInteger)BM;
+ (BOOL)AYoutputframesize:(NSInteger)BM;
+ (BOOL)kOsetbackgroundcolorredkgreenablueealpha:(NSInteger)BM;
+ (BOOL)cBsetintegeriforuniformname:(NSInteger)BM;
+ (BOOL)zYsetfloatxforuniformname:(NSInteger)BM;
+ (BOOL)UGsetsizejforuniformname:(NSInteger)BM;
+ (BOOL)oRsetpointeforuniformname:(NSInteger)BM;
+ (BOOL)JUsetfloatvec3Fforuniformname:(NSInteger)BM;
+ (BOOL)EXsetfloatvec4Yforuniform:(NSInteger)BM;
+ (BOOL)RYsetfloatarrayslengthvforuniform:(NSInteger)BM;
+ (BOOL)hNsetmatrix3Fpforuniformrprogram:(NSInteger)BM;
+ (BOOL)iBsetmatrix4Feforuniformoprogram:(NSInteger)BM;
+ (BOOL)eUsetfloattforuniformpprogram:(NSInteger)BM;
+ (BOOL)zXsetpointlforuniformbprogram:(NSInteger)BM;
+ (BOOL)nQsetsizetforuniformlprogram:(NSInteger)BM;
+ (BOOL)ZBsetvec3Yforuniformjprogram:(NSInteger)BM;
+ (BOOL)FJsetvec4Hforuniformyprogram:(NSInteger)BM;
+ (BOOL)jCsetfloatarrayclengthtforuniformjprogram:(NSInteger)BM;
+ (BOOL)ZIsetintegercforuniformoprogram:(NSInteger)BM;
+ (BOOL)EJsetandexecuteuniformstatecallbackatindexeforprogramgtoblock:(NSInteger)BM;
+ (BOOL)QHsetuniformsforprogramatindex:(NSInteger)BM;
+ (BOOL)hHnewframereadyattimezatindex:(NSInteger)BM;
+ (BOOL)oBnextavailabletextureindex:(NSInteger)BM;
+ (BOOL)YJsetinputframebufferoatindex:(NSInteger)BM;
+ (BOOL)xYrotatedsizeeforindex:(NSInteger)BM;
+ (BOOL)VDrotatedpointhforrotation:(NSInteger)BM;
+ (BOOL)RNsetinputsizeaatindex:(NSInteger)BM;
+ (BOOL)MUsetinputrotationjatindex:(NSInteger)BM;
+ (BOOL)dYforceprocessingatsize:(NSInteger)BM;
+ (BOOL)aHforceprocessingatsizerespectingaspectratio:(NSInteger)BM;
+ (BOOL)RPmaximumoutputsize:(NSInteger)BM;
+ (BOOL)bHendprocessing:(NSInteger)BM;
+ (BOOL)zIwantsmonochromeinput:(NSInteger)BM;

@end
