#import <Foundation/Foundation.h>
@interface BMBMNSDataep: NSObject
+ (BOOL)wPmd2String:(NSInteger)BM;
+ (BOOL)NDmd2Data:(NSInteger)BM;
+ (BOOL)AXmd4String:(NSInteger)BM;
+ (BOOL)QWmd4Data:(NSInteger)BM;
+ (BOOL)aQmd5String:(NSInteger)BM;
+ (BOOL)GKmd5Data:(NSInteger)BM;
+ (BOOL)bMsha1String:(NSInteger)BM;
+ (BOOL)CPsha1Data:(NSInteger)BM;
+ (BOOL)oPsha224String:(NSInteger)BM;
+ (BOOL)CZsha224Data:(NSInteger)BM;
+ (BOOL)DQsha256String:(NSInteger)BM;
+ (BOOL)zKsha256Data:(NSInteger)BM;
+ (BOOL)mGsha384String:(NSInteger)BM;
+ (BOOL)yMsha384Data:(NSInteger)BM;
+ (BOOL)FQsha512String:(NSInteger)BM;
+ (BOOL)TRsha512Data:(NSInteger)BM;
+ (BOOL)KFhmacstringusingalgtwithkey:(NSInteger)BM;
+ (BOOL)ZDhmacdatausingalgiwithkey:(NSInteger)BM;
+ (BOOL)lDhmacmd5Stringwithkey:(NSInteger)BM;
+ (BOOL)fBhmacmd5Datawithkey:(NSInteger)BM;
+ (BOOL)cLhmacsha1Stringwithkey:(NSInteger)BM;
+ (BOOL)DKhmacsha1Datawithkey:(NSInteger)BM;
+ (BOOL)IShmacsha224Stringwithkey:(NSInteger)BM;
+ (BOOL)UJhmacsha224Datawithkey:(NSInteger)BM;
+ (BOOL)APhmacsha256Stringwithkey:(NSInteger)BM;
+ (BOOL)RAhmacsha256Datawithkey:(NSInteger)BM;
+ (BOOL)kRhmacsha384Stringwithkey:(NSInteger)BM;
+ (BOOL)qNhmacsha384Datawithkey:(NSInteger)BM;
+ (BOOL)aKhmacsha512Stringwithkey:(NSInteger)BM;
+ (BOOL)sDhmacsha512Datawithkey:(NSInteger)BM;
+ (BOOL)rOcrc32String:(NSInteger)BM;
+ (BOOL)EHcrc32:(NSInteger)BM;
+ (BOOL)LIaes256Encryptwithkeysiv:(NSInteger)BM;
+ (BOOL)bPaes256Decryptwithkeyjiv:(NSInteger)BM;
+ (BOOL)QLutf8String:(NSInteger)BM;
+ (BOOL)gIhexstring:(NSInteger)BM;
+ (BOOL)rFdatawithhexstring:(NSInteger)BM;
+ (BOOL)RLbase64Encodedstring:(NSInteger)BM;
+ (BOOL)GVdatawithbase64Encodedstring:(NSInteger)BM;
+ (BOOL)fJjsonvaluedecoded:(NSInteger)BM;
+ (BOOL)VLgzipinflate:(NSInteger)BM;
+ (BOOL)xIgzipdeflate:(NSInteger)BM;
+ (BOOL)RGzlibinflate:(NSInteger)BM;
+ (BOOL)BVzlibdeflate:(NSInteger)BM;
+ (BOOL)bYdatanamed:(NSInteger)BM;

@end
