#import <Foundation/Foundation.h>
@interface BMBMBMNSDataepI: NSObject
+ (BOOL)wWpmd2String:(NSInteger)BM;
+ (BOOL)dNdmd2Data:(NSInteger)BM;
+ (BOOL)qAxmd4String:(NSInteger)BM;
+ (BOOL)SQwmd4Data:(NSInteger)BM;
+ (BOOL)dAqmd5String:(NSInteger)BM;
+ (BOOL)jGkmd5Data:(NSInteger)BM;
+ (BOOL)rBmsha1String:(NSInteger)BM;
+ (BOOL)JCpsha1Data:(NSInteger)BM;
+ (BOOL)QOpsha224String:(NSInteger)BM;
+ (BOOL)LCzsha224Data:(NSInteger)BM;
+ (BOOL)LDqsha256String:(NSInteger)BM;
+ (BOOL)fZksha256Data:(NSInteger)BM;
+ (BOOL)nMgsha384String:(NSInteger)BM;
+ (BOOL)tYmsha384Data:(NSInteger)BM;
+ (BOOL)pFqsha512String:(NSInteger)BM;
+ (BOOL)dTrsha512Data:(NSInteger)BM;
+ (BOOL)QKfhmacstringusingalgtwithkey:(NSInteger)BM;
+ (BOOL)DZdhmacdatausingalgiwithkey:(NSInteger)BM;
+ (BOOL)NLdhmacmd5Stringwithkey:(NSInteger)BM;
+ (BOOL)QFbhmacmd5Datawithkey:(NSInteger)BM;
+ (BOOL)LClhmacsha1Stringwithkey:(NSInteger)BM;
+ (BOOL)GDkhmacsha1Datawithkey:(NSInteger)BM;
+ (BOOL)iIshmacsha224Stringwithkey:(NSInteger)BM;
+ (BOOL)eUjhmacsha224Datawithkey:(NSInteger)BM;
+ (BOOL)fAphmacsha256Stringwithkey:(NSInteger)BM;
+ (BOOL)SRahmacsha256Datawithkey:(NSInteger)BM;
+ (BOOL)TKrhmacsha384Stringwithkey:(NSInteger)BM;
+ (BOOL)GQnhmacsha384Datawithkey:(NSInteger)BM;
+ (BOOL)rAkhmacsha512Stringwithkey:(NSInteger)BM;
+ (BOOL)BSdhmacsha512Datawithkey:(NSInteger)BM;
+ (BOOL)gRocrc32String:(NSInteger)BM;
+ (BOOL)lEhcrc32:(NSInteger)BM;
+ (BOOL)fLiaes256Encryptwithkeysiv:(NSInteger)BM;
+ (BOOL)ZBpaes256Decryptwithkeyjiv:(NSInteger)BM;
+ (BOOL)XQlutf8String:(NSInteger)BM;
+ (BOOL)KGihexstring:(NSInteger)BM;
+ (BOOL)QRfdatawithhexstring:(NSInteger)BM;
+ (BOOL)fRlbase64Encodedstring:(NSInteger)BM;
+ (BOOL)mGvdatawithbase64Encodedstring:(NSInteger)BM;
+ (BOOL)iFjjsonvaluedecoded:(NSInteger)BM;
+ (BOOL)pVlgzipinflate:(NSInteger)BM;
+ (BOOL)vXigzipdeflate:(NSInteger)BM;
+ (BOOL)QRgzlibinflate:(NSInteger)BM;
+ (BOOL)FBvzlibdeflate:(NSInteger)BM;
+ (BOOL)dBydatanamed:(NSInteger)BM;

@end
