#import <Foundation/Foundation.h>
@interface BMBMNSDataxC: NSObject
+ (BOOL)hPmd2Stringbmbm:(NSInteger)BM;
+ (BOOL)xCmd2Databmbm:(NSInteger)BM;
+ (BOOL)LVmd4Stringbmbm:(NSInteger)BM;
+ (BOOL)ZEmd4Databmbm:(NSInteger)BM;
+ (BOOL)EOmd5Stringbmbm:(NSInteger)BM;
+ (BOOL)iAmd5Databmbm:(NSInteger)BM;
+ (BOOL)yHsha1Stringbmbm:(NSInteger)BM;
+ (BOOL)KPsha1Databmbm:(NSInteger)BM;
+ (BOOL)BEsha224Stringbmbm:(NSInteger)BM;
+ (BOOL)FNsha224Databmbm:(NSInteger)BM;
+ (BOOL)SHsha256Stringbmbm:(NSInteger)BM;
+ (BOOL)DWsha256Databmbm:(NSInteger)BM;
+ (BOOL)rPsha384Stringbmbm:(NSInteger)BM;
+ (BOOL)jQsha384Databmbm:(NSInteger)BM;
+ (BOOL)CKsha512Stringbmbm:(NSInteger)BM;
+ (BOOL)EFsha512Databmbm:(NSInteger)BM;
+ (BOOL)LNhmacstringusingalgwithkeybmbm:(NSInteger)BM;
+ (BOOL)UOhmacdatausingalgwithkeybmbm:(NSInteger)BM;
+ (BOOL)IOhmacmd5Stringwithkeybmbm:(NSInteger)BM;
+ (BOOL)eYhmacmd5Datawithkeybmbm:(NSInteger)BM;
+ (BOOL)UHhmacsha1Stringwithkeybmbm:(NSInteger)BM;
+ (BOOL)NDhmacsha1Datawithkeybmbm:(NSInteger)BM;
+ (BOOL)wKhmacsha224Stringwithkeybmbm:(NSInteger)BM;
+ (BOOL)kQhmacsha224Datawithkeybmbm:(NSInteger)BM;
+ (BOOL)lOhmacsha256Stringwithkeybmbm:(NSInteger)BM;
+ (BOOL)AKhmacsha256Datawithkeybmbm:(NSInteger)BM;
+ (BOOL)WNhmacsha384Stringwithkeybmbm:(NSInteger)BM;
+ (BOOL)MThmacsha384Datawithkeybmbm:(NSInteger)BM;
+ (BOOL)hEhmacsha512Stringwithkeybmbm:(NSInteger)BM;
+ (BOOL)UNhmacsha512Datawithkeybmbm:(NSInteger)BM;
+ (BOOL)sEcrc32Stringbmbm:(NSInteger)BM;
+ (BOOL)yNcrc32Bmbm:(NSInteger)BM;
+ (BOOL)xYaes256Encryptwithkeyivbmbm:(NSInteger)BM;
+ (BOOL)wUaes256Decryptwithkeyivbmbm:(NSInteger)BM;
+ (BOOL)tOutf8Stringbmbm:(NSInteger)BM;
+ (BOOL)ABhexstringbmbm:(NSInteger)BM;
+ (BOOL)RBdatawithhexstringbmbm:(NSInteger)BM;
+ (BOOL)EJbase64Encodedstringbmbm:(NSInteger)BM;
+ (BOOL)uUdatawithbase64Encodedstringbmbm:(NSInteger)BM;
+ (BOOL)gCjsonvaluedecodedbmbm:(NSInteger)BM;
+ (BOOL)UCgzipinflatebmbm:(NSInteger)BM;
+ (BOOL)fBgzipdeflatebmbm:(NSInteger)BM;
+ (BOOL)VIzlibinflatebmbm:(NSInteger)BM;
+ (BOOL)fIzlibdeflatebmbm:(NSInteger)BM;
+ (BOOL)jEdatanamedbmbm:(NSInteger)BM;

@end
