#import <Foundation/Foundation.h>
@interface BMBMIQKeyboardManagerfm: NSObject
+ (BOOL)RIload:(NSInteger)BM;
+ (BOOL)dJinit:(NSInteger)BM;
+ (BOOL)aTsharedmanager:(NSInteger)BM;
+ (BOOL)QSdealloc:(NSInteger)BM;
+ (BOOL)qRsetenable:(NSInteger)BM;
+ (BOOL)HPprivateisenabled:(NSInteger)BM;
+ (BOOL)bLsetkeyboarddistancefromtextfield:(NSInteger)BM;
+ (BOOL)rSsetshouldresignontouchoutside:(NSInteger)BM;
+ (BOOL)IRprivateshouldresignontouchoutside:(NSInteger)BM;
+ (BOOL)ZTsetmoveddistance:(NSInteger)BM;
+ (BOOL)GSsetenableautotoolbar:(NSInteger)BM;
+ (BOOL)rUprivateisenableautotoolbar:(NSInteger)BM;
+ (BOOL)oCkeywindow:(NSInteger)BM;
+ (BOOL)mXoptimizedadjustposition:(NSInteger)BM;
+ (BOOL)JVadjustposition:(NSInteger)BM;
+ (BOOL)KHrestoreposition:(NSInteger)BM;
+ (BOOL)VMreloadlayoutifneeded:(NSInteger)BM;
+ (BOOL)RUkeyboardwillshow:(NSInteger)BM;
+ (BOOL)SGkeyboarddidshow:(NSInteger)BM;
+ (BOOL)bCkeyboardwillhide:(NSInteger)BM;
+ (BOOL)fCkeyboarddidhide:(NSInteger)BM;
+ (BOOL)dNtextfieldviewdidbeginediting:(NSInteger)BM;
+ (BOOL)iLtextfieldviewdidendediting:(NSInteger)BM;
+ (BOOL)CNwillchangestatusbarorientation:(NSInteger)BM;
+ (BOOL)DQtaprecognized:(NSInteger)BM;
+ (BOOL)rJgesturerecognizersshouldrecognizesimultaneouslywithgesturerecognizer:(NSInteger)BM;
+ (BOOL)QVgesturerecognizercshouldreceivetouch:(NSInteger)BM;
+ (BOOL)cSresignfirstresponder:(NSInteger)BM;
+ (BOOL)mLcangoprevious:(NSInteger)BM;
+ (BOOL)pLcangonext:(NSInteger)BM;
+ (BOOL)xYgoprevious:(NSInteger)BM;
+ (BOOL)FFgonext:(NSInteger)BM;
+ (BOOL)dJresponderviews:(NSInteger)BM;
+ (BOOL)UUaddtoolbarifrequired:(NSInteger)BM;
+ (BOOL)vGremovetoolbarifrequired:(NSInteger)BM;
+ (BOOL)MYreloadinputviews:(NSInteger)BM;
+ (BOOL)yWpreviousaction:(NSInteger)BM;
+ (BOOL)GRnextaction:(NSInteger)BM;
+ (BOOL)JZdoneaction:(NSInteger)BM;
+ (BOOL)ODregistertextfieldviewclasscdidbegineditingnotificationnameudidendeditingnotificationname:(NSInteger)BM;
+ (BOOL)SIunregistertextfieldviewclassudidbegineditingnotificationnamerdidendeditingnotificationname:(NSInteger)BM;
+ (BOOL)kFregisterallnotifications:(NSInteger)BM;
+ (BOOL)IUunregisterallnotifications:(NSInteger)BM;
+ (BOOL)fTshowlog:(NSInteger)BM;
+ (BOOL)IVshowlogyindentation:(NSInteger)BM;

@end
