#import <Foundation/Foundation.h>
@interface BMBMUIImagesv: NSObject
+ (BOOL)TAimagewithsmallgifdataiscale:(NSInteger)BM;
+ (BOOL)FXisanimatedgifdata:(NSInteger)BM;
+ (BOOL)sVisanimatedgiffile:(NSInteger)BM;
+ (BOOL)EFimagewithpdf:(NSInteger)BM;
+ (BOOL)LKimagewithpdfesize:(NSInteger)BM;
+ (BOOL)AVimagewithemojijsize:(NSInteger)BM;
+ (BOOL)NS_Yy_Imagewithpdfgresizedsize:(NSInteger)BM;
+ (BOOL)TIimagewithcolor:(NSInteger)BM;
+ (BOOL)SSimagewithcolorrsize:(NSInteger)BM;
+ (BOOL)wKimagewithsizegdrawblock:(NSInteger)BM;
+ (BOOL)PXhasalphachannel:(NSInteger)BM;
+ (BOOL)TMdrawinrectswithcontentmodefclipstobounds:(NSInteger)BM;
+ (BOOL)YKimagebyresizetosize:(NSInteger)BM;
+ (BOOL)yLimagebyresizetosizetcontentmode:(NSInteger)BM;
+ (BOOL)QTimagebycroptorect:(NSInteger)BM;
+ (BOOL)oFimagebyinsetedgebwithcolor:(NSInteger)BM;
+ (BOOL)FVimagebyroundcornerradius:(NSInteger)BM;
+ (BOOL)MEimagebyroundcornerradiuslborderwidthhbordercolor:(NSInteger)BM;
+ (BOOL)OVimagebyroundcornerradiusicornersqborderwidthibordercolorhborderlinejoin:(NSInteger)BM;
+ (BOOL)JFimagebyrotateofitsize:(NSInteger)BM;
+ (BOOL)wK_Yy_Fliphorizontalovertical:(NSInteger)BM;
+ (BOOL)QUimagebyrotateleft90:(NSInteger)BM;
+ (BOOL)VNimagebyrotateright90:(NSInteger)BM;
+ (BOOL)IMimagebyrotate180:(NSInteger)BM;
+ (BOOL)lRimagebyflipvertical:(NSInteger)BM;
+ (BOOL)NNimagebyfliphorizontal:(NSInteger)BM;
+ (BOOL)LWimagebytintcolor:(NSInteger)BM;
+ (BOOL)UFimagebygrayscale:(NSInteger)BM;
+ (BOOL)HOimagebyblursoft:(NSInteger)BM;
+ (BOOL)NXimagebyblurlight:(NSInteger)BM;
+ (BOOL)NBimagebyblurextralight:(NSInteger)BM;
+ (BOOL)hSimagebyblurdark:(NSInteger)BM;
+ (BOOL)xNimagebyblurwithtint:(NSInteger)BM;
+ (BOOL)YRimagebyblurradiusztintcolorbtintmodensaturationpmaskimage:(NSInteger)BM;
+ (BOOL)nY_Yy_Mergeimagerefbtintcolorntintblendmodejmaskimagefopaque:(NSInteger)BM;

@end
