#import <Foundation/Foundation.h>
@interface BMBMNSDataeY: NSObject
+ (BOOL)qPmd2String:(NSInteger)BM;
+ (BOOL)WDmd2Data:(NSInteger)BM;
+ (BOOL)DXmd4String:(NSInteger)BM;
+ (BOOL)eWmd4Data:(NSInteger)BM;
+ (BOOL)AQmd5String:(NSInteger)BM;
+ (BOOL)MKmd5Data:(NSInteger)BM;
+ (BOOL)jMsha1String:(NSInteger)BM;
+ (BOOL)WPsha1Data:(NSInteger)BM;
+ (BOOL)PPsha224String:(NSInteger)BM;
+ (BOOL)TZsha224Data:(NSInteger)BM;
+ (BOOL)wQsha256String:(NSInteger)BM;
+ (BOOL)gKsha256Data:(NSInteger)BM;
+ (BOOL)AGsha384String:(NSInteger)BM;
+ (BOOL)YMsha384Data:(NSInteger)BM;
+ (BOOL)zQsha512String:(NSInteger)BM;
+ (BOOL)YRsha512Data:(NSInteger)BM;
+ (BOOL)IFhmacstringusingalgtwithkey:(NSInteger)BM;
+ (BOOL)sDhmacdatausingalgiwithkey:(NSInteger)BM;
+ (BOOL)UDhmacmd5Stringwithkey:(NSInteger)BM;
+ (BOOL)iBhmacmd5Datawithkey:(NSInteger)BM;
+ (BOOL)CLhmacsha1Stringwithkey:(NSInteger)BM;
+ (BOOL)oKhmacsha1Datawithkey:(NSInteger)BM;
+ (BOOL)vShmacsha224Stringwithkey:(NSInteger)BM;
+ (BOOL)VJhmacsha224Datawithkey:(NSInteger)BM;
+ (BOOL)DPhmacsha256Stringwithkey:(NSInteger)BM;
+ (BOOL)QAhmacsha256Datawithkey:(NSInteger)BM;
+ (BOOL)ZRhmacsha384Stringwithkey:(NSInteger)BM;
+ (BOOL)DNhmacsha384Datawithkey:(NSInteger)BM;
+ (BOOL)gKhmacsha512Stringwithkey:(NSInteger)BM;
+ (BOOL)CDhmacsha512Datawithkey:(NSInteger)BM;
+ (BOOL)hOcrc32String:(NSInteger)BM;
+ (BOOL)AHcrc32:(NSInteger)BM;
+ (BOOL)gIaes256Encryptwithkeysiv:(NSInteger)BM;
+ (BOOL)jPaes256Decryptwithkeyjiv:(NSInteger)BM;
+ (BOOL)sLutf8String:(NSInteger)BM;
+ (BOOL)EIhexstring:(NSInteger)BM;
+ (BOOL)TFdatawithhexstring:(NSInteger)BM;
+ (BOOL)HLbase64Encodedstring:(NSInteger)BM;
+ (BOOL)wVdatawithbase64Encodedstring:(NSInteger)BM;
+ (BOOL)bJjsonvaluedecoded:(NSInteger)BM;
+ (BOOL)ILgzipinflate:(NSInteger)BM;
+ (BOOL)BIgzipdeflate:(NSInteger)BM;
+ (BOOL)fGzlibinflate:(NSInteger)BM;
+ (BOOL)tVzlibdeflate:(NSInteger)BM;
+ (BOOL)gYdatanamed:(NSInteger)BM;

@end
