#import <Foundation/Foundation.h>
@interface BMBMMBProgressHUDPi: NSObject
+ (BOOL)GEshowhudaddedtojanimated:(NSInteger)BM;
+ (BOOL)HLhidehudforviewganimated:(NSInteger)BM;
+ (BOOL)DLhideallhudsforviewwanimated:(NSInteger)BM;
+ (BOOL)KJhudforview:(NSInteger)BM;
+ (BOOL)iMallhudsforview:(NSInteger)BM;
+ (BOOL)JTinitwithframe:(NSInteger)BM;
+ (BOOL)YFinitwithview:(NSInteger)BM;
+ (BOOL)nBinitwithwindow:(NSInteger)BM;
+ (BOOL)kYdealloc:(NSInteger)BM;
+ (BOOL)gXshow:(NSInteger)BM;
+ (BOOL)uIhide:(NSInteger)BM;
+ (BOOL)eHhideqafterdelay:(NSInteger)BM;
+ (BOOL)APhidedelayed:(NSInteger)BM;
+ (BOOL)ELhandlegracetimer:(NSInteger)BM;
+ (BOOL)SChandleminshowtimer:(NSInteger)BM;
+ (BOOL)zUdidmovetosuperview:(NSInteger)BM;
+ (BOOL)aDshowusinganimation:(NSInteger)BM;
+ (BOOL)gKhideusinganimation:(NSInteger)BM;
+ (BOOL)WLanimationfinishedpfinishedpcontext:(NSInteger)BM;
+ (BOOL)jZdone:(NSInteger)BM;
+ (BOOL)JFshowwhileexecutingaontargetnwithobjecthanimated:(NSInteger)BM;
+ (BOOL)FBshowanimatedkwhileexecutingblock:(NSInteger)BM;
+ (BOOL)WUshowanimatedjwhileexecutingblockhcompletionblock:(NSInteger)BM;
+ (BOOL)tUshowanimatedawhileexecutingblockbonqueue:(NSInteger)BM;
+ (BOOL)RHshowanimatedpwhileexecutingblockjonqueuercompletionblock:(NSInteger)BM;
+ (BOOL)YSlaunchexecution:(NSInteger)BM;
+ (BOOL)IScleanup:(NSInteger)BM;
+ (BOOL)zZsetuplabels:(NSInteger)BM;
+ (BOOL)lWupdateindicators:(NSInteger)BM;
+ (BOOL)JZlayoutsubviews:(NSInteger)BM;
+ (BOOL)EBdrawrect:(NSInteger)BM;
+ (BOOL)ZRregisterforkvo:(NSInteger)BM;
+ (BOOL)SBunregisterfromkvo:(NSInteger)BM;
+ (BOOL)NZobservablekeypaths:(NSInteger)BM;
+ (BOOL)oZobservevalueforkeypathuofobjecthchangeocontext:(NSInteger)BM;
+ (BOOL)dWupdateuiforkeypath:(NSInteger)BM;
+ (BOOL)VJregisterfornotifications:(NSInteger)BM;
+ (BOOL)zJunregisterfromnotifications:(NSInteger)BM;
+ (BOOL)oRstatusbarorientationdidchange:(NSInteger)BM;
+ (BOOL)GTupdateforcurrentorientationanimated:(NSInteger)BM;

@end
