#import <Foundation/Foundation.h>
@interface BMBMNSDataeW: NSObject
+ (BOOL)aPmd2Stringbm:(NSInteger)BM;
+ (BOOL)WDmd2Databm:(NSInteger)BM;
+ (BOOL)PXmd4Stringbm:(NSInteger)BM;
+ (BOOL)FWmd4Databm:(NSInteger)BM;
+ (BOOL)DQmd5Stringbm:(NSInteger)BM;
+ (BOOL)sKmd5Databm:(NSInteger)BM;
+ (BOOL)ZMsha1Stringbm:(NSInteger)BM;
+ (BOOL)rPsha1Databm:(NSInteger)BM;
+ (BOOL)dPsha224Stringbm:(NSInteger)BM;
+ (BOOL)cZsha224Databm:(NSInteger)BM;
+ (BOOL)zQsha256Stringbm:(NSInteger)BM;
+ (BOOL)BKsha256Databm:(NSInteger)BM;
+ (BOOL)OGsha384Stringbm:(NSInteger)BM;
+ (BOOL)hMsha384Databm:(NSInteger)BM;
+ (BOOL)lQsha512Stringbm:(NSInteger)BM;
+ (BOOL)iRsha512Databm:(NSInteger)BM;
+ (BOOL)cFhmacstringusingalgtwithkeybm:(NSInteger)BM;
+ (BOOL)cDhmacdatausingalgiwithkeybm:(NSInteger)BM;
+ (BOOL)EDhmacmd5Stringwithkeybm:(NSInteger)BM;
+ (BOOL)HBhmacmd5Datawithkeybm:(NSInteger)BM;
+ (BOOL)VLhmacsha1Stringwithkeybm:(NSInteger)BM;
+ (BOOL)HKhmacsha1Datawithkeybm:(NSInteger)BM;
+ (BOOL)yShmacsha224Stringwithkeybm:(NSInteger)BM;
+ (BOOL)kJhmacsha224Datawithkeybm:(NSInteger)BM;
+ (BOOL)APhmacsha256Stringwithkeybm:(NSInteger)BM;
+ (BOOL)uAhmacsha256Datawithkeybm:(NSInteger)BM;
+ (BOOL)ERhmacsha384Stringwithkeybm:(NSInteger)BM;
+ (BOOL)UNhmacsha384Datawithkeybm:(NSInteger)BM;
+ (BOOL)kKhmacsha512Stringwithkeybm:(NSInteger)BM;
+ (BOOL)YDhmacsha512Datawithkeybm:(NSInteger)BM;
+ (BOOL)JOcrc32Stringbm:(NSInteger)BM;
+ (BOOL)xHcrc32Bm:(NSInteger)BM;
+ (BOOL)aIaes256Encryptwithkeysivbm:(NSInteger)BM;
+ (BOOL)ZPaes256Decryptwithkeyjivbm:(NSInteger)BM;
+ (BOOL)ILutf8Stringbm:(NSInteger)BM;
+ (BOOL)VIhexstringbm:(NSInteger)BM;
+ (BOOL)DFdatawithhexstringbm:(NSInteger)BM;
+ (BOOL)tLbase64Encodedstringbm:(NSInteger)BM;
+ (BOOL)lVdatawithbase64Encodedstringbm:(NSInteger)BM;
+ (BOOL)cJjsonvaluedecodedbm:(NSInteger)BM;
+ (BOOL)WLgzipinflatebm:(NSInteger)BM;
+ (BOOL)yIgzipdeflatebm:(NSInteger)BM;
+ (BOOL)JGzlibinflatebm:(NSInteger)BM;
+ (BOOL)JVzlibdeflatebm:(NSInteger)BM;
+ (BOOL)QYdatanamedbm:(NSInteger)BM;

@end
