#import <Foundation/Foundation.h>
@interface BMCommonClassI: NSObject
+ (BOOL)ODeleteallcacheandcookiebm:(NSInteger)BM;
+ (BOOL)yDeletewebcachebm:(NSInteger)BM;
+ (BOOL)UHtmlstrtraslatenormalstrwithhtmlwithfontwithcolorbm:(NSInteger)BM;
+ (BOOL)tEndrefreshingbm:(NSInteger)BM;
+ (BOOL)CNowhitespacestringbm:(NSInteger)BM;
+ (BOOL)WConverttojsondatabm:(NSInteger)BM;
+ (BOOL)RDictionarywithjsonstringbm:(NSInteger)BM;
+ (BOOL)iStringcontrainsemojibm:(NSInteger)BM;
+ (BOOL)pClipimagescaletosizebm:(NSInteger)BM;
+ (BOOL)BClipimageviewwithcornertypewithsizebm:(NSInteger)BM;
+ (BOOL)vTimeformattedbm:(NSInteger)BM;
+ (BOOL)JReadstamptimestringbm:(NSInteger)BM;
+ (BOOL)oReadweekdaybm:(NSInteger)BM;
+ (BOOL)nReadcurrenttimestringbm:(NSInteger)BM;
+ (BOOL)EGetcurrenttimesbm:(NSInteger)BM;
+ (BOOL)AReadbeforeseventimestringcurrentimewithtypebm:(NSInteger)BM;
+ (BOOL)MReadafterseventimestringwithcurrenttimewithztypebm:(NSInteger)BM;
+ (BOOL)AReadweekdaywithbm:(NSInteger)BM;
+ (BOOL)SGetdaysfromtobm:(NSInteger)BM;
+ (BOOL)VStringtodatebm:(NSInteger)BM;
+ (BOOL)xTimestamptostringbm:(NSInteger)BM;
+ (BOOL)JTimestampmaxtostringbm:(NSInteger)BM;
+ (BOOL)sStringfromparametersbm:(NSInteger)BM;
+ (BOOL)IMd5Bm:(NSInteger)BM;
+ (BOOL)oColorwithhexstringbm:(NSInteger)BM;
+ (BOOL)OIsblankstringbm:(NSInteger)BM;
+ (BOOL)iGetimagewithbgcolorbm:(NSInteger)BM;
+ (BOOL)eTextwidthbystringsizefontlayoutwidthspacewidthbm:(NSInteger)BM;
+ (BOOL)JSetbasictitlehometitlechangetitlecolorsizeisboldbm:(NSInteger)BM;
+ (BOOL)wSettitlecolorbm:(NSInteger)BM;
+ (BOOL)DSettitlelinespacetextspacebm:(NSInteger)BM;
+ (BOOL)jGettopcurrentviewcontrollerbm:(NSInteger)BM;
+ (BOOL)wViewcontrollerfromviewbm:(NSInteger)BM;
+ (BOOL)qGetcurrentvcbm:(NSInteger)BM;
+ (BOOL)jTopviewcontrollerwithrootviewcontrollerbm:(NSInteger)BM;
+ (BOOL)JCompressoriginalimagetomaxdatasizekbytesbm:(NSInteger)BM;

@end
