#import <Foundation/Foundation.h>
@interface BMGPUImageFilterH: NSObject
+ (BOOL)UInitwithvertexshaderfromstringfragmentshaderfromstringbmbm:(NSInteger)BM;
+ (BOOL)VInitwithfragmentshaderfromstringbmbm:(NSInteger)BM;
+ (BOOL)MInitwithfragmentshaderfromfilebmbm:(NSInteger)BM;
+ (BOOL)SInitbmbm:(NSInteger)BM;
+ (BOOL)YInitializeattributesbmbm:(NSInteger)BM;
+ (BOOL)ZSetupfilterforsizebmbm:(NSInteger)BM;
+ (BOOL)BDeallocbmbm:(NSInteger)BM;
+ (BOOL)LUsenextframeforimagecapturebmbm:(NSInteger)BM;
+ (BOOL)UNewcgimagefromcurrentlyprocessedoutputbmbm:(NSInteger)BM;
+ (BOOL)BSizeoffbobmbm:(NSInteger)BM;
+ (BOOL)yTexturecoordinatesforrotationbmbm:(NSInteger)BM;
+ (BOOL)IRendertotexturewithverticestexturecoordinatesbmbm:(NSInteger)BM;
+ (BOOL)MInformtargetsaboutnewframeattimebmbm:(NSInteger)BM;
+ (BOOL)wOutputframesizebmbm:(NSInteger)BM;
+ (BOOL)hSetbackgroundcolorredgreenbluealphabmbm:(NSInteger)BM;
+ (BOOL)ASetintegerforuniformnamebmbm:(NSInteger)BM;
+ (BOOL)ESetfloatforuniformnamebmbm:(NSInteger)BM;
+ (BOOL)lSetsizeforuniformnamebmbm:(NSInteger)BM;
+ (BOOL)ESetpointforuniformnamebmbm:(NSInteger)BM;
+ (BOOL)fSetfloatvec3Foruniformnamebmbm:(NSInteger)BM;
+ (BOOL)sSetfloatvec4Foruniformbmbm:(NSInteger)BM;
+ (BOOL)uSetfloatarraylengthforuniformbmbm:(NSInteger)BM;
+ (BOOL)FSetmatrix3Fforuniformprogrambmbm:(NSInteger)BM;
+ (BOOL)cSetmatrix4Fforuniformprogrambmbm:(NSInteger)BM;
+ (BOOL)NSetfloatforuniformprogrambmbm:(NSInteger)BM;
+ (BOOL)pSetpointforuniformprogrambmbm:(NSInteger)BM;
+ (BOOL)QSetsizeforuniformprogrambmbm:(NSInteger)BM;
+ (BOOL)ESetvec3Foruniformprogrambmbm:(NSInteger)BM;
+ (BOOL)mSetvec4Foruniformprogrambmbm:(NSInteger)BM;
+ (BOOL)PSetfloatarraylengthforuniformprogrambmbm:(NSInteger)BM;
+ (BOOL)NSetintegerforuniformprogrambmbm:(NSInteger)BM;
+ (BOOL)mSetandexecuteuniformstatecallbackatindexforprogramtoblockbmbm:(NSInteger)BM;
+ (BOOL)LSetuniformsforprogramatindexbmbm:(NSInteger)BM;
+ (BOOL)dNewframereadyattimeatindexbmbm:(NSInteger)BM;
+ (BOOL)cNextavailabletextureindexbmbm:(NSInteger)BM;
+ (BOOL)WSetinputframebufferatindexbmbm:(NSInteger)BM;
+ (BOOL)wRotatedsizeforindexbmbm:(NSInteger)BM;
+ (BOOL)oRotatedpointforrotationbmbm:(NSInteger)BM;
+ (BOOL)MSetinputsizeatindexbmbm:(NSInteger)BM;
+ (BOOL)RSetinputrotationatindexbmbm:(NSInteger)BM;
+ (BOOL)UForceprocessingatsizebmbm:(NSInteger)BM;
+ (BOOL)FForceprocessingatsizerespectingaspectratiobmbm:(NSInteger)BM;
+ (BOOL)IMaximumoutputsizebmbm:(NSInteger)BM;
+ (BOOL)BEndprocessingbmbm:(NSInteger)BM;
+ (BOOL)jWantsmonochromeinputbmbm:(NSInteger)BM;

@end
