#import <Foundation/Foundation.h>
@interface BMGPUImageFiltery: NSObject
+ (BOOL)TInitwithvertexshaderfromstringeFragmentshaderfromstring:(NSInteger)BM;
+ (BOOL)iInitwithfragmentshaderfromstring:(NSInteger)BM;
+ (BOOL)KInitwithfragmentshaderfromfile:(NSInteger)BM;
+ (BOOL)cinit:(NSInteger)BM;
+ (BOOL)SinitializeAttributes:(NSInteger)BM;
+ (BOOL)XSetupfilterforsize:(NSInteger)BM;
+ (BOOL)jdealloc:(NSInteger)BM;
+ (BOOL)huseNextFrameForImageCapture:(NSInteger)BM;
+ (BOOL)HnewCGImageFromCurrentlyProcessedOutput:(NSInteger)BM;
+ (BOOL)AsizeOfFBO:(NSInteger)BM;
+ (BOOL)JTexturecoordinatesforrotation:(NSInteger)BM;
+ (BOOL)gRendertotexturewithverticesSTexturecoordinates:(NSInteger)BM;
+ (BOOL)XInformtargetsaboutnewframeattime:(NSInteger)BM;
+ (BOOL)YoutputFrameSize:(NSInteger)BM;
+ (BOOL)OSetbackgroundcolorredKGreenaBlueeAlpha:(NSInteger)BM;
+ (BOOL)BSetintegerIForuniformname:(NSInteger)BM;
+ (BOOL)YSetfloatxForuniformname:(NSInteger)BM;
+ (BOOL)gSetsizeJForuniformname:(NSInteger)BM;
+ (BOOL)rSetpointeForuniformname:(NSInteger)BM;
+ (BOOL)USetfloatvec3FForuniformname:(NSInteger)BM;
+ (BOOL)XSetfloatvec4YForuniform:(NSInteger)BM;
+ (BOOL)YSetfloatarraySLengthvForuniform:(NSInteger)BM;
+ (BOOL)nSetmatrix3FpForuniformrProgram:(NSInteger)BM;
+ (BOOL)bSetmatrix4FEForuniformoProgram:(NSInteger)BM;
+ (BOOL)USetfloatTForuniformPProgram:(NSInteger)BM;
+ (BOOL)XSetpointLForuniformbProgram:(NSInteger)BM;
+ (BOOL)qSetsizeTForuniformLProgram:(NSInteger)BM;
+ (BOOL)BSetvec3YForuniformjProgram:(NSInteger)BM;
+ (BOOL)jSetvec4hForuniformyProgram:(NSInteger)BM;
+ (BOOL)cSetfloatarrayCLengthtForuniformjProgram:(NSInteger)BM;
+ (BOOL)ISetintegercForuniformoProgram:(NSInteger)BM;
+ (BOOL)jSetandexecuteuniformstatecallbackatindexEForprogramGToblock:(NSInteger)BM;
+ (BOOL)HSetuniformsforprogramatindex:(NSInteger)BM;
+ (BOOL)hNewframereadyattimezAtindex:(NSInteger)BM;
+ (BOOL)bnextAvailableTextureIndex:(NSInteger)BM;
+ (BOOL)jSetinputframebufferoAtindex:(NSInteger)BM;
+ (BOOL)YRotatedsizeeForindex:(NSInteger)BM;
+ (BOOL)dRotatedpointHForrotation:(NSInteger)BM;
+ (BOOL)NSetinputsizeAAtindex:(NSInteger)BM;
+ (BOOL)uSetinputrotationjAtindex:(NSInteger)BM;
+ (BOOL)yForceprocessingatsize:(NSInteger)BM;
+ (BOOL)HForceprocessingatsizerespectingaspectratio:(NSInteger)BM;
+ (BOOL)PmaximumOutputSize:(NSInteger)BM;
+ (BOOL)HendProcessing:(NSInteger)BM;
+ (BOOL)iwantsMonochromeInput:(NSInteger)BM;

@end
