#import <Foundation/Foundation.h>
@interface BMGPUImageFilterN: NSObject
+ (BOOL)VInitwithvertexshaderfromstringfragmentshaderfromstringbm:(NSInteger)BM;
+ (BOOL)YInitwithfragmentshaderfromstringbm:(NSInteger)BM;
+ (BOOL)DInitwithfragmentshaderfromfilebm:(NSInteger)BM;
+ (BOOL)KInitbm:(NSInteger)BM;
+ (BOOL)sInitializeattributesbm:(NSInteger)BM;
+ (BOOL)eSetupfilterforsizebm:(NSInteger)BM;
+ (BOOL)zDeallocbm:(NSInteger)BM;
+ (BOOL)jUsenextframeforimagecapturebm:(NSInteger)BM;
+ (BOOL)DNewcgimagefromcurrentlyprocessedoutputbm:(NSInteger)BM;
+ (BOOL)CSizeoffbobm:(NSInteger)BM;
+ (BOOL)DTexturecoordinatesforrotationbm:(NSInteger)BM;
+ (BOOL)VRendertotexturewithverticestexturecoordinatesbm:(NSInteger)BM;
+ (BOOL)OInformtargetsaboutnewframeattimebm:(NSInteger)BM;
+ (BOOL)gOutputframesizebm:(NSInteger)BM;
+ (BOOL)tSetbackgroundcolorredgreenbluealphabm:(NSInteger)BM;
+ (BOOL)TSetintegerforuniformnamebm:(NSInteger)BM;
+ (BOOL)wSetfloatforuniformnamebm:(NSInteger)BM;
+ (BOOL)ISetsizeforuniformnamebm:(NSInteger)BM;
+ (BOOL)VSetpointforuniformnamebm:(NSInteger)BM;
+ (BOOL)vSetfloatvec3Foruniformnamebm:(NSInteger)BM;
+ (BOOL)fSetfloatvec4Foruniformbm:(NSInteger)BM;
+ (BOOL)KSetfloatarraylengthforuniformbm:(NSInteger)BM;
+ (BOOL)ISetmatrix3Fforuniformprogrambm:(NSInteger)BM;
+ (BOOL)PSetmatrix4Fforuniformprogrambm:(NSInteger)BM;
+ (BOOL)ASetfloatforuniformprogrambm:(NSInteger)BM;
+ (BOOL)FSetpointforuniformprogrambm:(NSInteger)BM;
+ (BOOL)GSetsizeforuniformprogrambm:(NSInteger)BM;
+ (BOOL)XSetvec3Foruniformprogrambm:(NSInteger)BM;
+ (BOOL)pSetvec4Foruniformprogrambm:(NSInteger)BM;
+ (BOOL)GSetfloatarraylengthforuniformprogrambm:(NSInteger)BM;
+ (BOOL)ISetintegerforuniformprogrambm:(NSInteger)BM;
+ (BOOL)hSetandexecuteuniformstatecallbackatindexforprogramtoblockbm:(NSInteger)BM;
+ (BOOL)NSetuniformsforprogramatindexbm:(NSInteger)BM;
+ (BOOL)XNewframereadyattimeatindexbm:(NSInteger)BM;
+ (BOOL)sNextavailabletextureindexbm:(NSInteger)BM;
+ (BOOL)jSetinputframebufferatindexbm:(NSInteger)BM;
+ (BOOL)NRotatedsizeforindexbm:(NSInteger)BM;
+ (BOOL)ZRotatedpointforrotationbm:(NSInteger)BM;
+ (BOOL)SSetinputsizeatindexbm:(NSInteger)BM;
+ (BOOL)VSetinputrotationatindexbm:(NSInteger)BM;
+ (BOOL)vForceprocessingatsizebm:(NSInteger)BM;
+ (BOOL)QForceprocessingatsizerespectingaspectratiobm:(NSInteger)BM;
+ (BOOL)YMaximumoutputsizebm:(NSInteger)BM;
+ (BOOL)bEndprocessingbm:(NSInteger)BM;
+ (BOOL)pWantsmonochromeinputbm:(NSInteger)BM;

@end
