#import <Foundation/Foundation.h>
@interface BMIQKeyboardManagerf: NSObject
+ (BOOL)Iload:(NSInteger)BM;
+ (BOOL)Jinit:(NSInteger)BM;
+ (BOOL)TsharedManager:(NSInteger)BM;
+ (BOOL)sdealloc:(NSInteger)BM;
+ (BOOL)rSetenable:(NSInteger)BM;
+ (BOOL)pprivateIsEnabled:(NSInteger)BM;
+ (BOOL)lSetkeyboarddistancefromtextfield:(NSInteger)BM;
+ (BOOL)SSetshouldresignontouchoutside:(NSInteger)BM;
+ (BOOL)rprivateShouldResignOnTouchOutside:(NSInteger)BM;
+ (BOOL)tSetmoveddistance:(NSInteger)BM;
+ (BOOL)sSetenableautotoolbar:(NSInteger)BM;
+ (BOOL)UprivateIsEnableAutoToolbar:(NSInteger)BM;
+ (BOOL)ckeyWindow:(NSInteger)BM;
+ (BOOL)xoptimizedAdjustPosition:(NSInteger)BM;
+ (BOOL)vadjustPosition:(NSInteger)BM;
+ (BOOL)HrestorePosition:(NSInteger)BM;
+ (BOOL)mreloadLayoutIfNeeded:(NSInteger)BM;
+ (BOOL)uKeyboardwillshow:(NSInteger)BM;
+ (BOOL)gKeyboarddidshow:(NSInteger)BM;
+ (BOOL)cKeyboardwillhide:(NSInteger)BM;
+ (BOOL)cKeyboarddidhide:(NSInteger)BM;
+ (BOOL)nTextfieldviewdidbeginediting:(NSInteger)BM;
+ (BOOL)lTextfieldviewdidendediting:(NSInteger)BM;
+ (BOOL)nWillchangestatusbarorientation:(NSInteger)BM;
+ (BOOL)qTaprecognized:(NSInteger)BM;
+ (BOOL)jGesturerecognizerSShouldrecognizesimultaneouslywithgesturerecognizer:(NSInteger)BM;
+ (BOOL)vGesturerecognizerCShouldreceivetouch:(NSInteger)BM;
+ (BOOL)SresignFirstResponder:(NSInteger)BM;
+ (BOOL)LcanGoPrevious:(NSInteger)BM;
+ (BOOL)LcanGoNext:(NSInteger)BM;
+ (BOOL)YgoPrevious:(NSInteger)BM;
+ (BOOL)FgoNext:(NSInteger)BM;
+ (BOOL)JresponderViews:(NSInteger)BM;
+ (BOOL)uaddToolbarIfRequired:(NSInteger)BM;
+ (BOOL)GremoveToolbarIfRequired:(NSInteger)BM;
+ (BOOL)YreloadInputViews:(NSInteger)BM;
+ (BOOL)WPreviousaction:(NSInteger)BM;
+ (BOOL)RNextaction:(NSInteger)BM;
+ (BOOL)ZDoneaction:(NSInteger)BM;
+ (BOOL)dRegistertextfieldviewclasscDidbegineditingnotificationnameUDidendeditingnotificationname:(NSInteger)BM;
+ (BOOL)IUnregistertextfieldviewclassUDidbegineditingnotificationnameRDidendeditingnotificationname:(NSInteger)BM;
+ (BOOL)FregisterAllNotifications:(NSInteger)BM;
+ (BOOL)UunregisterAllNotifications:(NSInteger)BM;
+ (BOOL)tShowlog:(NSInteger)BM;
+ (BOOL)vShowlogyIndentation:(NSInteger)BM;

@end
