#import <Foundation/Foundation.h>
@interface BMMASConstraintY: NSObject
+ (BOOL)Ninit:(NSInteger)BM;
+ (BOOL)F(id))equalTo:(NSInteger)BM;
+ (BOOL)Z(id))mas_equalTo:(NSInteger)BM;
+ (BOOL)d(id))greaterThanOrEqualTo:(NSInteger)BM;
+ (BOOL)X(id))mas_greaterThanOrEqualTo:(NSInteger)BM;
+ (BOOL)a(id))lessThanOrEqualTo:(NSInteger)BM;
+ (BOOL)S(id))mas_lessThanOrEqualTo:(NSInteger)BM;
+ (BOOL)r(void))priorityLow:(NSInteger)BM;
+ (BOOL)R(void))priorityMedium:(NSInteger)BM;
+ (BOOL)h(void))priorityHigh:(NSInteger)BM;
+ (BOOL)Y(MASEdgeInsets))insets:(NSInteger)BM;
+ (BOOL)p(CGFloat))inset:(NSInteger)BM;
+ (BOOL)D(CGSize))sizeOffset:(NSInteger)BM;
+ (BOOL)D(CGPoint))centerOffset:(NSInteger)BM;
+ (BOOL)B(CGFloat))offset:(NSInteger)BM;
+ (BOOL)x(NSValue *value))valueOffset:(NSInteger)BM;
+ (BOOL)o(id offset))mas_offset:(NSInteger)BM;
+ (BOOL)kSetlayoutconstantwithvalue:(NSInteger)BM;
+ (BOOL)Twith:(NSInteger)BM;
+ (BOOL)Yand:(NSInteger)BM;
+ (BOOL)TAddconstraintwithlayoutattribute:(NSInteger)BM;
+ (BOOL)mleft:(NSInteger)BM;
+ (BOOL)dtop:(NSInteger)BM;
+ (BOOL)Bright:(NSInteger)BM;
+ (BOOL)dbottom:(NSInteger)BM;
+ (BOOL)fleading:(NSInteger)BM;
+ (BOOL)Vtrailing:(NSInteger)BM;
+ (BOOL)Twidth:(NSInteger)BM;
+ (BOOL)fheight:(NSInteger)BM;
+ (BOOL)zcenterX:(NSInteger)BM;
+ (BOOL)ncenterY:(NSInteger)BM;
+ (BOOL)Pbaseline:(NSInteger)BM;
+ (BOOL)UfirstBaseline:(NSInteger)BM;
+ (BOOL)blastBaseline:(NSInteger)BM;
+ (BOOL)rleftMargin:(NSInteger)BM;
+ (BOOL)xrightMargin:(NSInteger)BM;
+ (BOOL)XtopMargin:(NSInteger)BM;
+ (BOOL)ebottomMargin:(NSInteger)BM;
+ (BOOL)UleadingMargin:(NSInteger)BM;
+ (BOOL)BtrailingMargin:(NSInteger)BM;
+ (BOOL)gcenterXWithinMargins:(NSInteger)BM;
+ (BOOL)WcenterYWithinMargins:(NSInteger)BM;
+ (BOOL)b(CGFloat multiplier))multipliedBy:(NSInteger)BM;
+ (BOOL)c(CGFloat divider))dividedBy:(NSInteger)BM;
+ (BOOL)w(MASLayoutPriority priority))priority:(NSInteger)BM;
+ (BOOL)T(id, NSLayoutRelation))equalToWithRelation:(NSInteger)BM;
+ (BOOL)m(id key))key:(NSInteger)BM;
+ (BOOL)DSetinsets:(NSInteger)BM;
+ (BOOL)gSetinset:(NSInteger)BM;
+ (BOOL)uSetsizeoffset:(NSInteger)BM;
+ (BOOL)lSetcenteroffset:(NSInteger)BM;
+ (BOOL)dSetoffset:(NSInteger)BM;
+ (BOOL)manimator:(NSInteger)BM;
+ (BOOL)uactivate:(NSInteger)BM;
+ (BOOL)wdeactivate:(NSInteger)BM;
+ (BOOL)cinstall:(NSInteger)BM;
+ (BOOL)iuninstall:(NSInteger)BM;

@end
