#import <Foundation/Foundation.h>
@interface BMMASConstrainth: NSObject
+ (BOOL)oinit:(NSInteger)BM;
+ (BOOL)a(id))equalTo:(NSInteger)BM;
+ (BOOL)C(id))mas_equalTo:(NSInteger)BM;
+ (BOOL)n(id))greaterThanOrEqualTo:(NSInteger)BM;
+ (BOOL)G(id))mas_greaterThanOrEqualTo:(NSInteger)BM;
+ (BOOL)k(id))lessThanOrEqualTo:(NSInteger)BM;
+ (BOOL)I(id))mas_lessThanOrEqualTo:(NSInteger)BM;
+ (BOOL)V(void))priorityLow:(NSInteger)BM;
+ (BOOL)p(void))priorityMedium:(NSInteger)BM;
+ (BOOL)H(void))priorityHigh:(NSInteger)BM;
+ (BOOL)E(MASEdgeInsets))insets:(NSInteger)BM;
+ (BOOL)a(CGFloat))inset:(NSInteger)BM;
+ (BOOL)z(CGSize))sizeOffset:(NSInteger)BM;
+ (BOOL)a(CGPoint))centerOffset:(NSInteger)BM;
+ (BOOL)m(CGFloat))offset:(NSInteger)BM;
+ (BOOL)S(NSValue *value))valueOffset:(NSInteger)BM;
+ (BOOL)V(id offset))mas_offset:(NSInteger)BM;
+ (BOOL)USetlayoutconstantwithvalue:(NSInteger)BM;
+ (BOOL)Zwith:(NSInteger)BM;
+ (BOOL)sand:(NSInteger)BM;
+ (BOOL)LAddconstraintwithlayoutattribute:(NSInteger)BM;
+ (BOOL)Ileft:(NSInteger)BM;
+ (BOOL)ptop:(NSInteger)BM;
+ (BOOL)Jright:(NSInteger)BM;
+ (BOOL)Jbottom:(NSInteger)BM;
+ (BOOL)dleading:(NSInteger)BM;
+ (BOOL)ftrailing:(NSInteger)BM;
+ (BOOL)swidth:(NSInteger)BM;
+ (BOOL)Lheight:(NSInteger)BM;
+ (BOOL)dcenterX:(NSInteger)BM;
+ (BOOL)McenterY:(NSInteger)BM;
+ (BOOL)xbaseline:(NSInteger)BM;
+ (BOOL)yfirstBaseline:(NSInteger)BM;
+ (BOOL)dlastBaseline:(NSInteger)BM;
+ (BOOL)HleftMargin:(NSInteger)BM;
+ (BOOL)rrightMargin:(NSInteger)BM;
+ (BOOL)wtopMargin:(NSInteger)BM;
+ (BOOL)RbottomMargin:(NSInteger)BM;
+ (BOOL)RleadingMargin:(NSInteger)BM;
+ (BOOL)ItrailingMargin:(NSInteger)BM;
+ (BOOL)ocenterXWithinMargins:(NSInteger)BM;
+ (BOOL)AcenterYWithinMargins:(NSInteger)BM;
+ (BOOL)L(CGFloat multiplier))multipliedBy:(NSInteger)BM;
+ (BOOL)l(CGFloat divider))dividedBy:(NSInteger)BM;
+ (BOOL)i(MASLayoutPriority priority))priority:(NSInteger)BM;
+ (BOOL)U(id, NSLayoutRelation))equalToWithRelation:(NSInteger)BM;
+ (BOOL)B(id key))key:(NSInteger)BM;
+ (BOOL)SSetinsets:(NSInteger)BM;
+ (BOOL)xSetinset:(NSInteger)BM;
+ (BOOL)sSetsizeoffset:(NSInteger)BM;
+ (BOOL)DSetcenteroffset:(NSInteger)BM;
+ (BOOL)fSetoffset:(NSInteger)BM;
+ (BOOL)wanimator:(NSInteger)BM;
+ (BOOL)Iactivate:(NSInteger)BM;
+ (BOOL)Ddeactivate:(NSInteger)BM;
+ (BOOL)Winstall:(NSInteger)BM;
+ (BOOL)buninstall:(NSInteger)BM;

@end
