#import <Foundation/Foundation.h>
@interface BMMBProgressHUDP: NSObject
+ (BOOL)eShowhudaddedtojAnimated:(NSInteger)BM;
+ (BOOL)lHidehudforviewGAnimated:(NSInteger)BM;
+ (BOOL)lHideallhudsforviewWAnimated:(NSInteger)BM;
+ (BOOL)jHudforview:(NSInteger)BM;
+ (BOOL)mAllhudsforview:(NSInteger)BM;
+ (BOOL)tInitwithframe:(NSInteger)BM;
+ (BOOL)FInitwithview:(NSInteger)BM;
+ (BOOL)bInitwithwindow:(NSInteger)BM;
+ (BOOL)Ydealloc:(NSInteger)BM;
+ (BOOL)xShow:(NSInteger)BM;
+ (BOOL)IHide:(NSInteger)BM;
+ (BOOL)HHideQAfterdelay:(NSInteger)BM;
+ (BOOL)pHidedelayed:(NSInteger)BM;
+ (BOOL)lHandlegracetimer:(NSInteger)BM;
+ (BOOL)CHandleminshowtimer:(NSInteger)BM;
+ (BOOL)UdidMoveToSuperview:(NSInteger)BM;
+ (BOOL)DShowusinganimation:(NSInteger)BM;
+ (BOOL)KHideusinganimation:(NSInteger)BM;
+ (BOOL)LAnimationfinishedpFinishedpContext:(NSInteger)BM;
+ (BOOL)zdone:(NSInteger)BM;
+ (BOOL)FShowwhileexecutingAOntargetNWithobjectHAnimated:(NSInteger)BM;
+ (BOOL)bShowanimatedkWhileexecutingblock:(NSInteger)BM;
+ (BOOL)uShowanimatedjWhileexecutingblockhCompletionblock:(NSInteger)BM;
+ (BOOL)UShowanimatedAWhileexecutingblockbOnqueue:(NSInteger)BM;
+ (BOOL)hShowanimatedpWhileexecutingblockjOnqueuerCompletionblock:(NSInteger)BM;
+ (BOOL)slaunchExecution:(NSInteger)BM;
+ (BOOL)scleanUp:(NSInteger)BM;
+ (BOOL)ZsetupLabels:(NSInteger)BM;
+ (BOOL)wupdateIndicators:(NSInteger)BM;
+ (BOOL)ZlayoutSubviews:(NSInteger)BM;
+ (BOOL)BDrawrect:(NSInteger)BM;
+ (BOOL)RregisterForKVO:(NSInteger)BM;
+ (BOOL)BunregisterFromKVO:(NSInteger)BM;
+ (BOOL)zobservableKeypaths:(NSInteger)BM;
+ (BOOL)ZObservevalueforkeypathUOfobjectHChangeoContext:(NSInteger)BM;
+ (BOOL)WUpdateuiforkeypath:(NSInteger)BM;
+ (BOOL)JregisterForNotifications:(NSInteger)BM;
+ (BOOL)JunregisterFromNotifications:(NSInteger)BM;
+ (BOOL)rStatusbarorientationdidchange:(NSInteger)BM;
+ (BOOL)TUpdateforcurrentorientationanimated:(NSInteger)BM;

@end
