#import <Foundation/Foundation.h>
@interface BMNSDatao: NSObject
+ (BOOL)iMd2Stringbm:(NSInteger)BM;
+ (BOOL)TMd2Databm:(NSInteger)BM;
+ (BOOL)CMd4Stringbm:(NSInteger)BM;
+ (BOOL)eMd4Databm:(NSInteger)BM;
+ (BOOL)bMd5Stringbm:(NSInteger)BM;
+ (BOOL)BMd5Databm:(NSInteger)BM;
+ (BOOL)nSha1Stringbm:(NSInteger)BM;
+ (BOOL)lSha1Databm:(NSInteger)BM;
+ (BOOL)ASha224Stringbm:(NSInteger)BM;
+ (BOOL)fSha224Databm:(NSInteger)BM;
+ (BOOL)bSha256Stringbm:(NSInteger)BM;
+ (BOOL)QSha256Databm:(NSInteger)BM;
+ (BOOL)rSha384Stringbm:(NSInteger)BM;
+ (BOOL)cSha384Databm:(NSInteger)BM;
+ (BOOL)lSha512Stringbm:(NSInteger)BM;
+ (BOOL)oSha512Databm:(NSInteger)BM;
+ (BOOL)xHmacstringusingalgwithkeybm:(NSInteger)BM;
+ (BOOL)fHmacdatausingalgwithkeybm:(NSInteger)BM;
+ (BOOL)HHmacmd5Stringwithkeybm:(NSInteger)BM;
+ (BOOL)KHmacmd5Datawithkeybm:(NSInteger)BM;
+ (BOOL)MHmacsha1Stringwithkeybm:(NSInteger)BM;
+ (BOOL)OHmacsha1Datawithkeybm:(NSInteger)BM;
+ (BOOL)OHmacsha224Stringwithkeybm:(NSInteger)BM;
+ (BOOL)aHmacsha224Datawithkeybm:(NSInteger)BM;
+ (BOOL)fHmacsha256Stringwithkeybm:(NSInteger)BM;
+ (BOOL)AHmacsha256Datawithkeybm:(NSInteger)BM;
+ (BOOL)WHmacsha384Stringwithkeybm:(NSInteger)BM;
+ (BOOL)WHmacsha384Datawithkeybm:(NSInteger)BM;
+ (BOOL)sHmacsha512Stringwithkeybm:(NSInteger)BM;
+ (BOOL)XHmacsha512Datawithkeybm:(NSInteger)BM;
+ (BOOL)KCrc32Stringbm:(NSInteger)BM;
+ (BOOL)kCrc32Bm:(NSInteger)BM;
+ (BOOL)mAes256Encryptwithkeyivbm:(NSInteger)BM;
+ (BOOL)MAes256Decryptwithkeyivbm:(NSInteger)BM;
+ (BOOL)qUtf8Stringbm:(NSInteger)BM;
+ (BOOL)CHexstringbm:(NSInteger)BM;
+ (BOOL)cDatawithhexstringbm:(NSInteger)BM;
+ (BOOL)JBase64Encodedstringbm:(NSInteger)BM;
+ (BOOL)SDatawithbase64Encodedstringbm:(NSInteger)BM;
+ (BOOL)mJsonvaluedecodedbm:(NSInteger)BM;
+ (BOOL)gGzipinflatebm:(NSInteger)BM;
+ (BOOL)SGzipdeflatebm:(NSInteger)BM;
+ (BOOL)RZlibinflatebm:(NSInteger)BM;
+ (BOOL)rZlibdeflatebm:(NSInteger)BM;
+ (BOOL)ADatanamedbm:(NSInteger)BM;

@end
