#import <Foundation/Foundation.h>
@interface BMNSDataD: NSObject
+ (BOOL)nmd2String:(NSInteger)BM;
+ (BOOL)Hmd2Data:(NSInteger)BM;
+ (BOOL)smd4String:(NSInteger)BM;
+ (BOOL)cmd4Data:(NSInteger)BM;
+ (BOOL)qmd5String:(NSInteger)BM;
+ (BOOL)Rmd5Data:(NSInteger)BM;
+ (BOOL)Fsha1String:(NSInteger)BM;
+ (BOOL)Qsha1Data:(NSInteger)BM;
+ (BOOL)Msha224String:(NSInteger)BM;
+ (BOOL)msha224Data:(NSInteger)BM;
+ (BOOL)nsha256String:(NSInteger)BM;
+ (BOOL)usha256Data:(NSInteger)BM;
+ (BOOL)rsha384String:(NSInteger)BM;
+ (BOOL)isha384Data:(NSInteger)BM;
+ (BOOL)jsha512String:(NSInteger)BM;
+ (BOOL)isha512Data:(NSInteger)BM;
+ (BOOL)vHmacstringusingalgbWithkey:(NSInteger)BM;
+ (BOOL)tHmacdatausingalgcWithkey:(NSInteger)BM;
+ (BOOL)VHmacmd5Stringwithkey:(NSInteger)BM;
+ (BOOL)rHmacmd5Datawithkey:(NSInteger)BM;
+ (BOOL)PHmacsha1Stringwithkey:(NSInteger)BM;
+ (BOOL)UHmacsha1Datawithkey:(NSInteger)BM;
+ (BOOL)YHmacsha224Stringwithkey:(NSInteger)BM;
+ (BOOL)sHmacsha224Datawithkey:(NSInteger)BM;
+ (BOOL)YHmacsha256Stringwithkey:(NSInteger)BM;
+ (BOOL)zHmacsha256Datawithkey:(NSInteger)BM;
+ (BOOL)tHmacsha384Stringwithkey:(NSInteger)BM;
+ (BOOL)FHmacsha384Datawithkey:(NSInteger)BM;
+ (BOOL)pHmacsha512Stringwithkey:(NSInteger)BM;
+ (BOOL)EHmacsha512Datawithkey:(NSInteger)BM;
+ (BOOL)vcrc32String:(NSInteger)BM;
+ (BOOL)Jcrc32:(NSInteger)BM;
+ (BOOL)dAes256EncryptwithkeyRIv:(NSInteger)BM;
+ (BOOL)eAes256DecryptwithkeyLIv:(NSInteger)BM;
+ (BOOL)Zutf8String:(NSInteger)BM;
+ (BOOL)OhexString:(NSInteger)BM;
+ (BOOL)dDatawithhexstring:(NSInteger)BM;
+ (BOOL)Nbase64EncodedString:(NSInteger)BM;
+ (BOOL)SDatawithbase64Encodedstring:(NSInteger)BM;
+ (BOOL)njsonValueDecoded:(NSInteger)BM;
+ (BOOL)WgzipInflate:(NSInteger)BM;
+ (BOOL)fgzipDeflate:(NSInteger)BM;
+ (BOOL)czlibInflate:(NSInteger)BM;
+ (BOOL)dzlibDeflate:(NSInteger)BM;
+ (BOOL)GDatanamed:(NSInteger)BM;

@end
