#import <Foundation/Foundation.h>
@interface BMNSDatax: NSObject
+ (BOOL)PMd2Stringbmbm:(NSInteger)BM;
+ (BOOL)CMd2Databmbm:(NSInteger)BM;
+ (BOOL)VMd4Stringbmbm:(NSInteger)BM;
+ (BOOL)EMd4Databmbm:(NSInteger)BM;
+ (BOOL)OMd5Stringbmbm:(NSInteger)BM;
+ (BOOL)AMd5Databmbm:(NSInteger)BM;
+ (BOOL)hSha1Stringbmbm:(NSInteger)BM;
+ (BOOL)pSha1Databmbm:(NSInteger)BM;
+ (BOOL)ESha224Stringbmbm:(NSInteger)BM;
+ (BOOL)nSha224Databmbm:(NSInteger)BM;
+ (BOOL)HSha256Stringbmbm:(NSInteger)BM;
+ (BOOL)WSha256Databmbm:(NSInteger)BM;
+ (BOOL)pSha384Stringbmbm:(NSInteger)BM;
+ (BOOL)QSha384Databmbm:(NSInteger)BM;
+ (BOOL)KSha512Stringbmbm:(NSInteger)BM;
+ (BOOL)fSha512Databmbm:(NSInteger)BM;
+ (BOOL)nHmacstringusingalgwithkeybmbm:(NSInteger)BM;
+ (BOOL)oHmacdatausingalgwithkeybmbm:(NSInteger)BM;
+ (BOOL)oHmacmd5Stringwithkeybmbm:(NSInteger)BM;
+ (BOOL)yHmacmd5Datawithkeybmbm:(NSInteger)BM;
+ (BOOL)HHmacsha1Stringwithkeybmbm:(NSInteger)BM;
+ (BOOL)dHmacsha1Datawithkeybmbm:(NSInteger)BM;
+ (BOOL)kHmacsha224Stringwithkeybmbm:(NSInteger)BM;
+ (BOOL)QHmacsha224Datawithkeybmbm:(NSInteger)BM;
+ (BOOL)OHmacsha256Stringwithkeybmbm:(NSInteger)BM;
+ (BOOL)KHmacsha256Datawithkeybmbm:(NSInteger)BM;
+ (BOOL)nHmacsha384Stringwithkeybmbm:(NSInteger)BM;
+ (BOOL)tHmacsha384Datawithkeybmbm:(NSInteger)BM;
+ (BOOL)EHmacsha512Stringwithkeybmbm:(NSInteger)BM;
+ (BOOL)nHmacsha512Datawithkeybmbm:(NSInteger)BM;
+ (BOOL)eCrc32Stringbmbm:(NSInteger)BM;
+ (BOOL)nCrc32Bmbm:(NSInteger)BM;
+ (BOOL)yAes256Encryptwithkeyivbmbm:(NSInteger)BM;
+ (BOOL)uAes256Decryptwithkeyivbmbm:(NSInteger)BM;
+ (BOOL)OUtf8Stringbmbm:(NSInteger)BM;
+ (BOOL)BHexstringbmbm:(NSInteger)BM;
+ (BOOL)bDatawithhexstringbmbm:(NSInteger)BM;
+ (BOOL)JBase64Encodedstringbmbm:(NSInteger)BM;
+ (BOOL)UDatawithbase64Encodedstringbmbm:(NSInteger)BM;
+ (BOOL)CJsonvaluedecodedbmbm:(NSInteger)BM;
+ (BOOL)cGzipinflatebmbm:(NSInteger)BM;
+ (BOOL)bGzipdeflatebmbm:(NSInteger)BM;
+ (BOOL)iZlibinflatebmbm:(NSInteger)BM;
+ (BOOL)IZlibdeflatebmbm:(NSInteger)BM;
+ (BOOL)EDatanamedbmbm:(NSInteger)BM;

@end
