#import <Foundation/Foundation.h>
@interface BMNSDatae: NSObject
+ (BOOL)pmd2String:(NSInteger)BM;
+ (BOOL)Dmd2Data:(NSInteger)BM;
+ (BOOL)xmd4String:(NSInteger)BM;
+ (BOOL)Wmd4Data:(NSInteger)BM;
+ (BOOL)qmd5String:(NSInteger)BM;
+ (BOOL)kmd5Data:(NSInteger)BM;
+ (BOOL)msha1String:(NSInteger)BM;
+ (BOOL)Psha1Data:(NSInteger)BM;
+ (BOOL)psha224String:(NSInteger)BM;
+ (BOOL)zsha224Data:(NSInteger)BM;
+ (BOOL)Qsha256String:(NSInteger)BM;
+ (BOOL)ksha256Data:(NSInteger)BM;
+ (BOOL)gsha384String:(NSInteger)BM;
+ (BOOL)Msha384Data:(NSInteger)BM;
+ (BOOL)Qsha512String:(NSInteger)BM;
+ (BOOL)Rsha512Data:(NSInteger)BM;
+ (BOOL)fHmacstringusingalgTWithkey:(NSInteger)BM;
+ (BOOL)DHmacdatausingalgIWithkey:(NSInteger)BM;
+ (BOOL)dHmacmd5Stringwithkey:(NSInteger)BM;
+ (BOOL)bHmacmd5Datawithkey:(NSInteger)BM;
+ (BOOL)LHmacsha1Stringwithkey:(NSInteger)BM;
+ (BOOL)KHmacsha1Datawithkey:(NSInteger)BM;
+ (BOOL)sHmacsha224Stringwithkey:(NSInteger)BM;
+ (BOOL)jHmacsha224Datawithkey:(NSInteger)BM;
+ (BOOL)PHmacsha256Stringwithkey:(NSInteger)BM;
+ (BOOL)AHmacsha256Datawithkey:(NSInteger)BM;
+ (BOOL)rHmacsha384Stringwithkey:(NSInteger)BM;
+ (BOOL)nHmacsha384Datawithkey:(NSInteger)BM;
+ (BOOL)KHmacsha512Stringwithkey:(NSInteger)BM;
+ (BOOL)DHmacsha512Datawithkey:(NSInteger)BM;
+ (BOOL)ocrc32String:(NSInteger)BM;
+ (BOOL)Hcrc32:(NSInteger)BM;
+ (BOOL)iAes256EncryptwithkeysIv:(NSInteger)BM;
+ (BOOL)pAes256DecryptwithkeyjIv:(NSInteger)BM;
+ (BOOL)lutf8String:(NSInteger)BM;
+ (BOOL)ihexString:(NSInteger)BM;
+ (BOOL)fDatawithhexstring:(NSInteger)BM;
+ (BOOL)lbase64EncodedString:(NSInteger)BM;
+ (BOOL)VDatawithbase64Encodedstring:(NSInteger)BM;
+ (BOOL)JjsonValueDecoded:(NSInteger)BM;
+ (BOOL)LgzipInflate:(NSInteger)BM;
+ (BOOL)igzipDeflate:(NSInteger)BM;
+ (BOOL)GzlibInflate:(NSInteger)BM;
+ (BOOL)vzlibDeflate:(NSInteger)BM;
+ (BOOL)YDatanamed:(NSInteger)BM;

@end
