#import <Foundation/Foundation.h>
@interface BMNSDataB: NSObject
+ (BOOL)CMd2Stringbm:(NSInteger)BM;
+ (BOOL)SMd2Databm:(NSInteger)BM;
+ (BOOL)YMd4Stringbm:(NSInteger)BM;
+ (BOOL)CMd4Databm:(NSInteger)BM;
+ (BOOL)yMd5Stringbm:(NSInteger)BM;
+ (BOOL)sMd5Databm:(NSInteger)BM;
+ (BOOL)bSha1Stringbm:(NSInteger)BM;
+ (BOOL)wSha1Databm:(NSInteger)BM;
+ (BOOL)qSha224Stringbm:(NSInteger)BM;
+ (BOOL)kSha224Databm:(NSInteger)BM;
+ (BOOL)qSha256Stringbm:(NSInteger)BM;
+ (BOOL)zSha256Databm:(NSInteger)BM;
+ (BOOL)ESha384Stringbm:(NSInteger)BM;
+ (BOOL)HSha384Databm:(NSInteger)BM;
+ (BOOL)xSha512Stringbm:(NSInteger)BM;
+ (BOOL)NSha512Databm:(NSInteger)BM;
+ (BOOL)ZHmacstringusingalgwithkeybm:(NSInteger)BM;
+ (BOOL)dHmacdatausingalgwithkeybm:(NSInteger)BM;
+ (BOOL)JHmacmd5Stringwithkeybm:(NSInteger)BM;
+ (BOOL)HHmacmd5Datawithkeybm:(NSInteger)BM;
+ (BOOL)VHmacsha1Stringwithkeybm:(NSInteger)BM;
+ (BOOL)aHmacsha1Datawithkeybm:(NSInteger)BM;
+ (BOOL)WHmacsha224Stringwithkeybm:(NSInteger)BM;
+ (BOOL)lHmacsha224Datawithkeybm:(NSInteger)BM;
+ (BOOL)EHmacsha256Stringwithkeybm:(NSInteger)BM;
+ (BOOL)IHmacsha256Datawithkeybm:(NSInteger)BM;
+ (BOOL)oHmacsha384Stringwithkeybm:(NSInteger)BM;
+ (BOOL)THmacsha384Datawithkeybm:(NSInteger)BM;
+ (BOOL)BHmacsha512Stringwithkeybm:(NSInteger)BM;
+ (BOOL)THmacsha512Datawithkeybm:(NSInteger)BM;
+ (BOOL)lCrc32Stringbm:(NSInteger)BM;
+ (BOOL)dCrc32Bm:(NSInteger)BM;
+ (BOOL)oAes256Encryptwithkeyivbm:(NSInteger)BM;
+ (BOOL)xAes256Decryptwithkeyivbm:(NSInteger)BM;
+ (BOOL)VUtf8Stringbm:(NSInteger)BM;
+ (BOOL)BHexstringbm:(NSInteger)BM;
+ (BOOL)kDatawithhexstringbm:(NSInteger)BM;
+ (BOOL)zBase64Encodedstringbm:(NSInteger)BM;
+ (BOOL)IDatawithbase64Encodedstringbm:(NSInteger)BM;
+ (BOOL)sJsonvaluedecodedbm:(NSInteger)BM;
+ (BOOL)mGzipinflatebm:(NSInteger)BM;
+ (BOOL)RGzipdeflatebm:(NSInteger)BM;
+ (BOOL)cZlibinflatebm:(NSInteger)BM;
+ (BOOL)zZlibdeflatebm:(NSInteger)BM;
+ (BOOL)fDatanamedbm:(NSInteger)BM;

@end
