#import <Foundation/Foundation.h>
@interface hbBMGPUImageFilterma: NSObject
+ (BOOL)eJinitwithvertexshaderfromstringfragmentshaderfromstringbmbmbm:(NSInteger)hb;
+ (BOOL)SPinitwithfragmentshaderfromstringbmbmbm:(NSInteger)hb;
+ (BOOL)ILinitwithfragmentshaderfromfilebmbmbm:(NSInteger)hb;
+ (BOOL)mFinitbmbmbm:(NSInteger)hb;
+ (BOOL)yHinitializeattributesbmbmbm:(NSInteger)hb;
+ (BOOL)pLsetupfilterforsizebmbmbm:(NSInteger)hb;
+ (BOOL)vPdeallocbmbmbm:(NSInteger)hb;
+ (BOOL)rOusenextframeforimagecapturebmbmbm:(NSInteger)hb;
+ (BOOL)RNnewcgimagefromcurrentlyprocessedoutputbmbmbm:(NSInteger)hb;
+ (BOOL)SEsizeoffbobmbmbm:(NSInteger)hb;
+ (BOOL)fWtexturecoordinatesforrotationbmbmbm:(NSInteger)hb;
+ (BOOL)NOrendertotexturewithverticestexturecoordinatesbmbmbm:(NSInteger)hb;
+ (BOOL)JQinformtargetsaboutnewframeattimebmbmbm:(NSInteger)hb;
+ (BOOL)DYoutputframesizebmbmbm:(NSInteger)hb;
+ (BOOL)FZsetbackgroundcolorredgreenbluealphabmbmbm:(NSInteger)hb;
+ (BOOL)oCsetintegerforuniformnamebmbmbm:(NSInteger)hb;
+ (BOOL)pQsetfloatforuniformnamebmbmbm:(NSInteger)hb;
+ (BOOL)oDsetsizeforuniformnamebmbmbm:(NSInteger)hb;
+ (BOOL)aZsetpointforuniformnamebmbmbm:(NSInteger)hb;
+ (BOOL)rGsetfloatvec3Foruniformnamebmbmbm:(NSInteger)hb;
+ (BOOL)hMsetfloatvec4Foruniformbmbmbm:(NSInteger)hb;
+ (BOOL)tXsetfloatarraylengthforuniformbmbmbm:(NSInteger)hb;
+ (BOOL)oHsetmatrix3Fforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)hWsetmatrix4Fforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)ZUsetfloatforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)xBsetpointforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)YTsetsizeforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)YJsetvec3Foruniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)BRsetvec4Foruniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)iEsetfloatarraylengthforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)uFsetintegerforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)rPsetandexecuteuniformstatecallbackatindexforprogramtoblockbmbmbm:(NSInteger)hb;
+ (BOOL)VSsetuniformsforprogramatindexbmbmbm:(NSInteger)hb;
+ (BOOL)BJnewframereadyattimeatindexbmbmbm:(NSInteger)hb;
+ (BOOL)gNnextavailabletextureindexbmbmbm:(NSInteger)hb;
+ (BOOL)FUsetinputframebufferatindexbmbmbm:(NSInteger)hb;
+ (BOOL)GDrotatedsizeforindexbmbmbm:(NSInteger)hb;
+ (BOOL)eRrotatedpointforrotationbmbmbm:(NSInteger)hb;
+ (BOOL)sWsetinputsizeatindexbmbmbm:(NSInteger)hb;
+ (BOOL)pTsetinputrotationatindexbmbmbm:(NSInteger)hb;
+ (BOOL)VKforceprocessingatsizebmbmbm:(NSInteger)hb;
+ (BOOL)oOforceprocessingatsizerespectingaspectratiobmbmbm:(NSInteger)hb;
+ (BOOL)iWmaximumoutputsizebmbmbm:(NSInteger)hb;
+ (BOOL)nBendprocessingbmbmbm:(NSInteger)hb;
+ (BOOL)aMwantsmonochromeinputbmbmbm:(NSInteger)hb;

@end
