#import <Foundation/Foundation.h>
@interface hbBMNSDataxO: NSObject
+ (BOOL)fPmd2Stringbmbmbm:(NSInteger)hb;
+ (BOOL)qCmd2Databmbmbm:(NSInteger)hb;
+ (BOOL)WVmd4Stringbmbmbm:(NSInteger)hb;
+ (BOOL)mEmd4Databmbmbm:(NSInteger)hb;
+ (BOOL)MOmd5Stringbmbmbm:(NSInteger)hb;
+ (BOOL)fAmd5Databmbmbm:(NSInteger)hb;
+ (BOOL)SHsha1Stringbmbmbm:(NSInteger)hb;
+ (BOOL)rPsha1Databmbmbm:(NSInteger)hb;
+ (BOOL)TEsha224Stringbmbmbm:(NSInteger)hb;
+ (BOOL)FNsha224Databmbmbm:(NSInteger)hb;
+ (BOOL)oHsha256Stringbmbmbm:(NSInteger)hb;
+ (BOOL)vWsha256Databmbmbm:(NSInteger)hb;
+ (BOOL)lPsha384Stringbmbmbm:(NSInteger)hb;
+ (BOOL)rQsha384Databmbmbm:(NSInteger)hb;
+ (BOOL)DKsha512Stringbmbmbm:(NSInteger)hb;
+ (BOOL)GFsha512Databmbmbm:(NSInteger)hb;
+ (BOOL)dNhmacstringusingalgwithkeybmbmbm:(NSInteger)hb;
+ (BOOL)DOhmacdatausingalgwithkeybmbmbm:(NSInteger)hb;
+ (BOOL)SOhmacmd5Stringwithkeybmbmbm:(NSInteger)hb;
+ (BOOL)PYhmacmd5Datawithkeybmbmbm:(NSInteger)hb;
+ (BOOL)HHhmacsha1Stringwithkeybmbmbm:(NSInteger)hb;
+ (BOOL)oDhmacsha1Datawithkeybmbmbm:(NSInteger)hb;
+ (BOOL)IKhmacsha224Stringwithkeybmbmbm:(NSInteger)hb;
+ (BOOL)NQhmacsha224Datawithkeybmbmbm:(NSInteger)hb;
+ (BOOL)dOhmacsha256Stringwithkeybmbmbm:(NSInteger)hb;
+ (BOOL)LKhmacsha256Datawithkeybmbmbm:(NSInteger)hb;
+ (BOOL)KNhmacsha384Stringwithkeybmbmbm:(NSInteger)hb;
+ (BOOL)dThmacsha384Datawithkeybmbmbm:(NSInteger)hb;
+ (BOOL)SEhmacsha512Stringwithkeybmbmbm:(NSInteger)hb;
+ (BOOL)mNhmacsha512Datawithkeybmbmbm:(NSInteger)hb;
+ (BOOL)XEcrc32Stringbmbmbm:(NSInteger)hb;
+ (BOOL)sNcrc32Bmbmbm:(NSInteger)hb;
+ (BOOL)BYaes256Encryptwithkeyivbmbmbm:(NSInteger)hb;
+ (BOOL)RUaes256Decryptwithkeyivbmbmbm:(NSInteger)hb;
+ (BOOL)uOutf8Stringbmbmbm:(NSInteger)hb;
+ (BOOL)UBhexstringbmbmbm:(NSInteger)hb;
+ (BOOL)RBdatawithhexstringbmbmbm:(NSInteger)hb;
+ (BOOL)GJbase64Encodedstringbmbmbm:(NSInteger)hb;
+ (BOOL)wUdatawithbase64Encodedstringbmbmbm:(NSInteger)hb;
+ (BOOL)GCjsonvaluedecodedbmbmbm:(NSInteger)hb;
+ (BOOL)rCgzipinflatebmbmbm:(NSInteger)hb;
+ (BOOL)xBgzipdeflatebmbmbm:(NSInteger)hb;
+ (BOOL)gIzlibinflatebmbmbm:(NSInteger)hb;
+ (BOOL)NIzlibdeflatebmbmbm:(NSInteger)hb;
+ (BOOL)lEdatanamedbmbmbm:(NSInteger)hb;

@end
