#import <Foundation/Foundation.h>
@interface hbGPUImageFilterY: NSObject
+ (BOOL)JInitwithvertexshaderfromstringfragmentshaderfromstringbmbmbm:(NSInteger)hb;
+ (BOOL)WInitwithfragmentshaderfromstringbmbmbm:(NSInteger)hb;
+ (BOOL)yInitwithfragmentshaderfromfilebmbmbm:(NSInteger)hb;
+ (BOOL)pInitbmbmbm:(NSInteger)hb;
+ (BOOL)VInitializeattributesbmbmbm:(NSInteger)hb;
+ (BOOL)cSetupfilterforsizebmbmbm:(NSInteger)hb;
+ (BOOL)uDeallocbmbmbm:(NSInteger)hb;
+ (BOOL)vUsenextframeforimagecapturebmbmbm:(NSInteger)hb;
+ (BOOL)XNewcgimagefromcurrentlyprocessedoutputbmbmbm:(NSInteger)hb;
+ (BOOL)MSizeoffbobmbmbm:(NSInteger)hb;
+ (BOOL)kTexturecoordinatesforrotationbmbmbm:(NSInteger)hb;
+ (BOOL)oRendertotexturewithverticestexturecoordinatesbmbmbm:(NSInteger)hb;
+ (BOOL)qInformtargetsaboutnewframeattimebmbmbm:(NSInteger)hb;
+ (BOOL)KOutputframesizebmbmbm:(NSInteger)hb;
+ (BOOL)fSetbackgroundcolorredgreenbluealphabmbmbm:(NSInteger)hb;
+ (BOOL)HSetintegerforuniformnamebmbmbm:(NSInteger)hb;
+ (BOOL)GSetfloatforuniformnamebmbmbm:(NSInteger)hb;
+ (BOOL)pSetsizeforuniformnamebmbmbm:(NSInteger)hb;
+ (BOOL)nSetpointforuniformnamebmbmbm:(NSInteger)hb;
+ (BOOL)ySetfloatvec3Foruniformnamebmbmbm:(NSInteger)hb;
+ (BOOL)SSetfloatvec4Foruniformbmbmbm:(NSInteger)hb;
+ (BOOL)pSetfloatarraylengthforuniformbmbmbm:(NSInteger)hb;
+ (BOOL)dSetmatrix3Fforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)dSetmatrix4Fforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)ISetfloatforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)DSetpointforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)kSetsizeforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)TSetvec3Foruniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)lSetvec4Foruniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)HSetfloatarraylengthforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)ESetintegerforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)mSetandexecuteuniformstatecallbackatindexforprogramtoblockbmbmbm:(NSInteger)hb;
+ (BOOL)uSetuniformsforprogramatindexbmbmbm:(NSInteger)hb;
+ (BOOL)wNewframereadyattimeatindexbmbmbm:(NSInteger)hb;
+ (BOOL)fNextavailabletextureindexbmbmbm:(NSInteger)hb;
+ (BOOL)bSetinputframebufferatindexbmbmbm:(NSInteger)hb;
+ (BOOL)ORotatedsizeforindexbmbmbm:(NSInteger)hb;
+ (BOOL)gRotatedpointforrotationbmbmbm:(NSInteger)hb;
+ (BOOL)uSetinputsizeatindexbmbmbm:(NSInteger)hb;
+ (BOOL)iSetinputrotationatindexbmbmbm:(NSInteger)hb;
+ (BOOL)AForceprocessingatsizebmbmbm:(NSInteger)hb;
+ (BOOL)zForceprocessingatsizerespectingaspectratiobmbmbm:(NSInteger)hb;
+ (BOOL)AMaximumoutputsizebmbmbm:(NSInteger)hb;
+ (BOOL)nEndprocessingbmbmbm:(NSInteger)hb;
+ (BOOL)WWantsmonochromeinputbmbmbm:(NSInteger)hb;

@end
