#import <Foundation/Foundation.h>
@interface hbGPUImageFiltert: NSObject
+ (BOOL)fInitwithvertexshaderfromstringfragmentshaderfromstringbmbmbmhb:(NSInteger)hb;
+ (BOOL)xInitwithfragmentshaderfromstringbmbmbmhb:(NSInteger)hb;
+ (BOOL)NInitwithfragmentshaderfromfilebmbmbmhb:(NSInteger)hb;
+ (BOOL)kInitbmbmbmhb:(NSInteger)hb;
+ (BOOL)yInitializeattributesbmbmbmhb:(NSInteger)hb;
+ (BOOL)nSetupfilterforsizebmbmbmhb:(NSInteger)hb;
+ (BOOL)gDeallocbmbmbmhb:(NSInteger)hb;
+ (BOOL)lUsenextframeforimagecapturebmbmbmhb:(NSInteger)hb;
+ (BOOL)dNewcgimagefromcurrentlyprocessedoutputbmbmbmhb:(NSInteger)hb;
+ (BOOL)zSizeoffbobmbmbmhb:(NSInteger)hb;
+ (BOOL)uTexturecoordinatesforrotationbmbmbmhb:(NSInteger)hb;
+ (BOOL)SRendertotexturewithverticestexturecoordinatesbmbmbmhb:(NSInteger)hb;
+ (BOOL)NInformtargetsaboutnewframeattimebmbmbmhb:(NSInteger)hb;
+ (BOOL)ROutputframesizebmbmbmhb:(NSInteger)hb;
+ (BOOL)xSetbackgroundcolorredgreenbluealphabmbmbmhb:(NSInteger)hb;
+ (BOOL)vSetintegerforuniformnamebmbmbmhb:(NSInteger)hb;
+ (BOOL)YSetfloatforuniformnamebmbmbmhb:(NSInteger)hb;
+ (BOOL)zSetsizeforuniformnamebmbmbmhb:(NSInteger)hb;
+ (BOOL)lSetpointforuniformnamebmbmbmhb:(NSInteger)hb;
+ (BOOL)OSetfloatvec3Foruniformnamebmbmbmhb:(NSInteger)hb;
+ (BOOL)cSetfloatvec4Foruniformbmbmbmhb:(NSInteger)hb;
+ (BOOL)aSetfloatarraylengthforuniformbmbmbmhb:(NSInteger)hb;
+ (BOOL)wSetmatrix3Fforuniformprogrambmbmbmhb:(NSInteger)hb;
+ (BOOL)PSetmatrix4Fforuniformprogrambmbmbmhb:(NSInteger)hb;
+ (BOOL)ySetfloatforuniformprogrambmbmbmhb:(NSInteger)hb;
+ (BOOL)MSetpointforuniformprogrambmbmbmhb:(NSInteger)hb;
+ (BOOL)uSetsizeforuniformprogrambmbmbmhb:(NSInteger)hb;
+ (BOOL)nSetvec3Foruniformprogrambmbmbmhb:(NSInteger)hb;
+ (BOOL)FSetvec4Foruniformprogrambmbmbmhb:(NSInteger)hb;
+ (BOOL)FSetfloatarraylengthforuniformprogrambmbmbmhb:(NSInteger)hb;
+ (BOOL)zSetintegerforuniformprogrambmbmbmhb:(NSInteger)hb;
+ (BOOL)DSetandexecuteuniformstatecallbackatindexforprogramtoblockbmbmbmhb:(NSInteger)hb;
+ (BOOL)lSetuniformsforprogramatindexbmbmbmhb:(NSInteger)hb;
+ (BOOL)DNewframereadyattimeatindexbmbmbmhb:(NSInteger)hb;
+ (BOOL)BNextavailabletextureindexbmbmbmhb:(NSInteger)hb;
+ (BOOL)eSetinputframebufferatindexbmbmbmhb:(NSInteger)hb;
+ (BOOL)wRotatedsizeforindexbmbmbmhb:(NSInteger)hb;
+ (BOOL)SRotatedpointforrotationbmbmbmhb:(NSInteger)hb;
+ (BOOL)GSetinputsizeatindexbmbmbmhb:(NSInteger)hb;
+ (BOOL)NSetinputrotationatindexbmbmbmhb:(NSInteger)hb;
+ (BOOL)HForceprocessingatsizebmbmbmhb:(NSInteger)hb;
+ (BOOL)bForceprocessingatsizerespectingaspectratiobmbmbmhb:(NSInteger)hb;
+ (BOOL)sMaximumoutputsizebmbmbmhb:(NSInteger)hb;
+ (BOOL)REndprocessingbmbmbmhb:(NSInteger)hb;
+ (BOOL)tWantsmonochromeinputbmbmbmhb:(NSInteger)hb;

@end
