#import <Foundation/Foundation.h>
@interface hbGPUImageFilterV: NSObject
+ (BOOL)cInitwithvertexshaderfromstringsFragmentshaderfromstring:(NSInteger)hb;
+ (BOOL)mInitwithfragmentshaderfromstring:(NSInteger)hb;
+ (BOOL)AInitwithfragmentshaderfromfile:(NSInteger)hb;
+ (BOOL)Ainit:(NSInteger)hb;
+ (BOOL)tinitializeAttributes:(NSInteger)hb;
+ (BOOL)zSetupfilterforsize:(NSInteger)hb;
+ (BOOL)adealloc:(NSInteger)hb;
+ (BOOL)museNextFrameForImageCapture:(NSInteger)hb;
+ (BOOL)OnewCGImageFromCurrentlyProcessedOutput:(NSInteger)hb;
+ (BOOL)MsizeOfFBO:(NSInteger)hb;
+ (BOOL)KTexturecoordinatesforrotation:(NSInteger)hb;
+ (BOOL)VRendertotexturewithverticesXTexturecoordinates:(NSInteger)hb;
+ (BOOL)lInformtargetsaboutnewframeattime:(NSInteger)hb;
+ (BOOL)EoutputFrameSize:(NSInteger)hb;
+ (BOOL)YSetbackgroundcolorredEGreennBlueDAlpha:(NSInteger)hb;
+ (BOOL)GSetintegerHForuniformname:(NSInteger)hb;
+ (BOOL)xSetfloatQForuniformname:(NSInteger)hb;
+ (BOOL)lSetsizeqForuniformname:(NSInteger)hb;
+ (BOOL)RSetpointQForuniformname:(NSInteger)hb;
+ (BOOL)VSetfloatvec3dForuniformname:(NSInteger)hb;
+ (BOOL)NSetfloatvec4sForuniform:(NSInteger)hb;
+ (BOOL)uSetfloatarrayoLengthWForuniform:(NSInteger)hb;
+ (BOOL)RSetmatrix3FtForuniformoProgram:(NSInteger)hb;
+ (BOOL)WSetmatrix4FkForuniformkProgram:(NSInteger)hb;
+ (BOOL)cSetfloatgForuniformgProgram:(NSInteger)hb;
+ (BOOL)CSetpointcForuniformQProgram:(NSInteger)hb;
+ (BOOL)ISetsizeLForuniformMProgram:(NSInteger)hb;
+ (BOOL)GSetvec3eForuniformpProgram:(NSInteger)hb;
+ (BOOL)wSetvec4uForuniformSProgram:(NSInteger)hb;
+ (BOOL)kSetfloatarrayTLengthmForuniformNProgram:(NSInteger)hb;
+ (BOOL)eSetintegerIForuniformcProgram:(NSInteger)hb;
+ (BOOL)lSetandexecuteuniformstatecallbackatindexOForprogramxToblock:(NSInteger)hb;
+ (BOOL)sSetuniformsforprogramatindex:(NSInteger)hb;
+ (BOOL)pNewframereadyattimeFAtindex:(NSInteger)hb;
+ (BOOL)InextAvailableTextureIndex:(NSInteger)hb;
+ (BOOL)TSetinputframebufferXAtindex:(NSInteger)hb;
+ (BOOL)XRotatedsizeLForindex:(NSInteger)hb;
+ (BOOL)WRotatedpointIForrotation:(NSInteger)hb;
+ (BOOL)jSetinputsizeYAtindex:(NSInteger)hb;
+ (BOOL)JSetinputrotationhAtindex:(NSInteger)hb;
+ (BOOL)yForceprocessingatsize:(NSInteger)hb;
+ (BOOL)oForceprocessingatsizerespectingaspectratio:(NSInteger)hb;
+ (BOOL)zmaximumOutputSize:(NSInteger)hb;
+ (BOOL)EendProcessing:(NSInteger)hb;
+ (BOOL)UwantsMonochromeInput:(NSInteger)hb;

@end
