#import <Foundation/Foundation.h>
@interface hbGPUImageFilterF: NSObject
+ (BOOL)TInitwithvertexshaderfromstringfragmentshaderfromstringbmbmbm:(NSInteger)hb;
+ (BOOL)tInitwithfragmentshaderfromstringbmbmbm:(NSInteger)hb;
+ (BOOL)BInitwithfragmentshaderfromfilebmbmbm:(NSInteger)hb;
+ (BOOL)MInitbmbmbm:(NSInteger)hb;
+ (BOOL)zInitializeattributesbmbmbm:(NSInteger)hb;
+ (BOOL)sSetupfilterforsizebmbmbm:(NSInteger)hb;
+ (BOOL)bDeallocbmbmbm:(NSInteger)hb;
+ (BOOL)iUsenextframeforimagecapturebmbmbm:(NSInteger)hb;
+ (BOOL)RNewcgimagefromcurrentlyprocessedoutputbmbmbm:(NSInteger)hb;
+ (BOOL)ASizeoffbobmbmbm:(NSInteger)hb;
+ (BOOL)iTexturecoordinatesforrotationbmbmbm:(NSInteger)hb;
+ (BOOL)BRendertotexturewithverticestexturecoordinatesbmbmbm:(NSInteger)hb;
+ (BOOL)tInformtargetsaboutnewframeattimebmbmbm:(NSInteger)hb;
+ (BOOL)UOutputframesizebmbmbm:(NSInteger)hb;
+ (BOOL)VSetbackgroundcolorredgreenbluealphabmbmbm:(NSInteger)hb;
+ (BOOL)pSetintegerforuniformnamebmbmbm:(NSInteger)hb;
+ (BOOL)YSetfloatforuniformnamebmbmbm:(NSInteger)hb;
+ (BOOL)pSetsizeforuniformnamebmbmbm:(NSInteger)hb;
+ (BOOL)PSetpointforuniformnamebmbmbm:(NSInteger)hb;
+ (BOOL)dSetfloatvec3Foruniformnamebmbmbm:(NSInteger)hb;
+ (BOOL)MSetfloatvec4Foruniformbmbmbm:(NSInteger)hb;
+ (BOOL)bSetfloatarraylengthforuniformbmbmbm:(NSInteger)hb;
+ (BOOL)aSetmatrix3Fforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)vSetmatrix4Fforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)pSetfloatforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)vSetpointforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)aSetsizeforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)GSetvec3Foruniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)WSetvec4Foruniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)iSetfloatarraylengthforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)ySetintegerforuniformprogrambmbmbm:(NSInteger)hb;
+ (BOOL)cSetandexecuteuniformstatecallbackatindexforprogramtoblockbmbmbm:(NSInteger)hb;
+ (BOOL)CSetuniformsforprogramatindexbmbmbm:(NSInteger)hb;
+ (BOOL)oNewframereadyattimeatindexbmbmbm:(NSInteger)hb;
+ (BOOL)yNextavailabletextureindexbmbmbm:(NSInteger)hb;
+ (BOOL)xSetinputframebufferatindexbmbmbm:(NSInteger)hb;
+ (BOOL)wRotatedsizeforindexbmbmbm:(NSInteger)hb;
+ (BOOL)HRotatedpointforrotationbmbmbm:(NSInteger)hb;
+ (BOOL)KSetinputsizeatindexbmbmbm:(NSInteger)hb;
+ (BOOL)lSetinputrotationatindexbmbmbm:(NSInteger)hb;
+ (BOOL)cForceprocessingatsizebmbmbm:(NSInteger)hb;
+ (BOOL)dForceprocessingatsizerespectingaspectratiobmbmbm:(NSInteger)hb;
+ (BOOL)wMaximumoutputsizebmbmbm:(NSInteger)hb;
+ (BOOL)SEndprocessingbmbmbm:(NSInteger)hb;
+ (BOOL)ZWantsmonochromeinputbmbmbm:(NSInteger)hb;

@end
