#import <Foundation/Foundation.h>
@interface hbIQKeyboardManagerB: NSObject
+ (BOOL)Oload:(NSInteger)hb;
+ (BOOL)binit:(NSInteger)hb;
+ (BOOL)vsharedManager:(NSInteger)hb;
+ (BOOL)Bdealloc:(NSInteger)hb;
+ (BOOL)VSetenable:(NSInteger)hb;
+ (BOOL)pprivateIsEnabled:(NSInteger)hb;
+ (BOOL)GSetkeyboarddistancefromtextfield:(NSInteger)hb;
+ (BOOL)OSetshouldresignontouchoutside:(NSInteger)hb;
+ (BOOL)dprivateShouldResignOnTouchOutside:(NSInteger)hb;
+ (BOOL)MSetmoveddistance:(NSInteger)hb;
+ (BOOL)YSetenableautotoolbar:(NSInteger)hb;
+ (BOOL)SprivateIsEnableAutoToolbar:(NSInteger)hb;
+ (BOOL)ykeyWindow:(NSInteger)hb;
+ (BOOL)QoptimizedAdjustPosition:(NSInteger)hb;
+ (BOOL)madjustPosition:(NSInteger)hb;
+ (BOOL)mrestorePosition:(NSInteger)hb;
+ (BOOL)OreloadLayoutIfNeeded:(NSInteger)hb;
+ (BOOL)fKeyboardwillshow:(NSInteger)hb;
+ (BOOL)xKeyboarddidshow:(NSInteger)hb;
+ (BOOL)RKeyboardwillhide:(NSInteger)hb;
+ (BOOL)lKeyboarddidhide:(NSInteger)hb;
+ (BOOL)hTextfieldviewdidbeginediting:(NSInteger)hb;
+ (BOOL)sTextfieldviewdidendediting:(NSInteger)hb;
+ (BOOL)cWillchangestatusbarorientation:(NSInteger)hb;
+ (BOOL)BTaprecognized:(NSInteger)hb;
+ (BOOL)pGesturerecognizerRShouldrecognizesimultaneouslywithgesturerecognizer:(NSInteger)hb;
+ (BOOL)ZGesturerecognizergShouldreceivetouch:(NSInteger)hb;
+ (BOOL)EresignFirstResponder:(NSInteger)hb;
+ (BOOL)ocanGoPrevious:(NSInteger)hb;
+ (BOOL)XcanGoNext:(NSInteger)hb;
+ (BOOL)ygoPrevious:(NSInteger)hb;
+ (BOOL)XgoNext:(NSInteger)hb;
+ (BOOL)OresponderViews:(NSInteger)hb;
+ (BOOL)oaddToolbarIfRequired:(NSInteger)hb;
+ (BOOL)fremoveToolbarIfRequired:(NSInteger)hb;
+ (BOOL)zreloadInputViews:(NSInteger)hb;
+ (BOOL)VPreviousaction:(NSInteger)hb;
+ (BOOL)NNextaction:(NSInteger)hb;
+ (BOOL)CDoneaction:(NSInteger)hb;
+ (BOOL)kRegistertextfieldviewclasszDidbegineditingnotificationnameQDidendeditingnotificationname:(NSInteger)hb;
+ (BOOL)UUnregistertextfieldviewclassIDidbegineditingnotificationnamefDidendeditingnotificationname:(NSInteger)hb;
+ (BOOL)iregisterAllNotifications:(NSInteger)hb;
+ (BOOL)KunregisterAllNotifications:(NSInteger)hb;
+ (BOOL)OShowlog:(NSInteger)hb;
+ (BOOL)KShowlogmIndentation:(NSInteger)hb;

@end
