#import <Foundation/Foundation.h>
@interface hbIQKeyboardManagerz: NSObject
+ (BOOL)Xload:(NSInteger)hb;
+ (BOOL)tinit:(NSInteger)hb;
+ (BOOL)VsharedManager:(NSInteger)hb;
+ (BOOL)hdealloc:(NSInteger)hb;
+ (BOOL)QSetenable:(NSInteger)hb;
+ (BOOL)RprivateIsEnabled:(NSInteger)hb;
+ (BOOL)dSetkeyboarddistancefromtextfield:(NSInteger)hb;
+ (BOOL)dSetshouldresignontouchoutside:(NSInteger)hb;
+ (BOOL)IprivateShouldResignOnTouchOutside:(NSInteger)hb;
+ (BOOL)TSetmoveddistance:(NSInteger)hb;
+ (BOOL)ESetenableautotoolbar:(NSInteger)hb;
+ (BOOL)uprivateIsEnableAutoToolbar:(NSInteger)hb;
+ (BOOL)nkeyWindow:(NSInteger)hb;
+ (BOOL)AoptimizedAdjustPosition:(NSInteger)hb;
+ (BOOL)hadjustPosition:(NSInteger)hb;
+ (BOOL)CrestorePosition:(NSInteger)hb;
+ (BOOL)AreloadLayoutIfNeeded:(NSInteger)hb;
+ (BOOL)vKeyboardwillshow:(NSInteger)hb;
+ (BOOL)AKeyboarddidshow:(NSInteger)hb;
+ (BOOL)ZKeyboardwillhide:(NSInteger)hb;
+ (BOOL)OKeyboarddidhide:(NSInteger)hb;
+ (BOOL)mTextfieldviewdidbeginediting:(NSInteger)hb;
+ (BOOL)oTextfieldviewdidendediting:(NSInteger)hb;
+ (BOOL)cWillchangestatusbarorientation:(NSInteger)hb;
+ (BOOL)pTaprecognized:(NSInteger)hb;
+ (BOOL)HGesturerecognizerfShouldrecognizesimultaneouslywithgesturerecognizer:(NSInteger)hb;
+ (BOOL)YGesturerecognizerDShouldreceivetouch:(NSInteger)hb;
+ (BOOL)bresignFirstResponder:(NSInteger)hb;
+ (BOOL)fcanGoPrevious:(NSInteger)hb;
+ (BOOL)NcanGoNext:(NSInteger)hb;
+ (BOOL)zgoPrevious:(NSInteger)hb;
+ (BOOL)dgoNext:(NSInteger)hb;
+ (BOOL)NresponderViews:(NSInteger)hb;
+ (BOOL)caddToolbarIfRequired:(NSInteger)hb;
+ (BOOL)OremoveToolbarIfRequired:(NSInteger)hb;
+ (BOOL)treloadInputViews:(NSInteger)hb;
+ (BOOL)vPreviousaction:(NSInteger)hb;
+ (BOOL)YNextaction:(NSInteger)hb;
+ (BOOL)jDoneaction:(NSInteger)hb;
+ (BOOL)zRegistertextfieldviewclassEDidbegineditingnotificationnameWDidendeditingnotificationname:(NSInteger)hb;
+ (BOOL)IUnregistertextfieldviewclassFDidbegineditingnotificationnamejDidendeditingnotificationname:(NSInteger)hb;
+ (BOOL)EregisterAllNotifications:(NSInteger)hb;
+ (BOOL)BunregisterAllNotifications:(NSInteger)hb;
+ (BOOL)uShowlog:(NSInteger)hb;
+ (BOOL)XShowlogRIndentation:(NSInteger)hb;

@end
