#import <Foundation/Foundation.h>
@interface hbMASConstraintR: NSObject
+ (BOOL)cinit:(NSInteger)hb;
+ (BOOL)p(id))equalTo:(NSInteger)hb;
+ (BOOL)Q(id))mas_equalTo:(NSInteger)hb;
+ (BOOL)v(id))greaterThanOrEqualTo:(NSInteger)hb;
+ (BOOL)Y(id))mas_greaterThanOrEqualTo:(NSInteger)hb;
+ (BOOL)y(id))lessThanOrEqualTo:(NSInteger)hb;
+ (BOOL)R(id))mas_lessThanOrEqualTo:(NSInteger)hb;
+ (BOOL)i(void))priorityLow:(NSInteger)hb;
+ (BOOL)U(void))priorityMedium:(NSInteger)hb;
+ (BOOL)M(void))priorityHigh:(NSInteger)hb;
+ (BOOL)C(MASEdgeInsets))insets:(NSInteger)hb;
+ (BOOL)f(CGFloat))inset:(NSInteger)hb;
+ (BOOL)d(CGSize))sizeOffset:(NSInteger)hb;
+ (BOOL)c(CGPoint))centerOffset:(NSInteger)hb;
+ (BOOL)K(CGFloat))offset:(NSInteger)hb;
+ (BOOL)d(NSValue *value))valueOffset:(NSInteger)hb;
+ (BOOL)f(id offset))mas_offset:(NSInteger)hb;
+ (BOOL)DSetlayoutconstantwithvalue:(NSInteger)hb;
+ (BOOL)kwith:(NSInteger)hb;
+ (BOOL)Xand:(NSInteger)hb;
+ (BOOL)NAddconstraintwithlayoutattribute:(NSInteger)hb;
+ (BOOL)Nleft:(NSInteger)hb;
+ (BOOL)ntop:(NSInteger)hb;
+ (BOOL)iright:(NSInteger)hb;
+ (BOOL)Ubottom:(NSInteger)hb;
+ (BOOL)Sleading:(NSInteger)hb;
+ (BOOL)rtrailing:(NSInteger)hb;
+ (BOOL)Zwidth:(NSInteger)hb;
+ (BOOL)Rheight:(NSInteger)hb;
+ (BOOL)RcenterX:(NSInteger)hb;
+ (BOOL)tcenterY:(NSInteger)hb;
+ (BOOL)rbaseline:(NSInteger)hb;
+ (BOOL)ufirstBaseline:(NSInteger)hb;
+ (BOOL)PlastBaseline:(NSInteger)hb;
+ (BOOL)GleftMargin:(NSInteger)hb;
+ (BOOL)srightMargin:(NSInteger)hb;
+ (BOOL)FtopMargin:(NSInteger)hb;
+ (BOOL)ybottomMargin:(NSInteger)hb;
+ (BOOL)MleadingMargin:(NSInteger)hb;
+ (BOOL)NtrailingMargin:(NSInteger)hb;
+ (BOOL)QcenterXWithinMargins:(NSInteger)hb;
+ (BOOL)wcenterYWithinMargins:(NSInteger)hb;
+ (BOOL)r(CGFloat multiplier))multipliedBy:(NSInteger)hb;
+ (BOOL)B(CGFloat divider))dividedBy:(NSInteger)hb;
+ (BOOL)k(MASLayoutPriority priority))priority:(NSInteger)hb;
+ (BOOL)K(id, NSLayoutRelation))equalToWithRelation:(NSInteger)hb;
+ (BOOL)j(id key))key:(NSInteger)hb;
+ (BOOL)ZSetinsets:(NSInteger)hb;
+ (BOOL)nSetinset:(NSInteger)hb;
+ (BOOL)QSetsizeoffset:(NSInteger)hb;
+ (BOOL)XSetcenteroffset:(NSInteger)hb;
+ (BOOL)tSetoffset:(NSInteger)hb;
+ (BOOL)Nanimator:(NSInteger)hb;
+ (BOOL)iactivate:(NSInteger)hb;
+ (BOOL)Qdeactivate:(NSInteger)hb;
+ (BOOL)Winstall:(NSInteger)hb;
+ (BOOL)Vuninstall:(NSInteger)hb;

@end
