#import <Foundation/Foundation.h>
@interface hbMASConstraintp: NSObject
+ (BOOL)Iinit:(NSInteger)hb;
+ (BOOL)G(id))equalTo:(NSInteger)hb;
+ (BOOL)V(id))mas_equalTo:(NSInteger)hb;
+ (BOOL)A(id))greaterThanOrEqualTo:(NSInteger)hb;
+ (BOOL)A(id))mas_greaterThanOrEqualTo:(NSInteger)hb;
+ (BOOL)S(id))lessThanOrEqualTo:(NSInteger)hb;
+ (BOOL)s(id))mas_lessThanOrEqualTo:(NSInteger)hb;
+ (BOOL)T(void))priorityLow:(NSInteger)hb;
+ (BOOL)I(void))priorityMedium:(NSInteger)hb;
+ (BOOL)F(void))priorityHigh:(NSInteger)hb;
+ (BOOL)c(MASEdgeInsets))insets:(NSInteger)hb;
+ (BOOL)q(CGFloat))inset:(NSInteger)hb;
+ (BOOL)r(CGSize))sizeOffset:(NSInteger)hb;
+ (BOOL)L(CGPoint))centerOffset:(NSInteger)hb;
+ (BOOL)v(CGFloat))offset:(NSInteger)hb;
+ (BOOL)T(NSValue *value))valueOffset:(NSInteger)hb;
+ (BOOL)P(id offset))mas_offset:(NSInteger)hb;
+ (BOOL)uSetlayoutconstantwithvalue:(NSInteger)hb;
+ (BOOL)Zwith:(NSInteger)hb;
+ (BOOL)Yand:(NSInteger)hb;
+ (BOOL)DAddconstraintwithlayoutattribute:(NSInteger)hb;
+ (BOOL)gleft:(NSInteger)hb;
+ (BOOL)ltop:(NSInteger)hb;
+ (BOOL)wright:(NSInteger)hb;
+ (BOOL)dbottom:(NSInteger)hb;
+ (BOOL)yleading:(NSInteger)hb;
+ (BOOL)ytrailing:(NSInteger)hb;
+ (BOOL)rwidth:(NSInteger)hb;
+ (BOOL)bheight:(NSInteger)hb;
+ (BOOL)TcenterX:(NSInteger)hb;
+ (BOOL)PcenterY:(NSInteger)hb;
+ (BOOL)sbaseline:(NSInteger)hb;
+ (BOOL)KfirstBaseline:(NSInteger)hb;
+ (BOOL)blastBaseline:(NSInteger)hb;
+ (BOOL)eleftMargin:(NSInteger)hb;
+ (BOOL)brightMargin:(NSInteger)hb;
+ (BOOL)TtopMargin:(NSInteger)hb;
+ (BOOL)kbottomMargin:(NSInteger)hb;
+ (BOOL)WleadingMargin:(NSInteger)hb;
+ (BOOL)xtrailingMargin:(NSInteger)hb;
+ (BOOL)dcenterXWithinMargins:(NSInteger)hb;
+ (BOOL)ucenterYWithinMargins:(NSInteger)hb;
+ (BOOL)g(CGFloat multiplier))multipliedBy:(NSInteger)hb;
+ (BOOL)N(CGFloat divider))dividedBy:(NSInteger)hb;
+ (BOOL)w(MASLayoutPriority priority))priority:(NSInteger)hb;
+ (BOOL)U(id, NSLayoutRelation))equalToWithRelation:(NSInteger)hb;
+ (BOOL)I(id key))key:(NSInteger)hb;
+ (BOOL)PSetinsets:(NSInteger)hb;
+ (BOOL)LSetinset:(NSInteger)hb;
+ (BOOL)YSetsizeoffset:(NSInteger)hb;
+ (BOOL)iSetcenteroffset:(NSInteger)hb;
+ (BOOL)BSetoffset:(NSInteger)hb;
+ (BOOL)danimator:(NSInteger)hb;
+ (BOOL)uactivate:(NSInteger)hb;
+ (BOOL)Fdeactivate:(NSInteger)hb;
+ (BOOL)ninstall:(NSInteger)hb;
+ (BOOL)buninstall:(NSInteger)hb;

@end
