#import <Foundation/Foundation.h>
@interface hbNSDataJ: NSObject
+ (BOOL)Zmd2String:(NSInteger)hb;
+ (BOOL)bmd2Data:(NSInteger)hb;
+ (BOOL)Mmd4String:(NSInteger)hb;
+ (BOOL)Gmd4Data:(NSInteger)hb;
+ (BOOL)Wmd5String:(NSInteger)hb;
+ (BOOL)Wmd5Data:(NSInteger)hb;
+ (BOOL)Ssha1String:(NSInteger)hb;
+ (BOOL)Asha1Data:(NSInteger)hb;
+ (BOOL)nsha224String:(NSInteger)hb;
+ (BOOL)tsha224Data:(NSInteger)hb;
+ (BOOL)dsha256String:(NSInteger)hb;
+ (BOOL)Ysha256Data:(NSInteger)hb;
+ (BOOL)Wsha384String:(NSInteger)hb;
+ (BOOL)asha384Data:(NSInteger)hb;
+ (BOOL)Wsha512String:(NSInteger)hb;
+ (BOOL)isha512Data:(NSInteger)hb;
+ (BOOL)MHmacstringusingalgHWithkey:(NSInteger)hb;
+ (BOOL)OHmacdatausingalgDWithkey:(NSInteger)hb;
+ (BOOL)yHmacmd5Stringwithkey:(NSInteger)hb;
+ (BOOL)PHmacmd5Datawithkey:(NSInteger)hb;
+ (BOOL)WHmacsha1Stringwithkey:(NSInteger)hb;
+ (BOOL)WHmacsha1Datawithkey:(NSInteger)hb;
+ (BOOL)THmacsha224Stringwithkey:(NSInteger)hb;
+ (BOOL)hHmacsha224Datawithkey:(NSInteger)hb;
+ (BOOL)OHmacsha256Stringwithkey:(NSInteger)hb;
+ (BOOL)JHmacsha256Datawithkey:(NSInteger)hb;
+ (BOOL)EHmacsha384Stringwithkey:(NSInteger)hb;
+ (BOOL)oHmacsha384Datawithkey:(NSInteger)hb;
+ (BOOL)nHmacsha512Stringwithkey:(NSInteger)hb;
+ (BOOL)QHmacsha512Datawithkey:(NSInteger)hb;
+ (BOOL)Kcrc32String:(NSInteger)hb;
+ (BOOL)vcrc32:(NSInteger)hb;
+ (BOOL)SAes256EncryptwithkeyyIv:(NSInteger)hb;
+ (BOOL)BAes256DecryptwithkeyEIv:(NSInteger)hb;
+ (BOOL)Wutf8String:(NSInteger)hb;
+ (BOOL)EhexString:(NSInteger)hb;
+ (BOOL)nDatawithhexstring:(NSInteger)hb;
+ (BOOL)Qbase64EncodedString:(NSInteger)hb;
+ (BOOL)xDatawithbase64Encodedstring:(NSInteger)hb;
+ (BOOL)PjsonValueDecoded:(NSInteger)hb;
+ (BOOL)tgzipInflate:(NSInteger)hb;
+ (BOOL)vgzipDeflate:(NSInteger)hb;
+ (BOOL)czlibInflate:(NSInteger)hb;
+ (BOOL)JzlibDeflate:(NSInteger)hb;
+ (BOOL)pDatanamed:(NSInteger)hb;

@end
