#import <Foundation/Foundation.h>
@interface hbNSDataB: NSObject
+ (BOOL)MMd2Stringbmbm:(NSInteger)hb;
+ (BOOL)GMd2Databmbm:(NSInteger)hb;
+ (BOOL)zMd4Stringbmbm:(NSInteger)hb;
+ (BOOL)NMd4Databmbm:(NSInteger)hb;
+ (BOOL)AMd5Stringbmbm:(NSInteger)hb;
+ (BOOL)uMd5Databmbm:(NSInteger)hb;
+ (BOOL)FSha1Stringbmbm:(NSInteger)hb;
+ (BOOL)QSha1Databmbm:(NSInteger)hb;
+ (BOOL)HSha224Stringbmbm:(NSInteger)hb;
+ (BOOL)dSha224Databmbm:(NSInteger)hb;
+ (BOOL)pSha256Stringbmbm:(NSInteger)hb;
+ (BOOL)aSha256Databmbm:(NSInteger)hb;
+ (BOOL)zSha384Stringbmbm:(NSInteger)hb;
+ (BOOL)KSha384Databmbm:(NSInteger)hb;
+ (BOOL)zSha512Stringbmbm:(NSInteger)hb;
+ (BOOL)lSha512Databmbm:(NSInteger)hb;
+ (BOOL)wHmacstringusingalgwithkeybmbm:(NSInteger)hb;
+ (BOOL)bHmacdatausingalgwithkeybmbm:(NSInteger)hb;
+ (BOOL)wHmacmd5Stringwithkeybmbm:(NSInteger)hb;
+ (BOOL)YHmacmd5Datawithkeybmbm:(NSInteger)hb;
+ (BOOL)jHmacsha1Stringwithkeybmbm:(NSInteger)hb;
+ (BOOL)VHmacsha1Datawithkeybmbm:(NSInteger)hb;
+ (BOOL)HHmacsha224Stringwithkeybmbm:(NSInteger)hb;
+ (BOOL)NHmacsha224Datawithkeybmbm:(NSInteger)hb;
+ (BOOL)fHmacsha256Stringwithkeybmbm:(NSInteger)hb;
+ (BOOL)iHmacsha256Datawithkeybmbm:(NSInteger)hb;
+ (BOOL)EHmacsha384Stringwithkeybmbm:(NSInteger)hb;
+ (BOOL)XHmacsha384Datawithkeybmbm:(NSInteger)hb;
+ (BOOL)EHmacsha512Stringwithkeybmbm:(NSInteger)hb;
+ (BOOL)UHmacsha512Datawithkeybmbm:(NSInteger)hb;
+ (BOOL)bCrc32Stringbmbm:(NSInteger)hb;
+ (BOOL)KCrc32Bmbm:(NSInteger)hb;
+ (BOOL)OAes256Encryptwithkeyivbmbm:(NSInteger)hb;
+ (BOOL)CAes256Decryptwithkeyivbmbm:(NSInteger)hb;
+ (BOOL)fUtf8Stringbmbm:(NSInteger)hb;
+ (BOOL)RHexstringbmbm:(NSInteger)hb;
+ (BOOL)nDatawithhexstringbmbm:(NSInteger)hb;
+ (BOOL)ABase64Encodedstringbmbm:(NSInteger)hb;
+ (BOOL)RDatawithbase64Encodedstringbmbm:(NSInteger)hb;
+ (BOOL)EJsonvaluedecodedbmbm:(NSInteger)hb;
+ (BOOL)UGzipinflatebmbm:(NSInteger)hb;
+ (BOOL)GGzipdeflatebmbm:(NSInteger)hb;
+ (BOOL)AZlibinflatebmbm:(NSInteger)hb;
+ (BOOL)iZlibdeflatebmbm:(NSInteger)hb;
+ (BOOL)fDatanamedbmbm:(NSInteger)hb;

@end
