#import <Foundation/Foundation.h>
@interface hbUIViewp: NSObject
+ (BOOL)JShouldreadjustframebeforestorecachebmbm:(NSInteger)hb;
+ (BOOL)cSetshouldreadjustframebeforestorecachebmbm:(NSInteger)hb;
+ (BOOL)TLeft_Sdbmbm:(NSInteger)hb;
+ (BOOL)HSetleft_Sdbmbm:(NSInteger)hb;
+ (BOOL)bTop_Sdbmbm:(NSInteger)hb;
+ (BOOL)VSettop_Sdbmbm:(NSInteger)hb;
+ (BOOL)FRight_Sdbmbm:(NSInteger)hb;
+ (BOOL)JSetright_Sdbmbm:(NSInteger)hb;
+ (BOOL)jBottom_Sdbmbm:(NSInteger)hb;
+ (BOOL)MSetbottom_Sdbmbm:(NSInteger)hb;
+ (BOOL)zCenterx_Sdbmbm:(NSInteger)hb;
+ (BOOL)bSetcenterx_Sdbmbm:(NSInteger)hb;
+ (BOOL)TCentery_Sdbmbm:(NSInteger)hb;
+ (BOOL)kSetcentery_Sdbmbm:(NSInteger)hb;
+ (BOOL)dWidth_Sdbmbm:(NSInteger)hb;
+ (BOOL)kSetwidth_Sdbmbm:(NSInteger)hb;
+ (BOOL)oHeight_Sdbmbm:(NSInteger)hb;
+ (BOOL)BSetheight_Sdbmbm:(NSInteger)hb;
+ (BOOL)zOrigin_Sdbmbm:(NSInteger)hb;
+ (BOOL)oSetorigin_Sdbmbm:(NSInteger)hb;
+ (BOOL)cSize_Sdbmbm:(NSInteger)hb;
+ (BOOL)NSetsize_Sdbmbm:(NSInteger)hb;
+ (BOOL)XSetwidthbmbm:(NSInteger)hb;
+ (BOOL)mSetheightbmbm:(NSInteger)hb;
+ (BOOL)ASetsizebmbm:(NSInteger)hb;
+ (BOOL)YLeftbmbm:(NSInteger)hb;
+ (BOOL)zSetleftbmbm:(NSInteger)hb;
+ (BOOL)dRightbmbm:(NSInteger)hb;
+ (BOOL)zSetrightbmbm:(NSInteger)hb;
+ (BOOL)MWidthbmbm:(NSInteger)hb;
+ (BOOL)HHeightbmbm:(NSInteger)hb;
+ (BOOL)pTopbmbm:(NSInteger)hb;
+ (BOOL)KSettopbmbm:(NSInteger)hb;
+ (BOOL)zBottombmbm:(NSInteger)hb;
+ (BOOL)aSetbottombmbm:(NSInteger)hb;
+ (BOOL)bCenterxbmbm:(NSInteger)hb;
+ (BOOL)NSetcenterxbmbm:(NSInteger)hb;
+ (BOOL)KCenterybmbm:(NSInteger)hb;
+ (BOOL)gSetcenterybmbm:(NSInteger)hb;
+ (BOOL)tOriginbmbm:(NSInteger)hb;
+ (BOOL)WSetoriginbmbm:(NSInteger)hb;
+ (BOOL)HSizebmbm:(NSInteger)hb;

@end
