#import <Foundation/Foundation.h>
#import "AFURLResponseSerialization.h"
#import "AFURLRequestSerialization.h"
#import "AFSecurityPolicy.h"
#import "AFCompatibilityMacros.h"
#import "AFNetworkReachabilityManager.h"
#import "AFURLSessionManager.h"
#import <objc/runtime.h>

@interface AFURLSessionManager (-Deletecomments)
+ (BOOL)init-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithSessionConfiguration-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dealloc-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)session-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)taskDescriptionForSessionTasks-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)taskDidResume-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)taskDidSuspend-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)delegateForTask-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setDelegateFortask-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)addDelegateForDataTaskUploadprogressDownloadprogressCompletionhandler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)addDelegateForUploadTaskProgressCompletionhandler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)addDelegateForDownloadTaskProgressDestinationCompletionhandler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)removeDelegateForTask-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tasksForKeyPath-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tasks-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dataTasks-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)uploadTasks-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)downloadTasks-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)invalidateSessionCancelingTasksResetsession-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setResponseSerializer-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)addNotificationObserverForTask-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)removeNotificationObserverForTask-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dataTaskWithRequestUploadprogressDownloadprogressCompletionhandler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)uploadTaskWithRequestFromfileProgressCompletionhandler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)uploadTaskWithRequestFromdataProgressCompletionhandler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)uploadTaskWithStreamedRequestProgressCompletionhandler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)downloadTaskWithRequestProgressDestinationCompletionhandler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)downloadTaskWithResumeDataProgressDestinationCompletionhandler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)uploadProgressForTask-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)downloadProgressForTask-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setSessionDidBecomeInvalidBlock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setSessionDidReceiveAuthenticationChallengeBlock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setDidFinishEventsForBackgroundURLSessionBlock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTaskNeedNewBodyStreamBlock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTaskWillPerformHTTPRedirectionBlock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTaskDidSendBodyDataBlock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTaskDidCompleteBlock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTaskDidFinishCollectingMetricsBlock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setDataTaskDidReceiveResponseBlock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setDataTaskDidBecomeDownloadTaskBlock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setDataTaskDidReceiveDataBlock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setDataTaskWillCacheResponseBlock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setDownloadTaskDidFinishDownloadingBlock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setDownloadTaskDidWriteDataBlock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setDownloadTaskDidResumeBlock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)description-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)respondsToSelector-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionDidbecomeinvalidwitherror-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionDidreceivechallengeCompletionhandler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionTaskWillperformhttpredirectionNewrequestCompletionhandler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionTaskDidreceivechallengeCompletionhandler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)serverTrustErrorForServerTrustUrl-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionTaskNeednewbodystream-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionTaskDidsendbodydataTotalbytessentTotalbytesexpectedtosend-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionTaskDidcompletewitherror-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionTaskDidfinishcollectingmetrics-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionDatataskDidreceiveresponseCompletionhandler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionDatataskDidbecomedownloadtask-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionDatataskDidreceivedata-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionDatataskWillcacheresponseCompletionhandler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionDidFinishEventsForBackgroundURLSession-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionDownloadtaskDidfinishdownloadingtourl-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionDownloadtaskDidwritedataTotalbyteswrittenTotalbytesexpectedtowrite-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URLSessionDownloadtaskDidresumeatoffsetExpectedtotalbytes-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)supportsSecureCoding-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithCoder-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)encodeWithCoder-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)copyWithZone-Deletecomments:(NSInteger)-deleteComments;

@end
