#import <Foundation/Foundation.h>
#import "AFURLResponseSerialization.h"
#import "AFURLRequestSerialization.h"
#import "AFSecurityPolicy.h"
#import "AFCompatibilityMacros.h"
#import "AFNetworkReachabilityManager.h"
#import "AFURLSessionManager.h"
#import <objc/runtime.h>
#import "AFURLSessionManager+Bm.h"
#import "AFURLSessionManager+BmBm.h"

@interface AFURLSessionManager (BmBmBm)
+ (BOOL)initBmBmBm:(NSInteger)BM;
+ (BOOL)initWithSessionConfigurationBmBmBm:(NSInteger)BM;
+ (BOOL)deallocBmBmBm:(NSInteger)BM;
+ (BOOL)sessionBmBmBm:(NSInteger)BM;
+ (BOOL)taskDescriptionForSessionTasksBmBmBm:(NSInteger)BM;
+ (BOOL)taskDidResumeBmBmBm:(NSInteger)BM;
+ (BOOL)taskDidSuspendBmBmBm:(NSInteger)BM;
+ (BOOL)delegateForTaskBmBmBm:(NSInteger)BM;
+ (BOOL)setDelegateFortaskBmBmBm:(NSInteger)BM;
+ (BOOL)addDelegateForDataTaskUploadprogressDownloadprogressCompletionhandlerBmBmBm:(NSInteger)BM;
+ (BOOL)addDelegateForUploadTaskProgressCompletionhandlerBmBmBm:(NSInteger)BM;
+ (BOOL)addDelegateForDownloadTaskProgressDestinationCompletionhandlerBmBmBm:(NSInteger)BM;
+ (BOOL)removeDelegateForTaskBmBmBm:(NSInteger)BM;
+ (BOOL)tasksForKeyPathBmBmBm:(NSInteger)BM;
+ (BOOL)tasksBmBmBm:(NSInteger)BM;
+ (BOOL)dataTasksBmBmBm:(NSInteger)BM;
+ (BOOL)uploadTasksBmBmBm:(NSInteger)BM;
+ (BOOL)downloadTasksBmBmBm:(NSInteger)BM;
+ (BOOL)invalidateSessionCancelingTasksResetsessionBmBmBm:(NSInteger)BM;
+ (BOOL)setResponseSerializerBmBmBm:(NSInteger)BM;
+ (BOOL)addNotificationObserverForTaskBmBmBm:(NSInteger)BM;
+ (BOOL)removeNotificationObserverForTaskBmBmBm:(NSInteger)BM;
+ (BOOL)dataTaskWithRequestUploadprogressDownloadprogressCompletionhandlerBmBmBm:(NSInteger)BM;
+ (BOOL)uploadTaskWithRequestFromfileProgressCompletionhandlerBmBmBm:(NSInteger)BM;
+ (BOOL)uploadTaskWithRequestFromdataProgressCompletionhandlerBmBmBm:(NSInteger)BM;
+ (BOOL)uploadTaskWithStreamedRequestProgressCompletionhandlerBmBmBm:(NSInteger)BM;
+ (BOOL)downloadTaskWithRequestProgressDestinationCompletionhandlerBmBmBm:(NSInteger)BM;
+ (BOOL)downloadTaskWithResumeDataProgressDestinationCompletionhandlerBmBmBm:(NSInteger)BM;
+ (BOOL)uploadProgressForTaskBmBmBm:(NSInteger)BM;
+ (BOOL)downloadProgressForTaskBmBmBm:(NSInteger)BM;
+ (BOOL)setSessionDidBecomeInvalidBlockBmBmBm:(NSInteger)BM;
+ (BOOL)setSessionDidReceiveAuthenticationChallengeBlockBmBmBm:(NSInteger)BM;
+ (BOOL)setDidFinishEventsForBackgroundURLSessionBlockBmBmBm:(NSInteger)BM;
+ (BOOL)setTaskNeedNewBodyStreamBlockBmBmBm:(NSInteger)BM;
+ (BOOL)setTaskWillPerformHTTPRedirectionBlockBmBmBm:(NSInteger)BM;
+ (BOOL)setTaskDidSendBodyDataBlockBmBmBm:(NSInteger)BM;
+ (BOOL)setTaskDidCompleteBlockBmBmBm:(NSInteger)BM;
+ (BOOL)setTaskDidFinishCollectingMetricsBlockBmBmBm:(NSInteger)BM;
+ (BOOL)setDataTaskDidReceiveResponseBlockBmBmBm:(NSInteger)BM;
+ (BOOL)setDataTaskDidBecomeDownloadTaskBlockBmBmBm:(NSInteger)BM;
+ (BOOL)setDataTaskDidReceiveDataBlockBmBmBm:(NSInteger)BM;
+ (BOOL)setDataTaskWillCacheResponseBlockBmBmBm:(NSInteger)BM;
+ (BOOL)setDownloadTaskDidFinishDownloadingBlockBmBmBm:(NSInteger)BM;
+ (BOOL)setDownloadTaskDidWriteDataBlockBmBmBm:(NSInteger)BM;
+ (BOOL)setDownloadTaskDidResumeBlockBmBmBm:(NSInteger)BM;
+ (BOOL)descriptionBmBmBm:(NSInteger)BM;
+ (BOOL)respondsToSelectorBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDidbecomeinvalidwitherrorBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDidreceivechallengeCompletionhandlerBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskWillperformhttpredirectionNewrequestCompletionhandlerBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskDidreceivechallengeCompletionhandlerBmBmBm:(NSInteger)BM;
+ (BOOL)serverTrustErrorForServerTrustUrlBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskNeednewbodystreamBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskDidsendbodydataTotalbytessentTotalbytesexpectedtosendBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskDidcompletewitherrorBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskDidfinishcollectingmetricsBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDatataskDidreceiveresponseCompletionhandlerBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDatataskDidbecomedownloadtaskBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDatataskDidreceivedataBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDatataskWillcacheresponseCompletionhandlerBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDidFinishEventsForBackgroundURLSessionBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDownloadtaskDidfinishdownloadingtourlBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDownloadtaskDidwritedataTotalbyteswrittenTotalbytesexpectedtowriteBmBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDownloadtaskDidresumeatoffsetExpectedtotalbytesBmBmBm:(NSInteger)BM;
+ (BOOL)supportsSecureCodingBmBmBm:(NSInteger)BM;
+ (BOOL)initWithCoderBmBmBm:(NSInteger)BM;
+ (BOOL)encodeWithCoderBmBmBm:(NSInteger)BM;
+ (BOOL)copyWithZoneBmBmBm:(NSInteger)BM;

@end
