#import <Foundation/Foundation.h>
#import "AFURLResponseSerialization.h"
#import "AFURLRequestSerialization.h"
#import "AFSecurityPolicy.h"
#import "AFCompatibilityMacros.h"
#import "AFNetworkReachabilityManager.h"
#import "AFURLSessionManager.h"
#import <objc/runtime.h>

@interface AFURLSessionManager (Bm)
+ (BOOL)initBm:(NSInteger)BM;
+ (BOOL)initWithSessionConfigurationBm:(NSInteger)BM;
+ (BOOL)deallocBm:(NSInteger)BM;
+ (BOOL)sessionBm:(NSInteger)BM;
+ (BOOL)taskDescriptionForSessionTasksBm:(NSInteger)BM;
+ (BOOL)taskDidResumeBm:(NSInteger)BM;
+ (BOOL)taskDidSuspendBm:(NSInteger)BM;
+ (BOOL)delegateForTaskBm:(NSInteger)BM;
+ (BOOL)setDelegateFortaskBm:(NSInteger)BM;
+ (BOOL)addDelegateForDataTaskUploadprogressDownloadprogressCompletionhandlerBm:(NSInteger)BM;
+ (BOOL)addDelegateForUploadTaskProgressCompletionhandlerBm:(NSInteger)BM;
+ (BOOL)addDelegateForDownloadTaskProgressDestinationCompletionhandlerBm:(NSInteger)BM;
+ (BOOL)removeDelegateForTaskBm:(NSInteger)BM;
+ (BOOL)tasksForKeyPathBm:(NSInteger)BM;
+ (BOOL)tasksBm:(NSInteger)BM;
+ (BOOL)dataTasksBm:(NSInteger)BM;
+ (BOOL)uploadTasksBm:(NSInteger)BM;
+ (BOOL)downloadTasksBm:(NSInteger)BM;
+ (BOOL)invalidateSessionCancelingTasksResetsessionBm:(NSInteger)BM;
+ (BOOL)setResponseSerializerBm:(NSInteger)BM;
+ (BOOL)addNotificationObserverForTaskBm:(NSInteger)BM;
+ (BOOL)removeNotificationObserverForTaskBm:(NSInteger)BM;
+ (BOOL)dataTaskWithRequestUploadprogressDownloadprogressCompletionhandlerBm:(NSInteger)BM;
+ (BOOL)uploadTaskWithRequestFromfileProgressCompletionhandlerBm:(NSInteger)BM;
+ (BOOL)uploadTaskWithRequestFromdataProgressCompletionhandlerBm:(NSInteger)BM;
+ (BOOL)uploadTaskWithStreamedRequestProgressCompletionhandlerBm:(NSInteger)BM;
+ (BOOL)downloadTaskWithRequestProgressDestinationCompletionhandlerBm:(NSInteger)BM;
+ (BOOL)downloadTaskWithResumeDataProgressDestinationCompletionhandlerBm:(NSInteger)BM;
+ (BOOL)uploadProgressForTaskBm:(NSInteger)BM;
+ (BOOL)downloadProgressForTaskBm:(NSInteger)BM;
+ (BOOL)setSessionDidBecomeInvalidBlockBm:(NSInteger)BM;
+ (BOOL)setSessionDidReceiveAuthenticationChallengeBlockBm:(NSInteger)BM;
+ (BOOL)setDidFinishEventsForBackgroundURLSessionBlockBm:(NSInteger)BM;
+ (BOOL)setTaskNeedNewBodyStreamBlockBm:(NSInteger)BM;
+ (BOOL)setTaskWillPerformHTTPRedirectionBlockBm:(NSInteger)BM;
+ (BOOL)setTaskDidSendBodyDataBlockBm:(NSInteger)BM;
+ (BOOL)setTaskDidCompleteBlockBm:(NSInteger)BM;
+ (BOOL)setTaskDidFinishCollectingMetricsBlockBm:(NSInteger)BM;
+ (BOOL)setDataTaskDidReceiveResponseBlockBm:(NSInteger)BM;
+ (BOOL)setDataTaskDidBecomeDownloadTaskBlockBm:(NSInteger)BM;
+ (BOOL)setDataTaskDidReceiveDataBlockBm:(NSInteger)BM;
+ (BOOL)setDataTaskWillCacheResponseBlockBm:(NSInteger)BM;
+ (BOOL)setDownloadTaskDidFinishDownloadingBlockBm:(NSInteger)BM;
+ (BOOL)setDownloadTaskDidWriteDataBlockBm:(NSInteger)BM;
+ (BOOL)setDownloadTaskDidResumeBlockBm:(NSInteger)BM;
+ (BOOL)descriptionBm:(NSInteger)BM;
+ (BOOL)respondsToSelectorBm:(NSInteger)BM;
+ (BOOL)URLSessionDidbecomeinvalidwitherrorBm:(NSInteger)BM;
+ (BOOL)URLSessionDidreceivechallengeCompletionhandlerBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskWillperformhttpredirectionNewrequestCompletionhandlerBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskDidreceivechallengeCompletionhandlerBm:(NSInteger)BM;
+ (BOOL)serverTrustErrorForServerTrustUrlBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskNeednewbodystreamBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskDidsendbodydataTotalbytessentTotalbytesexpectedtosendBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskDidcompletewitherrorBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskDidfinishcollectingmetricsBm:(NSInteger)BM;
+ (BOOL)URLSessionDatataskDidreceiveresponseCompletionhandlerBm:(NSInteger)BM;
+ (BOOL)URLSessionDatataskDidbecomedownloadtaskBm:(NSInteger)BM;
+ (BOOL)URLSessionDatataskDidreceivedataBm:(NSInteger)BM;
+ (BOOL)URLSessionDatataskWillcacheresponseCompletionhandlerBm:(NSInteger)BM;
+ (BOOL)URLSessionDidFinishEventsForBackgroundURLSessionBm:(NSInteger)BM;
+ (BOOL)URLSessionDownloadtaskDidfinishdownloadingtourlBm:(NSInteger)BM;
+ (BOOL)URLSessionDownloadtaskDidwritedataTotalbyteswrittenTotalbytesexpectedtowriteBm:(NSInteger)BM;
+ (BOOL)URLSessionDownloadtaskDidresumeatoffsetExpectedtotalbytesBm:(NSInteger)BM;
+ (BOOL)supportsSecureCodingBm:(NSInteger)BM;
+ (BOOL)initWithCoderBm:(NSInteger)BM;
+ (BOOL)encodeWithCoderBm:(NSInteger)BM;
+ (BOOL)copyWithZoneBm:(NSInteger)BM;

@end
