#import <Foundation/Foundation.h>
#import "AFURLResponseSerialization.h"
#import "AFURLRequestSerialization.h"
#import "AFSecurityPolicy.h"
#import "AFCompatibilityMacros.h"
#import "AFNetworkReachabilityManager.h"
#import "AFURLSessionManager.h"
#import <objc/runtime.h>
#import "AFURLSessionManager+Bm.h"

@interface AFURLSessionManager (BmBm)
+ (BOOL)initBmBm:(NSInteger)BM;
+ (BOOL)initWithSessionConfigurationBmBm:(NSInteger)BM;
+ (BOOL)deallocBmBm:(NSInteger)BM;
+ (BOOL)sessionBmBm:(NSInteger)BM;
+ (BOOL)taskDescriptionForSessionTasksBmBm:(NSInteger)BM;
+ (BOOL)taskDidResumeBmBm:(NSInteger)BM;
+ (BOOL)taskDidSuspendBmBm:(NSInteger)BM;
+ (BOOL)delegateForTaskBmBm:(NSInteger)BM;
+ (BOOL)setDelegateFortaskBmBm:(NSInteger)BM;
+ (BOOL)addDelegateForDataTaskUploadprogressDownloadprogressCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)addDelegateForUploadTaskProgressCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)addDelegateForDownloadTaskProgressDestinationCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)removeDelegateForTaskBmBm:(NSInteger)BM;
+ (BOOL)tasksForKeyPathBmBm:(NSInteger)BM;
+ (BOOL)tasksBmBm:(NSInteger)BM;
+ (BOOL)dataTasksBmBm:(NSInteger)BM;
+ (BOOL)uploadTasksBmBm:(NSInteger)BM;
+ (BOOL)downloadTasksBmBm:(NSInteger)BM;
+ (BOOL)invalidateSessionCancelingTasksResetsessionBmBm:(NSInteger)BM;
+ (BOOL)setResponseSerializerBmBm:(NSInteger)BM;
+ (BOOL)addNotificationObserverForTaskBmBm:(NSInteger)BM;
+ (BOOL)removeNotificationObserverForTaskBmBm:(NSInteger)BM;
+ (BOOL)dataTaskWithRequestUploadprogressDownloadprogressCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)uploadTaskWithRequestFromfileProgressCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)uploadTaskWithRequestFromdataProgressCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)uploadTaskWithStreamedRequestProgressCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)downloadTaskWithRequestProgressDestinationCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)downloadTaskWithResumeDataProgressDestinationCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)uploadProgressForTaskBmBm:(NSInteger)BM;
+ (BOOL)downloadProgressForTaskBmBm:(NSInteger)BM;
+ (BOOL)setSessionDidBecomeInvalidBlockBmBm:(NSInteger)BM;
+ (BOOL)setSessionDidReceiveAuthenticationChallengeBlockBmBm:(NSInteger)BM;
+ (BOOL)setDidFinishEventsForBackgroundURLSessionBlockBmBm:(NSInteger)BM;
+ (BOOL)setTaskNeedNewBodyStreamBlockBmBm:(NSInteger)BM;
+ (BOOL)setTaskWillPerformHTTPRedirectionBlockBmBm:(NSInteger)BM;
+ (BOOL)setTaskDidSendBodyDataBlockBmBm:(NSInteger)BM;
+ (BOOL)setTaskDidCompleteBlockBmBm:(NSInteger)BM;
+ (BOOL)setTaskDidFinishCollectingMetricsBlockBmBm:(NSInteger)BM;
+ (BOOL)setDataTaskDidReceiveResponseBlockBmBm:(NSInteger)BM;
+ (BOOL)setDataTaskDidBecomeDownloadTaskBlockBmBm:(NSInteger)BM;
+ (BOOL)setDataTaskDidReceiveDataBlockBmBm:(NSInteger)BM;
+ (BOOL)setDataTaskWillCacheResponseBlockBmBm:(NSInteger)BM;
+ (BOOL)setDownloadTaskDidFinishDownloadingBlockBmBm:(NSInteger)BM;
+ (BOOL)setDownloadTaskDidWriteDataBlockBmBm:(NSInteger)BM;
+ (BOOL)setDownloadTaskDidResumeBlockBmBm:(NSInteger)BM;
+ (BOOL)descriptionBmBm:(NSInteger)BM;
+ (BOOL)respondsToSelectorBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDidbecomeinvalidwitherrorBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDidreceivechallengeCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskWillperformhttpredirectionNewrequestCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskDidreceivechallengeCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)serverTrustErrorForServerTrustUrlBmBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskNeednewbodystreamBmBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskDidsendbodydataTotalbytessentTotalbytesexpectedtosendBmBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskDidcompletewitherrorBmBm:(NSInteger)BM;
+ (BOOL)URLSessionTaskDidfinishcollectingmetricsBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDatataskDidreceiveresponseCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDatataskDidbecomedownloadtaskBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDatataskDidreceivedataBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDatataskWillcacheresponseCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDidFinishEventsForBackgroundURLSessionBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDownloadtaskDidfinishdownloadingtourlBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDownloadtaskDidwritedataTotalbyteswrittenTotalbytesexpectedtowriteBmBm:(NSInteger)BM;
+ (BOOL)URLSessionDownloadtaskDidresumeatoffsetExpectedtotalbytesBmBm:(NSInteger)BM;
+ (BOOL)supportsSecureCodingBmBm:(NSInteger)BM;
+ (BOOL)initWithCoderBmBm:(NSInteger)BM;
+ (BOOL)encodeWithCoderBmBm:(NSInteger)BM;
+ (BOOL)copyWithZoneBmBm:(NSInteger)BM;

@end
