#import <Foundation/Foundation.h>
#import "BMAFURLSessionManagern.h"
#import "BMAFURLSessionManagern+Bm.h"

@interface BMAFURLSessionManagern (BmHb)
+ (BOOL)WInitbmBmHb:(NSInteger)hb;
+ (BOOL)lInitwithsessionconfigurationbmBmHb:(NSInteger)hb;
+ (BOOL)XDeallocbmBmHb:(NSInteger)hb;
+ (BOOL)FSessionbmBmHb:(NSInteger)hb;
+ (BOOL)JTaskdescriptionforsessiontasksbmBmHb:(NSInteger)hb;
+ (BOOL)ETaskdidresumebmBmHb:(NSInteger)hb;
+ (BOOL)HTaskdidsuspendbmBmHb:(NSInteger)hb;
+ (BOOL)jDelegatefortaskbmBmHb:(NSInteger)hb;
+ (BOOL)zSetdelegatefortaskbmBmHb:(NSInteger)hb;
+ (BOOL)jAdddelegatefordatataskuploadprogressdownloadprogresscompletionhandlerbmBmHb:(NSInteger)hb;
+ (BOOL)lAdddelegateforuploadtaskprogresscompletionhandlerbmBmHb:(NSInteger)hb;
+ (BOOL)PAdddelegatefordownloadtaskprogressdestinationcompletionhandlerbmBmHb:(NSInteger)hb;
+ (BOOL)NRemovedelegatefortaskbmBmHb:(NSInteger)hb;
+ (BOOL)KTasksforkeypathbmBmHb:(NSInteger)hb;
+ (BOOL)GTasksbmBmHb:(NSInteger)hb;
+ (BOOL)JDatatasksbmBmHb:(NSInteger)hb;
+ (BOOL)uUploadtasksbmBmHb:(NSInteger)hb;
+ (BOOL)nDownloadtasksbmBmHb:(NSInteger)hb;
+ (BOOL)wInvalidatesessioncancelingtasksresetsessionbmBmHb:(NSInteger)hb;
+ (BOOL)NSetresponseserializerbmBmHb:(NSInteger)hb;
+ (BOOL)JAddnotificationobserverfortaskbmBmHb:(NSInteger)hb;
+ (BOOL)fRemovenotificationobserverfortaskbmBmHb:(NSInteger)hb;
+ (BOOL)TDatataskwithrequestuploadprogressdownloadprogresscompletionhandlerbmBmHb:(NSInteger)hb;
+ (BOOL)nUploadtaskwithrequestfromfileprogresscompletionhandlerbmBmHb:(NSInteger)hb;
+ (BOOL)hUploadtaskwithrequestfromdataprogresscompletionhandlerbmBmHb:(NSInteger)hb;
+ (BOOL)ZUploadtaskwithstreamedrequestprogresscompletionhandlerbmBmHb:(NSInteger)hb;
+ (BOOL)ADownloadtaskwithrequestprogressdestinationcompletionhandlerbmBmHb:(NSInteger)hb;
+ (BOOL)lDownloadtaskwithresumedataprogressdestinationcompletionhandlerbmBmHb:(NSInteger)hb;
+ (BOOL)dUploadprogressfortaskbmBmHb:(NSInteger)hb;
+ (BOOL)mDownloadprogressfortaskbmBmHb:(NSInteger)hb;
+ (BOOL)TSetsessiondidbecomeinvalidblockbmBmHb:(NSInteger)hb;
+ (BOOL)HSetsessiondidreceiveauthenticationchallengeblockbmBmHb:(NSInteger)hb;
+ (BOOL)HSetdidfinisheventsforbackgroundurlsessionblockbmBmHb:(NSInteger)hb;
+ (BOOL)QSettaskneednewbodystreamblockbmBmHb:(NSInteger)hb;
+ (BOOL)TSettaskwillperformhttpredirectionblockbmBmHb:(NSInteger)hb;
+ (BOOL)JSettaskdidsendbodydatablockbmBmHb:(NSInteger)hb;
+ (BOOL)NSettaskdidcompleteblockbmBmHb:(NSInteger)hb;
+ (BOOL)JSettaskdidfinishcollectingmetricsblockbmBmHb:(NSInteger)hb;
+ (BOOL)ZSetdatataskdidreceiveresponseblockbmBmHb:(NSInteger)hb;
+ (BOOL)LSetdatataskdidbecomedownloadtaskblockbmBmHb:(NSInteger)hb;
+ (BOOL)ISetdatataskdidreceivedatablockbmBmHb:(NSInteger)hb;
+ (BOOL)NSetdatataskwillcacheresponseblockbmBmHb:(NSInteger)hb;
+ (BOOL)lSetdownloadtaskdidfinishdownloadingblockbmBmHb:(NSInteger)hb;
+ (BOOL)LSetdownloadtaskdidwritedatablockbmBmHb:(NSInteger)hb;
+ (BOOL)bSetdownloadtaskdidresumeblockbmBmHb:(NSInteger)hb;
+ (BOOL)DDescriptionbmBmHb:(NSInteger)hb;
+ (BOOL)eRespondstoselectorbmBmHb:(NSInteger)hb;
+ (BOOL)LUrlsessiondidbecomeinvalidwitherrorbmBmHb:(NSInteger)hb;
+ (BOOL)MUrlsessiondidreceivechallengecompletionhandlerbmBmHb:(NSInteger)hb;
+ (BOOL)fUrlsessiontaskwillperformhttpredirectionnewrequestcompletionhandlerbmBmHb:(NSInteger)hb;
+ (BOOL)pUrlsessiontaskdidreceivechallengecompletionhandlerbmBmHb:(NSInteger)hb;
+ (BOOL)qServertrusterrorforservertrusturlbmBmHb:(NSInteger)hb;
+ (BOOL)AUrlsessiontaskneednewbodystreambmBmHb:(NSInteger)hb;
+ (BOOL)HUrlsessiontaskdidsendbodydatatotalbytessenttotalbytesexpectedtosendbmBmHb:(NSInteger)hb;
+ (BOOL)oUrlsessiontaskdidcompletewitherrorbmBmHb:(NSInteger)hb;
+ (BOOL)GUrlsessiontaskdidfinishcollectingmetricsbmBmHb:(NSInteger)hb;
+ (BOOL)kUrlsessiondatataskdidreceiveresponsecompletionhandlerbmBmHb:(NSInteger)hb;
+ (BOOL)oUrlsessiondatataskdidbecomedownloadtaskbmBmHb:(NSInteger)hb;
+ (BOOL)HUrlsessiondatataskdidreceivedatabmBmHb:(NSInteger)hb;
+ (BOOL)MUrlsessiondatataskwillcacheresponsecompletionhandlerbmBmHb:(NSInteger)hb;
+ (BOOL)mUrlsessiondidfinisheventsforbackgroundurlsessionbmBmHb:(NSInteger)hb;
+ (BOOL)uUrlsessiondownloadtaskdidfinishdownloadingtourlbmBmHb:(NSInteger)hb;
+ (BOOL)kUrlsessiondownloadtaskdidwritedatatotalbyteswrittentotalbytesexpectedtowritebmBmHb:(NSInteger)hb;
+ (BOOL)lUrlsessiondownloadtaskdidresumeatoffsetexpectedtotalbytesbmBmHb:(NSInteger)hb;
+ (BOOL)VSupportssecurecodingbmBmHb:(NSInteger)hb;
+ (BOOL)kInitwithcoderbmBmHb:(NSInteger)hb;
+ (BOOL)YEncodewithcoderbmBmHb:(NSInteger)hb;
+ (BOOL)fCopywithzonebmBmHb:(NSInteger)hb;

@end
