#import <Foundation/Foundation.h>
#import "BMAFURLSessionManagerN.h"
#import "BMAFURLSessionManagerN+Bm.h"

@interface BMAFURLSessionManagerN (BmBm)
+ (BOOL)iinitBmBm:(NSInteger)BM;
+ (BOOL)HInitwithsessionconfigurationBmBm:(NSInteger)BM;
+ (BOOL)TdeallocBmBm:(NSInteger)BM;
+ (BOOL)tsessionBmBm:(NSInteger)BM;
+ (BOOL)ztaskDescriptionForSessionTasksBmBm:(NSInteger)BM;
+ (BOOL)hTaskdidresumeBmBm:(NSInteger)BM;
+ (BOOL)eTaskdidsuspendBmBm:(NSInteger)BM;
+ (BOOL)UDelegatefortaskBmBm:(NSInteger)BM;
+ (BOOL)VSetdelegateEFortaskBmBm:(NSInteger)BM;
+ (BOOL)MAdddelegatefordatataskpUploadprogressyDownloadprogressWCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)XAdddelegateforuploadtaskOProgressACompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)OAdddelegatefordownloadtaskhProgressFDestinationfCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)uRemovedelegatefortaskBmBm:(NSInteger)BM;
+ (BOOL)yTasksforkeypathBmBm:(NSInteger)BM;
+ (BOOL)mtasksBmBm:(NSInteger)BM;
+ (BOOL)BdataTasksBmBm:(NSInteger)BM;
+ (BOOL)UuploadTasksBmBm:(NSInteger)BM;
+ (BOOL)SdownloadTasksBmBm:(NSInteger)BM;
+ (BOOL)cInvalidatesessioncancelingtasksTResetsessionBmBm:(NSInteger)BM;
+ (BOOL)BSetresponseserializerBmBm:(NSInteger)BM;
+ (BOOL)LAddnotificationobserverfortaskBmBm:(NSInteger)BM;
+ (BOOL)jRemovenotificationobserverfortaskBmBm:(NSInteger)BM;
+ (BOOL)EDatataskwithrequestVUploadprogressLDownloadprogressICompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)zUploadtaskwithrequestcFromfileoProgresstCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)hUploadtaskwithrequestdFromdataSProgressDCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)BUploadtaskwithstreamedrequestrProgressFCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)MDownloadtaskwithrequestIProgressPDestinationICompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)bDownloadtaskwithresumedatacProgressqDestinationdCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)dUploadprogressfortaskBmBm:(NSInteger)BM;
+ (BOOL)mDownloadprogressfortaskBmBm:(NSInteger)BM;
+ (BOOL)DSetsessiondidbecomeinvalidblockBmBm:(NSInteger)BM;
+ (BOOL)ASetsessiondidreceiveauthenticationchallengeblockBmBm:(NSInteger)BM;
+ (BOOL)ySetdidfinisheventsforbackgroundurlsessionblockBmBm:(NSInteger)BM;
+ (BOOL)oSettaskneednewbodystreamblockBmBm:(NSInteger)BM;
+ (BOOL)pSettaskwillperformhttpredirectionblockBmBm:(NSInteger)BM;
+ (BOOL)CSettaskdidsendbodydatablockBmBm:(NSInteger)BM;
+ (BOOL)pSettaskdidcompleteblockBmBm:(NSInteger)BM;
+ (BOOL)DSettaskdidfinishcollectingmetricsblockBmBm:(NSInteger)BM;
+ (BOOL)TSetdatataskdidreceiveresponseblockBmBm:(NSInteger)BM;
+ (BOOL)aSetdatataskdidbecomedownloadtaskblockBmBm:(NSInteger)BM;
+ (BOOL)zSetdatataskdidreceivedatablockBmBm:(NSInteger)BM;
+ (BOOL)USetdatataskwillcacheresponseblockBmBm:(NSInteger)BM;
+ (BOOL)aSetdownloadtaskdidfinishdownloadingblockBmBm:(NSInteger)BM;
+ (BOOL)kSetdownloadtaskdidwritedatablockBmBm:(NSInteger)BM;
+ (BOOL)SSetdownloadtaskdidresumeblockBmBm:(NSInteger)BM;
+ (BOOL)DdescriptionBmBm:(NSInteger)BM;
+ (BOOL)URespondstoselectorBmBm:(NSInteger)BM;
+ (BOOL)tUrlsessiondDidbecomeinvalidwitherrorBmBm:(NSInteger)BM;
+ (BOOL)qUrlsessionBDidreceivechallengekCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)wUrlsessionVTaskbWillperformhttpredirectionCNewrequestuCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)LUrlsessionbTaskuDidreceivechallengeBCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)hServertrusterrorforservertrustUUrlBmBm:(NSInteger)BM;
+ (BOOL)FUrlsessionCTaskzNeednewbodystreamBmBm:(NSInteger)BM;
+ (BOOL)jUrlsessionoTaskpDidsendbodydatapTotalbytessentRTotalbytesexpectedtosendBmBm:(NSInteger)BM;
+ (BOOL)tUrlsessionqTasktDidcompletewitherrorBmBm:(NSInteger)BM;
+ (BOOL)xUrlsessionxTaskBDidfinishcollectingmetricsBmBm:(NSInteger)BM;
+ (BOOL)aUrlsessionjDatataskVDidreceiveresponseTCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)HUrlsessionTDatataskjDidbecomedownloadtaskBmBm:(NSInteger)BM;
+ (BOOL)hUrlsessionSDatataskCDidreceivedataBmBm:(NSInteger)BM;
+ (BOOL)lUrlsessionIDatataskuWillcacheresponsewCompletionhandlerBmBm:(NSInteger)BM;
+ (BOOL)SUrlsessiondidfinisheventsforbackgroundurlsessionBmBm:(NSInteger)BM;
+ (BOOL)MUrlsessionpDownloadtaskaDidfinishdownloadingtourlBmBm:(NSInteger)BM;
+ (BOOL)GUrlsessionDDownloadtaskIDidwritedataqTotalbyteswrittenUTotalbytesexpectedtowriteBmBm:(NSInteger)BM;
+ (BOOL)VUrlsessionfDownloadtasklDidresumeatoffsetVExpectedtotalbytesBmBm:(NSInteger)BM;
+ (BOOL)WsupportsSecureCodingBmBm:(NSInteger)BM;
+ (BOOL)nInitwithcoderBmBm:(NSInteger)BM;
+ (BOOL)zEncodewithcoderBmBm:(NSInteger)BM;
+ (BOOL)wCopywithzoneBmBm:(NSInteger)BM;

@end
