#import <Foundation/Foundation.h>
#import "BMBMGPUImageFilteryT.h"

@interface BMBMGPUImageFilteryT (-Deletecomments)
+ (BOOL)tTinitwithvertexshaderfromstringefragmentshaderfromstring-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zIinitwithfragmentshaderfromstring-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)IKinitwithfragmentshaderfromfile-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bCinit-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rSinitializeattributes-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)OXsetupfilterforsize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)qJdealloc-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)UHusenextframeforimagecapture-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zHnewcgimagefromcurrentlyprocessedoutput-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dAsizeoffbo-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)DJtexturecoordinatesforrotation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)KGrendertotexturewithverticesstexturecoordinates-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)lXinformtargetsaboutnewframeattime-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)AYoutputframesize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)kOsetbackgroundcolorredkgreenablueealpha-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cBsetintegeriforuniformname-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zYsetfloatxforuniformname-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)UGsetsizejforuniformname-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oRsetpointeforuniformname-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)JUsetfloatvec3Fforuniformname-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)EXsetfloatvec4Yforuniform-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RYsetfloatarrayslengthvforuniform-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hNsetmatrix3Fpforuniformrprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iBsetmatrix4Feforuniformoprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)eUsetfloattforuniformpprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zXsetpointlforuniformbprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)nQsetsizetforuniformlprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ZBsetvec3Yforuniformjprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)FJsetvec4Hforuniformyprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)jCsetfloatarrayclengthtforuniformjprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ZIsetintegercforuniformoprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)EJsetandexecuteuniformstatecallbackatindexeforprogramgtoblock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QHsetuniformsforprogramatindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hHnewframereadyattimezatindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oBnextavailabletextureindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YJsetinputframebufferoatindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)xYrotatedsizeeforindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)VDrotatedpointhforrotation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RNsetinputsizeaatindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)MUsetinputrotationjatindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dYforceprocessingatsize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aHforceprocessingatsizerespectingaspectratio-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RPmaximumoutputsize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bHendprocessing-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zIwantsmonochromeinput-Deletecomments:(NSInteger)-deleteComments;

@end
