#import <Foundation/Foundation.h>
#import "BMBMMASConstraintYm.h"
#import "BMBMMASConstraintYm+Bm.h"

@interface BMBMMASConstraintYm (BmHb)
+ (BOOL)hNinitBmHb:(NSInteger)hb;
+ (BOOL)IEqualtoBmHb:(NSInteger)hb;
+ (BOOL)hMas_EqualtoBmHb:(NSInteger)hb;
+ (BOOL)VGreaterthanorequaltoBmHb:(NSInteger)hb;
+ (BOOL)tMas_GreaterthanorequaltoBmHb:(NSInteger)hb;
+ (BOOL)fLessthanorequaltoBmHb:(NSInteger)hb;
+ (BOOL)eMas_LessthanorequaltoBmHb:(NSInteger)hb;
+ (BOOL)HPrioritylowBmHb:(NSInteger)hb;
+ (BOOL)UPrioritymediumBmHb:(NSInteger)hb;
+ (BOOL)VPriorityhighBmHb:(NSInteger)hb;
+ (BOOL)gInsetsBmHb:(NSInteger)hb;
+ (BOOL)CInsetBmHb:(NSInteger)hb;
+ (BOOL)KSizeoffsetBmHb:(NSInteger)hb;
+ (BOOL)gCenteroffsetBmHb:(NSInteger)hb;
+ (BOOL)ROffsetBmHb:(NSInteger)hb;
+ (BOOL)lValueoffsetBmHb:(NSInteger)hb;
+ (BOOL)iMas_OffsetBmHb:(NSInteger)hb;
+ (BOOL)pKsetlayoutconstantwithvalueBmHb:(NSInteger)hb;
+ (BOOL)RTwithBmHb:(NSInteger)hb;
+ (BOOL)mYandBmHb:(NSInteger)hb;
+ (BOOL)dTaddconstraintwithlayoutattributeBmHb:(NSInteger)hb;
+ (BOOL)uMleftBmHb:(NSInteger)hb;
+ (BOOL)qDtopBmHb:(NSInteger)hb;
+ (BOOL)tBrightBmHb:(NSInteger)hb;
+ (BOOL)YDbottomBmHb:(NSInteger)hb;
+ (BOOL)oFleadingBmHb:(NSInteger)hb;
+ (BOOL)QVtrailingBmHb:(NSInteger)hb;
+ (BOOL)CTwidthBmHb:(NSInteger)hb;
+ (BOOL)IFheightBmHb:(NSInteger)hb;
+ (BOOL)WZcenterxBmHb:(NSInteger)hb;
+ (BOOL)CNcenteryBmHb:(NSInteger)hb;
+ (BOOL)xPbaselineBmHb:(NSInteger)hb;
+ (BOOL)zUfirstbaselineBmHb:(NSInteger)hb;
+ (BOOL)hBlastbaselineBmHb:(NSInteger)hb;
+ (BOOL)dRleftmarginBmHb:(NSInteger)hb;
+ (BOOL)IXrightmarginBmHb:(NSInteger)hb;
+ (BOOL)aXtopmarginBmHb:(NSInteger)hb;
+ (BOOL)lEbottommarginBmHb:(NSInteger)hb;
+ (BOOL)EUleadingmarginBmHb:(NSInteger)hb;
+ (BOOL)WBtrailingmarginBmHb:(NSInteger)hb;
+ (BOOL)YGcenterxwithinmarginsBmHb:(NSInteger)hb;
+ (BOOL)TWcenterywithinmarginsBmHb:(NSInteger)hb;
+ (BOOL)cMultipliedbyBmHb:(NSInteger)hb;
+ (BOOL)tDividedbyBmHb:(NSInteger)hb;
+ (BOOL)zPriorityBmHb:(NSInteger)hb;
+ (BOOL)eEqualtowithrelationBmHb:(NSInteger)hb;
+ (BOOL)OKeyBmHb:(NSInteger)hb;
+ (BOOL)dDsetinsetsBmHb:(NSInteger)hb;
+ (BOOL)yGsetinsetBmHb:(NSInteger)hb;
+ (BOOL)tUsetsizeoffsetBmHb:(NSInteger)hb;
+ (BOOL)sLsetcenteroffsetBmHb:(NSInteger)hb;
+ (BOOL)bDsetoffsetBmHb:(NSInteger)hb;
+ (BOOL)oManimatorBmHb:(NSInteger)hb;
+ (BOOL)oUactivateBmHb:(NSInteger)hb;
+ (BOOL)EWdeactivateBmHb:(NSInteger)hb;
+ (BOOL)rCinstallBmHb:(NSInteger)hb;
+ (BOOL)fIuninstallBmHb:(NSInteger)hb;

@end
