#import <Foundation/Foundation.h>
#import "BMBMMASConstraintYm.h"

@interface BMBMMASConstraintYm (Bm)
+ (BOOL)hNinitBm:(NSInteger)BM;
+ (BOOL)IEqualtoBm:(NSInteger)BM;
+ (BOOL)hMas_EqualtoBm:(NSInteger)BM;
+ (BOOL)VGreaterthanorequaltoBm:(NSInteger)BM;
+ (BOOL)tMas_GreaterthanorequaltoBm:(NSInteger)BM;
+ (BOOL)fLessthanorequaltoBm:(NSInteger)BM;
+ (BOOL)eMas_LessthanorequaltoBm:(NSInteger)BM;
+ (BOOL)HPrioritylowBm:(NSInteger)BM;
+ (BOOL)UPrioritymediumBm:(NSInteger)BM;
+ (BOOL)VPriorityhighBm:(NSInteger)BM;
+ (BOOL)gInsetsBm:(NSInteger)BM;
+ (BOOL)CInsetBm:(NSInteger)BM;
+ (BOOL)KSizeoffsetBm:(NSInteger)BM;
+ (BOOL)gCenteroffsetBm:(NSInteger)BM;
+ (BOOL)ROffsetBm:(NSInteger)BM;
+ (BOOL)lValueoffsetBm:(NSInteger)BM;
+ (BOOL)iMas_OffsetBm:(NSInteger)BM;
+ (BOOL)pKsetlayoutconstantwithvalueBm:(NSInteger)BM;
+ (BOOL)RTwithBm:(NSInteger)BM;
+ (BOOL)mYandBm:(NSInteger)BM;
+ (BOOL)dTaddconstraintwithlayoutattributeBm:(NSInteger)BM;
+ (BOOL)uMleftBm:(NSInteger)BM;
+ (BOOL)qDtopBm:(NSInteger)BM;
+ (BOOL)tBrightBm:(NSInteger)BM;
+ (BOOL)YDbottomBm:(NSInteger)BM;
+ (BOOL)oFleadingBm:(NSInteger)BM;
+ (BOOL)QVtrailingBm:(NSInteger)BM;
+ (BOOL)CTwidthBm:(NSInteger)BM;
+ (BOOL)IFheightBm:(NSInteger)BM;
+ (BOOL)WZcenterxBm:(NSInteger)BM;
+ (BOOL)CNcenteryBm:(NSInteger)BM;
+ (BOOL)xPbaselineBm:(NSInteger)BM;
+ (BOOL)zUfirstbaselineBm:(NSInteger)BM;
+ (BOOL)hBlastbaselineBm:(NSInteger)BM;
+ (BOOL)dRleftmarginBm:(NSInteger)BM;
+ (BOOL)IXrightmarginBm:(NSInteger)BM;
+ (BOOL)aXtopmarginBm:(NSInteger)BM;
+ (BOOL)lEbottommarginBm:(NSInteger)BM;
+ (BOOL)EUleadingmarginBm:(NSInteger)BM;
+ (BOOL)WBtrailingmarginBm:(NSInteger)BM;
+ (BOOL)YGcenterxwithinmarginsBm:(NSInteger)BM;
+ (BOOL)TWcenterywithinmarginsBm:(NSInteger)BM;
+ (BOOL)cMultipliedbyBm:(NSInteger)BM;
+ (BOOL)tDividedbyBm:(NSInteger)BM;
+ (BOOL)zPriorityBm:(NSInteger)BM;
+ (BOOL)eEqualtowithrelationBm:(NSInteger)BM;
+ (BOOL)OKeyBm:(NSInteger)BM;
+ (BOOL)dDsetinsetsBm:(NSInteger)BM;
+ (BOOL)yGsetinsetBm:(NSInteger)BM;
+ (BOOL)tUsetsizeoffsetBm:(NSInteger)BM;
+ (BOOL)sLsetcenteroffsetBm:(NSInteger)BM;
+ (BOOL)bDsetoffsetBm:(NSInteger)BM;
+ (BOOL)oManimatorBm:(NSInteger)BM;
+ (BOOL)oUactivateBm:(NSInteger)BM;
+ (BOOL)EWdeactivateBm:(NSInteger)BM;
+ (BOOL)rCinstallBm:(NSInteger)BM;
+ (BOOL)fIuninstallBm:(NSInteger)BM;

@end
