#import <Foundation/Foundation.h>
#import "BMBMTOCropViewoD.h"

@interface BMBMTOCropViewoD (Bm)
+ (BOOL)HPinitwithimageBm:(NSInteger)BM;
+ (BOOL)mPinitwithcroppingstyletimageBm:(NSInteger)BM;
+ (BOOL)MTsetupBm:(NSInteger)BM;
+ (BOOL)QWperforminitialsetupBm:(NSInteger)BM;
+ (BOOL)gVlayoutinitialimageBm:(NSInteger)BM;
+ (BOOL)vRprepareforrotationBm:(NSInteger)BM;
+ (BOOL)nBperformrelayoutforrotationBm:(NSInteger)BM;
+ (BOOL)VJmatchforegroundtobackgroundBm:(NSInteger)BM;
+ (BOOL)GQupdatecropboxframewithgesturepointBm:(NSInteger)BM;
+ (BOOL)JRresetlayouttodefaultanimatedBm:(NSInteger)BM;
+ (BOOL)qBtoggletranslucencyviewvisibleBm:(NSInteger)BM;
+ (BOOL)eRupdatetoimagecropframeBm:(NSInteger)BM;
+ (BOOL)WIgridpangesturerecognizedBm:(NSInteger)BM;
+ (BOOL)ODlongpressgesturerecognizedBm:(NSInteger)BM;
+ (BOOL)aQgesturerecognizershouldbeginBm:(NSInteger)BM;
+ (BOOL)XHgesturerecognizerwshouldreceivetouchBm:(NSInteger)BM;
+ (BOOL)kHstartresettimerBm:(NSInteger)BM;
+ (BOOL)nAtimertriggeredBm:(NSInteger)BM;
+ (BOOL)MOcancelresettimerBm:(NSInteger)BM;
+ (BOOL)dCcropedgeforpointBm:(NSInteger)BM;
+ (BOOL)PCviewforzoominginscrollviewBm:(NSInteger)BM;
+ (BOOL)DQscrollviewdidscrollBm:(NSInteger)BM;
+ (BOOL)dIscrollviewwillbegindraggingBm:(NSInteger)BM;
+ (BOOL)RQscrollviewwillbeginzoomingowithviewBm:(NSInteger)BM;
+ (BOOL)XVscrollviewdidenddeceleratingBm:(NSInteger)BM;
+ (BOOL)OKscrollviewdidendzoomingswithviewlatscaleBm:(NSInteger)BM;
+ (BOOL)ZLscrollviewdidzoomBm:(NSInteger)BM;
+ (BOOL)LQscrollviewdidenddraggingiwilldecelerateBm:(NSInteger)BM;
+ (BOOL)iTsetcropboxresizeenabledBm:(NSInteger)BM;
+ (BOOL)bXsetcropboxframeBm:(NSInteger)BM;
+ (BOOL)dAseteditingBm:(NSInteger)BM;
+ (BOOL)bRsetsimplerendermodeBm:(NSInteger)BM;
+ (BOOL)XMcropboxaspectratioisportraitBm:(NSInteger)BM;
+ (BOOL)lIimagecropframeBm:(NSInteger)BM;
+ (BOOL)yZsetimagecropframeBm:(NSInteger)BM;
+ (BOOL)WMsetcroppingviewshiddenBm:(NSInteger)BM;
+ (BOOL)CGsetcroppingviewshiddenwanimatedBm:(NSInteger)BM;
+ (BOOL)JGsetbackgroundimageviewhiddenganimatedBm:(NSInteger)BM;
+ (BOOL)HFsetgridoverlayhiddenBm:(NSInteger)BM;
+ (BOOL)JYsetgridoverlayhiddenmanimatedBm:(NSInteger)BM;
+ (BOOL)FXimageviewframeBm:(NSInteger)BM;
+ (BOOL)fNsetcanberesetBm:(NSInteger)BM;
+ (BOOL)NTsetangleBm:(NSInteger)BM;
+ (BOOL)kOstarteditingBm:(NSInteger)BM;
+ (BOOL)iLseteditingiresetcropboxuanimatedBm:(NSInteger)BM;
+ (BOOL)hWmovecroppedcontenttocenteranimatedBm:(NSInteger)BM;
+ (BOOL)KBsetsimplerendermodebanimatedBm:(NSInteger)BM;
+ (BOOL)cGsetaspectratioBm:(NSInteger)BM;
+ (BOOL)QTsetaspectratioaanimatedBm:(NSInteger)BM;
+ (BOOL)GMrotateimageninetydegreesanimatedBm:(NSInteger)BM;
+ (BOOL)KArotateimageninetydegreesanimatedbclockwiseBm:(NSInteger)BM;
+ (BOOL)tEcapturestateforimagerotationBm:(NSInteger)BM;
+ (BOOL)REcheckforcanresetBm:(NSInteger)BM;
+ (BOOL)FMcontentboundsBm:(NSInteger)BM;
+ (BOOL)TWimagesizeBm:(NSInteger)BM;
+ (BOOL)oHhasaspectratioBm:(NSInteger)BM;

@end
