#import <Foundation/Foundation.h>
#import "BMBMCALayerrX.h"

@interface BMBMCALayerrX (Bm)
+ (BOOL)KYsnapshotimagebmBm:(NSInteger)BM;
+ (BOOL)CGsnapshotpdfbmBm:(NSInteger)BM;
+ (BOOL)uNsetlayershadoweoffsetpradiusbmBm:(NSInteger)BM;
+ (BOOL)nQremoveallsublayersbmBm:(NSInteger)BM;
+ (BOOL)sMleftbmBm:(NSInteger)BM;
+ (BOOL)wJsetleftbmBm:(NSInteger)BM;
+ (BOOL)wQtopbmBm:(NSInteger)BM;
+ (BOOL)xTsettopbmBm:(NSInteger)BM;
+ (BOOL)kUrightbmBm:(NSInteger)BM;
+ (BOOL)vZsetrightbmBm:(NSInteger)BM;
+ (BOOL)YDbottombmBm:(NSInteger)BM;
+ (BOOL)qMsetbottombmBm:(NSInteger)BM;
+ (BOOL)vQwidthbmBm:(NSInteger)BM;
+ (BOOL)KBsetwidthbmBm:(NSInteger)BM;
+ (BOOL)sKheightbmBm:(NSInteger)BM;
+ (BOOL)NLsetheightbmBm:(NSInteger)BM;
+ (BOOL)JVcenterbmBm:(NSInteger)BM;
+ (BOOL)fFsetcenterbmBm:(NSInteger)BM;
+ (BOOL)NQcenterxbmBm:(NSInteger)BM;
+ (BOOL)vPsetcenterxbmBm:(NSInteger)BM;
+ (BOOL)sJcenterybmBm:(NSInteger)BM;
+ (BOOL)uCsetcenterybmBm:(NSInteger)BM;
+ (BOOL)bLoriginbmBm:(NSInteger)BM;
+ (BOOL)FOsetoriginbmBm:(NSInteger)BM;
+ (BOOL)GUframesizebmBm:(NSInteger)BM;
+ (BOOL)xEsetframesizebmBm:(NSInteger)BM;
+ (BOOL)yUtransformrotationbmBm:(NSInteger)BM;
+ (BOOL)PZsettransformrotationbmBm:(NSInteger)BM;
+ (BOOL)lOtransformrotationxbmBm:(NSInteger)BM;
+ (BOOL)qJsettransformrotationxbmBm:(NSInteger)BM;
+ (BOOL)WJtransformrotationybmBm:(NSInteger)BM;
+ (BOOL)QRsettransformrotationybmBm:(NSInteger)BM;
+ (BOOL)iCtransformrotationzbmBm:(NSInteger)BM;
+ (BOOL)UYsettransformrotationzbmBm:(NSInteger)BM;
+ (BOOL)vRtransformscalexbmBm:(NSInteger)BM;
+ (BOOL)TRsettransformscalexbmBm:(NSInteger)BM;
+ (BOOL)nNtransformscaleybmBm:(NSInteger)BM;
+ (BOOL)nXsettransformscaleybmBm:(NSInteger)BM;
+ (BOOL)bJtransformscalezbmBm:(NSInteger)BM;
+ (BOOL)nMsettransformscalezbmBm:(NSInteger)BM;
+ (BOOL)UKtransformscalebmBm:(NSInteger)BM;
+ (BOOL)TJsettransformscalebmBm:(NSInteger)BM;
+ (BOOL)dXtransformtranslationxbmBm:(NSInteger)BM;
+ (BOOL)ZFsettransformtranslationxbmBm:(NSInteger)BM;
+ (BOOL)ZItransformtranslationybmBm:(NSInteger)BM;
+ (BOOL)AYsettransformtranslationybmBm:(NSInteger)BM;
+ (BOOL)DWtransformtranslationzbmBm:(NSInteger)BM;
+ (BOOL)JFsettransformtranslationzbmBm:(NSInteger)BM;
+ (BOOL)CGtransformdepthbmBm:(NSInteger)BM;
+ (BOOL)ZZsettransformdepthbmBm:(NSInteger)BM;
+ (BOOL)bAcontentmodebmBm:(NSInteger)BM;
+ (BOOL)ZIsetcontentmodebmBm:(NSInteger)BM;
+ (BOOL)QUaddfadeanimationwithdurationdcurvebmBm:(NSInteger)BM;
+ (BOOL)IBremovepreviousfadeanimationbmBm:(NSInteger)BM;

@end
