#import <Foundation/Foundation.h>
#import "BMBMLLSimpleCamerazI.h"

@interface BMBMLLSimpleCamerazI (-Deletecomments)
+ (BOOL)yTinit-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)fVinitwithvideoenabled-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iXinitwithqualityapositionlvideoenabled-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)IAinitwithcoder-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YTsetupwithqualityqpositioncvideoenabled-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)UZviewdidload-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)DYgesturerecognizershouldbegin-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ZThandlepinchgesture-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)WGattachtoviewcontrollerowithframe-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QNstart-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)qOinitialize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aQstop-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)EMcaptureaexactseenimage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)GJcapture-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)UCstartrecordingwithoutputurl-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)kUstoprecording-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oUcaptureoutputgdidstartrecordingtooutputfileaturlrfromconnections-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bAcaptureoutputodidfinishrecordingtooutputfileaturlefromconnectionsrerror-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)VEenabletorch-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sVcropimageusingpreviewbounds-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)MBcaptureconnection-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)JDsetvideocapturedevice-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QPisflashavailable-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)BOistorchavailable-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)FTupdateflashmode-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)CIsetwhitebalancemode-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)TNsetmirror-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)TRtoggleposition-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XEsetcameraposition-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)GOcamerawithposition-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)uDpreviewtapped-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XFadddefaultfocusbox-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)fCalterfocusboxianimation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)PQfocusatpoint-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)yKshowfocusbox-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)fPconverttopointofinterestfromviewcoordinates-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)SJviewwillappear-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)uDviewwilldisappear-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cZviewwilllayoutsubviews-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)SSorientationforconnection-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)OHwillrotatetointerfaceorientationeduration-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XAdidreceivememorywarning-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)AQdealloc-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)jMrequestcamerapermission-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cZrequestmicrophonepermission-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)UWisfrontcameraavailable-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)fPisrearcameraavailable-Deletecomments:(NSInteger)-deleteComments;

@end
