#import <Foundation/Foundation.h>
#import "BMBMGPUImageFiltermY.h"

@interface BMBMGPUImageFiltermY (-Deletecomments)
+ (BOOL)xOinitwithvertexshaderfromstringnfragmentshaderfromstring-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bHinitwithfragmentshaderfromstring-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ANinitwithfragmentshaderfromfile-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)KWinit-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YRinitializeattributes-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)PQsetupfilterforsize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bEdealloc-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)KEusenextframeforimagecapture-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dCnewcgimagefromcurrentlyprocessedoutput-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)wKsizeoffbo-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oGtexturecoordinatesforrotation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vYrendertotexturewithverticesntexturecoordinates-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)HAinformtargetsaboutnewframeattime-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)mWoutputframesize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)kZsetbackgroundcolorredkgreennbluegalpha-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)lCsetintegerhforuniformname-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)GVsetfloatsforuniformname-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tYsetsizeyforuniformname-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hCsetpointmforuniformname-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)GZsetfloatvec3Yforuniformname-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QVsetfloatvec4Aforuniform-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rWsetfloatarrayplengthpforuniform-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)MOsetmatrix3Fpforuniformtprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)qAsetmatrix4Fuforuniformyprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)FDsetfloateforuniformgprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)BKsetpointkforuniformxprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)lYsetsizehforuniformcprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dOsetvec3Dforuniformyprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)WSsetvec4Uforuniformkprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XNsetfloatarrayxlengthuforuniformpprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RIsetintegervforuniformaprogram-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)UEsetandexecuteuniformstatecallbackatindexeforprogrametoblock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XJsetuniformsforprogramatindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YBnewframereadyattimecatindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)mAnextavailabletextureindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)eOsetinputframebufferuatindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QTrotatedsizecforindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)jUrotatedpointyforrotation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)SEsetinputsizepatindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)fSsetinputrotationcatindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)CFforceprocessingatsize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RLforceprocessingatsizerespectingaspectratio-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oNmaximumoutputsize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)MZendprocessing-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)VNwantsmonochromeinput-Deletecomments:(NSInteger)-deleteComments;

@end
