#import <Foundation/Foundation.h>
#import "BMBMTKImageViewTm.h"

@interface BMBMTKImageViewTm (-Deletecomments)
+ (BOOL)DVinitwithframe-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XZinitwithcoder-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ADcommoninit-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QAdealloc-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bHsetup-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)EZbindpangestures-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)NBhandlecropareapinch-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)wNhandlecropareapan-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)xUhandlemidpan-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cKhandlecornerpan-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vBresetcornersoncropareaframechanged-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bHresetcropareaoncornersframechanged-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zDresetminspaceifneeded-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)PQresetcroptransparentarea-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aZresetcornersonsizechanged-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)IJcreatecorners-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iZcreatemidlines-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oTremovemidlines-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)LMresetmidlines-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)uFresetimageview-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)mMresetcropareabyaspectratio-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)lFresetcropareabyscalefactor-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)JMsetinitialscalefactor-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)BCcornermargin-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)FMsetmaskcolor-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aUsetminspace-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iQsettocropimage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)fEsetneedscalecrop-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dCsetcropareacrosslinewidth-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gMsetcropareacrosslinecolor-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)CFsetcropareamidlinewidth-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XRsetcropareamidlineheight-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)VEsetcropareamidlinecolor-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)HJsetcropareaborderlinewidth-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hLsetcropareaborderlinecolor-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)NKsetcropareacornerlinecolor-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)lJsetcropareacornerlinewidth-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iRsetcropareacornerwidth-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)SBsetcropareacornerheight-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oUsetcropaspectratio-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)jFsetshowmidlines-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)NHsetshowcrosslines-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)TLsetcornerborderinimage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)fTsetframe-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)THsetcenter-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YUobservevalueforkeypathqofobjectachangencontext-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)pLrotate-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)PPshow-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)OOhide-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sEcurrentcroppedimage-Deletecomments:(NSInteger)-deleteComments;

@end
