#import <Foundation/Foundation.h>
#import "BMBMBMTOCropViewvau.h"

@interface BMBMBMTOCropViewvau (-Deletecomments)
+ (BOOL)oCjinitwithimagebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)MLdinitwithcroppingstyleimagebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)FUssetupbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RZqperforminitialsetupbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ROplayoutinitialimagebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iKcprepareforrotationbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)LGfperformrelayoutforrotationbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oXymatchforegroundtobackgroundbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)eTdupdatecropboxframewithgesturepointbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)OBlresetlayouttodefaultanimatedbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iPutoggletranslucencyviewvisiblebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sByupdatetoimagecropframebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YRxgridpangesturerecognizedbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)mZllongpressgesturerecognizedbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ENlgesturerecognizershouldbeginbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iJigesturerecognizershouldreceivetouchbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)IYfstartresettimerbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)FCztimertriggeredbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RWacancelresettimerbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RLdcropedgeforpointbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cYbviewforzoominginscrollviewbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)EXzscrollviewdidscrollbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iDzscrollviewwillbegindraggingbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RLiscrollviewwillbeginzoomingwithviewbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cEjscrollviewdidenddeceleratingbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)IJkscrollviewdidendzoomingwithviewatscalebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vTpscrollviewdidzoombm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oPwscrollviewdidenddraggingwilldeceleratebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)fWcsetcropboxresizeenabledbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)PFosetcropboxframebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)DAlseteditingbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)SMqsetsimplerendermodebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bAlcropboxaspectratioisportraitbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)PBdimagecropframebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hRwsetimagecropframebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)yRdsetcroppingviewshiddenbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)BWbsetcroppingviewshiddenanimatedbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cQvsetbackgroundimageviewhiddenanimatedbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)fEnsetgridoverlayhiddenbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)pOdsetgridoverlayhiddenanimatedbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iIhimageviewframebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cUbsetcanberesetbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zFzsetanglebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)FHjstarteditingbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)THcseteditingresetcropboxanimatedbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RPimovecroppedcontenttocenteranimatedbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vHhsetsimplerendermodeanimatedbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)nZlsetaspectratiobm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)wLksetaspectratioanimatedbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iEqrotateimageninetydegreesanimatedbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dSprotateimageninetydegreesanimatedclockwisebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)BCrcapturestateforimagerotationbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)HRjcheckforcanresetbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)EPccontentboundsbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)EMsimagesizebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vUkhasaspectratiobm-Deletecomments:(NSInteger)-deleteComments;

@end
