#import <Foundation/Foundation.h>
#import "BMBMCALayersF.h"

@interface BMBMCALayersF (Hb)
+ (BOOL)XTsnapshotimagebmHb:(NSInteger)hb;
+ (BOOL)XQsnapshotpdfbmHb:(NSInteger)hb;
+ (BOOL)YTsetlayershadowoffsetradiusbmHb:(NSInteger)hb;
+ (BOOL)DJremoveallsublayersbmHb:(NSInteger)hb;
+ (BOOL)aNleftbmHb:(NSInteger)hb;
+ (BOOL)qMsetleftbmHb:(NSInteger)hb;
+ (BOOL)eCtopbmHb:(NSInteger)hb;
+ (BOOL)cBsettopbmHb:(NSInteger)hb;
+ (BOOL)QArightbmHb:(NSInteger)hb;
+ (BOOL)eSsetrightbmHb:(NSInteger)hb;
+ (BOOL)QKbottombmHb:(NSInteger)hb;
+ (BOOL)KAsetbottombmHb:(NSInteger)hb;
+ (BOOL)dFwidthbmHb:(NSInteger)hb;
+ (BOOL)gKsetwidthbmHb:(NSInteger)hb;
+ (BOOL)KJheightbmHb:(NSInteger)hb;
+ (BOOL)vNsetheightbmHb:(NSInteger)hb;
+ (BOOL)RDcenterbmHb:(NSInteger)hb;
+ (BOOL)UKsetcenterbmHb:(NSInteger)hb;
+ (BOOL)KTcenterxbmHb:(NSInteger)hb;
+ (BOOL)dCsetcenterxbmHb:(NSInteger)hb;
+ (BOOL)YAcenterybmHb:(NSInteger)hb;
+ (BOOL)ZHsetcenterybmHb:(NSInteger)hb;
+ (BOOL)tGoriginbmHb:(NSInteger)hb;
+ (BOOL)NJsetoriginbmHb:(NSInteger)hb;
+ (BOOL)hJframesizebmHb:(NSInteger)hb;
+ (BOOL)vFsetframesizebmHb:(NSInteger)hb;
+ (BOOL)nTtransformrotationbmHb:(NSInteger)hb;
+ (BOOL)zAsettransformrotationbmHb:(NSInteger)hb;
+ (BOOL)LLtransformrotationxbmHb:(NSInteger)hb;
+ (BOOL)MLsettransformrotationxbmHb:(NSInteger)hb;
+ (BOOL)qKtransformrotationybmHb:(NSInteger)hb;
+ (BOOL)rZsettransformrotationybmHb:(NSInteger)hb;
+ (BOOL)MKtransformrotationzbmHb:(NSInteger)hb;
+ (BOOL)qLsettransformrotationzbmHb:(NSInteger)hb;
+ (BOOL)iUtransformscalexbmHb:(NSInteger)hb;
+ (BOOL)pOsettransformscalexbmHb:(NSInteger)hb;
+ (BOOL)dBtransformscaleybmHb:(NSInteger)hb;
+ (BOOL)KWsettransformscaleybmHb:(NSInteger)hb;
+ (BOOL)rCtransformscalezbmHb:(NSInteger)hb;
+ (BOOL)REsettransformscalezbmHb:(NSInteger)hb;
+ (BOOL)EKtransformscalebmHb:(NSInteger)hb;
+ (BOOL)TWsettransformscalebmHb:(NSInteger)hb;
+ (BOOL)jStransformtranslationxbmHb:(NSInteger)hb;
+ (BOOL)iRsettransformtranslationxbmHb:(NSInteger)hb;
+ (BOOL)lAtransformtranslationybmHb:(NSInteger)hb;
+ (BOOL)DCsettransformtranslationybmHb:(NSInteger)hb;
+ (BOOL)nTtransformtranslationzbmHb:(NSInteger)hb;
+ (BOOL)uEsettransformtranslationzbmHb:(NSInteger)hb;
+ (BOOL)hCtransformdepthbmHb:(NSInteger)hb;
+ (BOOL)nIsettransformdepthbmHb:(NSInteger)hb;
+ (BOOL)vFcontentmodebmHb:(NSInteger)hb;
+ (BOOL)uPsetcontentmodebmHb:(NSInteger)hb;
+ (BOOL)ELaddfadeanimationwithdurationcurvebmHb:(NSInteger)hb;
+ (BOOL)bPremovepreviousfadeanimationbmHb:(NSInteger)hb;

@end
