#import <Foundation/Foundation.h>
#import "BMBMTOCropViewva.h"

@interface BMBMTOCropViewva (Bm)
+ (BOOL)cJinitwithimagebmBm:(NSInteger)BM;
+ (BOOL)lDinitwithcroppingstyleimagebmBm:(NSInteger)BM;
+ (BOOL)uSsetupbmBm:(NSInteger)BM;
+ (BOOL)zQperforminitialsetupbmBm:(NSInteger)BM;
+ (BOOL)OPlayoutinitialimagebmBm:(NSInteger)BM;
+ (BOOL)KCprepareforrotationbmBm:(NSInteger)BM;
+ (BOOL)gFperformrelayoutforrotationbmBm:(NSInteger)BM;
+ (BOOL)xYmatchforegroundtobackgroundbmBm:(NSInteger)BM;
+ (BOOL)tDupdatecropboxframewithgesturepointbmBm:(NSInteger)BM;
+ (BOOL)bLresetlayouttodefaultanimatedbmBm:(NSInteger)BM;
+ (BOOL)pUtoggletranslucencyviewvisiblebmBm:(NSInteger)BM;
+ (BOOL)bYupdatetoimagecropframebmBm:(NSInteger)BM;
+ (BOOL)rXgridpangesturerecognizedbmBm:(NSInteger)BM;
+ (BOOL)zLlongpressgesturerecognizedbmBm:(NSInteger)BM;
+ (BOOL)NLgesturerecognizershouldbeginbmBm:(NSInteger)BM;
+ (BOOL)jIgesturerecognizershouldreceivetouchbmBm:(NSInteger)BM;
+ (BOOL)yFstartresettimerbmBm:(NSInteger)BM;
+ (BOOL)CZtimertriggeredbmBm:(NSInteger)BM;
+ (BOOL)WAcancelresettimerbmBm:(NSInteger)BM;
+ (BOOL)LDcropedgeforpointbmBm:(NSInteger)BM;
+ (BOOL)YBviewforzoominginscrollviewbmBm:(NSInteger)BM;
+ (BOOL)xZscrollviewdidscrollbmBm:(NSInteger)BM;
+ (BOOL)DZscrollviewwillbegindraggingbmBm:(NSInteger)BM;
+ (BOOL)lIscrollviewwillbeginzoomingwithviewbmBm:(NSInteger)BM;
+ (BOOL)EJscrollviewdidenddeceleratingbmBm:(NSInteger)BM;
+ (BOOL)JKscrollviewdidendzoomingwithviewatscalebmBm:(NSInteger)BM;
+ (BOOL)tPscrollviewdidzoombmBm:(NSInteger)BM;
+ (BOOL)pWscrollviewdidenddraggingwilldeceleratebmBm:(NSInteger)BM;
+ (BOOL)wCsetcropboxresizeenabledbmBm:(NSInteger)BM;
+ (BOOL)FOsetcropboxframebmBm:(NSInteger)BM;
+ (BOOL)aLseteditingbmBm:(NSInteger)BM;
+ (BOOL)MQsetsimplerendermodebmBm:(NSInteger)BM;
+ (BOOL)ALcropboxaspectratioisportraitbmBm:(NSInteger)BM;
+ (BOOL)bDimagecropframebmBm:(NSInteger)BM;
+ (BOOL)RWsetimagecropframebmBm:(NSInteger)BM;
+ (BOOL)RDsetcroppingviewshiddenbmBm:(NSInteger)BM;
+ (BOOL)wBsetcroppingviewshiddenanimatedbmBm:(NSInteger)BM;
+ (BOOL)qVsetbackgroundimageviewhiddenanimatedbmBm:(NSInteger)BM;
+ (BOOL)ENsetgridoverlayhiddenbmBm:(NSInteger)BM;
+ (BOOL)oDsetgridoverlayhiddenanimatedbmBm:(NSInteger)BM;
+ (BOOL)IHimageviewframebmBm:(NSInteger)BM;
+ (BOOL)UBsetcanberesetbmBm:(NSInteger)BM;
+ (BOOL)fZsetanglebmBm:(NSInteger)BM;
+ (BOOL)hJstarteditingbmBm:(NSInteger)BM;
+ (BOOL)hCseteditingresetcropboxanimatedbmBm:(NSInteger)BM;
+ (BOOL)PImovecroppedcontenttocenteranimatedbmBm:(NSInteger)BM;
+ (BOOL)HHsetsimplerendermodeanimatedbmBm:(NSInteger)BM;
+ (BOOL)zLsetaspectratiobmBm:(NSInteger)BM;
+ (BOOL)lKsetaspectratioanimatedbmBm:(NSInteger)BM;
+ (BOOL)EQrotateimageninetydegreesanimatedbmBm:(NSInteger)BM;
+ (BOOL)sProtateimageninetydegreesanimatedclockwisebmBm:(NSInteger)BM;
+ (BOOL)cRcapturestateforimagerotationbmBm:(NSInteger)BM;
+ (BOOL)rJcheckforcanresetbmBm:(NSInteger)BM;
+ (BOOL)pCcontentboundsbmBm:(NSInteger)BM;
+ (BOOL)mSimagesizebmBm:(NSInteger)BM;
+ (BOOL)UKhasaspectratiobmBm:(NSInteger)BM;

@end
