#import <Foundation/Foundation.h>
#import "BMBMMASConstrainthP.h"

@interface BMBMMASConstrainthP (Hb)
+ (BOOL)ROinitHb:(NSInteger)hb;
+ (BOOL)EEqualtoHb:(NSInteger)hb;
+ (BOOL)PMas_EqualtoHb:(NSInteger)hb;
+ (BOOL)XGreaterthanorequaltoHb:(NSInteger)hb;
+ (BOOL)EMas_GreaterthanorequaltoHb:(NSInteger)hb;
+ (BOOL)DLessthanorequaltoHb:(NSInteger)hb;
+ (BOOL)CMas_LessthanorequaltoHb:(NSInteger)hb;
+ (BOOL)fPrioritylowHb:(NSInteger)hb;
+ (BOOL)XPrioritymediumHb:(NSInteger)hb;
+ (BOOL)qPriorityhighHb:(NSInteger)hb;
+ (BOOL)aInsetsHb:(NSInteger)hb;
+ (BOOL)LInsetHb:(NSInteger)hb;
+ (BOOL)tSizeoffsetHb:(NSInteger)hb;
+ (BOOL)PCenteroffsetHb:(NSInteger)hb;
+ (BOOL)FOffsetHb:(NSInteger)hb;
+ (BOOL)aValueoffsetHb:(NSInteger)hb;
+ (BOOL)nMas_OffsetHb:(NSInteger)hb;
+ (BOOL)DUsetlayoutconstantwithvalueHb:(NSInteger)hb;
+ (BOOL)KZwithHb:(NSInteger)hb;
+ (BOOL)OSandHb:(NSInteger)hb;
+ (BOOL)hLaddconstraintwithlayoutattributeHb:(NSInteger)hb;
+ (BOOL)oIleftHb:(NSInteger)hb;
+ (BOOL)uPtopHb:(NSInteger)hb;
+ (BOOL)KJrightHb:(NSInteger)hb;
+ (BOOL)NJbottomHb:(NSInteger)hb;
+ (BOOL)TDleadingHb:(NSInteger)hb;
+ (BOOL)EFtrailingHb:(NSInteger)hb;
+ (BOOL)aSwidthHb:(NSInteger)hb;
+ (BOOL)XLheightHb:(NSInteger)hb;
+ (BOOL)IDcenterxHb:(NSInteger)hb;
+ (BOOL)yMcenteryHb:(NSInteger)hb;
+ (BOOL)xXbaselineHb:(NSInteger)hb;
+ (BOOL)AYfirstbaselineHb:(NSInteger)hb;
+ (BOOL)YDlastbaselineHb:(NSInteger)hb;
+ (BOOL)BHleftmarginHb:(NSInteger)hb;
+ (BOOL)NRrightmarginHb:(NSInteger)hb;
+ (BOOL)UWtopmarginHb:(NSInteger)hb;
+ (BOOL)xRbottommarginHb:(NSInteger)hb;
+ (BOOL)yRleadingmarginHb:(NSInteger)hb;
+ (BOOL)ZItrailingmarginHb:(NSInteger)hb;
+ (BOOL)qOcenterxwithinmarginsHb:(NSInteger)hb;
+ (BOOL)JAcenterywithinmarginsHb:(NSInteger)hb;
+ (BOOL)ZMultipliedbyHb:(NSInteger)hb;
+ (BOOL)vDividedbyHb:(NSInteger)hb;
+ (BOOL)uPriorityHb:(NSInteger)hb;
+ (BOOL)lEqualtowithrelationHb:(NSInteger)hb;
+ (BOOL)LKeyHb:(NSInteger)hb;
+ (BOOL)fSsetinsetsHb:(NSInteger)hb;
+ (BOOL)pXsetinsetHb:(NSInteger)hb;
+ (BOOL)ySsetsizeoffsetHb:(NSInteger)hb;
+ (BOOL)UDsetcenteroffsetHb:(NSInteger)hb;
+ (BOOL)eFsetoffsetHb:(NSInteger)hb;
+ (BOOL)HWanimatorHb:(NSInteger)hb;
+ (BOOL)pIactivateHb:(NSInteger)hb;
+ (BOOL)VDdeactivateHb:(NSInteger)hb;
+ (BOOL)hWinstallHb:(NSInteger)hb;
+ (BOOL)QBuninstallHb:(NSInteger)hb;

@end
