#import <Foundation/Foundation.h>
#import "BMBMCALayerrf.h"

@interface BMBMCALayerrf (Bm)
+ (BOOL)pYsnapshotimageBm:(NSInteger)BM;
+ (BOOL)VGsnapshotpdfBm:(NSInteger)BM;
+ (BOOL)kNsetlayershadoweoffsetpradiusBm:(NSInteger)BM;
+ (BOOL)XQremoveallsublayersBm:(NSInteger)BM;
+ (BOOL)XMleftBm:(NSInteger)BM;
+ (BOOL)KJsetleftBm:(NSInteger)BM;
+ (BOOL)sQtopBm:(NSInteger)BM;
+ (BOOL)lTsettopBm:(NSInteger)BM;
+ (BOOL)ZUrightBm:(NSInteger)BM;
+ (BOOL)KZsetrightBm:(NSInteger)BM;
+ (BOOL)GDbottomBm:(NSInteger)BM;
+ (BOOL)cMsetbottomBm:(NSInteger)BM;
+ (BOOL)eQwidthBm:(NSInteger)BM;
+ (BOOL)EBsetwidthBm:(NSInteger)BM;
+ (BOOL)vKheightBm:(NSInteger)BM;
+ (BOOL)ZLsetheightBm:(NSInteger)BM;
+ (BOOL)OVcenterBm:(NSInteger)BM;
+ (BOOL)hFsetcenterBm:(NSInteger)BM;
+ (BOOL)mQcenterxBm:(NSInteger)BM;
+ (BOOL)oPsetcenterxBm:(NSInteger)BM;
+ (BOOL)bJcenteryBm:(NSInteger)BM;
+ (BOOL)wCsetcenteryBm:(NSInteger)BM;
+ (BOOL)gLoriginBm:(NSInteger)BM;
+ (BOOL)yOsetoriginBm:(NSInteger)BM;
+ (BOOL)wUframesizeBm:(NSInteger)BM;
+ (BOOL)yEsetframesizeBm:(NSInteger)BM;
+ (BOOL)LUtransformrotationBm:(NSInteger)BM;
+ (BOOL)jZsettransformrotationBm:(NSInteger)BM;
+ (BOOL)oOtransformrotationxBm:(NSInteger)BM;
+ (BOOL)TJsettransformrotationxBm:(NSInteger)BM;
+ (BOOL)lJtransformrotationyBm:(NSInteger)BM;
+ (BOOL)ARsettransformrotationyBm:(NSInteger)BM;
+ (BOOL)eCtransformrotationzBm:(NSInteger)BM;
+ (BOOL)eYsettransformrotationzBm:(NSInteger)BM;
+ (BOOL)RRtransformscalexBm:(NSInteger)BM;
+ (BOOL)ZRsettransformscalexBm:(NSInteger)BM;
+ (BOOL)nNtransformscaleyBm:(NSInteger)BM;
+ (BOOL)SXsettransformscaleyBm:(NSInteger)BM;
+ (BOOL)PJtransformscalezBm:(NSInteger)BM;
+ (BOOL)qMsettransformscalezBm:(NSInteger)BM;
+ (BOOL)kKtransformscaleBm:(NSInteger)BM;
+ (BOOL)BJsettransformscaleBm:(NSInteger)BM;
+ (BOOL)KXtransformtranslationxBm:(NSInteger)BM;
+ (BOOL)wFsettransformtranslationxBm:(NSInteger)BM;
+ (BOOL)jItransformtranslationyBm:(NSInteger)BM;
+ (BOOL)ZYsettransformtranslationyBm:(NSInteger)BM;
+ (BOOL)MWtransformtranslationzBm:(NSInteger)BM;
+ (BOOL)VFsettransformtranslationzBm:(NSInteger)BM;
+ (BOOL)wGtransformdepthBm:(NSInteger)BM;
+ (BOOL)NZsettransformdepthBm:(NSInteger)BM;
+ (BOOL)IAcontentmodeBm:(NSInteger)BM;
+ (BOOL)vIsetcontentmodeBm:(NSInteger)BM;
+ (BOOL)VUaddfadeanimationwithdurationdcurveBm:(NSInteger)BM;
+ (BOOL)eBremovepreviousfadeanimationBm:(NSInteger)BM;

@end
