#import <Foundation/Foundation.h>
#import "BMCALayerr.h"
#import "BMCALayerr+Bm.h"

@interface BMCALayerr (BmBm)
+ (BOOL)YsnapshotImageBmBm:(NSInteger)BM;
+ (BOOL)gsnapshotPDFBmBm:(NSInteger)BM;
+ (BOOL)NSetlayershadoweOffsetpRadiusBmBm:(NSInteger)BM;
+ (BOOL)qremoveAllSublayersBmBm:(NSInteger)BM;
+ (BOOL)MleftBmBm:(NSInteger)BM;
+ (BOOL)jSetleftBmBm:(NSInteger)BM;
+ (BOOL)qtopBmBm:(NSInteger)BM;
+ (BOOL)tSettopBmBm:(NSInteger)BM;
+ (BOOL)UrightBmBm:(NSInteger)BM;
+ (BOOL)ZSetrightBmBm:(NSInteger)BM;
+ (BOOL)dbottomBmBm:(NSInteger)BM;
+ (BOOL)mSetbottomBmBm:(NSInteger)BM;
+ (BOOL)qwidthBmBm:(NSInteger)BM;
+ (BOOL)bSetwidthBmBm:(NSInteger)BM;
+ (BOOL)KheightBmBm:(NSInteger)BM;
+ (BOOL)lSetheightBmBm:(NSInteger)BM;
+ (BOOL)VcenterBmBm:(NSInteger)BM;
+ (BOOL)fSetcenterBmBm:(NSInteger)BM;
+ (BOOL)QcenterXBmBm:(NSInteger)BM;
+ (BOOL)PSetcenterxBmBm:(NSInteger)BM;
+ (BOOL)jcenterYBmBm:(NSInteger)BM;
+ (BOOL)cSetcenteryBmBm:(NSInteger)BM;
+ (BOOL)LoriginBmBm:(NSInteger)BM;
+ (BOOL)oSetoriginBmBm:(NSInteger)BM;
+ (BOOL)uframeSizeBmBm:(NSInteger)BM;
+ (BOOL)eSetframesizeBmBm:(NSInteger)BM;
+ (BOOL)utransformRotationBmBm:(NSInteger)BM;
+ (BOOL)ZSettransformrotationBmBm:(NSInteger)BM;
+ (BOOL)OtransformRotationXBmBm:(NSInteger)BM;
+ (BOOL)jSettransformrotationxBmBm:(NSInteger)BM;
+ (BOOL)jtransformRotationYBmBm:(NSInteger)BM;
+ (BOOL)rSettransformrotationyBmBm:(NSInteger)BM;
+ (BOOL)ctransformRotationZBmBm:(NSInteger)BM;
+ (BOOL)YSettransformrotationzBmBm:(NSInteger)BM;
+ (BOOL)RtransformScaleXBmBm:(NSInteger)BM;
+ (BOOL)RSettransformscalexBmBm:(NSInteger)BM;
+ (BOOL)NtransformScaleYBmBm:(NSInteger)BM;
+ (BOOL)xSettransformscaleyBmBm:(NSInteger)BM;
+ (BOOL)JtransformScaleZBmBm:(NSInteger)BM;
+ (BOOL)MSettransformscalezBmBm:(NSInteger)BM;
+ (BOOL)ktransformScaleBmBm:(NSInteger)BM;
+ (BOOL)jSettransformscaleBmBm:(NSInteger)BM;
+ (BOOL)XtransformTranslationXBmBm:(NSInteger)BM;
+ (BOOL)fSettransformtranslationxBmBm:(NSInteger)BM;
+ (BOOL)itransformTranslationYBmBm:(NSInteger)BM;
+ (BOOL)YSettransformtranslationyBmBm:(NSInteger)BM;
+ (BOOL)wtransformTranslationZBmBm:(NSInteger)BM;
+ (BOOL)FSettransformtranslationzBmBm:(NSInteger)BM;
+ (BOOL)gtransformDepthBmBm:(NSInteger)BM;
+ (BOOL)ZSettransformdepthBmBm:(NSInteger)BM;
+ (BOOL)acontentModeBmBm:(NSInteger)BM;
+ (BOOL)ISetcontentmodeBmBm:(NSInteger)BM;
+ (BOOL)uAddfadeanimationwithdurationDCurveBmBm:(NSInteger)BM;
+ (BOOL)BremovePreviousFadeAnimationBmBm:(NSInteger)BM;

@end
