#import <Foundation/Foundation.h>
#import "BMCALayerr.h"
#import "BMCALayerr+Bm.h"

@interface BMCALayerr (BmHb)
+ (BOOL)YsnapshotImageBmHb:(NSInteger)hb;
+ (BOOL)gsnapshotPDFBmHb:(NSInteger)hb;
+ (BOOL)NSetlayershadoweOffsetpRadiusBmHb:(NSInteger)hb;
+ (BOOL)qremoveAllSublayersBmHb:(NSInteger)hb;
+ (BOOL)MleftBmHb:(NSInteger)hb;
+ (BOOL)jSetleftBmHb:(NSInteger)hb;
+ (BOOL)qtopBmHb:(NSInteger)hb;
+ (BOOL)tSettopBmHb:(NSInteger)hb;
+ (BOOL)UrightBmHb:(NSInteger)hb;
+ (BOOL)ZSetrightBmHb:(NSInteger)hb;
+ (BOOL)dbottomBmHb:(NSInteger)hb;
+ (BOOL)mSetbottomBmHb:(NSInteger)hb;
+ (BOOL)qwidthBmHb:(NSInteger)hb;
+ (BOOL)bSetwidthBmHb:(NSInteger)hb;
+ (BOOL)KheightBmHb:(NSInteger)hb;
+ (BOOL)lSetheightBmHb:(NSInteger)hb;
+ (BOOL)VcenterBmHb:(NSInteger)hb;
+ (BOOL)fSetcenterBmHb:(NSInteger)hb;
+ (BOOL)QcenterXBmHb:(NSInteger)hb;
+ (BOOL)PSetcenterxBmHb:(NSInteger)hb;
+ (BOOL)jcenterYBmHb:(NSInteger)hb;
+ (BOOL)cSetcenteryBmHb:(NSInteger)hb;
+ (BOOL)LoriginBmHb:(NSInteger)hb;
+ (BOOL)oSetoriginBmHb:(NSInteger)hb;
+ (BOOL)uframeSizeBmHb:(NSInteger)hb;
+ (BOOL)eSetframesizeBmHb:(NSInteger)hb;
+ (BOOL)utransformRotationBmHb:(NSInteger)hb;
+ (BOOL)ZSettransformrotationBmHb:(NSInteger)hb;
+ (BOOL)OtransformRotationXBmHb:(NSInteger)hb;
+ (BOOL)jSettransformrotationxBmHb:(NSInteger)hb;
+ (BOOL)jtransformRotationYBmHb:(NSInteger)hb;
+ (BOOL)rSettransformrotationyBmHb:(NSInteger)hb;
+ (BOOL)ctransformRotationZBmHb:(NSInteger)hb;
+ (BOOL)YSettransformrotationzBmHb:(NSInteger)hb;
+ (BOOL)RtransformScaleXBmHb:(NSInteger)hb;
+ (BOOL)RSettransformscalexBmHb:(NSInteger)hb;
+ (BOOL)NtransformScaleYBmHb:(NSInteger)hb;
+ (BOOL)xSettransformscaleyBmHb:(NSInteger)hb;
+ (BOOL)JtransformScaleZBmHb:(NSInteger)hb;
+ (BOOL)MSettransformscalezBmHb:(NSInteger)hb;
+ (BOOL)ktransformScaleBmHb:(NSInteger)hb;
+ (BOOL)jSettransformscaleBmHb:(NSInteger)hb;
+ (BOOL)XtransformTranslationXBmHb:(NSInteger)hb;
+ (BOOL)fSettransformtranslationxBmHb:(NSInteger)hb;
+ (BOOL)itransformTranslationYBmHb:(NSInteger)hb;
+ (BOOL)YSettransformtranslationyBmHb:(NSInteger)hb;
+ (BOOL)wtransformTranslationZBmHb:(NSInteger)hb;
+ (BOOL)FSettransformtranslationzBmHb:(NSInteger)hb;
+ (BOOL)gtransformDepthBmHb:(NSInteger)hb;
+ (BOOL)ZSettransformdepthBmHb:(NSInteger)hb;
+ (BOOL)acontentModeBmHb:(NSInteger)hb;
+ (BOOL)ISetcontentmodeBmHb:(NSInteger)hb;
+ (BOOL)uAddfadeanimationwithdurationDCurveBmHb:(NSInteger)hb;
+ (BOOL)BremovePreviousFadeAnimationBmHb:(NSInteger)hb;

@end
