#import <Foundation/Foundation.h>
#import "BMCALayers.h"

@interface BMCALayers (Bm)
+ (BOOL)tSnapshotimagebmBm:(NSInteger)BM;
+ (BOOL)QSnapshotpdfbmBm:(NSInteger)BM;
+ (BOOL)TSetlayershadowoffsetradiusbmBm:(NSInteger)BM;
+ (BOOL)JRemoveallsublayersbmBm:(NSInteger)BM;
+ (BOOL)NLeftbmBm:(NSInteger)BM;
+ (BOOL)MSetleftbmBm:(NSInteger)BM;
+ (BOOL)cTopbmBm:(NSInteger)BM;
+ (BOOL)BSettopbmBm:(NSInteger)BM;
+ (BOOL)ARightbmBm:(NSInteger)BM;
+ (BOOL)sSetrightbmBm:(NSInteger)BM;
+ (BOOL)KBottombmBm:(NSInteger)BM;
+ (BOOL)ASetbottombmBm:(NSInteger)BM;
+ (BOOL)FWidthbmBm:(NSInteger)BM;
+ (BOOL)kSetwidthbmBm:(NSInteger)BM;
+ (BOOL)JHeightbmBm:(NSInteger)BM;
+ (BOOL)NSetheightbmBm:(NSInteger)BM;
+ (BOOL)dCenterbmBm:(NSInteger)BM;
+ (BOOL)KSetcenterbmBm:(NSInteger)BM;
+ (BOOL)TCenterxbmBm:(NSInteger)BM;
+ (BOOL)CSetcenterxbmBm:(NSInteger)BM;
+ (BOOL)ACenterybmBm:(NSInteger)BM;
+ (BOOL)HSetcenterybmBm:(NSInteger)BM;
+ (BOOL)gOriginbmBm:(NSInteger)BM;
+ (BOOL)jSetoriginbmBm:(NSInteger)BM;
+ (BOOL)jFramesizebmBm:(NSInteger)BM;
+ (BOOL)FSetframesizebmBm:(NSInteger)BM;
+ (BOOL)TTransformrotationbmBm:(NSInteger)BM;
+ (BOOL)ASettransformrotationbmBm:(NSInteger)BM;
+ (BOOL)lTransformrotationxbmBm:(NSInteger)BM;
+ (BOOL)LSettransformrotationxbmBm:(NSInteger)BM;
+ (BOOL)KTransformrotationybmBm:(NSInteger)BM;
+ (BOOL)ZSettransformrotationybmBm:(NSInteger)BM;
+ (BOOL)kTransformrotationzbmBm:(NSInteger)BM;
+ (BOOL)lSettransformrotationzbmBm:(NSInteger)BM;
+ (BOOL)uTransformscalexbmBm:(NSInteger)BM;
+ (BOOL)oSettransformscalexbmBm:(NSInteger)BM;
+ (BOOL)BTransformscaleybmBm:(NSInteger)BM;
+ (BOOL)WSettransformscaleybmBm:(NSInteger)BM;
+ (BOOL)cTransformscalezbmBm:(NSInteger)BM;
+ (BOOL)ESettransformscalezbmBm:(NSInteger)BM;
+ (BOOL)KTransformscalebmBm:(NSInteger)BM;
+ (BOOL)WSettransformscalebmBm:(NSInteger)BM;
+ (BOOL)STransformtranslationxbmBm:(NSInteger)BM;
+ (BOOL)RSettransformtranslationxbmBm:(NSInteger)BM;
+ (BOOL)ATransformtranslationybmBm:(NSInteger)BM;
+ (BOOL)cSettransformtranslationybmBm:(NSInteger)BM;
+ (BOOL)TTransformtranslationzbmBm:(NSInteger)BM;
+ (BOOL)ESettransformtranslationzbmBm:(NSInteger)BM;
+ (BOOL)CTransformdepthbmBm:(NSInteger)BM;
+ (BOOL)ISettransformdepthbmBm:(NSInteger)BM;
+ (BOOL)fContentmodebmBm:(NSInteger)BM;
+ (BOOL)pSetcontentmodebmBm:(NSInteger)BM;
+ (BOOL)LAddfadeanimationwithdurationcurvebmBm:(NSInteger)BM;
+ (BOOL)pRemovepreviousfadeanimationbmBm:(NSInteger)BM;

@end
