#import <Foundation/Foundation.h>
#import "BMCALayers.h"
#import "BMCALayers+Bm.h"

@interface BMCALayers (BmHb)
+ (BOOL)tSnapshotimagebmBmHb:(NSInteger)hb;
+ (BOOL)QSnapshotpdfbmBmHb:(NSInteger)hb;
+ (BOOL)TSetlayershadowoffsetradiusbmBmHb:(NSInteger)hb;
+ (BOOL)JRemoveallsublayersbmBmHb:(NSInteger)hb;
+ (BOOL)NLeftbmBmHb:(NSInteger)hb;
+ (BOOL)MSetleftbmBmHb:(NSInteger)hb;
+ (BOOL)cTopbmBmHb:(NSInteger)hb;
+ (BOOL)BSettopbmBmHb:(NSInteger)hb;
+ (BOOL)ARightbmBmHb:(NSInteger)hb;
+ (BOOL)sSetrightbmBmHb:(NSInteger)hb;
+ (BOOL)KBottombmBmHb:(NSInteger)hb;
+ (BOOL)ASetbottombmBmHb:(NSInteger)hb;
+ (BOOL)FWidthbmBmHb:(NSInteger)hb;
+ (BOOL)kSetwidthbmBmHb:(NSInteger)hb;
+ (BOOL)JHeightbmBmHb:(NSInteger)hb;
+ (BOOL)NSetheightbmBmHb:(NSInteger)hb;
+ (BOOL)dCenterbmBmHb:(NSInteger)hb;
+ (BOOL)KSetcenterbmBmHb:(NSInteger)hb;
+ (BOOL)TCenterxbmBmHb:(NSInteger)hb;
+ (BOOL)CSetcenterxbmBmHb:(NSInteger)hb;
+ (BOOL)ACenterybmBmHb:(NSInteger)hb;
+ (BOOL)HSetcenterybmBmHb:(NSInteger)hb;
+ (BOOL)gOriginbmBmHb:(NSInteger)hb;
+ (BOOL)jSetoriginbmBmHb:(NSInteger)hb;
+ (BOOL)jFramesizebmBmHb:(NSInteger)hb;
+ (BOOL)FSetframesizebmBmHb:(NSInteger)hb;
+ (BOOL)TTransformrotationbmBmHb:(NSInteger)hb;
+ (BOOL)ASettransformrotationbmBmHb:(NSInteger)hb;
+ (BOOL)lTransformrotationxbmBmHb:(NSInteger)hb;
+ (BOOL)LSettransformrotationxbmBmHb:(NSInteger)hb;
+ (BOOL)KTransformrotationybmBmHb:(NSInteger)hb;
+ (BOOL)ZSettransformrotationybmBmHb:(NSInteger)hb;
+ (BOOL)kTransformrotationzbmBmHb:(NSInteger)hb;
+ (BOOL)lSettransformrotationzbmBmHb:(NSInteger)hb;
+ (BOOL)uTransformscalexbmBmHb:(NSInteger)hb;
+ (BOOL)oSettransformscalexbmBmHb:(NSInteger)hb;
+ (BOOL)BTransformscaleybmBmHb:(NSInteger)hb;
+ (BOOL)WSettransformscaleybmBmHb:(NSInteger)hb;
+ (BOOL)cTransformscalezbmBmHb:(NSInteger)hb;
+ (BOOL)ESettransformscalezbmBmHb:(NSInteger)hb;
+ (BOOL)KTransformscalebmBmHb:(NSInteger)hb;
+ (BOOL)WSettransformscalebmBmHb:(NSInteger)hb;
+ (BOOL)STransformtranslationxbmBmHb:(NSInteger)hb;
+ (BOOL)RSettransformtranslationxbmBmHb:(NSInteger)hb;
+ (BOOL)ATransformtranslationybmBmHb:(NSInteger)hb;
+ (BOOL)cSettransformtranslationybmBmHb:(NSInteger)hb;
+ (BOOL)TTransformtranslationzbmBmHb:(NSInteger)hb;
+ (BOOL)ESettransformtranslationzbmBmHb:(NSInteger)hb;
+ (BOOL)CTransformdepthbmBmHb:(NSInteger)hb;
+ (BOOL)ISettransformdepthbmBmHb:(NSInteger)hb;
+ (BOOL)fContentmodebmBmHb:(NSInteger)hb;
+ (BOOL)pSetcontentmodebmBmHb:(NSInteger)hb;
+ (BOOL)LAddfadeanimationwithdurationcurvebmBmHb:(NSInteger)hb;
+ (BOOL)pRemovepreviousfadeanimationbmBmHb:(NSInteger)hb;

@end
