#import <Foundation/Foundation.h>
#import "BMCALayerr.h"

@interface BMCALayerr (Bm)
+ (BOOL)YsnapshotImageBm:(NSInteger)BM;
+ (BOOL)gsnapshotPDFBm:(NSInteger)BM;
+ (BOOL)NSetlayershadoweOffsetpRadiusBm:(NSInteger)BM;
+ (BOOL)qremoveAllSublayersBm:(NSInteger)BM;
+ (BOOL)MleftBm:(NSInteger)BM;
+ (BOOL)jSetleftBm:(NSInteger)BM;
+ (BOOL)qtopBm:(NSInteger)BM;
+ (BOOL)tSettopBm:(NSInteger)BM;
+ (BOOL)UrightBm:(NSInteger)BM;
+ (BOOL)ZSetrightBm:(NSInteger)BM;
+ (BOOL)dbottomBm:(NSInteger)BM;
+ (BOOL)mSetbottomBm:(NSInteger)BM;
+ (BOOL)qwidthBm:(NSInteger)BM;
+ (BOOL)bSetwidthBm:(NSInteger)BM;
+ (BOOL)KheightBm:(NSInteger)BM;
+ (BOOL)lSetheightBm:(NSInteger)BM;
+ (BOOL)VcenterBm:(NSInteger)BM;
+ (BOOL)fSetcenterBm:(NSInteger)BM;
+ (BOOL)QcenterXBm:(NSInteger)BM;
+ (BOOL)PSetcenterxBm:(NSInteger)BM;
+ (BOOL)jcenterYBm:(NSInteger)BM;
+ (BOOL)cSetcenteryBm:(NSInteger)BM;
+ (BOOL)LoriginBm:(NSInteger)BM;
+ (BOOL)oSetoriginBm:(NSInteger)BM;
+ (BOOL)uframeSizeBm:(NSInteger)BM;
+ (BOOL)eSetframesizeBm:(NSInteger)BM;
+ (BOOL)utransformRotationBm:(NSInteger)BM;
+ (BOOL)ZSettransformrotationBm:(NSInteger)BM;
+ (BOOL)OtransformRotationXBm:(NSInteger)BM;
+ (BOOL)jSettransformrotationxBm:(NSInteger)BM;
+ (BOOL)jtransformRotationYBm:(NSInteger)BM;
+ (BOOL)rSettransformrotationyBm:(NSInteger)BM;
+ (BOOL)ctransformRotationZBm:(NSInteger)BM;
+ (BOOL)YSettransformrotationzBm:(NSInteger)BM;
+ (BOOL)RtransformScaleXBm:(NSInteger)BM;
+ (BOOL)RSettransformscalexBm:(NSInteger)BM;
+ (BOOL)NtransformScaleYBm:(NSInteger)BM;
+ (BOOL)xSettransformscaleyBm:(NSInteger)BM;
+ (BOOL)JtransformScaleZBm:(NSInteger)BM;
+ (BOOL)MSettransformscalezBm:(NSInteger)BM;
+ (BOOL)ktransformScaleBm:(NSInteger)BM;
+ (BOOL)jSettransformscaleBm:(NSInteger)BM;
+ (BOOL)XtransformTranslationXBm:(NSInteger)BM;
+ (BOOL)fSettransformtranslationxBm:(NSInteger)BM;
+ (BOOL)itransformTranslationYBm:(NSInteger)BM;
+ (BOOL)YSettransformtranslationyBm:(NSInteger)BM;
+ (BOOL)wtransformTranslationZBm:(NSInteger)BM;
+ (BOOL)FSettransformtranslationzBm:(NSInteger)BM;
+ (BOOL)gtransformDepthBm:(NSInteger)BM;
+ (BOOL)ZSettransformdepthBm:(NSInteger)BM;
+ (BOOL)acontentModeBm:(NSInteger)BM;
+ (BOOL)ISetcontentmodeBm:(NSInteger)BM;
+ (BOOL)uAddfadeanimationwithdurationDCurveBm:(NSInteger)BM;
+ (BOOL)BremovePreviousFadeAnimationBm:(NSInteger)BM;

@end
