#import <Foundation/Foundation.h>
#import "BMCALayerm.h"

@interface BMCALayerm (Bm)
+ (BOOL)BsnapshotImageBm:(NSInteger)BM;
+ (BOOL)MsnapshotPDFBm:(NSInteger)BM;
+ (BOOL)sSetlayershadowPOffsetkRadiusBm:(NSInteger)BM;
+ (BOOL)eremoveAllSublayersBm:(NSInteger)BM;
+ (BOOL)WleftBm:(NSInteger)BM;
+ (BOOL)xSetleftBm:(NSInteger)BM;
+ (BOOL)rtopBm:(NSInteger)BM;
+ (BOOL)PSettopBm:(NSInteger)BM;
+ (BOOL)lrightBm:(NSInteger)BM;
+ (BOOL)rSetrightBm:(NSInteger)BM;
+ (BOOL)WbottomBm:(NSInteger)BM;
+ (BOOL)USetbottomBm:(NSInteger)BM;
+ (BOOL)qwidthBm:(NSInteger)BM;
+ (BOOL)RSetwidthBm:(NSInteger)BM;
+ (BOOL)CheightBm:(NSInteger)BM;
+ (BOOL)mSetheightBm:(NSInteger)BM;
+ (BOOL)ZcenterBm:(NSInteger)BM;
+ (BOOL)zSetcenterBm:(NSInteger)BM;
+ (BOOL)IcenterXBm:(NSInteger)BM;
+ (BOOL)dSetcenterxBm:(NSInteger)BM;
+ (BOOL)WcenterYBm:(NSInteger)BM;
+ (BOOL)ESetcenteryBm:(NSInteger)BM;
+ (BOOL)MoriginBm:(NSInteger)BM;
+ (BOOL)fSetoriginBm:(NSInteger)BM;
+ (BOOL)EframeSizeBm:(NSInteger)BM;
+ (BOOL)jSetframesizeBm:(NSInteger)BM;
+ (BOOL)LtransformRotationBm:(NSInteger)BM;
+ (BOOL)bSettransformrotationBm:(NSInteger)BM;
+ (BOOL)qtransformRotationXBm:(NSInteger)BM;
+ (BOOL)NSettransformrotationxBm:(NSInteger)BM;
+ (BOOL)wtransformRotationYBm:(NSInteger)BM;
+ (BOOL)NSettransformrotationyBm:(NSInteger)BM;
+ (BOOL)VtransformRotationZBm:(NSInteger)BM;
+ (BOOL)CSettransformrotationzBm:(NSInteger)BM;
+ (BOOL)OtransformScaleXBm:(NSInteger)BM;
+ (BOOL)rSettransformscalexBm:(NSInteger)BM;
+ (BOOL)StransformScaleYBm:(NSInteger)BM;
+ (BOOL)gSettransformscaleyBm:(NSInteger)BM;
+ (BOOL)CtransformScaleZBm:(NSInteger)BM;
+ (BOOL)zSettransformscalezBm:(NSInteger)BM;
+ (BOOL)utransformScaleBm:(NSInteger)BM;
+ (BOOL)iSettransformscaleBm:(NSInteger)BM;
+ (BOOL)FtransformTranslationXBm:(NSInteger)BM;
+ (BOOL)tSettransformtranslationxBm:(NSInteger)BM;
+ (BOOL)PtransformTranslationYBm:(NSInteger)BM;
+ (BOOL)BSettransformtranslationyBm:(NSInteger)BM;
+ (BOOL)NtransformTranslationZBm:(NSInteger)BM;
+ (BOOL)GSettransformtranslationzBm:(NSInteger)BM;
+ (BOOL)AtransformDepthBm:(NSInteger)BM;
+ (BOOL)ASettransformdepthBm:(NSInteger)BM;
+ (BOOL)xcontentModeBm:(NSInteger)BM;
+ (BOOL)NSetcontentmodeBm:(NSInteger)BM;
+ (BOOL)VAddfadeanimationwithdurationhCurveBm:(NSInteger)BM;
+ (BOOL)qremovePreviousFadeAnimationBm:(NSInteger)BM;

@end
