#import <Foundation/Foundation.h>
#import "BMGPUImageFilterm.h"
#import "BMGPUImageFilterm+Bm.h"
#import "BMGPUImageFilterm+BmBm.h"

@interface BMGPUImageFilterm (BmBmHb)
+ (BOOL)JInitwithvertexshaderfromstringfragmentshaderfromstringbmBmBmHb:(NSInteger)hb;
+ (BOOL)PInitwithfragmentshaderfromstringbmBmBmHb:(NSInteger)hb;
+ (BOOL)LInitwithfragmentshaderfromfilebmBmBmHb:(NSInteger)hb;
+ (BOOL)FInitbmBmBmHb:(NSInteger)hb;
+ (BOOL)HInitializeattributesbmBmBmHb:(NSInteger)hb;
+ (BOOL)LSetupfilterforsizebmBmBmHb:(NSInteger)hb;
+ (BOOL)PDeallocbmBmBmHb:(NSInteger)hb;
+ (BOOL)oUsenextframeforimagecapturebmBmBmHb:(NSInteger)hb;
+ (BOOL)nNewcgimagefromcurrentlyprocessedoutputbmBmBmHb:(NSInteger)hb;
+ (BOOL)eSizeoffbobmBmBmHb:(NSInteger)hb;
+ (BOOL)WTexturecoordinatesforrotationbmBmBmHb:(NSInteger)hb;
+ (BOOL)ORendertotexturewithverticestexturecoordinatesbmBmBmHb:(NSInteger)hb;
+ (BOOL)qInformtargetsaboutnewframeattimebmBmBmHb:(NSInteger)hb;
+ (BOOL)yOutputframesizebmBmBmHb:(NSInteger)hb;
+ (BOOL)ZSetbackgroundcolorredgreenbluealphabmBmBmHb:(NSInteger)hb;
+ (BOOL)cSetintegerforuniformnamebmBmBmHb:(NSInteger)hb;
+ (BOOL)qSetfloatforuniformnamebmBmBmHb:(NSInteger)hb;
+ (BOOL)dSetsizeforuniformnamebmBmBmHb:(NSInteger)hb;
+ (BOOL)zSetpointforuniformnamebmBmBmHb:(NSInteger)hb;
+ (BOOL)GSetfloatvec3ForuniformnamebmBmBmHb:(NSInteger)hb;
+ (BOOL)mSetfloatvec4ForuniformbmBmBmHb:(NSInteger)hb;
+ (BOOL)XSetfloatarraylengthforuniformbmBmBmHb:(NSInteger)hb;
+ (BOOL)hSetmatrix3FforuniformprogrambmBmBmHb:(NSInteger)hb;
+ (BOOL)wSetmatrix4FforuniformprogrambmBmBmHb:(NSInteger)hb;
+ (BOOL)uSetfloatforuniformprogrambmBmBmHb:(NSInteger)hb;
+ (BOOL)bSetpointforuniformprogrambmBmBmHb:(NSInteger)hb;
+ (BOOL)tSetsizeforuniformprogrambmBmBmHb:(NSInteger)hb;
+ (BOOL)jSetvec3ForuniformprogrambmBmBmHb:(NSInteger)hb;
+ (BOOL)RSetvec4ForuniformprogrambmBmBmHb:(NSInteger)hb;
+ (BOOL)ESetfloatarraylengthforuniformprogrambmBmBmHb:(NSInteger)hb;
+ (BOOL)FSetintegerforuniformprogrambmBmBmHb:(NSInteger)hb;
+ (BOOL)pSetandexecuteuniformstatecallbackatindexforprogramtoblockbmBmBmHb:(NSInteger)hb;
+ (BOOL)SSetuniformsforprogramatindexbmBmBmHb:(NSInteger)hb;
+ (BOOL)jNewframereadyattimeatindexbmBmBmHb:(NSInteger)hb;
+ (BOOL)nNextavailabletextureindexbmBmBmHb:(NSInteger)hb;
+ (BOOL)USetinputframebufferatindexbmBmBmHb:(NSInteger)hb;
+ (BOOL)dRotatedsizeforindexbmBmBmHb:(NSInteger)hb;
+ (BOOL)rRotatedpointforrotationbmBmBmHb:(NSInteger)hb;
+ (BOOL)wSetinputsizeatindexbmBmBmHb:(NSInteger)hb;
+ (BOOL)TSetinputrotationatindexbmBmBmHb:(NSInteger)hb;
+ (BOOL)kForceprocessingatsizebmBmBmHb:(NSInteger)hb;
+ (BOOL)OForceprocessingatsizerespectingaspectratiobmBmBmHb:(NSInteger)hb;
+ (BOOL)WMaximumoutputsizebmBmBmHb:(NSInteger)hb;
+ (BOOL)BEndprocessingbmBmBmHb:(NSInteger)hb;
+ (BOOL)mWantsmonochromeinputbmBmBmHb:(NSInteger)hb;

@end
