#import <Foundation/Foundation.h>
#import "BMLLSimpleCameraz.h"

@interface BMLLSimpleCameraz (Bm)
+ (BOOL)tinitBm:(NSInteger)BM;
+ (BOOL)vInitwithvideoenabledBm:(NSInteger)BM;
+ (BOOL)xInitwithqualityaPositionLVideoenabledBm:(NSInteger)BM;
+ (BOOL)aInitwithcoderBm:(NSInteger)BM;
+ (BOOL)tSetupwithqualityQPositioncVideoenabledBm:(NSInteger)BM;
+ (BOOL)zviewDidLoadBm:(NSInteger)BM;
+ (BOOL)YGesturerecognizershouldbeginBm:(NSInteger)BM;
+ (BOOL)tHandlepinchgestureBm:(NSInteger)BM;
+ (BOOL)gAttachtoviewcontrolleroWithframeBm:(NSInteger)BM;
+ (BOOL)nstartBm:(NSInteger)BM;
+ (BOOL)oinitializeBm:(NSInteger)BM;
+ (BOOL)qstopBm:(NSInteger)BM;
+ (BOOL)mCaptureaExactseenimageBm:(NSInteger)BM;
+ (BOOL)JCaptureBm:(NSInteger)BM;
+ (BOOL)cStartrecordingwithoutputurlBm:(NSInteger)BM;
+ (BOOL)UStoprecordingBm:(NSInteger)BM;
+ (BOOL)uCaptureoutputgDidstartrecordingtooutputfileaturlrFromconnectionsBm:(NSInteger)BM;
+ (BOOL)aCaptureoutputoDidfinishrecordingtooutputfileaturlEFromconnectionsRErrorBm:(NSInteger)BM;
+ (BOOL)EEnabletorchBm:(NSInteger)BM;
+ (BOOL)vCropimageusingpreviewboundsBm:(NSInteger)BM;
+ (BOOL)BcaptureConnectionBm:(NSInteger)BM;
+ (BOOL)DSetvideocapturedeviceBm:(NSInteger)BM;
+ (BOOL)PisFlashAvailableBm:(NSInteger)BM;
+ (BOOL)oisTorchAvailableBm:(NSInteger)BM;
+ (BOOL)tUpdateflashmodeBm:(NSInteger)BM;
+ (BOOL)ISetwhitebalancemodeBm:(NSInteger)BM;
+ (BOOL)nSetmirrorBm:(NSInteger)BM;
+ (BOOL)RtogglePositionBm:(NSInteger)BM;
+ (BOOL)ESetcamerapositionBm:(NSInteger)BM;
+ (BOOL)oCamerawithpositionBm:(NSInteger)BM;
+ (BOOL)DPreviewtappedBm:(NSInteger)BM;
+ (BOOL)FaddDefaultFocusBoxBm:(NSInteger)BM;
+ (BOOL)cAlterfocusboxIAnimationBm:(NSInteger)BM;
+ (BOOL)qFocusatpointBm:(NSInteger)BM;
+ (BOOL)kShowfocusboxBm:(NSInteger)BM;
+ (BOOL)pConverttopointofinterestfromviewcoordinatesBm:(NSInteger)BM;
+ (BOOL)jViewwillappearBm:(NSInteger)BM;
+ (BOOL)DViewwilldisappearBm:(NSInteger)BM;
+ (BOOL)ZviewWillLayoutSubviewsBm:(NSInteger)BM;
+ (BOOL)SorientationForConnectionBm:(NSInteger)BM;
+ (BOOL)hWillrotatetointerfaceorientationeDurationBm:(NSInteger)BM;
+ (BOOL)AdidReceiveMemoryWarningBm:(NSInteger)BM;
+ (BOOL)QdeallocBm:(NSInteger)BM;
+ (BOOL)mRequestcamerapermissionBm:(NSInteger)BM;
+ (BOOL)zRequestmicrophonepermissionBm:(NSInteger)BM;
+ (BOOL)WisFrontCameraAvailableBm:(NSInteger)BM;
+ (BOOL)pisRearCameraAvailableBm:(NSInteger)BM;

@end
