#import <Foundation/Foundation.h>
#import "BMMASConstraintn.h"

@interface BMMASConstraintn (Bm)
+ (BOOL)mInitbmBm:(NSInteger)BM;
+ (BOOL)cEqualtobmBm:(NSInteger)BM;
+ (BOOL)uMas_EqualtobmBm:(NSInteger)BM;
+ (BOOL)fGreaterthanorequaltobmBm:(NSInteger)BM;
+ (BOOL)vMas_GreaterthanorequaltobmBm:(NSInteger)BM;
+ (BOOL)YLessthanorequaltobmBm:(NSInteger)BM;
+ (BOOL)VMas_LessthanorequaltobmBm:(NSInteger)BM;
+ (BOOL)KPrioritylowbmBm:(NSInteger)BM;
+ (BOOL)PPrioritymediumbmBm:(NSInteger)BM;
+ (BOOL)EPriorityhighbmBm:(NSInteger)BM;
+ (BOOL)mInsetsbmBm:(NSInteger)BM;
+ (BOOL)fInsetbmBm:(NSInteger)BM;
+ (BOOL)tSizeoffsetbmBm:(NSInteger)BM;
+ (BOOL)hCenteroffsetbmBm:(NSInteger)BM;
+ (BOOL)nOffsetbmBm:(NSInteger)BM;
+ (BOOL)OValueoffsetbmBm:(NSInteger)BM;
+ (BOOL)DMas_OffsetbmBm:(NSInteger)BM;
+ (BOOL)bSetlayoutconstantwithvaluebmBm:(NSInteger)BM;
+ (BOOL)KWithbmBm:(NSInteger)BM;
+ (BOOL)NAndbmBm:(NSInteger)BM;
+ (BOOL)mAddconstraintwithlayoutattributebmBm:(NSInteger)BM;
+ (BOOL)ILeftbmBm:(NSInteger)BM;
+ (BOOL)MTopbmBm:(NSInteger)BM;
+ (BOOL)kRightbmBm:(NSInteger)BM;
+ (BOOL)bBottombmBm:(NSInteger)BM;
+ (BOOL)dLeadingbmBm:(NSInteger)BM;
+ (BOOL)OTrailingbmBm:(NSInteger)BM;
+ (BOOL)iWidthbmBm:(NSInteger)BM;
+ (BOOL)RHeightbmBm:(NSInteger)BM;
+ (BOOL)aCenterxbmBm:(NSInteger)BM;
+ (BOOL)pCenterybmBm:(NSInteger)BM;
+ (BOOL)ZBaselinebmBm:(NSInteger)BM;
+ (BOOL)XFirstbaselinebmBm:(NSInteger)BM;
+ (BOOL)zLastbaselinebmBm:(NSInteger)BM;
+ (BOOL)QLeftmarginbmBm:(NSInteger)BM;
+ (BOOL)pRightmarginbmBm:(NSInteger)BM;
+ (BOOL)jTopmarginbmBm:(NSInteger)BM;
+ (BOOL)wBottommarginbmBm:(NSInteger)BM;
+ (BOOL)FLeadingmarginbmBm:(NSInteger)BM;
+ (BOOL)gTrailingmarginbmBm:(NSInteger)BM;
+ (BOOL)vCenterxwithinmarginsbmBm:(NSInteger)BM;
+ (BOOL)gCenterywithinmarginsbmBm:(NSInteger)BM;
+ (BOOL)rMultipliedbybmBm:(NSInteger)BM;
+ (BOOL)RDividedbybmBm:(NSInteger)BM;
+ (BOOL)ZPrioritybmBm:(NSInteger)BM;
+ (BOOL)GEqualtowithrelationbmBm:(NSInteger)BM;
+ (BOOL)jKeybmBm:(NSInteger)BM;
+ (BOOL)VSetinsetsbmBm:(NSInteger)BM;
+ (BOOL)gSetinsetbmBm:(NSInteger)BM;
+ (BOOL)RSetsizeoffsetbmBm:(NSInteger)BM;
+ (BOOL)XSetcenteroffsetbmBm:(NSInteger)BM;
+ (BOOL)oSetoffsetbmBm:(NSInteger)BM;
+ (BOOL)qAnimatorbmBm:(NSInteger)BM;
+ (BOOL)oActivatebmBm:(NSInteger)BM;
+ (BOOL)MDeactivatebmBm:(NSInteger)BM;
+ (BOOL)dInstallbmBm:(NSInteger)BM;
+ (BOOL)uUninstallbmBm:(NSInteger)BM;

@end
