#import <Foundation/Foundation.h>
#import "BMMASConstraintY.h"
#import "BMMASConstraintY+Bm.h"

@interface BMMASConstraintY (BmBm)
+ (BOOL)NinitBmBm:(NSInteger)BM;
+ (BOOL)equalToBmBm:(NSInteger)BM;
+ (BOOL)mas_equalToBmBm:(NSInteger)BM;
+ (BOOL)greaterThanOrEqualToBmBm:(NSInteger)BM;
+ (BOOL)mas_greaterThanOrEqualToBmBm:(NSInteger)BM;
+ (BOOL)lessThanOrEqualToBmBm:(NSInteger)BM;
+ (BOOL)mas_lessThanOrEqualToBmBm:(NSInteger)BM;
+ (BOOL)priorityLowBmBm:(NSInteger)BM;
+ (BOOL)priorityMediumBmBm:(NSInteger)BM;
+ (BOOL)priorityHighBmBm:(NSInteger)BM;
+ (BOOL)insetsBmBm:(NSInteger)BM;
+ (BOOL)insetBmBm:(NSInteger)BM;
+ (BOOL)sizeOffsetBmBm:(NSInteger)BM;
+ (BOOL)centerOffsetBmBm:(NSInteger)BM;
+ (BOOL)offsetBmBm:(NSInteger)BM;
+ (BOOL)valueOffsetBmBm:(NSInteger)BM;
+ (BOOL)mas_offsetBmBm:(NSInteger)BM;
+ (BOOL)kSetlayoutconstantwithvalueBmBm:(NSInteger)BM;
+ (BOOL)TwithBmBm:(NSInteger)BM;
+ (BOOL)YandBmBm:(NSInteger)BM;
+ (BOOL)TAddconstraintwithlayoutattributeBmBm:(NSInteger)BM;
+ (BOOL)mleftBmBm:(NSInteger)BM;
+ (BOOL)dtopBmBm:(NSInteger)BM;
+ (BOOL)BrightBmBm:(NSInteger)BM;
+ (BOOL)dbottomBmBm:(NSInteger)BM;
+ (BOOL)fleadingBmBm:(NSInteger)BM;
+ (BOOL)VtrailingBmBm:(NSInteger)BM;
+ (BOOL)TwidthBmBm:(NSInteger)BM;
+ (BOOL)fheightBmBm:(NSInteger)BM;
+ (BOOL)zcenterXBmBm:(NSInteger)BM;
+ (BOOL)ncenterYBmBm:(NSInteger)BM;
+ (BOOL)PbaselineBmBm:(NSInteger)BM;
+ (BOOL)UfirstBaselineBmBm:(NSInteger)BM;
+ (BOOL)blastBaselineBmBm:(NSInteger)BM;
+ (BOOL)rleftMarginBmBm:(NSInteger)BM;
+ (BOOL)xrightMarginBmBm:(NSInteger)BM;
+ (BOOL)XtopMarginBmBm:(NSInteger)BM;
+ (BOOL)ebottomMarginBmBm:(NSInteger)BM;
+ (BOOL)UleadingMarginBmBm:(NSInteger)BM;
+ (BOOL)BtrailingMarginBmBm:(NSInteger)BM;
+ (BOOL)gcenterXWithinMarginsBmBm:(NSInteger)BM;
+ (BOOL)WcenterYWithinMarginsBmBm:(NSInteger)BM;
+ (BOOL)multipliedByBmBm:(NSInteger)BM;
+ (BOOL)dividedByBmBm:(NSInteger)BM;
+ (BOOL)priorityBmBm:(NSInteger)BM;
+ (BOOL)equalToWithRelationBmBm:(NSInteger)BM;
+ (BOOL)keyBmBm:(NSInteger)BM;
+ (BOOL)DSetinsetsBmBm:(NSInteger)BM;
+ (BOOL)gSetinsetBmBm:(NSInteger)BM;
+ (BOOL)uSetsizeoffsetBmBm:(NSInteger)BM;
+ (BOOL)lSetcenteroffsetBmBm:(NSInteger)BM;
+ (BOOL)dSetoffsetBmBm:(NSInteger)BM;
+ (BOOL)manimatorBmBm:(NSInteger)BM;
+ (BOOL)uactivateBmBm:(NSInteger)BM;
+ (BOOL)wdeactivateBmBm:(NSInteger)BM;
+ (BOOL)cinstallBmBm:(NSInteger)BM;
+ (BOOL)iuninstallBmBm:(NSInteger)BM;

@end
