#import <Foundation/Foundation.h>
#import "BMMASConstraintY.h"

@interface BMMASConstraintY (Bm)
+ (BOOL)NinitBm:(NSInteger)BM;
+ (BOOL)equalToBm:(NSInteger)BM;
+ (BOOL)mas_equalToBm:(NSInteger)BM;
+ (BOOL)greaterThanOrEqualToBm:(NSInteger)BM;
+ (BOOL)mas_greaterThanOrEqualToBm:(NSInteger)BM;
+ (BOOL)lessThanOrEqualToBm:(NSInteger)BM;
+ (BOOL)mas_lessThanOrEqualToBm:(NSInteger)BM;
+ (BOOL)priorityLowBm:(NSInteger)BM;
+ (BOOL)priorityMediumBm:(NSInteger)BM;
+ (BOOL)priorityHighBm:(NSInteger)BM;
+ (BOOL)insetsBm:(NSInteger)BM;
+ (BOOL)insetBm:(NSInteger)BM;
+ (BOOL)sizeOffsetBm:(NSInteger)BM;
+ (BOOL)centerOffsetBm:(NSInteger)BM;
+ (BOOL)offsetBm:(NSInteger)BM;
+ (BOOL)valueOffsetBm:(NSInteger)BM;
+ (BOOL)mas_offsetBm:(NSInteger)BM;
+ (BOOL)kSetlayoutconstantwithvalueBm:(NSInteger)BM;
+ (BOOL)TwithBm:(NSInteger)BM;
+ (BOOL)YandBm:(NSInteger)BM;
+ (BOOL)TAddconstraintwithlayoutattributeBm:(NSInteger)BM;
+ (BOOL)mleftBm:(NSInteger)BM;
+ (BOOL)dtopBm:(NSInteger)BM;
+ (BOOL)BrightBm:(NSInteger)BM;
+ (BOOL)dbottomBm:(NSInteger)BM;
+ (BOOL)fleadingBm:(NSInteger)BM;
+ (BOOL)VtrailingBm:(NSInteger)BM;
+ (BOOL)TwidthBm:(NSInteger)BM;
+ (BOOL)fheightBm:(NSInteger)BM;
+ (BOOL)zcenterXBm:(NSInteger)BM;
+ (BOOL)ncenterYBm:(NSInteger)BM;
+ (BOOL)PbaselineBm:(NSInteger)BM;
+ (BOOL)UfirstBaselineBm:(NSInteger)BM;
+ (BOOL)blastBaselineBm:(NSInteger)BM;
+ (BOOL)rleftMarginBm:(NSInteger)BM;
+ (BOOL)xrightMarginBm:(NSInteger)BM;
+ (BOOL)XtopMarginBm:(NSInteger)BM;
+ (BOOL)ebottomMarginBm:(NSInteger)BM;
+ (BOOL)UleadingMarginBm:(NSInteger)BM;
+ (BOOL)BtrailingMarginBm:(NSInteger)BM;
+ (BOOL)gcenterXWithinMarginsBm:(NSInteger)BM;
+ (BOOL)WcenterYWithinMarginsBm:(NSInteger)BM;
+ (BOOL)multipliedByBm:(NSInteger)BM;
+ (BOOL)dividedByBm:(NSInteger)BM;
+ (BOOL)priorityBm:(NSInteger)BM;
+ (BOOL)equalToWithRelationBm:(NSInteger)BM;
+ (BOOL)keyBm:(NSInteger)BM;
+ (BOOL)DSetinsetsBm:(NSInteger)BM;
+ (BOOL)gSetinsetBm:(NSInteger)BM;
+ (BOOL)uSetsizeoffsetBm:(NSInteger)BM;
+ (BOOL)lSetcenteroffsetBm:(NSInteger)BM;
+ (BOOL)dSetoffsetBm:(NSInteger)BM;
+ (BOOL)manimatorBm:(NSInteger)BM;
+ (BOOL)uactivateBm:(NSInteger)BM;
+ (BOOL)wdeactivateBm:(NSInteger)BM;
+ (BOOL)cinstallBm:(NSInteger)BM;
+ (BOOL)iuninstallBm:(NSInteger)BM;

@end
