#import <Foundation/Foundation.h>
#import "BMMASConstrainth.h"

@interface BMMASConstrainth (Bm)
+ (BOOL)oinitBm:(NSInteger)BM;
+ (BOOL)equalToBm:(NSInteger)BM;
+ (BOOL)mas_equalToBm:(NSInteger)BM;
+ (BOOL)greaterThanOrEqualToBm:(NSInteger)BM;
+ (BOOL)mas_greaterThanOrEqualToBm:(NSInteger)BM;
+ (BOOL)lessThanOrEqualToBm:(NSInteger)BM;
+ (BOOL)mas_lessThanOrEqualToBm:(NSInteger)BM;
+ (BOOL)priorityLowBm:(NSInteger)BM;
+ (BOOL)priorityMediumBm:(NSInteger)BM;
+ (BOOL)priorityHighBm:(NSInteger)BM;
+ (BOOL)insetsBm:(NSInteger)BM;
+ (BOOL)insetBm:(NSInteger)BM;
+ (BOOL)sizeOffsetBm:(NSInteger)BM;
+ (BOOL)centerOffsetBm:(NSInteger)BM;
+ (BOOL)offsetBm:(NSInteger)BM;
+ (BOOL)valueOffsetBm:(NSInteger)BM;
+ (BOOL)mas_offsetBm:(NSInteger)BM;
+ (BOOL)USetlayoutconstantwithvalueBm:(NSInteger)BM;
+ (BOOL)ZwithBm:(NSInteger)BM;
+ (BOOL)sandBm:(NSInteger)BM;
+ (BOOL)LAddconstraintwithlayoutattributeBm:(NSInteger)BM;
+ (BOOL)IleftBm:(NSInteger)BM;
+ (BOOL)ptopBm:(NSInteger)BM;
+ (BOOL)JrightBm:(NSInteger)BM;
+ (BOOL)JbottomBm:(NSInteger)BM;
+ (BOOL)dleadingBm:(NSInteger)BM;
+ (BOOL)ftrailingBm:(NSInteger)BM;
+ (BOOL)swidthBm:(NSInteger)BM;
+ (BOOL)LheightBm:(NSInteger)BM;
+ (BOOL)dcenterXBm:(NSInteger)BM;
+ (BOOL)McenterYBm:(NSInteger)BM;
+ (BOOL)xbaselineBm:(NSInteger)BM;
+ (BOOL)yfirstBaselineBm:(NSInteger)BM;
+ (BOOL)dlastBaselineBm:(NSInteger)BM;
+ (BOOL)HleftMarginBm:(NSInteger)BM;
+ (BOOL)rrightMarginBm:(NSInteger)BM;
+ (BOOL)wtopMarginBm:(NSInteger)BM;
+ (BOOL)RbottomMarginBm:(NSInteger)BM;
+ (BOOL)RleadingMarginBm:(NSInteger)BM;
+ (BOOL)ItrailingMarginBm:(NSInteger)BM;
+ (BOOL)ocenterXWithinMarginsBm:(NSInteger)BM;
+ (BOOL)AcenterYWithinMarginsBm:(NSInteger)BM;
+ (BOOL)multipliedByBm:(NSInteger)BM;
+ (BOOL)dividedByBm:(NSInteger)BM;
+ (BOOL)priorityBm:(NSInteger)BM;
+ (BOOL)equalToWithRelationBm:(NSInteger)BM;
+ (BOOL)keyBm:(NSInteger)BM;
+ (BOOL)SSetinsetsBm:(NSInteger)BM;
+ (BOOL)xSetinsetBm:(NSInteger)BM;
+ (BOOL)sSetsizeoffsetBm:(NSInteger)BM;
+ (BOOL)DSetcenteroffsetBm:(NSInteger)BM;
+ (BOOL)fSetoffsetBm:(NSInteger)BM;
+ (BOOL)wanimatorBm:(NSInteger)BM;
+ (BOOL)IactivateBm:(NSInteger)BM;
+ (BOOL)DdeactivateBm:(NSInteger)BM;
+ (BOOL)WinstallBm:(NSInteger)BM;
+ (BOOL)buninstallBm:(NSInteger)BM;

@end
