#import <Foundation/Foundation.h>
#import "BMMASConstraintn.h"
#import "BMMASConstraintn+Bm.h"

@interface BMMASConstraintn (BmHb)
+ (BOOL)mInitbmBmHb:(NSInteger)hb;
+ (BOOL)cEqualtobmBmHb:(NSInteger)hb;
+ (BOOL)uMas_EqualtobmBmHb:(NSInteger)hb;
+ (BOOL)fGreaterthanorequaltobmBmHb:(NSInteger)hb;
+ (BOOL)vMas_GreaterthanorequaltobmBmHb:(NSInteger)hb;
+ (BOOL)YLessthanorequaltobmBmHb:(NSInteger)hb;
+ (BOOL)VMas_LessthanorequaltobmBmHb:(NSInteger)hb;
+ (BOOL)KPrioritylowbmBmHb:(NSInteger)hb;
+ (BOOL)PPrioritymediumbmBmHb:(NSInteger)hb;
+ (BOOL)EPriorityhighbmBmHb:(NSInteger)hb;
+ (BOOL)mInsetsbmBmHb:(NSInteger)hb;
+ (BOOL)fInsetbmBmHb:(NSInteger)hb;
+ (BOOL)tSizeoffsetbmBmHb:(NSInteger)hb;
+ (BOOL)hCenteroffsetbmBmHb:(NSInteger)hb;
+ (BOOL)nOffsetbmBmHb:(NSInteger)hb;
+ (BOOL)OValueoffsetbmBmHb:(NSInteger)hb;
+ (BOOL)DMas_OffsetbmBmHb:(NSInteger)hb;
+ (BOOL)bSetlayoutconstantwithvaluebmBmHb:(NSInteger)hb;
+ (BOOL)KWithbmBmHb:(NSInteger)hb;
+ (BOOL)NAndbmBmHb:(NSInteger)hb;
+ (BOOL)mAddconstraintwithlayoutattributebmBmHb:(NSInteger)hb;
+ (BOOL)ILeftbmBmHb:(NSInteger)hb;
+ (BOOL)MTopbmBmHb:(NSInteger)hb;
+ (BOOL)kRightbmBmHb:(NSInteger)hb;
+ (BOOL)bBottombmBmHb:(NSInteger)hb;
+ (BOOL)dLeadingbmBmHb:(NSInteger)hb;
+ (BOOL)OTrailingbmBmHb:(NSInteger)hb;
+ (BOOL)iWidthbmBmHb:(NSInteger)hb;
+ (BOOL)RHeightbmBmHb:(NSInteger)hb;
+ (BOOL)aCenterxbmBmHb:(NSInteger)hb;
+ (BOOL)pCenterybmBmHb:(NSInteger)hb;
+ (BOOL)ZBaselinebmBmHb:(NSInteger)hb;
+ (BOOL)XFirstbaselinebmBmHb:(NSInteger)hb;
+ (BOOL)zLastbaselinebmBmHb:(NSInteger)hb;
+ (BOOL)QLeftmarginbmBmHb:(NSInteger)hb;
+ (BOOL)pRightmarginbmBmHb:(NSInteger)hb;
+ (BOOL)jTopmarginbmBmHb:(NSInteger)hb;
+ (BOOL)wBottommarginbmBmHb:(NSInteger)hb;
+ (BOOL)FLeadingmarginbmBmHb:(NSInteger)hb;
+ (BOOL)gTrailingmarginbmBmHb:(NSInteger)hb;
+ (BOOL)vCenterxwithinmarginsbmBmHb:(NSInteger)hb;
+ (BOOL)gCenterywithinmarginsbmBmHb:(NSInteger)hb;
+ (BOOL)rMultipliedbybmBmHb:(NSInteger)hb;
+ (BOOL)RDividedbybmBmHb:(NSInteger)hb;
+ (BOOL)ZPrioritybmBmHb:(NSInteger)hb;
+ (BOOL)GEqualtowithrelationbmBmHb:(NSInteger)hb;
+ (BOOL)jKeybmBmHb:(NSInteger)hb;
+ (BOOL)VSetinsetsbmBmHb:(NSInteger)hb;
+ (BOOL)gSetinsetbmBmHb:(NSInteger)hb;
+ (BOOL)RSetsizeoffsetbmBmHb:(NSInteger)hb;
+ (BOOL)XSetcenteroffsetbmBmHb:(NSInteger)hb;
+ (BOOL)oSetoffsetbmBmHb:(NSInteger)hb;
+ (BOOL)qAnimatorbmBmHb:(NSInteger)hb;
+ (BOOL)oActivatebmBmHb:(NSInteger)hb;
+ (BOOL)MDeactivatebmBmHb:(NSInteger)hb;
+ (BOOL)dInstallbmBmHb:(NSInteger)hb;
+ (BOOL)uUninstallbmBmHb:(NSInteger)hb;

@end
