#import <Foundation/Foundation.h>
#import "BMMASConstrainth.h"
#import "BMMASConstrainth+Bm.h"

@interface BMMASConstrainth (BmHb)
+ (BOOL)oinitBmHb:(NSInteger)hb;
+ (BOOL)equalToBmHb:(NSInteger)hb;
+ (BOOL)mas_equalToBmHb:(NSInteger)hb;
+ (BOOL)greaterThanOrEqualToBmHb:(NSInteger)hb;
+ (BOOL)mas_greaterThanOrEqualToBmHb:(NSInteger)hb;
+ (BOOL)lessThanOrEqualToBmHb:(NSInteger)hb;
+ (BOOL)mas_lessThanOrEqualToBmHb:(NSInteger)hb;
+ (BOOL)priorityLowBmHb:(NSInteger)hb;
+ (BOOL)priorityMediumBmHb:(NSInteger)hb;
+ (BOOL)priorityHighBmHb:(NSInteger)hb;
+ (BOOL)insetsBmHb:(NSInteger)hb;
+ (BOOL)insetBmHb:(NSInteger)hb;
+ (BOOL)sizeOffsetBmHb:(NSInteger)hb;
+ (BOOL)centerOffsetBmHb:(NSInteger)hb;
+ (BOOL)offsetBmHb:(NSInteger)hb;
+ (BOOL)valueOffsetBmHb:(NSInteger)hb;
+ (BOOL)mas_offsetBmHb:(NSInteger)hb;
+ (BOOL)USetlayoutconstantwithvalueBmHb:(NSInteger)hb;
+ (BOOL)ZwithBmHb:(NSInteger)hb;
+ (BOOL)sandBmHb:(NSInteger)hb;
+ (BOOL)LAddconstraintwithlayoutattributeBmHb:(NSInteger)hb;
+ (BOOL)IleftBmHb:(NSInteger)hb;
+ (BOOL)ptopBmHb:(NSInteger)hb;
+ (BOOL)JrightBmHb:(NSInteger)hb;
+ (BOOL)JbottomBmHb:(NSInteger)hb;
+ (BOOL)dleadingBmHb:(NSInteger)hb;
+ (BOOL)ftrailingBmHb:(NSInteger)hb;
+ (BOOL)swidthBmHb:(NSInteger)hb;
+ (BOOL)LheightBmHb:(NSInteger)hb;
+ (BOOL)dcenterXBmHb:(NSInteger)hb;
+ (BOOL)McenterYBmHb:(NSInteger)hb;
+ (BOOL)xbaselineBmHb:(NSInteger)hb;
+ (BOOL)yfirstBaselineBmHb:(NSInteger)hb;
+ (BOOL)dlastBaselineBmHb:(NSInteger)hb;
+ (BOOL)HleftMarginBmHb:(NSInteger)hb;
+ (BOOL)rrightMarginBmHb:(NSInteger)hb;
+ (BOOL)wtopMarginBmHb:(NSInteger)hb;
+ (BOOL)RbottomMarginBmHb:(NSInteger)hb;
+ (BOOL)RleadingMarginBmHb:(NSInteger)hb;
+ (BOOL)ItrailingMarginBmHb:(NSInteger)hb;
+ (BOOL)ocenterXWithinMarginsBmHb:(NSInteger)hb;
+ (BOOL)AcenterYWithinMarginsBmHb:(NSInteger)hb;
+ (BOOL)multipliedByBmHb:(NSInteger)hb;
+ (BOOL)dividedByBmHb:(NSInteger)hb;
+ (BOOL)priorityBmHb:(NSInteger)hb;
+ (BOOL)equalToWithRelationBmHb:(NSInteger)hb;
+ (BOOL)keyBmHb:(NSInteger)hb;
+ (BOOL)SSetinsetsBmHb:(NSInteger)hb;
+ (BOOL)xSetinsetBmHb:(NSInteger)hb;
+ (BOOL)sSetsizeoffsetBmHb:(NSInteger)hb;
+ (BOOL)DSetcenteroffsetBmHb:(NSInteger)hb;
+ (BOOL)fSetoffsetBmHb:(NSInteger)hb;
+ (BOOL)wanimatorBmHb:(NSInteger)hb;
+ (BOOL)IactivateBmHb:(NSInteger)hb;
+ (BOOL)DdeactivateBmHb:(NSInteger)hb;
+ (BOOL)WinstallBmHb:(NSInteger)hb;
+ (BOOL)buninstallBmHb:(NSInteger)hb;

@end
