#import <Foundation/Foundation.h>
#import "BMNSDataD.h"

@interface BMNSDataD (-Deletecomments)
+ (BOOL)nmd2String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)Hmd2Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)smd4String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cmd4Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)qmd5String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)Rmd5Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)Fsha1String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)Qsha1Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)Msha224String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)msha224Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)nsha256String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)usha256Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rsha384String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)isha384Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)jsha512String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)isha512Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vHmacstringusingalgbWithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tHmacdatausingalgcWithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)VHmacmd5Stringwithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rHmacmd5Datawithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)PHmacsha1Stringwithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)UHmacsha1Datawithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YHmacsha224Stringwithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sHmacsha224Datawithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YHmacsha256Stringwithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zHmacsha256Datawithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tHmacsha384Stringwithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)FHmacsha384Datawithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)pHmacsha512Stringwithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)EHmacsha512Datawithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vcrc32String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)Jcrc32-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dAes256EncryptwithkeyRIv-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)eAes256DecryptwithkeyLIv-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)Zutf8String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)OhexString-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dDatawithhexstring-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)Nbase64EncodedString-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)SDatawithbase64Encodedstring-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)njsonValueDecoded-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)WgzipInflate-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)fgzipDeflate-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)czlibInflate-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dzlibDeflate-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)GDatanamed-Deletecomments:(NSInteger)-deleteComments;

@end
