#import <Foundation/Foundation.h>
#import "BMNSDatax.h"
#import "BMNSDatax+Bm.h"

@interface BMNSDatax (Bm-Deletecomments)
+ (BOOL)PMd2StringbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)CMd2DatabmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)VMd4StringbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)EMd4DatabmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)OMd5StringbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)AMd5DatabmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hSha1StringbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)pSha1DatabmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ESha224StringbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)nSha224DatabmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)HSha256StringbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)WSha256DatabmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)pSha384StringbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QSha384DatabmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)KSha512StringbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)fSha512DatabmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)nHmacstringusingalgwithkeybmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oHmacdatausingalgwithkeybmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oHmacmd5StringwithkeybmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)yHmacmd5DatawithkeybmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)HHmacsha1StringwithkeybmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dHmacsha1DatawithkeybmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)kHmacsha224StringwithkeybmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QHmacsha224DatawithkeybmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)OHmacsha256StringwithkeybmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)KHmacsha256DatawithkeybmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)nHmacsha384StringwithkeybmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tHmacsha384DatawithkeybmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)EHmacsha512StringwithkeybmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)nHmacsha512DatawithkeybmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)eCrc32StringbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)nCrc32BmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)yAes256EncryptwithkeyivbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)uAes256DecryptwithkeyivbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)OUtf8StringbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)BHexstringbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bDatawithhexstringbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)JBase64EncodedstringbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)UDatawithbase64EncodedstringbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)CJsonvaluedecodedbmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cGzipinflatebmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bGzipdeflatebmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iZlibinflatebmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)IZlibdeflatebmbmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)EDatanamedbmbmBm-Deletecomments:(NSInteger)-deleteComments;

@end
