#import <Foundation/Foundation.h>
#import "BMNSStringP.h"

@interface BMNSStringP (-Deletecomments)
+ (BOOL)Emd2String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)amd4String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)Nmd5String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)Hsha1String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rsha224String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)Usha256String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)Nsha384String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tsha512String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)Ycrc32String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)mHmacmd5Stringwithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QHmacsha1Stringwithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oHmacsha224Stringwithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)HHmacsha256Stringwithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)CHmacsha384Stringwithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tHmacsha512Stringwithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)nbase64EncodedString-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)SStringwithbase64Encodedstring-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)EstringByURLEncode-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cstringByURLDecode-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)PstringByEscapingHTML-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)TSizeforfontSSizedMode-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zWidthforfont-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dHeightforfontEWidth-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)HMatchesregexSOptions-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rEnumerateregexmatchesIOptionshUsingblock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)lStringbyreplacingregexaOptionsaWithstring-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gcharValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)xunsignedCharValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)FshortValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)MunsignedShortValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)DunsignedIntValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dlongValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ZunsignedLongValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)NunsignedLongLongValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)runsignedIntegerValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)IstringWithUUID-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)wStringwithutf32Char-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QStringwithutf32CharskLength-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)DEnumerateutf32CharinrangeeUsingblock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XstringByTrim-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)xStringbyappendingnamescale-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)yStringbyappendingpathscale-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tpathScale-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)DisNotBlank-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)kContainsstring-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oContainscharacterset-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)BnumberValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vdataValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vrangeOfAll-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)KjsonValueDecoded-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)kStringnamed-Deletecomments:(NSInteger)-deleteComments;

@end
