#import <Foundation/Foundation.h>
#import "BMNSDataB.h"

@interface BMNSDataB (-Deletecomments)
+ (BOOL)CMd2Stringbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)SMd2Databm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YMd4Stringbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)CMd4Databm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)yMd5Stringbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sMd5Databm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bSha1Stringbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)wSha1Databm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)qSha224Stringbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)kSha224Databm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)qSha256Stringbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zSha256Databm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ESha384Stringbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)HSha384Databm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)xSha512Stringbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)NSha512Databm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ZHmacstringusingalgwithkeybm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dHmacdatausingalgwithkeybm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)JHmacmd5Stringwithkeybm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)HHmacmd5Datawithkeybm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)VHmacsha1Stringwithkeybm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aHmacsha1Datawithkeybm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)WHmacsha224Stringwithkeybm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)lHmacsha224Datawithkeybm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)EHmacsha256Stringwithkeybm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)IHmacsha256Datawithkeybm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oHmacsha384Stringwithkeybm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)THmacsha384Datawithkeybm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)BHmacsha512Stringwithkeybm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)THmacsha512Datawithkeybm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)lCrc32Stringbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dCrc32Bm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oAes256Encryptwithkeyivbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)xAes256Decryptwithkeyivbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)VUtf8Stringbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)BHexstringbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)kDatawithhexstringbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zBase64Encodedstringbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)IDatawithbase64Encodedstringbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sJsonvaluedecodedbm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)mGzipinflatebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RGzipdeflatebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cZlibinflatebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zZlibdeflatebm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)fDatanamedbm-Deletecomments:(NSInteger)-deleteComments;

@end
