#import <Foundation/Foundation.h>
#import "BMRACSignalS.h"
#import "BMRACSignalS+Bm.h"

@interface BMRACSignalS (BmBm)
+ (BOOL)JDonextBmBm:(NSInteger)BM;
+ (BOOL)ODoerrorBmBm:(NSInteger)BM;
+ (BOOL)vDocompletedBmBm:(NSInteger)BM;
+ (BOOL)mThrottleBmBm:(NSInteger)BM;
+ (BOOL)QThrottleFValuespassingtestBmBm:(NSInteger)BM;
+ (BOOL)GDelayBmBm:(NSInteger)BM;
+ (BOOL)LrepeatBmBm:(NSInteger)BM;
+ (BOOL)OCatchBmBm:(NSInteger)BM;
+ (BOOL)VCatchtoBmBm:(NSInteger)BM;
+ (BOOL)WTryBmBm:(NSInteger)BM;
+ (BOOL)ETryBmBm:(NSInteger)BM;
+ (BOOL)zTrymapBmBm:(NSInteger)BM;
+ (BOOL)xInitiallyBmBm:(NSInteger)BM;
+ (BOOL)IFinallyBmBm:(NSInteger)BM;
+ (BOOL)kBufferwithtimeTOnschedulerBmBm:(NSInteger)BM;
+ (BOOL)ucollectBmBm:(NSInteger)BM;
+ (BOOL)wTakelastBmBm:(NSInteger)BM;
+ (BOOL)zCombinelatestwithBmBm:(NSInteger)BM;
+ (BOOL)KCombinelatestBmBm:(NSInteger)BM;
+ (BOOL)qCombinelatesteReduceBmBm:(NSInteger)BM;
+ (BOOL)EMergeBmBm:(NSInteger)BM;
+ (BOOL)wMergeBmBm:(NSInteger)BM;
+ (BOOL)TFlattenBmBm:(NSInteger)BM;
+ (BOOL)eThenBmBm:(NSInteger)BM;
+ (BOOL)econcatBmBm:(NSInteger)BM;
+ (BOOL)MAggregatewithstartfactoryPReduceBmBm:(NSInteger)BM;
+ (BOOL)OAggregatewithstartcReduceBmBm:(NSInteger)BM;
+ (BOOL)aAggregatewithstartLReducewithindexBmBm:(NSInteger)BM;
+ (BOOL)USetkeypathYOnobjectBmBm:(NSInteger)BM;
+ (BOOL)dSetkeypathIOnobjectxNilvalueBmBm:(NSInteger)BM;
+ (BOOL)BIntervalaOnschedulerBmBm:(NSInteger)BM;
+ (BOOL)lIntervalMOnschedulercWithleewayBmBm:(NSInteger)BM;
+ (BOOL)KTakeuntilBmBm:(NSInteger)BM;
+ (BOOL)KTakeuntilreplacementBmBm:(NSInteger)BM;
+ (BOOL)ZswitchToLatestBmBm:(NSInteger)BM;
+ (BOOL)MSwitchlCasesxDefaultBmBm:(NSInteger)BM;
+ (BOOL)oIfFThenPElseBmBm:(NSInteger)BM;
+ (BOOL)CfirstBmBm:(NSInteger)BM;
+ (BOOL)tFirstordefaultBmBm:(NSInteger)BM;
+ (BOOL)KFirstordefaultHSuccesseErrorBmBm:(NSInteger)BM;
+ (BOOL)oWaituntilcompletedBmBm:(NSInteger)BM;
+ (BOOL)sDeferBmBm:(NSInteger)BM;
+ (BOOL)ktoArrayBmBm:(NSInteger)BM;
+ (BOOL)FsequenceBmBm:(NSInteger)BM;
+ (BOOL)OpublishBmBm:(NSInteger)BM;
+ (BOOL)VMulticastBmBm:(NSInteger)BM;
+ (BOOL)LreplayBmBm:(NSInteger)BM;
+ (BOOL)rreplayLastBmBm:(NSInteger)BM;
+ (BOOL)lreplayLazilyBmBm:(NSInteger)BM;
+ (BOOL)DTimeoutnOnschedulerBmBm:(NSInteger)BM;
+ (BOOL)NDeliveronBmBm:(NSInteger)BM;
+ (BOOL)wSubscribeonBmBm:(NSInteger)BM;
+ (BOOL)UdeliverOnMainThreadBmBm:(NSInteger)BM;
+ (BOOL)NGroupbywTransformBmBm:(NSInteger)BM;
+ (BOOL)jGroupbyBmBm:(NSInteger)BM;
+ (BOOL)yanyBmBm:(NSInteger)BM;
+ (BOOL)sAnyBmBm:(NSInteger)BM;
+ (BOOL)rAllBmBm:(NSInteger)BM;
+ (BOOL)ORetryBmBm:(NSInteger)BM;
+ (BOOL)dretryBmBm:(NSInteger)BM;
+ (BOOL)ISampleBmBm:(NSInteger)BM;
+ (BOOL)dignoreValuesBmBm:(NSInteger)BM;
+ (BOOL)CmaterializeBmBm:(NSInteger)BM;
+ (BOOL)cdematerializeBmBm:(NSInteger)BM;
+ (BOOL)unotBmBm:(NSInteger)BM;
+ (BOOL)YandBmBm:(NSInteger)BM;
+ (BOOL)vorBmBm:(NSInteger)BM;
+ (BOOL)creduceApplyBmBm:(NSInteger)BM;

@end
