#import <Foundation/Foundation.h>
#import "BMSDCycleScrollViewo.h"

@interface BMSDCycleScrollViewo (Bm)
+ (BOOL)zInitwithframeBm:(NSInteger)BM;
+ (BOOL)SawakeFromNibBm:(NSInteger)BM;
+ (BOOL)sinitializationBm:(NSInteger)BM;
+ (BOOL)BCyclescrollviewwithframeMImagenamesgroupBm:(NSInteger)BM;
+ (BOOL)JCyclescrollviewwithframeKShouldinfiniteloopUImagenamesgroupBm:(NSInteger)BM;
+ (BOOL)NCyclescrollviewwithframeuImageurlstringsgroupBm:(NSInteger)BM;
+ (BOOL)pCyclescrollviewwithframexDelegateuPlaceholderimageBm:(NSInteger)BM;
+ (BOOL)zsetupMainViewBm:(NSInteger)BM;
+ (BOOL)gSetdelegateBm:(NSInteger)BM;
+ (BOOL)HSetplaceholderimageBm:(NSInteger)BM;
+ (BOOL)RSetpagecontroldotsizeBm:(NSInteger)BM;
+ (BOOL)KSetshowpagecontrolBm:(NSInteger)BM;
+ (BOOL)WSetcurrentpagedotcolorBm:(NSInteger)BM;
+ (BOOL)RSetpagedotcolorBm:(NSInteger)BM;
+ (BOOL)sSetcurrentpagedotimageBm:(NSInteger)BM;
+ (BOOL)aSetpagedotimageBm:(NSInteger)BM;
+ (BOOL)JSetcustompagecontroldotimageoIscurrentpagedotBm:(NSInteger)BM;
+ (BOOL)nSetinfiniteloopBm:(NSInteger)BM;
+ (BOOL)KSetautoscrollBm:(NSInteger)BM;
+ (BOOL)zSetscrolldirectionBm:(NSInteger)BM;
+ (BOOL)USetautoscrolltimeintervalBm:(NSInteger)BM;
+ (BOOL)kSetpagecontrolstyleBm:(NSInteger)BM;
+ (BOOL)ISetimagepathsgroupBm:(NSInteger)BM;
+ (BOOL)XSetimageurlstringsgroupBm:(NSInteger)BM;
+ (BOOL)oSetlocalizationimagenamesgroupBm:(NSInteger)BM;
+ (BOOL)ESettitlesgroupBm:(NSInteger)BM;
+ (BOOL)RdisableScrollGestureBm:(NSInteger)BM;
+ (BOOL)lsetupTimerBm:(NSInteger)BM;
+ (BOOL)sinvalidateTimerBm:(NSInteger)BM;
+ (BOOL)FsetupPageControlBm:(NSInteger)BM;
+ (BOOL)ZautomaticScrollBm:(NSInteger)BM;
+ (BOOL)yScrolltoindexBm:(NSInteger)BM;
+ (BOOL)ncurrentIndexBm:(NSInteger)BM;
+ (BOOL)nPagecontrolindexwithcurrentcellindexBm:(NSInteger)BM;
+ (BOOL)VclearCacheBm:(NSInteger)BM;
+ (BOOL)JclearImagesCacheBm:(NSInteger)BM;
+ (BOOL)ulayoutSubviewsBm:(NSInteger)BM;
+ (BOOL)zWillmovetosuperviewBm:(NSInteger)BM;
+ (BOOL)mdeallocBm:(NSInteger)BM;
+ (BOOL)sadjustWhenControllerViewWillApperaBm:(NSInteger)BM;
+ (BOOL)DCollectionviewxNumberofitemsinsectionBm:(NSInteger)BM;
+ (BOOL)ACollectionviewwCellforitematindexpathBm:(NSInteger)BM;
+ (BOOL)lCollectionviewWDidselectitematindexpathBm:(NSInteger)BM;
+ (BOOL)zScrollviewdidscrollBm:(NSInteger)BM;
+ (BOOL)RScrollviewwillbegindraggingBm:(NSInteger)BM;
+ (BOOL)hScrollviewdidenddraggingdWilldecelerateBm:(NSInteger)BM;
+ (BOOL)dScrollviewdidenddeceleratingBm:(NSInteger)BM;
+ (BOOL)YScrollviewdidendscrollinganimationBm:(NSInteger)BM;
+ (BOOL)JMakescrollviewscrolltoindexBm:(NSInteger)BM;

@end
