#import <Foundation/Foundation.h>
#import "BMTKImageViewT.h"

@interface BMTKImageViewT (Bm)
+ (BOOL)VInitwithframeBm:(NSInteger)BM;
+ (BOOL)zInitwithcoderBm:(NSInteger)BM;
+ (BOOL)DcommonInitBm:(NSInteger)BM;
+ (BOOL)adeallocBm:(NSInteger)BM;
+ (BOOL)hsetUpBm:(NSInteger)BM;
+ (BOOL)ZbindPanGesturesBm:(NSInteger)BM;
+ (BOOL)BHandlecropareapinchBm:(NSInteger)BM;
+ (BOOL)nHandlecropareapanBm:(NSInteger)BM;
+ (BOOL)uHandlemidpanBm:(NSInteger)BM;
+ (BOOL)KHandlecornerpanBm:(NSInteger)BM;
+ (BOOL)bresetCornersOnCropAreaFrameChangedBm:(NSInteger)BM;
+ (BOOL)HresetCropAreaOnCornersFrameChangedBm:(NSInteger)BM;
+ (BOOL)dresetMinSpaceIfNeededBm:(NSInteger)BM;
+ (BOOL)qresetCropTransparentAreaBm:(NSInteger)BM;
+ (BOOL)ZresetCornersOnSizeChangedBm:(NSInteger)BM;
+ (BOOL)JcreateCornersBm:(NSInteger)BM;
+ (BOOL)zcreateMidLinesBm:(NSInteger)BM;
+ (BOOL)TremoveMidLinesBm:(NSInteger)BM;
+ (BOOL)MresetMidLinesBm:(NSInteger)BM;
+ (BOOL)FresetImageViewBm:(NSInteger)BM;
+ (BOOL)MresetCropAreaByAspectRatioBm:(NSInteger)BM;
+ (BOOL)fResetcropareabyscalefactorBm:(NSInteger)BM;
+ (BOOL)MSetinitialscalefactorBm:(NSInteger)BM;
+ (BOOL)ccornerMarginBm:(NSInteger)BM;
+ (BOOL)MSetmaskcolorBm:(NSInteger)BM;
+ (BOOL)uSetminspaceBm:(NSInteger)BM;
+ (BOOL)QSettocropimageBm:(NSInteger)BM;
+ (BOOL)ESetneedscalecropBm:(NSInteger)BM;
+ (BOOL)CSetcropareacrosslinewidthBm:(NSInteger)BM;
+ (BOOL)mSetcropareacrosslinecolorBm:(NSInteger)BM;
+ (BOOL)FSetcropareamidlinewidthBm:(NSInteger)BM;
+ (BOOL)RSetcropareamidlineheightBm:(NSInteger)BM;
+ (BOOL)ESetcropareamidlinecolorBm:(NSInteger)BM;
+ (BOOL)JSetcropareaborderlinewidthBm:(NSInteger)BM;
+ (BOOL)LSetcropareaborderlinecolorBm:(NSInteger)BM;
+ (BOOL)kSetcropareacornerlinecolorBm:(NSInteger)BM;
+ (BOOL)jSetcropareacornerlinewidthBm:(NSInteger)BM;
+ (BOOL)rSetcropareacornerwidthBm:(NSInteger)BM;
+ (BOOL)bSetcropareacornerheightBm:(NSInteger)BM;
+ (BOOL)USetcropaspectratioBm:(NSInteger)BM;
+ (BOOL)fSetshowmidlinesBm:(NSInteger)BM;
+ (BOOL)hSetshowcrosslinesBm:(NSInteger)BM;
+ (BOOL)lSetcornerborderinimageBm:(NSInteger)BM;
+ (BOOL)TSetframeBm:(NSInteger)BM;
+ (BOOL)HSetcenterBm:(NSInteger)BM;
+ (BOOL)uObservevalueforkeypathqOfobjectaChangeNContextBm:(NSInteger)BM;
+ (BOOL)LrotateBm:(NSInteger)BM;
+ (BOOL)pshowBm:(NSInteger)BM;
+ (BOOL)OhideBm:(NSInteger)BM;
+ (BOOL)ecurrentCroppedImageBm:(NSInteger)BM;

@end
