#import <Foundation/Foundation.h>
#import "BMTOCropViewControllert.h"
#import "BMTOCropViewControllert+Bm.h"
#import "BMTOCropViewControllert+BmBm.h"

@interface BMTOCropViewControllert (BmBm-Deletecomments)
+ (BOOL)KInitwithcroppingstylesImageBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bInitwithimageBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)IviewDidLoadBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XViewwillappearBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)KViewdidappearBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hViewwilldisappearBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)yViewdiddisappearBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)VpreferredStatusBarStyleBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)TprefersStatusBarHiddenBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)JpreferredScreenEdgesDeferringSystemGesturesBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iFramefortoolbarwithverticallayoutBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XFrameforcropviewwithverticallayoutBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sFramefortitlelabelwithsizeBVerticallayoutBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)jadjustCropViewInsetsBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)VadjustToolbarInsetsBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vviewSafeAreaInsetsDidChangeBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YviewDidLayoutSubviewsBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gWillrotatetointerfaceorientationdDurationBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rWillanimaterotationtointerfaceorientationvDurationBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)xDidrotatefrominterfaceorientationBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)fViewwilltransitiontosizeSWithtransitioncoordinatorBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)UresetCropViewLayoutBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)mshowAspectRatioDialogBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YActionsheetYDiddismisswithbuttonindexBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)SSetaspectratiopresettAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)drotateCropViewClockwiseBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vrotateCropViewCounterclockwiseBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)WCropviewdidbecomeresettableBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)NCropviewdidbecomenonresettableBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)kPresentanimatedfromparentviewcontrollerMFromviewZFromframeiSetupyCompletionBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hPresentanimatedfromparentviewcontrollerpFromimageYFromviewjFromframeFAnglefToimageframePSetupGCompletionBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)mDismissanimatedfromparentviewcontrolleroToviewQToframeoSetupCCompletionBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)WDismissanimatedfromparentviewcontrollerHWithcroppedimageZToviewIToframeuSetupmCompletionBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iAnimationcontrollerforpresentedcontrollerHPresentingcontrollerzSourcecontrollerBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)EAnimationcontrollerfordismissedcontrollerBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ZcancelButtonTappedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tdoneButtonTappedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)pSettitleBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RSetdonebuttontitleBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)NSetcancelbuttontitleBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YcropViewBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YtoolbarBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)KtitleLabelBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iSetaspectratiolockenabledBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ySetaspectratiolockdimensionswapenabledBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QaspectRatioLockEnabledBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oSetrotatebuttonshiddenBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)grotateButtonsHiddenBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)BSetrotateclockwisebuttonhiddenBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)JrotateClockwiseButtonHiddenBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)NSetaspectratiopickerbuttonhiddenBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RaspectRatioPickerButtonHiddenBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)USetresetaspectratioenabledBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)HSetcustomaspectratioBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)CresetAspectRatioEnabledBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)qSetangleBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oangleBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XSetimagecropframeBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)yimageCropFrameBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)fverticalLayoutBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)OoverrideStatusBarBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rstatusBarHiddenBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)UstatusBarHeightBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)UstatusBarSafeInsetsBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zSetminimumaspectratioBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)VminimumAspectRatioBmBm-Deletecomments:(NSInteger)-deleteComments;

@end
