#import <Foundation/Foundation.h>
#import "BMTOCropViewh.h"

@interface BMTOCropViewh (-Deletecomments)
+ (BOOL)pInitwithimage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rInitwithcroppingstyleQImage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)Ksetup-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)eperformInitialSetup-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)SlayoutInitialImage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ZprepareforRotation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)AperformRelayoutForRotation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)NmatchForegroundToBackground-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XUpdatecropboxframewithgesturepoint-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)AResetlayouttodefaultanimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iToggletranslucencyviewvisible-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)PUpdatetoimagecropframe-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)AGridpangesturerecognized-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)uLongpressgesturerecognized-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zGesturerecognizershouldbegin-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)mGesturerecognizerhShouldreceivetouch-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sstartResetTimer-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vtimerTriggered-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)VcancelResetTimer-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dCropedgeforpoint-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dViewforzoominginscrollview-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zScrollviewdidscroll-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)SScrollviewwillbegindragging-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)fScrollviewwillbeginzoomingnWithview-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)VScrollviewdidenddecelerating-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)kScrollviewdidendzoomingaWithviewVAtscale-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)pScrollviewdidzoom-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)uScrollviewdidenddraggingsWilldecelerate-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RSetcropboxresizeenabled-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)lSetcropboxframe-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)HSetediting-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ySetsimplerendermode-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)AcropBoxAspectRatioIsPortrait-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)jimageCropFrame-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vSetimagecropframe-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QSetcroppingviewshidden-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)JSetcroppingviewshiddenHAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oSetbackgroundimageviewhiddenxAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)WSetgridoverlayhidden-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)USetgridoverlayhiddenMAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)WimageViewFrame-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vSetcanbereset-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)qSetangle-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)BstartEditing-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bSeteditingwResetcropboxhAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vMovecroppedcontenttocenteranimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)uSetsimplerendermodelAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)eSetaspectratio-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)DSetaspectratiocAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hRotateimageninetydegreesanimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)URotateimageninetydegreesanimatedDClockwise-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QcaptureStateForImageRotation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)kcheckForCanReset-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)econtentBounds-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dimageSize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)uhasAspectRatio-Deletecomments:(NSInteger)-deleteComments;

@end
