#import <Foundation/Foundation.h>
#import "BMTOCropViewo.h"
#import "BMTOCropViewo+Bm.h"

@interface BMTOCropViewo (BmBm)
+ (BOOL)PInitwithimageBmBm:(NSInteger)BM;
+ (BOOL)pInitwithcroppingstyleTImageBmBm:(NSInteger)BM;
+ (BOOL)TsetupBmBm:(NSInteger)BM;
+ (BOOL)WperformInitialSetupBmBm:(NSInteger)BM;
+ (BOOL)vlayoutInitialImageBmBm:(NSInteger)BM;
+ (BOOL)RprepareforRotationBmBm:(NSInteger)BM;
+ (BOOL)bperformRelayoutForRotationBmBm:(NSInteger)BM;
+ (BOOL)JmatchForegroundToBackgroundBmBm:(NSInteger)BM;
+ (BOOL)QUpdatecropboxframewithgesturepointBmBm:(NSInteger)BM;
+ (BOOL)rResetlayouttodefaultanimatedBmBm:(NSInteger)BM;
+ (BOOL)BToggletranslucencyviewvisibleBmBm:(NSInteger)BM;
+ (BOOL)RUpdatetoimagecropframeBmBm:(NSInteger)BM;
+ (BOOL)IGridpangesturerecognizedBmBm:(NSInteger)BM;
+ (BOOL)DLongpressgesturerecognizedBmBm:(NSInteger)BM;
+ (BOOL)qGesturerecognizershouldbeginBmBm:(NSInteger)BM;
+ (BOOL)hGesturerecognizerwShouldreceivetouchBmBm:(NSInteger)BM;
+ (BOOL)hstartResetTimerBmBm:(NSInteger)BM;
+ (BOOL)AtimerTriggeredBmBm:(NSInteger)BM;
+ (BOOL)OcancelResetTimerBmBm:(NSInteger)BM;
+ (BOOL)cCropedgeforpointBmBm:(NSInteger)BM;
+ (BOOL)CViewforzoominginscrollviewBmBm:(NSInteger)BM;
+ (BOOL)QScrollviewdidscrollBmBm:(NSInteger)BM;
+ (BOOL)IScrollviewwillbegindraggingBmBm:(NSInteger)BM;
+ (BOOL)QScrollviewwillbeginzoomingOWithviewBmBm:(NSInteger)BM;
+ (BOOL)vScrollviewdidenddeceleratingBmBm:(NSInteger)BM;
+ (BOOL)KScrollviewdidendzoomingsWithviewlAtscaleBmBm:(NSInteger)BM;
+ (BOOL)lScrollviewdidzoomBmBm:(NSInteger)BM;
+ (BOOL)qScrollviewdidenddraggingIWilldecelerateBmBm:(NSInteger)BM;
+ (BOOL)tSetcropboxresizeenabledBmBm:(NSInteger)BM;
+ (BOOL)XSetcropboxframeBmBm:(NSInteger)BM;
+ (BOOL)aSeteditingBmBm:(NSInteger)BM;
+ (BOOL)rSetsimplerendermodeBmBm:(NSInteger)BM;
+ (BOOL)McropBoxAspectRatioIsPortraitBmBm:(NSInteger)BM;
+ (BOOL)iimageCropFrameBmBm:(NSInteger)BM;
+ (BOOL)ZSetimagecropframeBmBm:(NSInteger)BM;
+ (BOOL)MSetcroppingviewshiddenBmBm:(NSInteger)BM;
+ (BOOL)GSetcroppingviewshiddenwAnimatedBmBm:(NSInteger)BM;
+ (BOOL)GSetbackgroundimageviewhiddengAnimatedBmBm:(NSInteger)BM;
+ (BOOL)FSetgridoverlayhiddenBmBm:(NSInteger)BM;
+ (BOOL)ySetgridoverlayhiddenmAnimatedBmBm:(NSInteger)BM;
+ (BOOL)XimageViewFrameBmBm:(NSInteger)BM;
+ (BOOL)NSetcanberesetBmBm:(NSInteger)BM;
+ (BOOL)tSetangleBmBm:(NSInteger)BM;
+ (BOOL)ostartEditingBmBm:(NSInteger)BM;
+ (BOOL)lSeteditingiResetcropboxUAnimatedBmBm:(NSInteger)BM;
+ (BOOL)WMovecroppedcontenttocenteranimatedBmBm:(NSInteger)BM;
+ (BOOL)BSetsimplerendermodeBAnimatedBmBm:(NSInteger)BM;
+ (BOOL)GSetaspectratioBmBm:(NSInteger)BM;
+ (BOOL)tSetaspectratioAAnimatedBmBm:(NSInteger)BM;
+ (BOOL)mRotateimageninetydegreesanimatedBmBm:(NSInteger)BM;
+ (BOOL)aRotateimageninetydegreesanimatedBClockwiseBmBm:(NSInteger)BM;
+ (BOOL)ecaptureStateForImageRotationBmBm:(NSInteger)BM;
+ (BOOL)echeckForCanResetBmBm:(NSInteger)BM;
+ (BOOL)mcontentBoundsBmBm:(NSInteger)BM;
+ (BOOL)wimageSizeBmBm:(NSInteger)BM;
+ (BOOL)hhasAspectRatioBmBm:(NSInteger)BM;

@end
