#import <Foundation/Foundation.h>
#import "BMTOCropViewo.h"

@interface BMTOCropViewo (-Deletecomments)
+ (BOOL)PInitwithimage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)pInitwithcroppingstyleTImage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)Tsetup-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)WperformInitialSetup-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vlayoutInitialImage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RprepareforRotation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bperformRelayoutForRotation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)JmatchForegroundToBackground-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QUpdatecropboxframewithgesturepoint-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rResetlayouttodefaultanimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)BToggletranslucencyviewvisible-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RUpdatetoimagecropframe-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)IGridpangesturerecognized-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)DLongpressgesturerecognized-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)qGesturerecognizershouldbegin-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hGesturerecognizerwShouldreceivetouch-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hstartResetTimer-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)AtimerTriggered-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)OcancelResetTimer-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cCropedgeforpoint-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)CViewforzoominginscrollview-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QScrollviewdidscroll-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)IScrollviewwillbegindragging-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QScrollviewwillbeginzoomingOWithview-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vScrollviewdidenddecelerating-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)KScrollviewdidendzoomingsWithviewlAtscale-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)lScrollviewdidzoom-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)qScrollviewdidenddraggingIWilldecelerate-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tSetcropboxresizeenabled-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XSetcropboxframe-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aSetediting-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rSetsimplerendermode-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)McropBoxAspectRatioIsPortrait-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iimageCropFrame-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ZSetimagecropframe-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)MSetcroppingviewshidden-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)GSetcroppingviewshiddenwAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)GSetbackgroundimageviewhiddengAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)FSetgridoverlayhidden-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ySetgridoverlayhiddenmAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XimageViewFrame-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)NSetcanbereset-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tSetangle-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ostartEditing-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)lSeteditingiResetcropboxUAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)WMovecroppedcontenttocenteranimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)BSetsimplerendermodeBAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)GSetaspectratio-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tSetaspectratioAAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)mRotateimageninetydegreesanimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aRotateimageninetydegreesanimatedBClockwise-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ecaptureStateForImageRotation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)echeckForCanReset-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)mcontentBounds-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)wimageSize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hhasAspectRatio-Deletecomments:(NSInteger)-deleteComments;

@end
