#import <Foundation/Foundation.h>
#import "BMTOCropViewo.h"
#import "BMTOCropViewo+Bm.h"
#import "BMTOCropViewo+BmBm.h"

@interface BMTOCropViewo (BmBm-Deletecomments)
+ (BOOL)PInitwithimageBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)pInitwithcroppingstyleTImageBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)TsetupBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)WperformInitialSetupBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vlayoutInitialImageBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RprepareforRotationBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bperformRelayoutForRotationBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)JmatchForegroundToBackgroundBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QUpdatecropboxframewithgesturepointBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rResetlayouttodefaultanimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)BToggletranslucencyviewvisibleBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RUpdatetoimagecropframeBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)IGridpangesturerecognizedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)DLongpressgesturerecognizedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)qGesturerecognizershouldbeginBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hGesturerecognizerwShouldreceivetouchBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hstartResetTimerBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)AtimerTriggeredBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)OcancelResetTimerBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cCropedgeforpointBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)CViewforzoominginscrollviewBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QScrollviewdidscrollBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)IScrollviewwillbegindraggingBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QScrollviewwillbeginzoomingOWithviewBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)vScrollviewdidenddeceleratingBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)KScrollviewdidendzoomingsWithviewlAtscaleBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)lScrollviewdidzoomBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)qScrollviewdidenddraggingIWilldecelerateBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tSetcropboxresizeenabledBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XSetcropboxframeBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aSeteditingBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rSetsimplerendermodeBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)McropBoxAspectRatioIsPortraitBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)iimageCropFrameBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ZSetimagecropframeBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)MSetcroppingviewshiddenBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)GSetcroppingviewshiddenwAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)GSetbackgroundimageviewhiddengAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)FSetgridoverlayhiddenBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ySetgridoverlayhiddenmAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XimageViewFrameBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)NSetcanberesetBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tSetangleBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ostartEditingBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)lSeteditingiResetcropboxUAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)WMovecroppedcontenttocenteranimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)BSetsimplerendermodeBAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)GSetaspectratioBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tSetaspectratioAAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)mRotateimageninetydegreesanimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aRotateimageninetydegreesanimatedBClockwiseBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ecaptureStateForImageRotationBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)echeckForCanResetBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)mcontentBoundsBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)wimageSizeBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hhasAspectRatioBmBm-Deletecomments:(NSInteger)-deleteComments;

@end
