#import <Foundation/Foundation.h>
#import "BMTOCropViewControllerb.h"
#import "BMTOCropViewControllerb+Bm.h"

@interface BMTOCropViewControllerb (Bm-Deletecomments)
+ (BOOL)jInitwithcroppingstyletImageBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zInitwithimageBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cviewDidLoadBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QViewwillappearBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ZViewdidappearBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)xViewwilldisappearBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)wViewdiddisappearBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zpreferredStatusBarStyleBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tprefersStatusBarHiddenBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YpreferredScreenEdgesDeferringSystemGesturesBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bFramefortoolbarwithverticallayoutBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cFrameforcropviewwithverticallayoutBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QFramefortitlelabelwithsizeVVerticallayoutBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)HadjustCropViewInsetsBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)qadjustToolbarInsetsBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)AviewSafeAreaInsetsDidChangeBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)XviewDidLayoutSubviewsBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)VWillrotatetointerfaceorientationlDurationBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)xWillanimaterotationtointerfaceorientationQDurationBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)PDidrotatefrominterfaceorientationBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RViewwilltransitiontosizeHWithtransitioncoordinatorBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rresetCropViewLayoutBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)EshowAspectRatioDialogBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aActionsheetvDiddismisswithbuttonindexBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)KSetaspectratiopresetCAnimatedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)jrotateCropViewClockwiseBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)IrotateCropViewCounterclockwiseBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)uCropviewdidbecomeresettableBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rCropviewdidbecomenonresettableBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)JPresentanimatedfromparentviewcontrollerYFromviewtFromframeWSetupiCompletionBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QPresentanimatedfromparentviewcontrollerdFromimageqFromviewXFromframetAngleqToimageframeySetuphCompletionBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)LDismissanimatedfromparentviewcontrollerNToviewvToframeWSetuppCompletionBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)oDismissanimatedfromparentviewcontrollergWithcroppedimagetToviewDToframerSetupJCompletionBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)CAnimationcontrollerforpresentedcontrolleraPresentingcontrolleraSourcecontrollerBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)QAnimationcontrollerfordismissedcontrollerBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)PcancelButtonTappedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)OdoneButtonTappedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)jSettitleBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)uSetdonebuttontitleBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)eSetcancelbuttontitleBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ucropViewBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)utoolbarBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YtitleLabelBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)SSetaspectratiolockenabledBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ASetaspectratiolockdimensionswapenabledBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zaspectRatioLockEnabledBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)eSetrotatebuttonshiddenBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)YrotateButtonsHiddenBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cSetrotateclockwisebuttonhiddenBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)irotateClockwiseButtonHiddenBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sSetaspectratiopickerbuttonhiddenBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)KaspectRatioPickerButtonHiddenBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)pSetresetaspectratioenabledBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sSetcustomaspectratioBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)RresetAspectRatioEnabledBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)PSetangleBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)FangleBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rSetimagecropframeBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)nimageCropFrameBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)qverticalLayoutBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)yoverrideStatusBarBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)astatusBarHiddenBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sstatusBarHeightBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)GstatusBarSafeInsetsBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)WSetminimumaspectratioBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)GminimumAspectRatioBm-Deletecomments:(NSInteger)-deleteComments;

@end
