#import <Foundation/Foundation.h>
#import "BMTOCropViewV.h"
#import "BMTOCropViewV+Bm.h"

@interface BMTOCropViewV (BmBm)
+ (BOOL)TInitwithimagebmBmBm:(NSInteger)BM;
+ (BOOL)TInitwithcroppingstyleimagebmBmBm:(NSInteger)BM;
+ (BOOL)eSetupbmBmBm:(NSInteger)BM;
+ (BOOL)PPerforminitialsetupbmBmBm:(NSInteger)BM;
+ (BOOL)kLayoutinitialimagebmBmBm:(NSInteger)BM;
+ (BOOL)YPrepareforrotationbmBmBm:(NSInteger)BM;
+ (BOOL)jPerformrelayoutforrotationbmBmBm:(NSInteger)BM;
+ (BOOL)lMatchforegroundtobackgroundbmBmBm:(NSInteger)BM;
+ (BOOL)vUpdatecropboxframewithgesturepointbmBmBm:(NSInteger)BM;
+ (BOOL)JResetlayouttodefaultanimatedbmBmBm:(NSInteger)BM;
+ (BOOL)YToggletranslucencyviewvisiblebmBmBm:(NSInteger)BM;
+ (BOOL)RUpdatetoimagecropframebmBmBm:(NSInteger)BM;
+ (BOOL)iGridpangesturerecognizedbmBmBm:(NSInteger)BM;
+ (BOOL)rLongpressgesturerecognizedbmBmBm:(NSInteger)BM;
+ (BOOL)bGesturerecognizershouldbeginbmBmBm:(NSInteger)BM;
+ (BOOL)SGesturerecognizershouldreceivetouchbmBmBm:(NSInteger)BM;
+ (BOOL)aStartresettimerbmBmBm:(NSInteger)BM;
+ (BOOL)PTimertriggeredbmBmBm:(NSInteger)BM;
+ (BOOL)zCancelresettimerbmBmBm:(NSInteger)BM;
+ (BOOL)NCropedgeforpointbmBmBm:(NSInteger)BM;
+ (BOOL)xViewforzoominginscrollviewbmBmBm:(NSInteger)BM;
+ (BOOL)zScrollviewdidscrollbmBmBm:(NSInteger)BM;
+ (BOOL)qScrollviewwillbegindraggingbmBmBm:(NSInteger)BM;
+ (BOOL)CScrollviewwillbeginzoomingwithviewbmBmBm:(NSInteger)BM;
+ (BOOL)aScrollviewdidenddeceleratingbmBmBm:(NSInteger)BM;
+ (BOOL)uScrollviewdidendzoomingwithviewatscalebmBmBm:(NSInteger)BM;
+ (BOOL)iScrollviewdidzoombmBmBm:(NSInteger)BM;
+ (BOOL)lScrollviewdidenddraggingwilldeceleratebmBmBm:(NSInteger)BM;
+ (BOOL)NSetcropboxresizeenabledbmBmBm:(NSInteger)BM;
+ (BOOL)aSetcropboxframebmBmBm:(NSInteger)BM;
+ (BOOL)oSeteditingbmBmBm:(NSInteger)BM;
+ (BOOL)wSetsimplerendermodebmBmBm:(NSInteger)BM;
+ (BOOL)wCropboxaspectratioisportraitbmBmBm:(NSInteger)BM;
+ (BOOL)bImagecropframebmBmBm:(NSInteger)BM;
+ (BOOL)cSetimagecropframebmBmBm:(NSInteger)BM;
+ (BOOL)aSetcroppingviewshiddenbmBmBm:(NSInteger)BM;
+ (BOOL)FSetcroppingviewshiddenanimatedbmBmBm:(NSInteger)BM;
+ (BOOL)uSetbackgroundimageviewhiddenanimatedbmBmBm:(NSInteger)BM;
+ (BOOL)hSetgridoverlayhiddenbmBmBm:(NSInteger)BM;
+ (BOOL)aSetgridoverlayhiddenanimatedbmBmBm:(NSInteger)BM;
+ (BOOL)sImageviewframebmBmBm:(NSInteger)BM;
+ (BOOL)tSetcanberesetbmBmBm:(NSInteger)BM;
+ (BOOL)nSetanglebmBmBm:(NSInteger)BM;
+ (BOOL)EStarteditingbmBmBm:(NSInteger)BM;
+ (BOOL)MSeteditingresetcropboxanimatedbmBmBm:(NSInteger)BM;
+ (BOOL)MMovecroppedcontenttocenteranimatedbmBmBm:(NSInteger)BM;
+ (BOOL)wSetsimplerendermodeanimatedbmBmBm:(NSInteger)BM;
+ (BOOL)VSetaspectratiobmBmBm:(NSInteger)BM;
+ (BOOL)kSetaspectratioanimatedbmBmBm:(NSInteger)BM;
+ (BOOL)yRotateimageninetydegreesanimatedbmBmBm:(NSInteger)BM;
+ (BOOL)YRotateimageninetydegreesanimatedclockwisebmBmBm:(NSInteger)BM;
+ (BOOL)hCapturestateforimagerotationbmBmBm:(NSInteger)BM;
+ (BOOL)FCheckforcanresetbmBmBm:(NSInteger)BM;
+ (BOOL)xContentboundsbmBmBm:(NSInteger)BM;
+ (BOOL)yImagesizebmBmBm:(NSInteger)BM;
+ (BOOL)oHasaspectratiobmBmBm:(NSInteger)BM;

@end
