#import <Foundation/Foundation.h>
#import "BMTOCropViewControllerb.h"
#import "BMTOCropViewControllerb+Bm.h"

@interface BMTOCropViewControllerb (BmHb)
+ (BOOL)jInitwithcroppingstyletImageBmHb:(NSInteger)hb;
+ (BOOL)zInitwithimageBmHb:(NSInteger)hb;
+ (BOOL)cviewDidLoadBmHb:(NSInteger)hb;
+ (BOOL)QViewwillappearBmHb:(NSInteger)hb;
+ (BOOL)ZViewdidappearBmHb:(NSInteger)hb;
+ (BOOL)xViewwilldisappearBmHb:(NSInteger)hb;
+ (BOOL)wViewdiddisappearBmHb:(NSInteger)hb;
+ (BOOL)zpreferredStatusBarStyleBmHb:(NSInteger)hb;
+ (BOOL)tprefersStatusBarHiddenBmHb:(NSInteger)hb;
+ (BOOL)YpreferredScreenEdgesDeferringSystemGesturesBmHb:(NSInteger)hb;
+ (BOOL)bFramefortoolbarwithverticallayoutBmHb:(NSInteger)hb;
+ (BOOL)cFrameforcropviewwithverticallayoutBmHb:(NSInteger)hb;
+ (BOOL)QFramefortitlelabelwithsizeVVerticallayoutBmHb:(NSInteger)hb;
+ (BOOL)HadjustCropViewInsetsBmHb:(NSInteger)hb;
+ (BOOL)qadjustToolbarInsetsBmHb:(NSInteger)hb;
+ (BOOL)AviewSafeAreaInsetsDidChangeBmHb:(NSInteger)hb;
+ (BOOL)XviewDidLayoutSubviewsBmHb:(NSInteger)hb;
+ (BOOL)VWillrotatetointerfaceorientationlDurationBmHb:(NSInteger)hb;
+ (BOOL)xWillanimaterotationtointerfaceorientationQDurationBmHb:(NSInteger)hb;
+ (BOOL)PDidrotatefrominterfaceorientationBmHb:(NSInteger)hb;
+ (BOOL)RViewwilltransitiontosizeHWithtransitioncoordinatorBmHb:(NSInteger)hb;
+ (BOOL)rresetCropViewLayoutBmHb:(NSInteger)hb;
+ (BOOL)EshowAspectRatioDialogBmHb:(NSInteger)hb;
+ (BOOL)aActionsheetvDiddismisswithbuttonindexBmHb:(NSInteger)hb;
+ (BOOL)KSetaspectratiopresetCAnimatedBmHb:(NSInteger)hb;
+ (BOOL)jrotateCropViewClockwiseBmHb:(NSInteger)hb;
+ (BOOL)IrotateCropViewCounterclockwiseBmHb:(NSInteger)hb;
+ (BOOL)uCropviewdidbecomeresettableBmHb:(NSInteger)hb;
+ (BOOL)rCropviewdidbecomenonresettableBmHb:(NSInteger)hb;
+ (BOOL)JPresentanimatedfromparentviewcontrollerYFromviewtFromframeWSetupiCompletionBmHb:(NSInteger)hb;
+ (BOOL)QPresentanimatedfromparentviewcontrollerdFromimageqFromviewXFromframetAngleqToimageframeySetuphCompletionBmHb:(NSInteger)hb;
+ (BOOL)LDismissanimatedfromparentviewcontrollerNToviewvToframeWSetuppCompletionBmHb:(NSInteger)hb;
+ (BOOL)oDismissanimatedfromparentviewcontrollergWithcroppedimagetToviewDToframerSetupJCompletionBmHb:(NSInteger)hb;
+ (BOOL)CAnimationcontrollerforpresentedcontrolleraPresentingcontrolleraSourcecontrollerBmHb:(NSInteger)hb;
+ (BOOL)QAnimationcontrollerfordismissedcontrollerBmHb:(NSInteger)hb;
+ (BOOL)PcancelButtonTappedBmHb:(NSInteger)hb;
+ (BOOL)OdoneButtonTappedBmHb:(NSInteger)hb;
+ (BOOL)jSettitleBmHb:(NSInteger)hb;
+ (BOOL)uSetdonebuttontitleBmHb:(NSInteger)hb;
+ (BOOL)eSetcancelbuttontitleBmHb:(NSInteger)hb;
+ (BOOL)ucropViewBmHb:(NSInteger)hb;
+ (BOOL)utoolbarBmHb:(NSInteger)hb;
+ (BOOL)YtitleLabelBmHb:(NSInteger)hb;
+ (BOOL)SSetaspectratiolockenabledBmHb:(NSInteger)hb;
+ (BOOL)ASetaspectratiolockdimensionswapenabledBmHb:(NSInteger)hb;
+ (BOOL)zaspectRatioLockEnabledBmHb:(NSInteger)hb;
+ (BOOL)eSetrotatebuttonshiddenBmHb:(NSInteger)hb;
+ (BOOL)YrotateButtonsHiddenBmHb:(NSInteger)hb;
+ (BOOL)cSetrotateclockwisebuttonhiddenBmHb:(NSInteger)hb;
+ (BOOL)irotateClockwiseButtonHiddenBmHb:(NSInteger)hb;
+ (BOOL)sSetaspectratiopickerbuttonhiddenBmHb:(NSInteger)hb;
+ (BOOL)KaspectRatioPickerButtonHiddenBmHb:(NSInteger)hb;
+ (BOOL)pSetresetaspectratioenabledBmHb:(NSInteger)hb;
+ (BOOL)sSetcustomaspectratioBmHb:(NSInteger)hb;
+ (BOOL)RresetAspectRatioEnabledBmHb:(NSInteger)hb;
+ (BOOL)PSetangleBmHb:(NSInteger)hb;
+ (BOOL)FangleBmHb:(NSInteger)hb;
+ (BOOL)rSetimagecropframeBmHb:(NSInteger)hb;
+ (BOOL)nimageCropFrameBmHb:(NSInteger)hb;
+ (BOOL)qverticalLayoutBmHb:(NSInteger)hb;
+ (BOOL)yoverrideStatusBarBmHb:(NSInteger)hb;
+ (BOOL)astatusBarHiddenBmHb:(NSInteger)hb;
+ (BOOL)sstatusBarHeightBmHb:(NSInteger)hb;
+ (BOOL)GstatusBarSafeInsetsBmHb:(NSInteger)hb;
+ (BOOL)WSetminimumaspectratioBmHb:(NSInteger)hb;
+ (BOOL)GminimumAspectRatioBmHb:(NSInteger)hb;

@end
