#import <Foundation/Foundation.h>
#import "BMTOCropViewControllert.h"
#import "BMTOCropViewControllert+Bm.h"

@interface BMTOCropViewControllert (BmBm)
+ (BOOL)KInitwithcroppingstylesImageBmBm:(NSInteger)BM;
+ (BOOL)bInitwithimageBmBm:(NSInteger)BM;
+ (BOOL)IviewDidLoadBmBm:(NSInteger)BM;
+ (BOOL)XViewwillappearBmBm:(NSInteger)BM;
+ (BOOL)KViewdidappearBmBm:(NSInteger)BM;
+ (BOOL)hViewwilldisappearBmBm:(NSInteger)BM;
+ (BOOL)yViewdiddisappearBmBm:(NSInteger)BM;
+ (BOOL)VpreferredStatusBarStyleBmBm:(NSInteger)BM;
+ (BOOL)TprefersStatusBarHiddenBmBm:(NSInteger)BM;
+ (BOOL)JpreferredScreenEdgesDeferringSystemGesturesBmBm:(NSInteger)BM;
+ (BOOL)iFramefortoolbarwithverticallayoutBmBm:(NSInteger)BM;
+ (BOOL)XFrameforcropviewwithverticallayoutBmBm:(NSInteger)BM;
+ (BOOL)sFramefortitlelabelwithsizeBVerticallayoutBmBm:(NSInteger)BM;
+ (BOOL)jadjustCropViewInsetsBmBm:(NSInteger)BM;
+ (BOOL)VadjustToolbarInsetsBmBm:(NSInteger)BM;
+ (BOOL)vviewSafeAreaInsetsDidChangeBmBm:(NSInteger)BM;
+ (BOOL)YviewDidLayoutSubviewsBmBm:(NSInteger)BM;
+ (BOOL)gWillrotatetointerfaceorientationdDurationBmBm:(NSInteger)BM;
+ (BOOL)rWillanimaterotationtointerfaceorientationvDurationBmBm:(NSInteger)BM;
+ (BOOL)xDidrotatefrominterfaceorientationBmBm:(NSInteger)BM;
+ (BOOL)fViewwilltransitiontosizeSWithtransitioncoordinatorBmBm:(NSInteger)BM;
+ (BOOL)UresetCropViewLayoutBmBm:(NSInteger)BM;
+ (BOOL)mshowAspectRatioDialogBmBm:(NSInteger)BM;
+ (BOOL)YActionsheetYDiddismisswithbuttonindexBmBm:(NSInteger)BM;
+ (BOOL)SSetaspectratiopresettAnimatedBmBm:(NSInteger)BM;
+ (BOOL)drotateCropViewClockwiseBmBm:(NSInteger)BM;
+ (BOOL)vrotateCropViewCounterclockwiseBmBm:(NSInteger)BM;
+ (BOOL)WCropviewdidbecomeresettableBmBm:(NSInteger)BM;
+ (BOOL)NCropviewdidbecomenonresettableBmBm:(NSInteger)BM;
+ (BOOL)kPresentanimatedfromparentviewcontrollerMFromviewZFromframeiSetupyCompletionBmBm:(NSInteger)BM;
+ (BOOL)hPresentanimatedfromparentviewcontrollerpFromimageYFromviewjFromframeFAnglefToimageframePSetupGCompletionBmBm:(NSInteger)BM;
+ (BOOL)mDismissanimatedfromparentviewcontrolleroToviewQToframeoSetupCCompletionBmBm:(NSInteger)BM;
+ (BOOL)WDismissanimatedfromparentviewcontrollerHWithcroppedimageZToviewIToframeuSetupmCompletionBmBm:(NSInteger)BM;
+ (BOOL)iAnimationcontrollerforpresentedcontrollerHPresentingcontrollerzSourcecontrollerBmBm:(NSInteger)BM;
+ (BOOL)EAnimationcontrollerfordismissedcontrollerBmBm:(NSInteger)BM;
+ (BOOL)ZcancelButtonTappedBmBm:(NSInteger)BM;
+ (BOOL)tdoneButtonTappedBmBm:(NSInteger)BM;
+ (BOOL)pSettitleBmBm:(NSInteger)BM;
+ (BOOL)RSetdonebuttontitleBmBm:(NSInteger)BM;
+ (BOOL)NSetcancelbuttontitleBmBm:(NSInteger)BM;
+ (BOOL)YcropViewBmBm:(NSInteger)BM;
+ (BOOL)YtoolbarBmBm:(NSInteger)BM;
+ (BOOL)KtitleLabelBmBm:(NSInteger)BM;
+ (BOOL)iSetaspectratiolockenabledBmBm:(NSInteger)BM;
+ (BOOL)ySetaspectratiolockdimensionswapenabledBmBm:(NSInteger)BM;
+ (BOOL)QaspectRatioLockEnabledBmBm:(NSInteger)BM;
+ (BOOL)oSetrotatebuttonshiddenBmBm:(NSInteger)BM;
+ (BOOL)grotateButtonsHiddenBmBm:(NSInteger)BM;
+ (BOOL)BSetrotateclockwisebuttonhiddenBmBm:(NSInteger)BM;
+ (BOOL)JrotateClockwiseButtonHiddenBmBm:(NSInteger)BM;
+ (BOOL)NSetaspectratiopickerbuttonhiddenBmBm:(NSInteger)BM;
+ (BOOL)RaspectRatioPickerButtonHiddenBmBm:(NSInteger)BM;
+ (BOOL)USetresetaspectratioenabledBmBm:(NSInteger)BM;
+ (BOOL)HSetcustomaspectratioBmBm:(NSInteger)BM;
+ (BOOL)CresetAspectRatioEnabledBmBm:(NSInteger)BM;
+ (BOOL)qSetangleBmBm:(NSInteger)BM;
+ (BOOL)oangleBmBm:(NSInteger)BM;
+ (BOOL)XSetimagecropframeBmBm:(NSInteger)BM;
+ (BOOL)yimageCropFrameBmBm:(NSInteger)BM;
+ (BOOL)fverticalLayoutBmBm:(NSInteger)BM;
+ (BOOL)OoverrideStatusBarBmBm:(NSInteger)BM;
+ (BOOL)rstatusBarHiddenBmBm:(NSInteger)BM;
+ (BOOL)UstatusBarHeightBmBm:(NSInteger)BM;
+ (BOOL)UstatusBarSafeInsetsBmBm:(NSInteger)BM;
+ (BOOL)zSetminimumaspectratioBmBm:(NSInteger)BM;
+ (BOOL)VminimumAspectRatioBmBm:(NSInteger)BM;

@end
