#import <Foundation/Foundation.h>
#import "BMTOCropViewV.h"

@interface BMTOCropViewV (Bm)
+ (BOOL)TInitwithimagebmBm:(NSInteger)BM;
+ (BOOL)TInitwithcroppingstyleimagebmBm:(NSInteger)BM;
+ (BOOL)eSetupbmBm:(NSInteger)BM;
+ (BOOL)PPerforminitialsetupbmBm:(NSInteger)BM;
+ (BOOL)kLayoutinitialimagebmBm:(NSInteger)BM;
+ (BOOL)YPrepareforrotationbmBm:(NSInteger)BM;
+ (BOOL)jPerformrelayoutforrotationbmBm:(NSInteger)BM;
+ (BOOL)lMatchforegroundtobackgroundbmBm:(NSInteger)BM;
+ (BOOL)vUpdatecropboxframewithgesturepointbmBm:(NSInteger)BM;
+ (BOOL)JResetlayouttodefaultanimatedbmBm:(NSInteger)BM;
+ (BOOL)YToggletranslucencyviewvisiblebmBm:(NSInteger)BM;
+ (BOOL)RUpdatetoimagecropframebmBm:(NSInteger)BM;
+ (BOOL)iGridpangesturerecognizedbmBm:(NSInteger)BM;
+ (BOOL)rLongpressgesturerecognizedbmBm:(NSInteger)BM;
+ (BOOL)bGesturerecognizershouldbeginbmBm:(NSInteger)BM;
+ (BOOL)SGesturerecognizershouldreceivetouchbmBm:(NSInteger)BM;
+ (BOOL)aStartresettimerbmBm:(NSInteger)BM;
+ (BOOL)PTimertriggeredbmBm:(NSInteger)BM;
+ (BOOL)zCancelresettimerbmBm:(NSInteger)BM;
+ (BOOL)NCropedgeforpointbmBm:(NSInteger)BM;
+ (BOOL)xViewforzoominginscrollviewbmBm:(NSInteger)BM;
+ (BOOL)zScrollviewdidscrollbmBm:(NSInteger)BM;
+ (BOOL)qScrollviewwillbegindraggingbmBm:(NSInteger)BM;
+ (BOOL)CScrollviewwillbeginzoomingwithviewbmBm:(NSInteger)BM;
+ (BOOL)aScrollviewdidenddeceleratingbmBm:(NSInteger)BM;
+ (BOOL)uScrollviewdidendzoomingwithviewatscalebmBm:(NSInteger)BM;
+ (BOOL)iScrollviewdidzoombmBm:(NSInteger)BM;
+ (BOOL)lScrollviewdidenddraggingwilldeceleratebmBm:(NSInteger)BM;
+ (BOOL)NSetcropboxresizeenabledbmBm:(NSInteger)BM;
+ (BOOL)aSetcropboxframebmBm:(NSInteger)BM;
+ (BOOL)oSeteditingbmBm:(NSInteger)BM;
+ (BOOL)wSetsimplerendermodebmBm:(NSInteger)BM;
+ (BOOL)wCropboxaspectratioisportraitbmBm:(NSInteger)BM;
+ (BOOL)bImagecropframebmBm:(NSInteger)BM;
+ (BOOL)cSetimagecropframebmBm:(NSInteger)BM;
+ (BOOL)aSetcroppingviewshiddenbmBm:(NSInteger)BM;
+ (BOOL)FSetcroppingviewshiddenanimatedbmBm:(NSInteger)BM;
+ (BOOL)uSetbackgroundimageviewhiddenanimatedbmBm:(NSInteger)BM;
+ (BOOL)hSetgridoverlayhiddenbmBm:(NSInteger)BM;
+ (BOOL)aSetgridoverlayhiddenanimatedbmBm:(NSInteger)BM;
+ (BOOL)sImageviewframebmBm:(NSInteger)BM;
+ (BOOL)tSetcanberesetbmBm:(NSInteger)BM;
+ (BOOL)nSetanglebmBm:(NSInteger)BM;
+ (BOOL)EStarteditingbmBm:(NSInteger)BM;
+ (BOOL)MSeteditingresetcropboxanimatedbmBm:(NSInteger)BM;
+ (BOOL)MMovecroppedcontenttocenteranimatedbmBm:(NSInteger)BM;
+ (BOOL)wSetsimplerendermodeanimatedbmBm:(NSInteger)BM;
+ (BOOL)VSetaspectratiobmBm:(NSInteger)BM;
+ (BOOL)kSetaspectratioanimatedbmBm:(NSInteger)BM;
+ (BOOL)yRotateimageninetydegreesanimatedbmBm:(NSInteger)BM;
+ (BOOL)YRotateimageninetydegreesanimatedclockwisebmBm:(NSInteger)BM;
+ (BOOL)hCapturestateforimagerotationbmBm:(NSInteger)BM;
+ (BOOL)FCheckforcanresetbmBm:(NSInteger)BM;
+ (BOOL)xContentboundsbmBm:(NSInteger)BM;
+ (BOOL)yImagesizebmBm:(NSInteger)BM;
+ (BOOL)oHasaspectratiobmBm:(NSInteger)BM;

@end
