#import <Foundation/Foundation.h>
#import "BMTOCropViewo.h"
#import "BMTOCropViewo+Bm.h"
#import "BMTOCropViewo+BmBm.h"
#import "BMTOCropViewo+BmBmHb.h"

@interface BMTOCropViewo (BmBmHbHb)
+ (BOOL)PInitwithimageBmBmHbHb:(NSInteger)hb;
+ (BOOL)pInitwithcroppingstyleTImageBmBmHbHb:(NSInteger)hb;
+ (BOOL)TsetupBmBmHbHb:(NSInteger)hb;
+ (BOOL)WperformInitialSetupBmBmHbHb:(NSInteger)hb;
+ (BOOL)vlayoutInitialImageBmBmHbHb:(NSInteger)hb;
+ (BOOL)RprepareforRotationBmBmHbHb:(NSInteger)hb;
+ (BOOL)bperformRelayoutForRotationBmBmHbHb:(NSInteger)hb;
+ (BOOL)JmatchForegroundToBackgroundBmBmHbHb:(NSInteger)hb;
+ (BOOL)QUpdatecropboxframewithgesturepointBmBmHbHb:(NSInteger)hb;
+ (BOOL)rResetlayouttodefaultanimatedBmBmHbHb:(NSInteger)hb;
+ (BOOL)BToggletranslucencyviewvisibleBmBmHbHb:(NSInteger)hb;
+ (BOOL)RUpdatetoimagecropframeBmBmHbHb:(NSInteger)hb;
+ (BOOL)IGridpangesturerecognizedBmBmHbHb:(NSInteger)hb;
+ (BOOL)DLongpressgesturerecognizedBmBmHbHb:(NSInteger)hb;
+ (BOOL)qGesturerecognizershouldbeginBmBmHbHb:(NSInteger)hb;
+ (BOOL)hGesturerecognizerwShouldreceivetouchBmBmHbHb:(NSInteger)hb;
+ (BOOL)hstartResetTimerBmBmHbHb:(NSInteger)hb;
+ (BOOL)AtimerTriggeredBmBmHbHb:(NSInteger)hb;
+ (BOOL)OcancelResetTimerBmBmHbHb:(NSInteger)hb;
+ (BOOL)cCropedgeforpointBmBmHbHb:(NSInteger)hb;
+ (BOOL)CViewforzoominginscrollviewBmBmHbHb:(NSInteger)hb;
+ (BOOL)QScrollviewdidscrollBmBmHbHb:(NSInteger)hb;
+ (BOOL)IScrollviewwillbegindraggingBmBmHbHb:(NSInteger)hb;
+ (BOOL)QScrollviewwillbeginzoomingOWithviewBmBmHbHb:(NSInteger)hb;
+ (BOOL)vScrollviewdidenddeceleratingBmBmHbHb:(NSInteger)hb;
+ (BOOL)KScrollviewdidendzoomingsWithviewlAtscaleBmBmHbHb:(NSInteger)hb;
+ (BOOL)lScrollviewdidzoomBmBmHbHb:(NSInteger)hb;
+ (BOOL)qScrollviewdidenddraggingIWilldecelerateBmBmHbHb:(NSInteger)hb;
+ (BOOL)tSetcropboxresizeenabledBmBmHbHb:(NSInteger)hb;
+ (BOOL)XSetcropboxframeBmBmHbHb:(NSInteger)hb;
+ (BOOL)aSeteditingBmBmHbHb:(NSInteger)hb;
+ (BOOL)rSetsimplerendermodeBmBmHbHb:(NSInteger)hb;
+ (BOOL)McropBoxAspectRatioIsPortraitBmBmHbHb:(NSInteger)hb;
+ (BOOL)iimageCropFrameBmBmHbHb:(NSInteger)hb;
+ (BOOL)ZSetimagecropframeBmBmHbHb:(NSInteger)hb;
+ (BOOL)MSetcroppingviewshiddenBmBmHbHb:(NSInteger)hb;
+ (BOOL)GSetcroppingviewshiddenwAnimatedBmBmHbHb:(NSInteger)hb;
+ (BOOL)GSetbackgroundimageviewhiddengAnimatedBmBmHbHb:(NSInteger)hb;
+ (BOOL)FSetgridoverlayhiddenBmBmHbHb:(NSInteger)hb;
+ (BOOL)ySetgridoverlayhiddenmAnimatedBmBmHbHb:(NSInteger)hb;
+ (BOOL)XimageViewFrameBmBmHbHb:(NSInteger)hb;
+ (BOOL)NSetcanberesetBmBmHbHb:(NSInteger)hb;
+ (BOOL)tSetangleBmBmHbHb:(NSInteger)hb;
+ (BOOL)ostartEditingBmBmHbHb:(NSInteger)hb;
+ (BOOL)lSeteditingiResetcropboxUAnimatedBmBmHbHb:(NSInteger)hb;
+ (BOOL)WMovecroppedcontenttocenteranimatedBmBmHbHb:(NSInteger)hb;
+ (BOOL)BSetsimplerendermodeBAnimatedBmBmHbHb:(NSInteger)hb;
+ (BOOL)GSetaspectratioBmBmHbHb:(NSInteger)hb;
+ (BOOL)tSetaspectratioAAnimatedBmBmHbHb:(NSInteger)hb;
+ (BOOL)mRotateimageninetydegreesanimatedBmBmHbHb:(NSInteger)hb;
+ (BOOL)aRotateimageninetydegreesanimatedBClockwiseBmBmHbHb:(NSInteger)hb;
+ (BOOL)ecaptureStateForImageRotationBmBmHbHb:(NSInteger)hb;
+ (BOOL)echeckForCanResetBmBmHbHb:(NSInteger)hb;
+ (BOOL)mcontentBoundsBmBmHbHb:(NSInteger)hb;
+ (BOOL)wimageSizeBmBmHbHb:(NSInteger)hb;
+ (BOOL)hhasAspectRatioBmBmHbHb:(NSInteger)hb;

@end
