#import <Foundation/Foundation.h>
#import "BMTOCropViewh.h"

@interface BMTOCropViewh (Bm)
+ (BOOL)pInitwithimageBm:(NSInteger)BM;
+ (BOOL)rInitwithcroppingstyleQImageBm:(NSInteger)BM;
+ (BOOL)KsetupBm:(NSInteger)BM;
+ (BOOL)eperformInitialSetupBm:(NSInteger)BM;
+ (BOOL)SlayoutInitialImageBm:(NSInteger)BM;
+ (BOOL)ZprepareforRotationBm:(NSInteger)BM;
+ (BOOL)AperformRelayoutForRotationBm:(NSInteger)BM;
+ (BOOL)NmatchForegroundToBackgroundBm:(NSInteger)BM;
+ (BOOL)XUpdatecropboxframewithgesturepointBm:(NSInteger)BM;
+ (BOOL)AResetlayouttodefaultanimatedBm:(NSInteger)BM;
+ (BOOL)iToggletranslucencyviewvisibleBm:(NSInteger)BM;
+ (BOOL)PUpdatetoimagecropframeBm:(NSInteger)BM;
+ (BOOL)AGridpangesturerecognizedBm:(NSInteger)BM;
+ (BOOL)uLongpressgesturerecognizedBm:(NSInteger)BM;
+ (BOOL)zGesturerecognizershouldbeginBm:(NSInteger)BM;
+ (BOOL)mGesturerecognizerhShouldreceivetouchBm:(NSInteger)BM;
+ (BOOL)sstartResetTimerBm:(NSInteger)BM;
+ (BOOL)vtimerTriggeredBm:(NSInteger)BM;
+ (BOOL)VcancelResetTimerBm:(NSInteger)BM;
+ (BOOL)dCropedgeforpointBm:(NSInteger)BM;
+ (BOOL)dViewforzoominginscrollviewBm:(NSInteger)BM;
+ (BOOL)zScrollviewdidscrollBm:(NSInteger)BM;
+ (BOOL)SScrollviewwillbegindraggingBm:(NSInteger)BM;
+ (BOOL)fScrollviewwillbeginzoomingnWithviewBm:(NSInteger)BM;
+ (BOOL)VScrollviewdidenddeceleratingBm:(NSInteger)BM;
+ (BOOL)kScrollviewdidendzoomingaWithviewVAtscaleBm:(NSInteger)BM;
+ (BOOL)pScrollviewdidzoomBm:(NSInteger)BM;
+ (BOOL)uScrollviewdidenddraggingsWilldecelerateBm:(NSInteger)BM;
+ (BOOL)RSetcropboxresizeenabledBm:(NSInteger)BM;
+ (BOOL)lSetcropboxframeBm:(NSInteger)BM;
+ (BOOL)HSeteditingBm:(NSInteger)BM;
+ (BOOL)ySetsimplerendermodeBm:(NSInteger)BM;
+ (BOOL)AcropBoxAspectRatioIsPortraitBm:(NSInteger)BM;
+ (BOOL)jimageCropFrameBm:(NSInteger)BM;
+ (BOOL)vSetimagecropframeBm:(NSInteger)BM;
+ (BOOL)QSetcroppingviewshiddenBm:(NSInteger)BM;
+ (BOOL)JSetcroppingviewshiddenHAnimatedBm:(NSInteger)BM;
+ (BOOL)oSetbackgroundimageviewhiddenxAnimatedBm:(NSInteger)BM;
+ (BOOL)WSetgridoverlayhiddenBm:(NSInteger)BM;
+ (BOOL)USetgridoverlayhiddenMAnimatedBm:(NSInteger)BM;
+ (BOOL)WimageViewFrameBm:(NSInteger)BM;
+ (BOOL)vSetcanberesetBm:(NSInteger)BM;
+ (BOOL)qSetangleBm:(NSInteger)BM;
+ (BOOL)BstartEditingBm:(NSInteger)BM;
+ (BOOL)bSeteditingwResetcropboxhAnimatedBm:(NSInteger)BM;
+ (BOOL)vMovecroppedcontenttocenteranimatedBm:(NSInteger)BM;
+ (BOOL)uSetsimplerendermodelAnimatedBm:(NSInteger)BM;
+ (BOOL)eSetaspectratioBm:(NSInteger)BM;
+ (BOOL)DSetaspectratiocAnimatedBm:(NSInteger)BM;
+ (BOOL)hRotateimageninetydegreesanimatedBm:(NSInteger)BM;
+ (BOOL)URotateimageninetydegreesanimatedDClockwiseBm:(NSInteger)BM;
+ (BOOL)QcaptureStateForImageRotationBm:(NSInteger)BM;
+ (BOOL)kcheckForCanResetBm:(NSInteger)BM;
+ (BOOL)econtentBoundsBm:(NSInteger)BM;
+ (BOOL)dimageSizeBm:(NSInteger)BM;
+ (BOOL)uhasAspectRatioBm:(NSInteger)BM;

@end
