#import <Foundation/Foundation.h>
#import "BMTOCropViewo.h"

@interface BMTOCropViewo (Bm)
+ (BOOL)PInitwithimageBm:(NSInteger)BM;
+ (BOOL)pInitwithcroppingstyleTImageBm:(NSInteger)BM;
+ (BOOL)TsetupBm:(NSInteger)BM;
+ (BOOL)WperformInitialSetupBm:(NSInteger)BM;
+ (BOOL)vlayoutInitialImageBm:(NSInteger)BM;
+ (BOOL)RprepareforRotationBm:(NSInteger)BM;
+ (BOOL)bperformRelayoutForRotationBm:(NSInteger)BM;
+ (BOOL)JmatchForegroundToBackgroundBm:(NSInteger)BM;
+ (BOOL)QUpdatecropboxframewithgesturepointBm:(NSInteger)BM;
+ (BOOL)rResetlayouttodefaultanimatedBm:(NSInteger)BM;
+ (BOOL)BToggletranslucencyviewvisibleBm:(NSInteger)BM;
+ (BOOL)RUpdatetoimagecropframeBm:(NSInteger)BM;
+ (BOOL)IGridpangesturerecognizedBm:(NSInteger)BM;
+ (BOOL)DLongpressgesturerecognizedBm:(NSInteger)BM;
+ (BOOL)qGesturerecognizershouldbeginBm:(NSInteger)BM;
+ (BOOL)hGesturerecognizerwShouldreceivetouchBm:(NSInteger)BM;
+ (BOOL)hstartResetTimerBm:(NSInteger)BM;
+ (BOOL)AtimerTriggeredBm:(NSInteger)BM;
+ (BOOL)OcancelResetTimerBm:(NSInteger)BM;
+ (BOOL)cCropedgeforpointBm:(NSInteger)BM;
+ (BOOL)CViewforzoominginscrollviewBm:(NSInteger)BM;
+ (BOOL)QScrollviewdidscrollBm:(NSInteger)BM;
+ (BOOL)IScrollviewwillbegindraggingBm:(NSInteger)BM;
+ (BOOL)QScrollviewwillbeginzoomingOWithviewBm:(NSInteger)BM;
+ (BOOL)vScrollviewdidenddeceleratingBm:(NSInteger)BM;
+ (BOOL)KScrollviewdidendzoomingsWithviewlAtscaleBm:(NSInteger)BM;
+ (BOOL)lScrollviewdidzoomBm:(NSInteger)BM;
+ (BOOL)qScrollviewdidenddraggingIWilldecelerateBm:(NSInteger)BM;
+ (BOOL)tSetcropboxresizeenabledBm:(NSInteger)BM;
+ (BOOL)XSetcropboxframeBm:(NSInteger)BM;
+ (BOOL)aSeteditingBm:(NSInteger)BM;
+ (BOOL)rSetsimplerendermodeBm:(NSInteger)BM;
+ (BOOL)McropBoxAspectRatioIsPortraitBm:(NSInteger)BM;
+ (BOOL)iimageCropFrameBm:(NSInteger)BM;
+ (BOOL)ZSetimagecropframeBm:(NSInteger)BM;
+ (BOOL)MSetcroppingviewshiddenBm:(NSInteger)BM;
+ (BOOL)GSetcroppingviewshiddenwAnimatedBm:(NSInteger)BM;
+ (BOOL)GSetbackgroundimageviewhiddengAnimatedBm:(NSInteger)BM;
+ (BOOL)FSetgridoverlayhiddenBm:(NSInteger)BM;
+ (BOOL)ySetgridoverlayhiddenmAnimatedBm:(NSInteger)BM;
+ (BOOL)XimageViewFrameBm:(NSInteger)BM;
+ (BOOL)NSetcanberesetBm:(NSInteger)BM;
+ (BOOL)tSetangleBm:(NSInteger)BM;
+ (BOOL)ostartEditingBm:(NSInteger)BM;
+ (BOOL)lSeteditingiResetcropboxUAnimatedBm:(NSInteger)BM;
+ (BOOL)WMovecroppedcontenttocenteranimatedBm:(NSInteger)BM;
+ (BOOL)BSetsimplerendermodeBAnimatedBm:(NSInteger)BM;
+ (BOOL)GSetaspectratioBm:(NSInteger)BM;
+ (BOOL)tSetaspectratioAAnimatedBm:(NSInteger)BM;
+ (BOOL)mRotateimageninetydegreesanimatedBm:(NSInteger)BM;
+ (BOOL)aRotateimageninetydegreesanimatedBClockwiseBm:(NSInteger)BM;
+ (BOOL)ecaptureStateForImageRotationBm:(NSInteger)BM;
+ (BOOL)echeckForCanResetBm:(NSInteger)BM;
+ (BOOL)mcontentBoundsBm:(NSInteger)BM;
+ (BOOL)wimageSizeBm:(NSInteger)BM;
+ (BOOL)hhasAspectRatioBm:(NSInteger)BM;

@end
