#import <Foundation/Foundation.h>
#import "BMTOCropViewControllert.h"
#import "BMTOCropViewControllert+Bm.h"
#import "BMTOCropViewControllert+BmBm.h"

@interface BMTOCropViewControllert (BmBmHb)
+ (BOOL)KInitwithcroppingstylesImageBmBmHb:(NSInteger)hb;
+ (BOOL)bInitwithimageBmBmHb:(NSInteger)hb;
+ (BOOL)IviewDidLoadBmBmHb:(NSInteger)hb;
+ (BOOL)XViewwillappearBmBmHb:(NSInteger)hb;
+ (BOOL)KViewdidappearBmBmHb:(NSInteger)hb;
+ (BOOL)hViewwilldisappearBmBmHb:(NSInteger)hb;
+ (BOOL)yViewdiddisappearBmBmHb:(NSInteger)hb;
+ (BOOL)VpreferredStatusBarStyleBmBmHb:(NSInteger)hb;
+ (BOOL)TprefersStatusBarHiddenBmBmHb:(NSInteger)hb;
+ (BOOL)JpreferredScreenEdgesDeferringSystemGesturesBmBmHb:(NSInteger)hb;
+ (BOOL)iFramefortoolbarwithverticallayoutBmBmHb:(NSInteger)hb;
+ (BOOL)XFrameforcropviewwithverticallayoutBmBmHb:(NSInteger)hb;
+ (BOOL)sFramefortitlelabelwithsizeBVerticallayoutBmBmHb:(NSInteger)hb;
+ (BOOL)jadjustCropViewInsetsBmBmHb:(NSInteger)hb;
+ (BOOL)VadjustToolbarInsetsBmBmHb:(NSInteger)hb;
+ (BOOL)vviewSafeAreaInsetsDidChangeBmBmHb:(NSInteger)hb;
+ (BOOL)YviewDidLayoutSubviewsBmBmHb:(NSInteger)hb;
+ (BOOL)gWillrotatetointerfaceorientationdDurationBmBmHb:(NSInteger)hb;
+ (BOOL)rWillanimaterotationtointerfaceorientationvDurationBmBmHb:(NSInteger)hb;
+ (BOOL)xDidrotatefrominterfaceorientationBmBmHb:(NSInteger)hb;
+ (BOOL)fViewwilltransitiontosizeSWithtransitioncoordinatorBmBmHb:(NSInteger)hb;
+ (BOOL)UresetCropViewLayoutBmBmHb:(NSInteger)hb;
+ (BOOL)mshowAspectRatioDialogBmBmHb:(NSInteger)hb;
+ (BOOL)YActionsheetYDiddismisswithbuttonindexBmBmHb:(NSInteger)hb;
+ (BOOL)SSetaspectratiopresettAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)drotateCropViewClockwiseBmBmHb:(NSInteger)hb;
+ (BOOL)vrotateCropViewCounterclockwiseBmBmHb:(NSInteger)hb;
+ (BOOL)WCropviewdidbecomeresettableBmBmHb:(NSInteger)hb;
+ (BOOL)NCropviewdidbecomenonresettableBmBmHb:(NSInteger)hb;
+ (BOOL)kPresentanimatedfromparentviewcontrollerMFromviewZFromframeiSetupyCompletionBmBmHb:(NSInteger)hb;
+ (BOOL)hPresentanimatedfromparentviewcontrollerpFromimageYFromviewjFromframeFAnglefToimageframePSetupGCompletionBmBmHb:(NSInteger)hb;
+ (BOOL)mDismissanimatedfromparentviewcontrolleroToviewQToframeoSetupCCompletionBmBmHb:(NSInteger)hb;
+ (BOOL)WDismissanimatedfromparentviewcontrollerHWithcroppedimageZToviewIToframeuSetupmCompletionBmBmHb:(NSInteger)hb;
+ (BOOL)iAnimationcontrollerforpresentedcontrollerHPresentingcontrollerzSourcecontrollerBmBmHb:(NSInteger)hb;
+ (BOOL)EAnimationcontrollerfordismissedcontrollerBmBmHb:(NSInteger)hb;
+ (BOOL)ZcancelButtonTappedBmBmHb:(NSInteger)hb;
+ (BOOL)tdoneButtonTappedBmBmHb:(NSInteger)hb;
+ (BOOL)pSettitleBmBmHb:(NSInteger)hb;
+ (BOOL)RSetdonebuttontitleBmBmHb:(NSInteger)hb;
+ (BOOL)NSetcancelbuttontitleBmBmHb:(NSInteger)hb;
+ (BOOL)YcropViewBmBmHb:(NSInteger)hb;
+ (BOOL)YtoolbarBmBmHb:(NSInteger)hb;
+ (BOOL)KtitleLabelBmBmHb:(NSInteger)hb;
+ (BOOL)iSetaspectratiolockenabledBmBmHb:(NSInteger)hb;
+ (BOOL)ySetaspectratiolockdimensionswapenabledBmBmHb:(NSInteger)hb;
+ (BOOL)QaspectRatioLockEnabledBmBmHb:(NSInteger)hb;
+ (BOOL)oSetrotatebuttonshiddenBmBmHb:(NSInteger)hb;
+ (BOOL)grotateButtonsHiddenBmBmHb:(NSInteger)hb;
+ (BOOL)BSetrotateclockwisebuttonhiddenBmBmHb:(NSInteger)hb;
+ (BOOL)JrotateClockwiseButtonHiddenBmBmHb:(NSInteger)hb;
+ (BOOL)NSetaspectratiopickerbuttonhiddenBmBmHb:(NSInteger)hb;
+ (BOOL)RaspectRatioPickerButtonHiddenBmBmHb:(NSInteger)hb;
+ (BOOL)USetresetaspectratioenabledBmBmHb:(NSInteger)hb;
+ (BOOL)HSetcustomaspectratioBmBmHb:(NSInteger)hb;
+ (BOOL)CresetAspectRatioEnabledBmBmHb:(NSInteger)hb;
+ (BOOL)qSetangleBmBmHb:(NSInteger)hb;
+ (BOOL)oangleBmBmHb:(NSInteger)hb;
+ (BOOL)XSetimagecropframeBmBmHb:(NSInteger)hb;
+ (BOOL)yimageCropFrameBmBmHb:(NSInteger)hb;
+ (BOOL)fverticalLayoutBmBmHb:(NSInteger)hb;
+ (BOOL)OoverrideStatusBarBmBmHb:(NSInteger)hb;
+ (BOOL)rstatusBarHiddenBmBmHb:(NSInteger)hb;
+ (BOOL)UstatusBarHeightBmBmHb:(NSInteger)hb;
+ (BOOL)UstatusBarSafeInsetsBmBmHb:(NSInteger)hb;
+ (BOOL)zSetminimumaspectratioBmBmHb:(NSInteger)hb;
+ (BOOL)VminimumAspectRatioBmBmHb:(NSInteger)hb;

@end
