#import <Foundation/Foundation.h>
#import "BMTOCropViewb.h"

@interface BMTOCropViewb (Bm)
+ (BOOL)XInitwithimagebmbmBm:(NSInteger)BM;
+ (BOOL)mInitwithcroppingstyleimagebmbmBm:(NSInteger)BM;
+ (BOOL)ESetupbmbmBm:(NSInteger)BM;
+ (BOOL)tPerforminitialsetupbmbmBm:(NSInteger)BM;
+ (BOOL)KLayoutinitialimagebmbmBm:(NSInteger)BM;
+ (BOOL)IPrepareforrotationbmbmBm:(NSInteger)BM;
+ (BOOL)IPerformrelayoutforrotationbmbmBm:(NSInteger)BM;
+ (BOOL)rMatchforegroundtobackgroundbmbmBm:(NSInteger)BM;
+ (BOOL)xUpdatecropboxframewithgesturepointbmbmBm:(NSInteger)BM;
+ (BOOL)NResetlayouttodefaultanimatedbmbmBm:(NSInteger)BM;
+ (BOOL)pToggletranslucencyviewvisiblebmbmBm:(NSInteger)BM;
+ (BOOL)BUpdatetoimagecropframebmbmBm:(NSInteger)BM;
+ (BOOL)KGridpangesturerecognizedbmbmBm:(NSInteger)BM;
+ (BOOL)SLongpressgesturerecognizedbmbmBm:(NSInteger)BM;
+ (BOOL)sGesturerecognizershouldbeginbmbmBm:(NSInteger)BM;
+ (BOOL)uGesturerecognizershouldreceivetouchbmbmBm:(NSInteger)BM;
+ (BOOL)JStartresettimerbmbmBm:(NSInteger)BM;
+ (BOOL)XTimertriggeredbmbmBm:(NSInteger)BM;
+ (BOOL)zCancelresettimerbmbmBm:(NSInteger)BM;
+ (BOOL)xCropedgeforpointbmbmBm:(NSInteger)BM;
+ (BOOL)TViewforzoominginscrollviewbmbmBm:(NSInteger)BM;
+ (BOOL)JScrollviewdidscrollbmbmBm:(NSInteger)BM;
+ (BOOL)LScrollviewwillbegindraggingbmbmBm:(NSInteger)BM;
+ (BOOL)ZScrollviewwillbeginzoomingwithviewbmbmBm:(NSInteger)BM;
+ (BOOL)aScrollviewdidenddeceleratingbmbmBm:(NSInteger)BM;
+ (BOOL)nScrollviewdidendzoomingwithviewatscalebmbmBm:(NSInteger)BM;
+ (BOOL)yScrollviewdidzoombmbmBm:(NSInteger)BM;
+ (BOOL)NScrollviewdidenddraggingwilldeceleratebmbmBm:(NSInteger)BM;
+ (BOOL)nSetcropboxresizeenabledbmbmBm:(NSInteger)BM;
+ (BOOL)iSetcropboxframebmbmBm:(NSInteger)BM;
+ (BOOL)KSeteditingbmbmBm:(NSInteger)BM;
+ (BOOL)dSetsimplerendermodebmbmBm:(NSInteger)BM;
+ (BOOL)RCropboxaspectratioisportraitbmbmBm:(NSInteger)BM;
+ (BOOL)SImagecropframebmbmBm:(NSInteger)BM;
+ (BOOL)LSetimagecropframebmbmBm:(NSInteger)BM;
+ (BOOL)XSetcroppingviewshiddenbmbmBm:(NSInteger)BM;
+ (BOOL)ZSetcroppingviewshiddenanimatedbmbmBm:(NSInteger)BM;
+ (BOOL)zSetbackgroundimageviewhiddenanimatedbmbmBm:(NSInteger)BM;
+ (BOOL)ASetgridoverlayhiddenbmbmBm:(NSInteger)BM;
+ (BOOL)MSetgridoverlayhiddenanimatedbmbmBm:(NSInteger)BM;
+ (BOOL)JImageviewframebmbmBm:(NSInteger)BM;
+ (BOOL)ySetcanberesetbmbmBm:(NSInteger)BM;
+ (BOOL)oSetanglebmbmBm:(NSInteger)BM;
+ (BOOL)yStarteditingbmbmBm:(NSInteger)BM;
+ (BOOL)TSeteditingresetcropboxanimatedbmbmBm:(NSInteger)BM;
+ (BOOL)BMovecroppedcontenttocenteranimatedbmbmBm:(NSInteger)BM;
+ (BOOL)rSetsimplerendermodeanimatedbmbmBm:(NSInteger)BM;
+ (BOOL)WSetaspectratiobmbmBm:(NSInteger)BM;
+ (BOOL)LSetaspectratioanimatedbmbmBm:(NSInteger)BM;
+ (BOOL)rRotateimageninetydegreesanimatedbmbmBm:(NSInteger)BM;
+ (BOOL)LRotateimageninetydegreesanimatedclockwisebmbmBm:(NSInteger)BM;
+ (BOOL)TCapturestateforimagerotationbmbmBm:(NSInteger)BM;
+ (BOOL)rCheckforcanresetbmbmBm:(NSInteger)BM;
+ (BOOL)aContentboundsbmbmBm:(NSInteger)BM;
+ (BOOL)GImagesizebmbmBm:(NSInteger)BM;
+ (BOOL)oHasaspectratiobmbmBm:(NSInteger)BM;

@end
