#import <Foundation/Foundation.h>
#import "BMTOCropViewo.h"
#import "BMTOCropViewo+Bm.h"
#import "BMTOCropViewo+BmBm.h"

@interface BMTOCropViewo (BmBmHb)
+ (BOOL)PInitwithimageBmBmHb:(NSInteger)hb;
+ (BOOL)pInitwithcroppingstyleTImageBmBmHb:(NSInteger)hb;
+ (BOOL)TsetupBmBmHb:(NSInteger)hb;
+ (BOOL)WperformInitialSetupBmBmHb:(NSInteger)hb;
+ (BOOL)vlayoutInitialImageBmBmHb:(NSInteger)hb;
+ (BOOL)RprepareforRotationBmBmHb:(NSInteger)hb;
+ (BOOL)bperformRelayoutForRotationBmBmHb:(NSInteger)hb;
+ (BOOL)JmatchForegroundToBackgroundBmBmHb:(NSInteger)hb;
+ (BOOL)QUpdatecropboxframewithgesturepointBmBmHb:(NSInteger)hb;
+ (BOOL)rResetlayouttodefaultanimatedBmBmHb:(NSInteger)hb;
+ (BOOL)BToggletranslucencyviewvisibleBmBmHb:(NSInteger)hb;
+ (BOOL)RUpdatetoimagecropframeBmBmHb:(NSInteger)hb;
+ (BOOL)IGridpangesturerecognizedBmBmHb:(NSInteger)hb;
+ (BOOL)DLongpressgesturerecognizedBmBmHb:(NSInteger)hb;
+ (BOOL)qGesturerecognizershouldbeginBmBmHb:(NSInteger)hb;
+ (BOOL)hGesturerecognizerwShouldreceivetouchBmBmHb:(NSInteger)hb;
+ (BOOL)hstartResetTimerBmBmHb:(NSInteger)hb;
+ (BOOL)AtimerTriggeredBmBmHb:(NSInteger)hb;
+ (BOOL)OcancelResetTimerBmBmHb:(NSInteger)hb;
+ (BOOL)cCropedgeforpointBmBmHb:(NSInteger)hb;
+ (BOOL)CViewforzoominginscrollviewBmBmHb:(NSInteger)hb;
+ (BOOL)QScrollviewdidscrollBmBmHb:(NSInteger)hb;
+ (BOOL)IScrollviewwillbegindraggingBmBmHb:(NSInteger)hb;
+ (BOOL)QScrollviewwillbeginzoomingOWithviewBmBmHb:(NSInteger)hb;
+ (BOOL)vScrollviewdidenddeceleratingBmBmHb:(NSInteger)hb;
+ (BOOL)KScrollviewdidendzoomingsWithviewlAtscaleBmBmHb:(NSInteger)hb;
+ (BOOL)lScrollviewdidzoomBmBmHb:(NSInteger)hb;
+ (BOOL)qScrollviewdidenddraggingIWilldecelerateBmBmHb:(NSInteger)hb;
+ (BOOL)tSetcropboxresizeenabledBmBmHb:(NSInteger)hb;
+ (BOOL)XSetcropboxframeBmBmHb:(NSInteger)hb;
+ (BOOL)aSeteditingBmBmHb:(NSInteger)hb;
+ (BOOL)rSetsimplerendermodeBmBmHb:(NSInteger)hb;
+ (BOOL)McropBoxAspectRatioIsPortraitBmBmHb:(NSInteger)hb;
+ (BOOL)iimageCropFrameBmBmHb:(NSInteger)hb;
+ (BOOL)ZSetimagecropframeBmBmHb:(NSInteger)hb;
+ (BOOL)MSetcroppingviewshiddenBmBmHb:(NSInteger)hb;
+ (BOOL)GSetcroppingviewshiddenwAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)GSetbackgroundimageviewhiddengAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)FSetgridoverlayhiddenBmBmHb:(NSInteger)hb;
+ (BOOL)ySetgridoverlayhiddenmAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)XimageViewFrameBmBmHb:(NSInteger)hb;
+ (BOOL)NSetcanberesetBmBmHb:(NSInteger)hb;
+ (BOOL)tSetangleBmBmHb:(NSInteger)hb;
+ (BOOL)ostartEditingBmBmHb:(NSInteger)hb;
+ (BOOL)lSeteditingiResetcropboxUAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)WMovecroppedcontenttocenteranimatedBmBmHb:(NSInteger)hb;
+ (BOOL)BSetsimplerendermodeBAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)GSetaspectratioBmBmHb:(NSInteger)hb;
+ (BOOL)tSetaspectratioAAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)mRotateimageninetydegreesanimatedBmBmHb:(NSInteger)hb;
+ (BOOL)aRotateimageninetydegreesanimatedBClockwiseBmBmHb:(NSInteger)hb;
+ (BOOL)ecaptureStateForImageRotationBmBmHb:(NSInteger)hb;
+ (BOOL)echeckForCanResetBmBmHb:(NSInteger)hb;
+ (BOOL)mcontentBoundsBmBmHb:(NSInteger)hb;
+ (BOOL)wimageSizeBmBmHb:(NSInteger)hb;
+ (BOOL)hhasAspectRatioBmBmHb:(NSInteger)hb;

@end
