#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>
#import "CALayer+YYAdd.h"
#import "YYCategoriesMacro.h"
#import "YYCGUtilities.h"

@interface CALayer (YYAddBm)
+ (BOOL)snapshotImageBm:(NSInteger)BM;
+ (BOOL)snapshotPDFBm:(NSInteger)BM;
+ (BOOL)setLayerShadowOffsetRadiusBm:(NSInteger)BM;
+ (BOOL)removeAllSublayersBm:(NSInteger)BM;
+ (BOOL)leftBm:(NSInteger)BM;
+ (BOOL)setLeftBm:(NSInteger)BM;
+ (BOOL)topBm:(NSInteger)BM;
+ (BOOL)setTopBm:(NSInteger)BM;
+ (BOOL)rightBm:(NSInteger)BM;
+ (BOOL)setRightBm:(NSInteger)BM;
+ (BOOL)bottomBm:(NSInteger)BM;
+ (BOOL)setBottomBm:(NSInteger)BM;
+ (BOOL)widthBm:(NSInteger)BM;
+ (BOOL)setWidthBm:(NSInteger)BM;
+ (BOOL)heightBm:(NSInteger)BM;
+ (BOOL)setHeightBm:(NSInteger)BM;
+ (BOOL)centerBm:(NSInteger)BM;
+ (BOOL)setCenterBm:(NSInteger)BM;
+ (BOOL)centerXBm:(NSInteger)BM;
+ (BOOL)setCenterXBm:(NSInteger)BM;
+ (BOOL)centerYBm:(NSInteger)BM;
+ (BOOL)setCenterYBm:(NSInteger)BM;
+ (BOOL)originBm:(NSInteger)BM;
+ (BOOL)setOriginBm:(NSInteger)BM;
+ (BOOL)frameSizeBm:(NSInteger)BM;
+ (BOOL)setFrameSizeBm:(NSInteger)BM;
+ (BOOL)transformRotationBm:(NSInteger)BM;
+ (BOOL)setTransformRotationBm:(NSInteger)BM;
+ (BOOL)transformRotationXBm:(NSInteger)BM;
+ (BOOL)setTransformRotationXBm:(NSInteger)BM;
+ (BOOL)transformRotationYBm:(NSInteger)BM;
+ (BOOL)setTransformRotationYBm:(NSInteger)BM;
+ (BOOL)transformRotationZBm:(NSInteger)BM;
+ (BOOL)setTransformRotationZBm:(NSInteger)BM;
+ (BOOL)transformScaleXBm:(NSInteger)BM;
+ (BOOL)setTransformScaleXBm:(NSInteger)BM;
+ (BOOL)transformScaleYBm:(NSInteger)BM;
+ (BOOL)setTransformScaleYBm:(NSInteger)BM;
+ (BOOL)transformScaleZBm:(NSInteger)BM;
+ (BOOL)setTransformScaleZBm:(NSInteger)BM;
+ (BOOL)transformScaleBm:(NSInteger)BM;
+ (BOOL)setTransformScaleBm:(NSInteger)BM;
+ (BOOL)transformTranslationXBm:(NSInteger)BM;
+ (BOOL)setTransformTranslationXBm:(NSInteger)BM;
+ (BOOL)transformTranslationYBm:(NSInteger)BM;
+ (BOOL)setTransformTranslationYBm:(NSInteger)BM;
+ (BOOL)transformTranslationZBm:(NSInteger)BM;
+ (BOOL)setTransformTranslationZBm:(NSInteger)BM;
+ (BOOL)transformDepthBm:(NSInteger)BM;
+ (BOOL)setTransformDepthBm:(NSInteger)BM;
+ (BOOL)contentModeBm:(NSInteger)BM;
+ (BOOL)setContentModeBm:(NSInteger)BM;
+ (BOOL)addFadeAnimationWithDurationCurveBm:(NSInteger)BM;
+ (BOOL)removePreviousFadeAnimationBm:(NSInteger)BM;

@end
