#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>
#import "CALayer+YYAdd.h"
#import "YYCategoriesMacro.h"
#import "YYCGUtilities.h"
#import "CALayer+YYAddBm.h"

@interface CALayer (YYAddBmBm)
+ (BOOL)snapshotImageBmBm:(NSInteger)BM;
+ (BOOL)snapshotPDFBmBm:(NSInteger)BM;
+ (BOOL)setLayerShadowOffsetRadiusBmBm:(NSInteger)BM;
+ (BOOL)removeAllSublayersBmBm:(NSInteger)BM;
+ (BOOL)leftBmBm:(NSInteger)BM;
+ (BOOL)setLeftBmBm:(NSInteger)BM;
+ (BOOL)topBmBm:(NSInteger)BM;
+ (BOOL)setTopBmBm:(NSInteger)BM;
+ (BOOL)rightBmBm:(NSInteger)BM;
+ (BOOL)setRightBmBm:(NSInteger)BM;
+ (BOOL)bottomBmBm:(NSInteger)BM;
+ (BOOL)setBottomBmBm:(NSInteger)BM;
+ (BOOL)widthBmBm:(NSInteger)BM;
+ (BOOL)setWidthBmBm:(NSInteger)BM;
+ (BOOL)heightBmBm:(NSInteger)BM;
+ (BOOL)setHeightBmBm:(NSInteger)BM;
+ (BOOL)centerBmBm:(NSInteger)BM;
+ (BOOL)setCenterBmBm:(NSInteger)BM;
+ (BOOL)centerXBmBm:(NSInteger)BM;
+ (BOOL)setCenterXBmBm:(NSInteger)BM;
+ (BOOL)centerYBmBm:(NSInteger)BM;
+ (BOOL)setCenterYBmBm:(NSInteger)BM;
+ (BOOL)originBmBm:(NSInteger)BM;
+ (BOOL)setOriginBmBm:(NSInteger)BM;
+ (BOOL)frameSizeBmBm:(NSInteger)BM;
+ (BOOL)setFrameSizeBmBm:(NSInteger)BM;
+ (BOOL)transformRotationBmBm:(NSInteger)BM;
+ (BOOL)setTransformRotationBmBm:(NSInteger)BM;
+ (BOOL)transformRotationXBmBm:(NSInteger)BM;
+ (BOOL)setTransformRotationXBmBm:(NSInteger)BM;
+ (BOOL)transformRotationYBmBm:(NSInteger)BM;
+ (BOOL)setTransformRotationYBmBm:(NSInteger)BM;
+ (BOOL)transformRotationZBmBm:(NSInteger)BM;
+ (BOOL)setTransformRotationZBmBm:(NSInteger)BM;
+ (BOOL)transformScaleXBmBm:(NSInteger)BM;
+ (BOOL)setTransformScaleXBmBm:(NSInteger)BM;
+ (BOOL)transformScaleYBmBm:(NSInteger)BM;
+ (BOOL)setTransformScaleYBmBm:(NSInteger)BM;
+ (BOOL)transformScaleZBmBm:(NSInteger)BM;
+ (BOOL)setTransformScaleZBmBm:(NSInteger)BM;
+ (BOOL)transformScaleBmBm:(NSInteger)BM;
+ (BOOL)setTransformScaleBmBm:(NSInteger)BM;
+ (BOOL)transformTranslationXBmBm:(NSInteger)BM;
+ (BOOL)setTransformTranslationXBmBm:(NSInteger)BM;
+ (BOOL)transformTranslationYBmBm:(NSInteger)BM;
+ (BOOL)setTransformTranslationYBmBm:(NSInteger)BM;
+ (BOOL)transformTranslationZBmBm:(NSInteger)BM;
+ (BOOL)setTransformTranslationZBmBm:(NSInteger)BM;
+ (BOOL)transformDepthBmBm:(NSInteger)BM;
+ (BOOL)setTransformDepthBmBm:(NSInteger)BM;
+ (BOOL)contentModeBmBm:(NSInteger)BM;
+ (BOOL)setContentModeBmBm:(NSInteger)BM;
+ (BOOL)addFadeAnimationWithDurationCurveBmBm:(NSInteger)BM;
+ (BOOL)removePreviousFadeAnimationBmBm:(NSInteger)BM;

@end
