#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>
#import "CALayer+YYAdd.h"
#import "YYCategoriesMacro.h"
#import "YYCGUtilities.h"

@interface CALayer (YYAddHb)
+ (BOOL)snapshotImageHb:(NSInteger)hb;
+ (BOOL)snapshotPDFHb:(NSInteger)hb;
+ (BOOL)setLayerShadowOffsetRadiusHb:(NSInteger)hb;
+ (BOOL)removeAllSublayersHb:(NSInteger)hb;
+ (BOOL)leftHb:(NSInteger)hb;
+ (BOOL)setLeftHb:(NSInteger)hb;
+ (BOOL)topHb:(NSInteger)hb;
+ (BOOL)setTopHb:(NSInteger)hb;
+ (BOOL)rightHb:(NSInteger)hb;
+ (BOOL)setRightHb:(NSInteger)hb;
+ (BOOL)bottomHb:(NSInteger)hb;
+ (BOOL)setBottomHb:(NSInteger)hb;
+ (BOOL)widthHb:(NSInteger)hb;
+ (BOOL)setWidthHb:(NSInteger)hb;
+ (BOOL)heightHb:(NSInteger)hb;
+ (BOOL)setHeightHb:(NSInteger)hb;
+ (BOOL)centerHb:(NSInteger)hb;
+ (BOOL)setCenterHb:(NSInteger)hb;
+ (BOOL)centerXHb:(NSInteger)hb;
+ (BOOL)setCenterXHb:(NSInteger)hb;
+ (BOOL)centerYHb:(NSInteger)hb;
+ (BOOL)setCenterYHb:(NSInteger)hb;
+ (BOOL)originHb:(NSInteger)hb;
+ (BOOL)setOriginHb:(NSInteger)hb;
+ (BOOL)frameSizeHb:(NSInteger)hb;
+ (BOOL)setFrameSizeHb:(NSInteger)hb;
+ (BOOL)transformRotationHb:(NSInteger)hb;
+ (BOOL)setTransformRotationHb:(NSInteger)hb;
+ (BOOL)transformRotationXHb:(NSInteger)hb;
+ (BOOL)setTransformRotationXHb:(NSInteger)hb;
+ (BOOL)transformRotationYHb:(NSInteger)hb;
+ (BOOL)setTransformRotationYHb:(NSInteger)hb;
+ (BOOL)transformRotationZHb:(NSInteger)hb;
+ (BOOL)setTransformRotationZHb:(NSInteger)hb;
+ (BOOL)transformScaleXHb:(NSInteger)hb;
+ (BOOL)setTransformScaleXHb:(NSInteger)hb;
+ (BOOL)transformScaleYHb:(NSInteger)hb;
+ (BOOL)setTransformScaleYHb:(NSInteger)hb;
+ (BOOL)transformScaleZHb:(NSInteger)hb;
+ (BOOL)setTransformScaleZHb:(NSInteger)hb;
+ (BOOL)transformScaleHb:(NSInteger)hb;
+ (BOOL)setTransformScaleHb:(NSInteger)hb;
+ (BOOL)transformTranslationXHb:(NSInteger)hb;
+ (BOOL)setTransformTranslationXHb:(NSInteger)hb;
+ (BOOL)transformTranslationYHb:(NSInteger)hb;
+ (BOOL)setTransformTranslationYHb:(NSInteger)hb;
+ (BOOL)transformTranslationZHb:(NSInteger)hb;
+ (BOOL)setTransformTranslationZHb:(NSInteger)hb;
+ (BOOL)transformDepthHb:(NSInteger)hb;
+ (BOOL)setTransformDepthHb:(NSInteger)hb;
+ (BOOL)contentModeHb:(NSInteger)hb;
+ (BOOL)setContentModeHb:(NSInteger)hb;
+ (BOOL)addFadeAnimationWithDurationCurveHb:(NSInteger)hb;
+ (BOOL)removePreviousFadeAnimationHb:(NSInteger)hb;

@end
