#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>
#import "CALayer+YYAdd.h"
#import "YYCategoriesMacro.h"
#import "YYCGUtilities.h"
#import "CALayer+YYAddHb.h"

@interface CALayer (YYAddHbHb)
+ (BOOL)snapshotImageHbHb:(NSInteger)hb;
+ (BOOL)snapshotPDFHbHb:(NSInteger)hb;
+ (BOOL)setLayerShadowOffsetRadiusHbHb:(NSInteger)hb;
+ (BOOL)removeAllSublayersHbHb:(NSInteger)hb;
+ (BOOL)leftHbHb:(NSInteger)hb;
+ (BOOL)setLeftHbHb:(NSInteger)hb;
+ (BOOL)topHbHb:(NSInteger)hb;
+ (BOOL)setTopHbHb:(NSInteger)hb;
+ (BOOL)rightHbHb:(NSInteger)hb;
+ (BOOL)setRightHbHb:(NSInteger)hb;
+ (BOOL)bottomHbHb:(NSInteger)hb;
+ (BOOL)setBottomHbHb:(NSInteger)hb;
+ (BOOL)widthHbHb:(NSInteger)hb;
+ (BOOL)setWidthHbHb:(NSInteger)hb;
+ (BOOL)heightHbHb:(NSInteger)hb;
+ (BOOL)setHeightHbHb:(NSInteger)hb;
+ (BOOL)centerHbHb:(NSInteger)hb;
+ (BOOL)setCenterHbHb:(NSInteger)hb;
+ (BOOL)centerXHbHb:(NSInteger)hb;
+ (BOOL)setCenterXHbHb:(NSInteger)hb;
+ (BOOL)centerYHbHb:(NSInteger)hb;
+ (BOOL)setCenterYHbHb:(NSInteger)hb;
+ (BOOL)originHbHb:(NSInteger)hb;
+ (BOOL)setOriginHbHb:(NSInteger)hb;
+ (BOOL)frameSizeHbHb:(NSInteger)hb;
+ (BOOL)setFrameSizeHbHb:(NSInteger)hb;
+ (BOOL)transformRotationHbHb:(NSInteger)hb;
+ (BOOL)setTransformRotationHbHb:(NSInteger)hb;
+ (BOOL)transformRotationXHbHb:(NSInteger)hb;
+ (BOOL)setTransformRotationXHbHb:(NSInteger)hb;
+ (BOOL)transformRotationYHbHb:(NSInteger)hb;
+ (BOOL)setTransformRotationYHbHb:(NSInteger)hb;
+ (BOOL)transformRotationZHbHb:(NSInteger)hb;
+ (BOOL)setTransformRotationZHbHb:(NSInteger)hb;
+ (BOOL)transformScaleXHbHb:(NSInteger)hb;
+ (BOOL)setTransformScaleXHbHb:(NSInteger)hb;
+ (BOOL)transformScaleYHbHb:(NSInteger)hb;
+ (BOOL)setTransformScaleYHbHb:(NSInteger)hb;
+ (BOOL)transformScaleZHbHb:(NSInteger)hb;
+ (BOOL)setTransformScaleZHbHb:(NSInteger)hb;
+ (BOOL)transformScaleHbHb:(NSInteger)hb;
+ (BOOL)setTransformScaleHbHb:(NSInteger)hb;
+ (BOOL)transformTranslationXHbHb:(NSInteger)hb;
+ (BOOL)setTransformTranslationXHbHb:(NSInteger)hb;
+ (BOOL)transformTranslationYHbHb:(NSInteger)hb;
+ (BOOL)setTransformTranslationYHbHb:(NSInteger)hb;
+ (BOOL)transformTranslationZHbHb:(NSInteger)hb;
+ (BOOL)setTransformTranslationZHbHb:(NSInteger)hb;
+ (BOOL)transformDepthHbHb:(NSInteger)hb;
+ (BOOL)setTransformDepthHbHb:(NSInteger)hb;
+ (BOOL)contentModeHbHb:(NSInteger)hb;
+ (BOOL)setContentModeHbHb:(NSInteger)hb;
+ (BOOL)addFadeAnimationWithDurationCurveHbHb:(NSInteger)hb;
+ (BOOL)removePreviousFadeAnimationHbHb:(NSInteger)hb;

@end
