#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>
#import "CALayer+YYAdd.h"
#import "YYCategoriesMacro.h"
#import "YYCGUtilities.h"
#import "CALayer+YYAddBm.h"
#import "CALayer+YYAddBmBm.h"

@interface CALayer (YYAddBmBmBm)
+ (BOOL)snapshotImageBmBmBm:(NSInteger)BM;
+ (BOOL)snapshotPDFBmBmBm:(NSInteger)BM;
+ (BOOL)setLayerShadowOffsetRadiusBmBmBm:(NSInteger)BM;
+ (BOOL)removeAllSublayersBmBmBm:(NSInteger)BM;
+ (BOOL)leftBmBmBm:(NSInteger)BM;
+ (BOOL)setLeftBmBmBm:(NSInteger)BM;
+ (BOOL)topBmBmBm:(NSInteger)BM;
+ (BOOL)setTopBmBmBm:(NSInteger)BM;
+ (BOOL)rightBmBmBm:(NSInteger)BM;
+ (BOOL)setRightBmBmBm:(NSInteger)BM;
+ (BOOL)bottomBmBmBm:(NSInteger)BM;
+ (BOOL)setBottomBmBmBm:(NSInteger)BM;
+ (BOOL)widthBmBmBm:(NSInteger)BM;
+ (BOOL)setWidthBmBmBm:(NSInteger)BM;
+ (BOOL)heightBmBmBm:(NSInteger)BM;
+ (BOOL)setHeightBmBmBm:(NSInteger)BM;
+ (BOOL)centerBmBmBm:(NSInteger)BM;
+ (BOOL)setCenterBmBmBm:(NSInteger)BM;
+ (BOOL)centerXBmBmBm:(NSInteger)BM;
+ (BOOL)setCenterXBmBmBm:(NSInteger)BM;
+ (BOOL)centerYBmBmBm:(NSInteger)BM;
+ (BOOL)setCenterYBmBmBm:(NSInteger)BM;
+ (BOOL)originBmBmBm:(NSInteger)BM;
+ (BOOL)setOriginBmBmBm:(NSInteger)BM;
+ (BOOL)frameSizeBmBmBm:(NSInteger)BM;
+ (BOOL)setFrameSizeBmBmBm:(NSInteger)BM;
+ (BOOL)transformRotationBmBmBm:(NSInteger)BM;
+ (BOOL)setTransformRotationBmBmBm:(NSInteger)BM;
+ (BOOL)transformRotationXBmBmBm:(NSInteger)BM;
+ (BOOL)setTransformRotationXBmBmBm:(NSInteger)BM;
+ (BOOL)transformRotationYBmBmBm:(NSInteger)BM;
+ (BOOL)setTransformRotationYBmBmBm:(NSInteger)BM;
+ (BOOL)transformRotationZBmBmBm:(NSInteger)BM;
+ (BOOL)setTransformRotationZBmBmBm:(NSInteger)BM;
+ (BOOL)transformScaleXBmBmBm:(NSInteger)BM;
+ (BOOL)setTransformScaleXBmBmBm:(NSInteger)BM;
+ (BOOL)transformScaleYBmBmBm:(NSInteger)BM;
+ (BOOL)setTransformScaleYBmBmBm:(NSInteger)BM;
+ (BOOL)transformScaleZBmBmBm:(NSInteger)BM;
+ (BOOL)setTransformScaleZBmBmBm:(NSInteger)BM;
+ (BOOL)transformScaleBmBmBm:(NSInteger)BM;
+ (BOOL)setTransformScaleBmBmBm:(NSInteger)BM;
+ (BOOL)transformTranslationXBmBmBm:(NSInteger)BM;
+ (BOOL)setTransformTranslationXBmBmBm:(NSInteger)BM;
+ (BOOL)transformTranslationYBmBmBm:(NSInteger)BM;
+ (BOOL)setTransformTranslationYBmBmBm:(NSInteger)BM;
+ (BOOL)transformTranslationZBmBmBm:(NSInteger)BM;
+ (BOOL)setTransformTranslationZBmBmBm:(NSInteger)BM;
+ (BOOL)transformDepthBmBmBm:(NSInteger)BM;
+ (BOOL)setTransformDepthBmBmBm:(NSInteger)BM;
+ (BOOL)contentModeBmBmBm:(NSInteger)BM;
+ (BOOL)setContentModeBmBmBm:(NSInteger)BM;
+ (BOOL)addFadeAnimationWithDurationCurveBmBmBm:(NSInteger)BM;
+ (BOOL)removePreviousFadeAnimationBmBmBm:(NSInteger)BM;

@end
