#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>
#import "CALayer+YYAdd.h"
#import "YYCategoriesMacro.h"
#import "YYCGUtilities.h"

@interface CALayer (YYAdd-Deletecomments)
+ (BOOL)snapshotImage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)snapshotPDF-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setLayerShadowOffsetRadius-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)removeAllSublayers-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)left-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setLeft-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)top-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTop-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)right-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setRight-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bottom-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setBottom-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)width-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setWidth-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)height-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setHeight-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)center-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCenter-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)centerX-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCenterX-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)centerY-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCenterY-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)origin-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setOrigin-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)frameSize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setFrameSize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)transformRotation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTransformRotation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)transformRotationX-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTransformRotationX-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)transformRotationY-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTransformRotationY-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)transformRotationZ-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTransformRotationZ-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)transformScaleX-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTransformScaleX-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)transformScaleY-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTransformScaleY-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)transformScaleZ-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTransformScaleZ-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)transformScale-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTransformScale-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)transformTranslationX-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTransformTranslationX-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)transformTranslationY-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTransformTranslationY-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)transformTranslationZ-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTransformTranslationZ-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)transformDepth-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTransformDepth-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)contentMode-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setContentMode-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)addFadeAnimationWithDurationCurve-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)removePreviousFadeAnimation-Deletecomments:(NSInteger)-deleteComments;

@end
