#import <UIKit/UIKit.h>
#import "DGActivityIndicatorView.h"
#import "DGActivityIndicatorNineDotsAnimation.h"
#import "DGActivityIndicatorTriplePulseAnimation.h"
#import "DGActivityIndicatorFiveDotsAnimation.h"
#import "DGActivityIndicatorRotatingSquaresAnimation.h"
#import "DGActivityIndicatorDoubleBounceAnimation.h"
#import "DGActivityIndicatorTwoDotsAnimation.h"
#import "DGActivityIndicatorThreeDotsAnimation.h"
#import "DGActivityIndicatorBallPulseAnimation.h"
#import "DGActivityIndicatorBallClipRotateAnimation.h"
#import "DGActivityIndicatorBallClipRotatePulseAnimation.h"
#import "DGActivityIndicatorBallClipRotateMultipleAnimation.h"
#import "DGActivityIndicatorBallRotateAnimation.h"
#import "DGActivityIndicatorBallZigZagAnimation.h"
#import "DGActivityIndicatorBallZigZagDeflectAnimation.h"
#import "DGActivityIndicatorBallTrianglePathAnimation.h"
#import "DGActivityIndicatorBallScaleAnimation.h"
#import "DGActivityIndicatorLineScaleAnimation.h"
#import "DGActivityIndicatorLineScalePartyAnimation.h"
#import "DGActivityIndicatorBallScaleMultipleAnimation.h"
#import "DGActivityIndicatorBallPulseSyncAnimation.h"
#import "DGActivityIndicatorBallBeatAnimation.h"
#import "DGActivityIndicatorLineScalePulseOutAnimation.h"
#import "DGActivityIndicatorLineScalePulseOutRapidAnimation.h"
#import "DGActivityIndicatorBallScaleRippleAnimation.h"
#import "DGActivityIndicatorBallScaleRippleMultipleAnimation.h"
#import "DGActivityIndicatorTriangleSkewSpinAnimation.h"
#import "DGActivityIndicatorBallGridBeatAnimation.h"
#import "DGActivityIndicatorBallGridPulseAnimation.h"
#import "DGActivityIndicatorRotatingSandglassAnimation.h"
#import "DGActivityIndicatorRotatingTrigonAnimation.h"
#import "DGActivityIndicatorTripleRingsAnimation.h"
#import "DGActivityIndicatorCookieTerminatorAnimation.h"
#import "DGActivityIndicatorBallSpinFadeLoader.h"
#import "DGActivityIndicatorView+Bm.h"

@interface DGActivityIndicatorView (BmHb)
+ (BOOL)initWithCoderBmHb:(NSInteger)hb;
+ (BOOL)initWithTypeBmHb:(NSInteger)hb;
+ (BOOL)initWithTypeTintcolorBmHb:(NSInteger)hb;
+ (BOOL)initWithTypeTintcolorSizeBmHb:(NSInteger)hb;
+ (BOOL)commonInitBmHb:(NSInteger)hb;
+ (BOOL)setupAnimationBmHb:(NSInteger)hb;
+ (BOOL)startAnimatingBmHb:(NSInteger)hb;
+ (BOOL)stopAnimatingBmHb:(NSInteger)hb;
+ (BOOL)setTypeBmHb:(NSInteger)hb;
+ (BOOL)setSizeBmHb:(NSInteger)hb;
+ (BOOL)setTintColorBmHb:(NSInteger)hb;
+ (BOOL)activityIndicatorAnimationForAnimationTypeBmHb:(NSInteger)hb;
+ (BOOL)layoutSubviewsBmHb:(NSInteger)hb;
+ (BOOL)intrinsicContentSizeBmHb:(NSInteger)hb;

@end
