#import <UIKit/UIKit.h>
#import "DGActivityIndicatorView.h"
#import "DGActivityIndicatorNineDotsAnimation.h"
#import "DGActivityIndicatorTriplePulseAnimation.h"
#import "DGActivityIndicatorFiveDotsAnimation.h"
#import "DGActivityIndicatorRotatingSquaresAnimation.h"
#import "DGActivityIndicatorDoubleBounceAnimation.h"
#import "DGActivityIndicatorTwoDotsAnimation.h"
#import "DGActivityIndicatorThreeDotsAnimation.h"
#import "DGActivityIndicatorBallPulseAnimation.h"
#import "DGActivityIndicatorBallClipRotateAnimation.h"
#import "DGActivityIndicatorBallClipRotatePulseAnimation.h"
#import "DGActivityIndicatorBallClipRotateMultipleAnimation.h"
#import "DGActivityIndicatorBallRotateAnimation.h"
#import "DGActivityIndicatorBallZigZagAnimation.h"
#import "DGActivityIndicatorBallZigZagDeflectAnimation.h"
#import "DGActivityIndicatorBallTrianglePathAnimation.h"
#import "DGActivityIndicatorBallScaleAnimation.h"
#import "DGActivityIndicatorLineScaleAnimation.h"
#import "DGActivityIndicatorLineScalePartyAnimation.h"
#import "DGActivityIndicatorBallScaleMultipleAnimation.h"
#import "DGActivityIndicatorBallPulseSyncAnimation.h"
#import "DGActivityIndicatorBallBeatAnimation.h"
#import "DGActivityIndicatorLineScalePulseOutAnimation.h"
#import "DGActivityIndicatorLineScalePulseOutRapidAnimation.h"
#import "DGActivityIndicatorBallScaleRippleAnimation.h"
#import "DGActivityIndicatorBallScaleRippleMultipleAnimation.h"
#import "DGActivityIndicatorTriangleSkewSpinAnimation.h"
#import "DGActivityIndicatorBallGridBeatAnimation.h"
#import "DGActivityIndicatorBallGridPulseAnimation.h"
#import "DGActivityIndicatorRotatingSandglassAnimation.h"
#import "DGActivityIndicatorRotatingTrigonAnimation.h"
#import "DGActivityIndicatorTripleRingsAnimation.h"
#import "DGActivityIndicatorCookieTerminatorAnimation.h"
#import "DGActivityIndicatorBallSpinFadeLoader.h"
#import "DGActivityIndicatorView+Bm.h"
#import "DGActivityIndicatorView+BmBm.h"

@interface DGActivityIndicatorView (BmBmHb)
+ (BOOL)initWithCoderBmBmHb:(NSInteger)hb;
+ (BOOL)initWithTypeBmBmHb:(NSInteger)hb;
+ (BOOL)initWithTypeTintcolorBmBmHb:(NSInteger)hb;
+ (BOOL)initWithTypeTintcolorSizeBmBmHb:(NSInteger)hb;
+ (BOOL)commonInitBmBmHb:(NSInteger)hb;
+ (BOOL)setupAnimationBmBmHb:(NSInteger)hb;
+ (BOOL)startAnimatingBmBmHb:(NSInteger)hb;
+ (BOOL)stopAnimatingBmBmHb:(NSInteger)hb;
+ (BOOL)setTypeBmBmHb:(NSInteger)hb;
+ (BOOL)setSizeBmBmHb:(NSInteger)hb;
+ (BOOL)setTintColorBmBmHb:(NSInteger)hb;
+ (BOOL)activityIndicatorAnimationForAnimationTypeBmBmHb:(NSInteger)hb;
+ (BOOL)layoutSubviewsBmBmHb:(NSInteger)hb;
+ (BOOL)intrinsicContentSizeBmBmHb:(NSInteger)hb;

@end
