#import <UIKit/UIKit.h>
#import "DGActivityIndicatorView.h"
#import "DGActivityIndicatorNineDotsAnimation.h"
#import "DGActivityIndicatorTriplePulseAnimation.h"
#import "DGActivityIndicatorFiveDotsAnimation.h"
#import "DGActivityIndicatorRotatingSquaresAnimation.h"
#import "DGActivityIndicatorDoubleBounceAnimation.h"
#import "DGActivityIndicatorTwoDotsAnimation.h"
#import "DGActivityIndicatorThreeDotsAnimation.h"
#import "DGActivityIndicatorBallPulseAnimation.h"
#import "DGActivityIndicatorBallClipRotateAnimation.h"
#import "DGActivityIndicatorBallClipRotatePulseAnimation.h"
#import "DGActivityIndicatorBallClipRotateMultipleAnimation.h"
#import "DGActivityIndicatorBallRotateAnimation.h"
#import "DGActivityIndicatorBallZigZagAnimation.h"
#import "DGActivityIndicatorBallZigZagDeflectAnimation.h"
#import "DGActivityIndicatorBallTrianglePathAnimation.h"
#import "DGActivityIndicatorBallScaleAnimation.h"
#import "DGActivityIndicatorLineScaleAnimation.h"
#import "DGActivityIndicatorLineScalePartyAnimation.h"
#import "DGActivityIndicatorBallScaleMultipleAnimation.h"
#import "DGActivityIndicatorBallPulseSyncAnimation.h"
#import "DGActivityIndicatorBallBeatAnimation.h"
#import "DGActivityIndicatorLineScalePulseOutAnimation.h"
#import "DGActivityIndicatorLineScalePulseOutRapidAnimation.h"
#import "DGActivityIndicatorBallScaleRippleAnimation.h"
#import "DGActivityIndicatorBallScaleRippleMultipleAnimation.h"
#import "DGActivityIndicatorTriangleSkewSpinAnimation.h"
#import "DGActivityIndicatorBallGridBeatAnimation.h"
#import "DGActivityIndicatorBallGridPulseAnimation.h"
#import "DGActivityIndicatorRotatingSandglassAnimation.h"
#import "DGActivityIndicatorRotatingTrigonAnimation.h"
#import "DGActivityIndicatorTripleRingsAnimation.h"
#import "DGActivityIndicatorCookieTerminatorAnimation.h"
#import "DGActivityIndicatorBallSpinFadeLoader.h"

@interface DGActivityIndicatorView (-Deletecomments)
+ (BOOL)initWithCoder-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithType-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithTypeTintcolor-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithTypeTintcolorSize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)commonInit-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setupAnimation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)startAnimating-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stopAnimating-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setType-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setSize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTintColor-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)activityIndicatorAnimationForAnimationType-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)layoutSubviews-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)intrinsicContentSize-Deletecomments:(NSInteger)-deleteComments;

@end
