#import "GPUImageOutput.h"
#import "GPUImageFilter.h"
#import "GPUImagePicture.h"
#import <AVFoundation/AVFoundation.h>
#import "GPUImageFilter+Bm.h"
#import "GPUImageFilter+BmBm.h"
#import "GPUImageFilter+BmBmBm.h"

@interface GPUImageFilter (BmBmBm-Deletecomments)
+ (BOOL)initWithVertexShaderFromStringFragmentshaderfromstringBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithFragmentShaderFromStringBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithFragmentShaderFromFileBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initializeAttributesBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setupFilterForSizeBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)deallocBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)useNextFrameForImageCaptureBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)newCGImageFromCurrentlyProcessedOutputBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sizeOfFBOBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)textureCoordinatesForRotationBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)renderToTextureWithVerticesTexturecoordinatesBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)informTargetsAboutNewFrameAtTimeBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)outputFrameSizeBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setBackgroundColorRedGreenBlueAlphaBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setIntegerForuniformnameBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setFloatForuniformnameBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setSizeForuniformnameBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setPointForuniformnameBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setFloatVec3ForuniformnameBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setFloatVec4ForuniformBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setFloatArrayLengthForuniformBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setMatrix3fForuniformProgramBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setMatrix4fForuniformProgramBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setFloatForuniformProgramBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setPointForuniformProgramBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setSizeForuniformProgramBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setVec3ForuniformProgramBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setVec4ForuniformProgramBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setFloatArrayLengthForuniformProgramBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setIntegerForuniformProgramBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAndExecuteUniformStateCallbackAtIndexForprogramToblockBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setUniformsForProgramAtIndexBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)newFrameReadyAtTimeAtindexBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)nextAvailableTextureIndexBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setInputFramebufferAtindexBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rotatedSizeForindexBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rotatedPointForrotationBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setInputSizeAtindexBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setInputRotationAtindexBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)forceProcessingAtSizeBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)forceProcessingAtSizeRespectingAspectRatioBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)maximumOutputSizeBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)endProcessingBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)wantsMonochromeInputBmBmBm-Deletecomments:(NSInteger)-deleteComments;

@end
