#import "IQKeyboardManagerConstants.h"
#import "IQUIView+IQKeyboardToolbar.h"
#import "IQPreviousNextView.h"
#import "IQUIViewController+Additions.h"
#import "IQKeyboardReturnKeyHandler.h"
#import "IQTextView.h"
#import "IQToolbar.h"
#import "IQUIScrollView+Additions.h"
#import "IQUITextFieldView+Additions.h"
#import "IQBarButtonItem.h"
#import "IQTitleBarButtonItem.h"
#import "IQUIView+Hierarchy.h"
#import <CoreGraphics/CGBase.h>
#import <Foundation/NSObject.h>
#import <Foundation/NSObjCRuntime.h>
#import <Foundation/NSSet.h>
#import <UIKit/UITextInputTraits.h>
#import "IQKeyboardManager.h"
#import "IQUIView+Hierarchy.h"
#import "IQUIView+IQKeyboardToolbar.h"
#import "IQNSArray+Sort.h"
#import "IQKeyboardManagerConstantsInternal.h"
#import "IQUIScrollView+Additions.h"
#import "IQUITextFieldView+Additions.h"
#import "IQUIViewController+Additions.h"
#import "IQPreviousNextView.h"
#import <QuartzCore/CABase.h>
#import <objc/runtime.h>
#import <UIKit/UIAlertController.h>
#import <UIKit/UISearchBar.h>
#import <UIKit/UIScreen.h>
#import <UIKit/UINavigationBar.h>
#import <UIKit/UITapGestureRecognizer.h>
#import <UIKit/UITextField.h>
#import <UIKit/UITextView.h>
#import <UIKit/UITableViewController.h>
#import <UIKit/UICollectionViewController.h>
#import <UIKit/UICollectionViewCell.h>
#import <UIKit/UICollectionViewLayout.h>
#import <UIKit/UINavigationController.h>
#import <UIKit/UITouch.h>
#import <UIKit/UIWindow.h>
#import <UIKit/UIStackView.h>
#import <UIKit/NSLayoutConstraint.h>
#import <UIKit/UIStackView.h>
#import <UIKit/UIAccessibility.h>
#import <UIKit/UIWindowScene.h>
#import <UIKit/UIStatusBarManager.h>

@interface IQKeyboardManager (Bm)
+ (BOOL)loadBm:(NSInteger)BM;
+ (BOOL)initBm:(NSInteger)BM;
+ (BOOL)sharedManagerBm:(NSInteger)BM;
+ (BOOL)deallocBm:(NSInteger)BM;
+ (BOOL)setEnableBm:(NSInteger)BM;
+ (BOOL)privateIsEnabledBm:(NSInteger)BM;
+ (BOOL)setKeyboardDistanceFromTextFieldBm:(NSInteger)BM;
+ (BOOL)setShouldResignOnTouchOutsideBm:(NSInteger)BM;
+ (BOOL)privateShouldResignOnTouchOutsideBm:(NSInteger)BM;
+ (BOOL)setMovedDistanceBm:(NSInteger)BM;
+ (BOOL)setEnableAutoToolbarBm:(NSInteger)BM;
+ (BOOL)privateIsEnableAutoToolbarBm:(NSInteger)BM;
+ (BOOL)keyWindowBm:(NSInteger)BM;
+ (BOOL)optimizedAdjustPositionBm:(NSInteger)BM;
+ (BOOL)adjustPositionBm:(NSInteger)BM;
+ (BOOL)restorePositionBm:(NSInteger)BM;
+ (BOOL)reloadLayoutIfNeededBm:(NSInteger)BM;
+ (BOOL)keyboardWillShowBm:(NSInteger)BM;
+ (BOOL)keyboardDidShowBm:(NSInteger)BM;
+ (BOOL)keyboardWillHideBm:(NSInteger)BM;
+ (BOOL)keyboardDidHideBm:(NSInteger)BM;
+ (BOOL)textFieldViewDidBeginEditingBm:(NSInteger)BM;
+ (BOOL)textFieldViewDidEndEditingBm:(NSInteger)BM;
+ (BOOL)willChangeStatusBarOrientationBm:(NSInteger)BM;
+ (BOOL)tapRecognizedBm:(NSInteger)BM;
+ (BOOL)gestureRecognizerShouldrecognizesimultaneouslywithgesturerecognizerBm:(NSInteger)BM;
+ (BOOL)gestureRecognizerShouldreceivetouchBm:(NSInteger)BM;
+ (BOOL)resignFirstResponderBm:(NSInteger)BM;
+ (BOOL)canGoPreviousBm:(NSInteger)BM;
+ (BOOL)canGoNextBm:(NSInteger)BM;
+ (BOOL)goPreviousBm:(NSInteger)BM;
+ (BOOL)goNextBm:(NSInteger)BM;
+ (BOOL)responderViewsBm:(NSInteger)BM;
+ (BOOL)addToolbarIfRequiredBm:(NSInteger)BM;
+ (BOOL)removeToolbarIfRequiredBm:(NSInteger)BM;
+ (BOOL)reloadInputViewsBm:(NSInteger)BM;
+ (BOOL)previousActionBm:(NSInteger)BM;
+ (BOOL)nextActionBm:(NSInteger)BM;
+ (BOOL)doneActionBm:(NSInteger)BM;
+ (BOOL)registerTextFieldViewClassDidbegineditingnotificationnameDidendeditingnotificationnameBm:(NSInteger)BM;
+ (BOOL)unregisterTextFieldViewClassDidbegineditingnotificationnameDidendeditingnotificationnameBm:(NSInteger)BM;
+ (BOOL)registerAllNotificationsBm:(NSInteger)BM;
+ (BOOL)unregisterAllNotificationsBm:(NSInteger)BM;
+ (BOOL)showLogBm:(NSInteger)BM;
+ (BOOL)showLogIndentationBm:(NSInteger)BM;

@end
