#import "IQKeyboardManagerConstants.h"
#import "IQUIView+IQKeyboardToolbar.h"
#import "IQPreviousNextView.h"
#import "IQUIViewController+Additions.h"
#import "IQKeyboardReturnKeyHandler.h"
#import "IQTextView.h"
#import "IQToolbar.h"
#import "IQUIScrollView+Additions.h"
#import "IQUITextFieldView+Additions.h"
#import "IQBarButtonItem.h"
#import "IQTitleBarButtonItem.h"
#import "IQUIView+Hierarchy.h"
#import <CoreGraphics/CGBase.h>
#import <Foundation/NSObject.h>
#import <Foundation/NSObjCRuntime.h>
#import <Foundation/NSSet.h>
#import <UIKit/UITextInputTraits.h>
#import "IQKeyboardManager.h"
#import "IQUIView+Hierarchy.h"
#import "IQUIView+IQKeyboardToolbar.h"
#import "IQNSArray+Sort.h"
#import "IQKeyboardManagerConstantsInternal.h"
#import "IQUIScrollView+Additions.h"
#import "IQUITextFieldView+Additions.h"
#import "IQUIViewController+Additions.h"
#import "IQPreviousNextView.h"
#import <QuartzCore/CABase.h>
#import <objc/runtime.h>
#import <UIKit/UIAlertController.h>
#import <UIKit/UISearchBar.h>
#import <UIKit/UIScreen.h>
#import <UIKit/UINavigationBar.h>
#import <UIKit/UITapGestureRecognizer.h>
#import <UIKit/UITextField.h>
#import <UIKit/UITextView.h>
#import <UIKit/UITableViewController.h>
#import <UIKit/UICollectionViewController.h>
#import <UIKit/UICollectionViewCell.h>
#import <UIKit/UICollectionViewLayout.h>
#import <UIKit/UINavigationController.h>
#import <UIKit/UITouch.h>
#import <UIKit/UIWindow.h>
#import <UIKit/UIStackView.h>
#import <UIKit/NSLayoutConstraint.h>
#import <UIKit/UIStackView.h>
#import <UIKit/UIAccessibility.h>
#import <UIKit/UIWindowScene.h>
#import <UIKit/UIStatusBarManager.h>

@interface IQKeyboardManager (Hb)
+ (BOOL)loadHb:(NSInteger)hb;
+ (BOOL)initHb:(NSInteger)hb;
+ (BOOL)sharedManagerHb:(NSInteger)hb;
+ (BOOL)deallocHb:(NSInteger)hb;
+ (BOOL)setEnableHb:(NSInteger)hb;
+ (BOOL)privateIsEnabledHb:(NSInteger)hb;
+ (BOOL)setKeyboardDistanceFromTextFieldHb:(NSInteger)hb;
+ (BOOL)setShouldResignOnTouchOutsideHb:(NSInteger)hb;
+ (BOOL)privateShouldResignOnTouchOutsideHb:(NSInteger)hb;
+ (BOOL)setMovedDistanceHb:(NSInteger)hb;
+ (BOOL)setEnableAutoToolbarHb:(NSInteger)hb;
+ (BOOL)privateIsEnableAutoToolbarHb:(NSInteger)hb;
+ (BOOL)keyWindowHb:(NSInteger)hb;
+ (BOOL)optimizedAdjustPositionHb:(NSInteger)hb;
+ (BOOL)adjustPositionHb:(NSInteger)hb;
+ (BOOL)restorePositionHb:(NSInteger)hb;
+ (BOOL)reloadLayoutIfNeededHb:(NSInteger)hb;
+ (BOOL)keyboardWillShowHb:(NSInteger)hb;
+ (BOOL)keyboardDidShowHb:(NSInteger)hb;
+ (BOOL)keyboardWillHideHb:(NSInteger)hb;
+ (BOOL)keyboardDidHideHb:(NSInteger)hb;
+ (BOOL)textFieldViewDidBeginEditingHb:(NSInteger)hb;
+ (BOOL)textFieldViewDidEndEditingHb:(NSInteger)hb;
+ (BOOL)willChangeStatusBarOrientationHb:(NSInteger)hb;
+ (BOOL)tapRecognizedHb:(NSInteger)hb;
+ (BOOL)gestureRecognizerShouldrecognizesimultaneouslywithgesturerecognizerHb:(NSInteger)hb;
+ (BOOL)gestureRecognizerShouldreceivetouchHb:(NSInteger)hb;
+ (BOOL)resignFirstResponderHb:(NSInteger)hb;
+ (BOOL)canGoPreviousHb:(NSInteger)hb;
+ (BOOL)canGoNextHb:(NSInteger)hb;
+ (BOOL)goPreviousHb:(NSInteger)hb;
+ (BOOL)goNextHb:(NSInteger)hb;
+ (BOOL)responderViewsHb:(NSInteger)hb;
+ (BOOL)addToolbarIfRequiredHb:(NSInteger)hb;
+ (BOOL)removeToolbarIfRequiredHb:(NSInteger)hb;
+ (BOOL)reloadInputViewsHb:(NSInteger)hb;
+ (BOOL)previousActionHb:(NSInteger)hb;
+ (BOOL)nextActionHb:(NSInteger)hb;
+ (BOOL)doneActionHb:(NSInteger)hb;
+ (BOOL)registerTextFieldViewClassDidbegineditingnotificationnameDidendeditingnotificationnameHb:(NSInteger)hb;
+ (BOOL)unregisterTextFieldViewClassDidbegineditingnotificationnameDidendeditingnotificationnameHb:(NSInteger)hb;
+ (BOOL)registerAllNotificationsHb:(NSInteger)hb;
+ (BOOL)unregisterAllNotificationsHb:(NSInteger)hb;
+ (BOOL)showLogHb:(NSInteger)hb;
+ (BOOL)showLogIndentationHb:(NSInteger)hb;

@end
