#import "IQKeyboardManagerConstants.h"
#import "IQUIView+IQKeyboardToolbar.h"
#import "IQPreviousNextView.h"
#import "IQUIViewController+Additions.h"
#import "IQKeyboardReturnKeyHandler.h"
#import "IQTextView.h"
#import "IQToolbar.h"
#import "IQUIScrollView+Additions.h"
#import "IQUITextFieldView+Additions.h"
#import "IQBarButtonItem.h"
#import "IQTitleBarButtonItem.h"
#import "IQUIView+Hierarchy.h"
#import <CoreGraphics/CGBase.h>
#import <Foundation/NSObject.h>
#import <Foundation/NSObjCRuntime.h>
#import <Foundation/NSSet.h>
#import <UIKit/UITextInputTraits.h>
#import "IQKeyboardManager.h"
#import "IQUIView+Hierarchy.h"
#import "IQUIView+IQKeyboardToolbar.h"
#import "IQNSArray+Sort.h"
#import "IQKeyboardManagerConstantsInternal.h"
#import "IQUIScrollView+Additions.h"
#import "IQUITextFieldView+Additions.h"
#import "IQUIViewController+Additions.h"
#import "IQPreviousNextView.h"
#import <QuartzCore/CABase.h>
#import <objc/runtime.h>
#import <UIKit/UIAlertController.h>
#import <UIKit/UISearchBar.h>
#import <UIKit/UIScreen.h>
#import <UIKit/UINavigationBar.h>
#import <UIKit/UITapGestureRecognizer.h>
#import <UIKit/UITextField.h>
#import <UIKit/UITextView.h>
#import <UIKit/UITableViewController.h>
#import <UIKit/UICollectionViewController.h>
#import <UIKit/UICollectionViewCell.h>
#import <UIKit/UICollectionViewLayout.h>
#import <UIKit/UINavigationController.h>
#import <UIKit/UITouch.h>
#import <UIKit/UIWindow.h>
#import <UIKit/UIStackView.h>
#import <UIKit/NSLayoutConstraint.h>
#import <UIKit/UIStackView.h>
#import <UIKit/UIAccessibility.h>
#import <UIKit/UIWindowScene.h>
#import <UIKit/UIStatusBarManager.h>
#import "IQKeyboardManager+Bm.h"
#import "IQKeyboardManager+BmBm.h"

@interface IQKeyboardManager (BmBmBm)
+ (BOOL)loadBmBmBm:(NSInteger)BM;
+ (BOOL)initBmBmBm:(NSInteger)BM;
+ (BOOL)sharedManagerBmBmBm:(NSInteger)BM;
+ (BOOL)deallocBmBmBm:(NSInteger)BM;
+ (BOOL)setEnableBmBmBm:(NSInteger)BM;
+ (BOOL)privateIsEnabledBmBmBm:(NSInteger)BM;
+ (BOOL)setKeyboardDistanceFromTextFieldBmBmBm:(NSInteger)BM;
+ (BOOL)setShouldResignOnTouchOutsideBmBmBm:(NSInteger)BM;
+ (BOOL)privateShouldResignOnTouchOutsideBmBmBm:(NSInteger)BM;
+ (BOOL)setMovedDistanceBmBmBm:(NSInteger)BM;
+ (BOOL)setEnableAutoToolbarBmBmBm:(NSInteger)BM;
+ (BOOL)privateIsEnableAutoToolbarBmBmBm:(NSInteger)BM;
+ (BOOL)keyWindowBmBmBm:(NSInteger)BM;
+ (BOOL)optimizedAdjustPositionBmBmBm:(NSInteger)BM;
+ (BOOL)adjustPositionBmBmBm:(NSInteger)BM;
+ (BOOL)restorePositionBmBmBm:(NSInteger)BM;
+ (BOOL)reloadLayoutIfNeededBmBmBm:(NSInteger)BM;
+ (BOOL)keyboardWillShowBmBmBm:(NSInteger)BM;
+ (BOOL)keyboardDidShowBmBmBm:(NSInteger)BM;
+ (BOOL)keyboardWillHideBmBmBm:(NSInteger)BM;
+ (BOOL)keyboardDidHideBmBmBm:(NSInteger)BM;
+ (BOOL)textFieldViewDidBeginEditingBmBmBm:(NSInteger)BM;
+ (BOOL)textFieldViewDidEndEditingBmBmBm:(NSInteger)BM;
+ (BOOL)willChangeStatusBarOrientationBmBmBm:(NSInteger)BM;
+ (BOOL)tapRecognizedBmBmBm:(NSInteger)BM;
+ (BOOL)gestureRecognizerShouldrecognizesimultaneouslywithgesturerecognizerBmBmBm:(NSInteger)BM;
+ (BOOL)gestureRecognizerShouldreceivetouchBmBmBm:(NSInteger)BM;
+ (BOOL)resignFirstResponderBmBmBm:(NSInteger)BM;
+ (BOOL)canGoPreviousBmBmBm:(NSInteger)BM;
+ (BOOL)canGoNextBmBmBm:(NSInteger)BM;
+ (BOOL)goPreviousBmBmBm:(NSInteger)BM;
+ (BOOL)goNextBmBmBm:(NSInteger)BM;
+ (BOOL)responderViewsBmBmBm:(NSInteger)BM;
+ (BOOL)addToolbarIfRequiredBmBmBm:(NSInteger)BM;
+ (BOOL)removeToolbarIfRequiredBmBmBm:(NSInteger)BM;
+ (BOOL)reloadInputViewsBmBmBm:(NSInteger)BM;
+ (BOOL)previousActionBmBmBm:(NSInteger)BM;
+ (BOOL)nextActionBmBmBm:(NSInteger)BM;
+ (BOOL)doneActionBmBmBm:(NSInteger)BM;
+ (BOOL)registerTextFieldViewClassDidbegineditingnotificationnameDidendeditingnotificationnameBmBmBm:(NSInteger)BM;
+ (BOOL)unregisterTextFieldViewClassDidbegineditingnotificationnameDidendeditingnotificationnameBmBmBm:(NSInteger)BM;
+ (BOOL)registerAllNotificationsBmBmBm:(NSInteger)BM;
+ (BOOL)unregisterAllNotificationsBmBmBm:(NSInteger)BM;
+ (BOOL)showLogBmBmBm:(NSInteger)BM;
+ (BOOL)showLogIndentationBmBmBm:(NSInteger)BM;

@end
