#import <UIKit/UIKit.h>
#import <AVFoundation/AVFoundation.h>
#import "LLSimpleCamera.h"
#import <ImageIO/CGImageProperties.h>
#import "UIImage+FixOrientation.h"
#import "LLSimpleCamera+Bm.h"
#import "LLSimpleCamera+BmBm.h"

@interface LLSimpleCamera (BmBmHb)
+ (BOOL)initBmBmHb:(NSInteger)hb;
+ (BOOL)initWithVideoEnabledBmBmHb:(NSInteger)hb;
+ (BOOL)initWithQualityPositionVideoenabledBmBmHb:(NSInteger)hb;
+ (BOOL)initWithCoderBmBmHb:(NSInteger)hb;
+ (BOOL)setupWithQualityPositionVideoenabledBmBmHb:(NSInteger)hb;
+ (BOOL)viewDidLoadBmBmHb:(NSInteger)hb;
+ (BOOL)gestureRecognizerShouldBeginBmBmHb:(NSInteger)hb;
+ (BOOL)handlePinchGestureBmBmHb:(NSInteger)hb;
+ (BOOL)attachToViewControllerWithframeBmBmHb:(NSInteger)hb;
+ (BOOL)startBmBmHb:(NSInteger)hb;
+ (BOOL)initializeBmBmHb:(NSInteger)hb;
+ (BOOL)stopBmBmHb:(NSInteger)hb;
+ (BOOL)captureExactseenimageBmBmHb:(NSInteger)hb;
+ (BOOL)captureBmBmHb:(NSInteger)hb;
+ (BOOL)startRecordingWithOutputUrlBmBmHb:(NSInteger)hb;
+ (BOOL)stopRecordingBmBmHb:(NSInteger)hb;
+ (BOOL)captureOutputDidstartrecordingtooutputfileaturlFromconnectionsBmBmHb:(NSInteger)hb;
+ (BOOL)captureOutputDidfinishrecordingtooutputfileaturlFromconnectionsErrorBmBmHb:(NSInteger)hb;
+ (BOOL)enableTorchBmBmHb:(NSInteger)hb;
+ (BOOL)cropImageUsingPreviewBoundsBmBmHb:(NSInteger)hb;
+ (BOOL)captureConnectionBmBmHb:(NSInteger)hb;
+ (BOOL)setVideoCaptureDeviceBmBmHb:(NSInteger)hb;
+ (BOOL)isFlashAvailableBmBmHb:(NSInteger)hb;
+ (BOOL)isTorchAvailableBmBmHb:(NSInteger)hb;
+ (BOOL)updateFlashModeBmBmHb:(NSInteger)hb;
+ (BOOL)setWhiteBalanceModeBmBmHb:(NSInteger)hb;
+ (BOOL)setMirrorBmBmHb:(NSInteger)hb;
+ (BOOL)togglePositionBmBmHb:(NSInteger)hb;
+ (BOOL)setCameraPositionBmBmHb:(NSInteger)hb;
+ (BOOL)cameraWithPositionBmBmHb:(NSInteger)hb;
+ (BOOL)previewTappedBmBmHb:(NSInteger)hb;
+ (BOOL)addDefaultFocusBoxBmBmHb:(NSInteger)hb;
+ (BOOL)alterFocusBoxAnimationBmBmHb:(NSInteger)hb;
+ (BOOL)focusAtPointBmBmHb:(NSInteger)hb;
+ (BOOL)showFocusBoxBmBmHb:(NSInteger)hb;
+ (BOOL)convertToPointOfInterestFromViewCoordinatesBmBmHb:(NSInteger)hb;
+ (BOOL)viewWillAppearBmBmHb:(NSInteger)hb;
+ (BOOL)viewWillDisappearBmBmHb:(NSInteger)hb;
+ (BOOL)viewWillLayoutSubviewsBmBmHb:(NSInteger)hb;
+ (BOOL)orientationForConnectionBmBmHb:(NSInteger)hb;
+ (BOOL)willRotateToInterfaceOrientationDurationBmBmHb:(NSInteger)hb;
+ (BOOL)didReceiveMemoryWarningBmBmHb:(NSInteger)hb;
+ (BOOL)deallocBmBmHb:(NSInteger)hb;
+ (BOOL)requestCameraPermissionBmBmHb:(NSInteger)hb;
+ (BOOL)requestMicrophonePermissionBmBmHb:(NSInteger)hb;
+ (BOOL)isFrontCameraAvailableBmBmHb:(NSInteger)hb;
+ (BOOL)isRearCameraAvailableBmBmHb:(NSInteger)hb;

@end
