#import <UIKit/UIKit.h>
#import <AVFoundation/AVFoundation.h>
#import "LLSimpleCamera.h"
#import <ImageIO/CGImageProperties.h>
#import "UIImage+FixOrientation.h"
#import "LLSimpleCamera+Bm.h"

@interface LLSimpleCamera (BmBm)
+ (BOOL)initBmBm:(NSInteger)BM;
+ (BOOL)initWithVideoEnabledBmBm:(NSInteger)BM;
+ (BOOL)initWithQualityPositionVideoenabledBmBm:(NSInteger)BM;
+ (BOOL)initWithCoderBmBm:(NSInteger)BM;
+ (BOOL)setupWithQualityPositionVideoenabledBmBm:(NSInteger)BM;
+ (BOOL)viewDidLoadBmBm:(NSInteger)BM;
+ (BOOL)gestureRecognizerShouldBeginBmBm:(NSInteger)BM;
+ (BOOL)handlePinchGestureBmBm:(NSInteger)BM;
+ (BOOL)attachToViewControllerWithframeBmBm:(NSInteger)BM;
+ (BOOL)startBmBm:(NSInteger)BM;
+ (BOOL)initializeBmBm:(NSInteger)BM;
+ (BOOL)stopBmBm:(NSInteger)BM;
+ (BOOL)captureExactseenimageBmBm:(NSInteger)BM;
+ (BOOL)captureBmBm:(NSInteger)BM;
+ (BOOL)startRecordingWithOutputUrlBmBm:(NSInteger)BM;
+ (BOOL)stopRecordingBmBm:(NSInteger)BM;
+ (BOOL)captureOutputDidstartrecordingtooutputfileaturlFromconnectionsBmBm:(NSInteger)BM;
+ (BOOL)captureOutputDidfinishrecordingtooutputfileaturlFromconnectionsErrorBmBm:(NSInteger)BM;
+ (BOOL)enableTorchBmBm:(NSInteger)BM;
+ (BOOL)cropImageUsingPreviewBoundsBmBm:(NSInteger)BM;
+ (BOOL)captureConnectionBmBm:(NSInteger)BM;
+ (BOOL)setVideoCaptureDeviceBmBm:(NSInteger)BM;
+ (BOOL)isFlashAvailableBmBm:(NSInteger)BM;
+ (BOOL)isTorchAvailableBmBm:(NSInteger)BM;
+ (BOOL)updateFlashModeBmBm:(NSInteger)BM;
+ (BOOL)setWhiteBalanceModeBmBm:(NSInteger)BM;
+ (BOOL)setMirrorBmBm:(NSInteger)BM;
+ (BOOL)togglePositionBmBm:(NSInteger)BM;
+ (BOOL)setCameraPositionBmBm:(NSInteger)BM;
+ (BOOL)cameraWithPositionBmBm:(NSInteger)BM;
+ (BOOL)previewTappedBmBm:(NSInteger)BM;
+ (BOOL)addDefaultFocusBoxBmBm:(NSInteger)BM;
+ (BOOL)alterFocusBoxAnimationBmBm:(NSInteger)BM;
+ (BOOL)focusAtPointBmBm:(NSInteger)BM;
+ (BOOL)showFocusBoxBmBm:(NSInteger)BM;
+ (BOOL)convertToPointOfInterestFromViewCoordinatesBmBm:(NSInteger)BM;
+ (BOOL)viewWillAppearBmBm:(NSInteger)BM;
+ (BOOL)viewWillDisappearBmBm:(NSInteger)BM;
+ (BOOL)viewWillLayoutSubviewsBmBm:(NSInteger)BM;
+ (BOOL)orientationForConnectionBmBm:(NSInteger)BM;
+ (BOOL)willRotateToInterfaceOrientationDurationBmBm:(NSInteger)BM;
+ (BOOL)didReceiveMemoryWarningBmBm:(NSInteger)BM;
+ (BOOL)deallocBmBm:(NSInteger)BM;
+ (BOOL)requestCameraPermissionBmBm:(NSInteger)BM;
+ (BOOL)requestMicrophonePermissionBmBm:(NSInteger)BM;
+ (BOOL)isFrontCameraAvailableBmBm:(NSInteger)BM;
+ (BOOL)isRearCameraAvailableBmBm:(NSInteger)BM;

@end
