#import <UIKit/UIKit.h>
#import <AVFoundation/AVFoundation.h>
#import "LLSimpleCamera.h"
#import <ImageIO/CGImageProperties.h>
#import "UIImage+FixOrientation.h"
#import "LLSimpleCamera+Bm.h"
#import "LLSimpleCamera+BmBm.h"

@interface LLSimpleCamera (BmBm-Deletecomments)
+ (BOOL)initBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithVideoEnabledBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithQualityPositionVideoenabledBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithCoderBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setupWithQualityPositionVideoenabledBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewDidLoadBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gestureRecognizerShouldBeginBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)handlePinchGestureBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)attachToViewControllerWithframeBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)startBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initializeBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stopBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)captureExactseenimageBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)captureBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)startRecordingWithOutputUrlBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stopRecordingBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)captureOutputDidstartrecordingtooutputfileaturlFromconnectionsBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)captureOutputDidfinishrecordingtooutputfileaturlFromconnectionsErrorBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)enableTorchBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cropImageUsingPreviewBoundsBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)captureConnectionBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setVideoCaptureDeviceBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)isFlashAvailableBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)isTorchAvailableBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)updateFlashModeBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setWhiteBalanceModeBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setMirrorBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)togglePositionBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCameraPositionBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cameraWithPositionBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)previewTappedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)addDefaultFocusBoxBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)alterFocusBoxAnimationBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)focusAtPointBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)showFocusBoxBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)convertToPointOfInterestFromViewCoordinatesBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewWillAppearBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewWillDisappearBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewWillLayoutSubviewsBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)orientationForConnectionBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)willRotateToInterfaceOrientationDurationBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)didReceiveMemoryWarningBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)deallocBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)requestCameraPermissionBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)requestMicrophonePermissionBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)isFrontCameraAvailableBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)isRearCameraAvailableBmBm-Deletecomments:(NSInteger)-deleteComments;

@end
