#import <UIKit/UIKit.h>
#import <AVFoundation/AVFoundation.h>
#import "LLSimpleCamera.h"
#import <ImageIO/CGImageProperties.h>
#import "UIImage+FixOrientation.h"
#import "LLSimpleCamera+Bm.h"

@interface LLSimpleCamera (Bm-Deletecomments)
+ (BOOL)initBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithVideoEnabledBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithQualityPositionVideoenabledBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithCoderBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setupWithQualityPositionVideoenabledBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewDidLoadBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gestureRecognizerShouldBeginBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)handlePinchGestureBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)attachToViewControllerWithframeBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)startBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initializeBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stopBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)captureExactseenimageBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)captureBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)startRecordingWithOutputUrlBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stopRecordingBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)captureOutputDidstartrecordingtooutputfileaturlFromconnectionsBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)captureOutputDidfinishrecordingtooutputfileaturlFromconnectionsErrorBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)enableTorchBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cropImageUsingPreviewBoundsBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)captureConnectionBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setVideoCaptureDeviceBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)isFlashAvailableBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)isTorchAvailableBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)updateFlashModeBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setWhiteBalanceModeBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setMirrorBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)togglePositionBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCameraPositionBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cameraWithPositionBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)previewTappedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)addDefaultFocusBoxBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)alterFocusBoxAnimationBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)focusAtPointBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)showFocusBoxBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)convertToPointOfInterestFromViewCoordinatesBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewWillAppearBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewWillDisappearBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewWillLayoutSubviewsBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)orientationForConnectionBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)willRotateToInterfaceOrientationDurationBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)didReceiveMemoryWarningBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)deallocBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)requestCameraPermissionBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)requestMicrophonePermissionBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)isFrontCameraAvailableBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)isRearCameraAvailableBm-Deletecomments:(NSInteger)-deleteComments;

@end
