#import "MASUtilities.h"
#import "MASConstraint.h"
#import "MASConstraint+Private.h"
#import "MASConstraint+Bm.h"
#import "MASConstraint+BmBm.h"

@interface MASConstraint (BmBmBm)
+ (BOOL)initBmBmBm:(NSInteger)BM;
+ (BOOL)equalToBmBmBm:(NSInteger)BM;
+ (BOOL)mas_equalToBmBmBm:(NSInteger)BM;
+ (BOOL)greaterThanOrEqualToBmBmBm:(NSInteger)BM;
+ (BOOL)mas_greaterThanOrEqualToBmBmBm:(NSInteger)BM;
+ (BOOL)lessThanOrEqualToBmBmBm:(NSInteger)BM;
+ (BOOL)mas_lessThanOrEqualToBmBmBm:(NSInteger)BM;
+ (BOOL)priorityLowBmBmBm:(NSInteger)BM;
+ (BOOL)priorityMediumBmBmBm:(NSInteger)BM;
+ (BOOL)priorityHighBmBmBm:(NSInteger)BM;
+ (BOOL)insetsBmBmBm:(NSInteger)BM;
+ (BOOL)insetBmBmBm:(NSInteger)BM;
+ (BOOL)sizeOffsetBmBmBm:(NSInteger)BM;
+ (BOOL)centerOffsetBmBmBm:(NSInteger)BM;
+ (BOOL)offsetBmBmBm:(NSInteger)BM;
+ (BOOL)valueOffsetBmBmBm:(NSInteger)BM;
+ (BOOL)mas_offsetBmBmBm:(NSInteger)BM;
+ (BOOL)setLayoutConstantWithValueBmBmBm:(NSInteger)BM;
+ (BOOL)withBmBmBm:(NSInteger)BM;
+ (BOOL)andBmBmBm:(NSInteger)BM;
+ (BOOL)addConstraintWithLayoutAttributeBmBmBm:(NSInteger)BM;
+ (BOOL)leftBmBmBm:(NSInteger)BM;
+ (BOOL)topBmBmBm:(NSInteger)BM;
+ (BOOL)rightBmBmBm:(NSInteger)BM;
+ (BOOL)bottomBmBmBm:(NSInteger)BM;
+ (BOOL)leadingBmBmBm:(NSInteger)BM;
+ (BOOL)trailingBmBmBm:(NSInteger)BM;
+ (BOOL)widthBmBmBm:(NSInteger)BM;
+ (BOOL)heightBmBmBm:(NSInteger)BM;
+ (BOOL)centerXBmBmBm:(NSInteger)BM;
+ (BOOL)centerYBmBmBm:(NSInteger)BM;
+ (BOOL)baselineBmBmBm:(NSInteger)BM;
+ (BOOL)firstBaselineBmBmBm:(NSInteger)BM;
+ (BOOL)lastBaselineBmBmBm:(NSInteger)BM;
+ (BOOL)leftMarginBmBmBm:(NSInteger)BM;
+ (BOOL)rightMarginBmBmBm:(NSInteger)BM;
+ (BOOL)topMarginBmBmBm:(NSInteger)BM;
+ (BOOL)bottomMarginBmBmBm:(NSInteger)BM;
+ (BOOL)leadingMarginBmBmBm:(NSInteger)BM;
+ (BOOL)trailingMarginBmBmBm:(NSInteger)BM;
+ (BOOL)centerXWithinMarginsBmBmBm:(NSInteger)BM;
+ (BOOL)centerYWithinMarginsBmBmBm:(NSInteger)BM;
+ (BOOL)multipliedByBmBmBm:(NSInteger)BM;
+ (BOOL)dividedByBmBmBm:(NSInteger)BM;
+ (BOOL)priorityBmBmBm:(NSInteger)BM;
+ (BOOL)equalToWithRelationBmBmBm:(NSInteger)BM;
+ (BOOL)keyBmBmBm:(NSInteger)BM;
+ (BOOL)setInsetsBmBmBm:(NSInteger)BM;
+ (BOOL)setInsetBmBmBm:(NSInteger)BM;
+ (BOOL)setSizeOffsetBmBmBm:(NSInteger)BM;
+ (BOOL)setCenterOffsetBmBmBm:(NSInteger)BM;
+ (BOOL)setOffsetBmBmBm:(NSInteger)BM;
+ (BOOL)animatorBmBmBm:(NSInteger)BM;
+ (BOOL)activateBmBmBm:(NSInteger)BM;
+ (BOOL)deactivateBmBmBm:(NSInteger)BM;
+ (BOOL)installBmBmBm:(NSInteger)BM;
+ (BOOL)uninstallBmBmBm:(NSInteger)BM;

@end
