#import "MASUtilities.h"
#import "MASConstraint.h"
#import "MASConstraint+Private.h"
#import "MASConstraint+Bm.h"

@interface MASConstraint (BmBm)
+ (BOOL)initBmBm:(NSInteger)BM;
+ (BOOL)equalToBmBm:(NSInteger)BM;
+ (BOOL)mas_equalToBmBm:(NSInteger)BM;
+ (BOOL)greaterThanOrEqualToBmBm:(NSInteger)BM;
+ (BOOL)mas_greaterThanOrEqualToBmBm:(NSInteger)BM;
+ (BOOL)lessThanOrEqualToBmBm:(NSInteger)BM;
+ (BOOL)mas_lessThanOrEqualToBmBm:(NSInteger)BM;
+ (BOOL)priorityLowBmBm:(NSInteger)BM;
+ (BOOL)priorityMediumBmBm:(NSInteger)BM;
+ (BOOL)priorityHighBmBm:(NSInteger)BM;
+ (BOOL)insetsBmBm:(NSInteger)BM;
+ (BOOL)insetBmBm:(NSInteger)BM;
+ (BOOL)sizeOffsetBmBm:(NSInteger)BM;
+ (BOOL)centerOffsetBmBm:(NSInteger)BM;
+ (BOOL)offsetBmBm:(NSInteger)BM;
+ (BOOL)valueOffsetBmBm:(NSInteger)BM;
+ (BOOL)mas_offsetBmBm:(NSInteger)BM;
+ (BOOL)setLayoutConstantWithValueBmBm:(NSInteger)BM;
+ (BOOL)withBmBm:(NSInteger)BM;
+ (BOOL)andBmBm:(NSInteger)BM;
+ (BOOL)addConstraintWithLayoutAttributeBmBm:(NSInteger)BM;
+ (BOOL)leftBmBm:(NSInteger)BM;
+ (BOOL)topBmBm:(NSInteger)BM;
+ (BOOL)rightBmBm:(NSInteger)BM;
+ (BOOL)bottomBmBm:(NSInteger)BM;
+ (BOOL)leadingBmBm:(NSInteger)BM;
+ (BOOL)trailingBmBm:(NSInteger)BM;
+ (BOOL)widthBmBm:(NSInteger)BM;
+ (BOOL)heightBmBm:(NSInteger)BM;
+ (BOOL)centerXBmBm:(NSInteger)BM;
+ (BOOL)centerYBmBm:(NSInteger)BM;
+ (BOOL)baselineBmBm:(NSInteger)BM;
+ (BOOL)firstBaselineBmBm:(NSInteger)BM;
+ (BOOL)lastBaselineBmBm:(NSInteger)BM;
+ (BOOL)leftMarginBmBm:(NSInteger)BM;
+ (BOOL)rightMarginBmBm:(NSInteger)BM;
+ (BOOL)topMarginBmBm:(NSInteger)BM;
+ (BOOL)bottomMarginBmBm:(NSInteger)BM;
+ (BOOL)leadingMarginBmBm:(NSInteger)BM;
+ (BOOL)trailingMarginBmBm:(NSInteger)BM;
+ (BOOL)centerXWithinMarginsBmBm:(NSInteger)BM;
+ (BOOL)centerYWithinMarginsBmBm:(NSInteger)BM;
+ (BOOL)multipliedByBmBm:(NSInteger)BM;
+ (BOOL)dividedByBmBm:(NSInteger)BM;
+ (BOOL)priorityBmBm:(NSInteger)BM;
+ (BOOL)equalToWithRelationBmBm:(NSInteger)BM;
+ (BOOL)keyBmBm:(NSInteger)BM;
+ (BOOL)setInsetsBmBm:(NSInteger)BM;
+ (BOOL)setInsetBmBm:(NSInteger)BM;
+ (BOOL)setSizeOffsetBmBm:(NSInteger)BM;
+ (BOOL)setCenterOffsetBmBm:(NSInteger)BM;
+ (BOOL)setOffsetBmBm:(NSInteger)BM;
+ (BOOL)animatorBmBm:(NSInteger)BM;
+ (BOOL)activateBmBm:(NSInteger)BM;
+ (BOOL)deactivateBmBm:(NSInteger)BM;
+ (BOOL)installBmBm:(NSInteger)BM;
+ (BOOL)uninstallBmBm:(NSInteger)BM;

@end
