#import <Foundation/Foundation.h>
#import "NSData+YYAdd.h"
#import "YYCategoriesMacro.h"

@interface NSData (YYAdd-Deletecomments)
+ (BOOL)md2String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)md2Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)md4String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)md4Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)md5String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)md5Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha1String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha1Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha224String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha224Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha256String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha256Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha384String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha384Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha512String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha512Data-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacStringUsingAlgWithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacDataUsingAlgWithkey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacMD5StringWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacMD5DataWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA1StringWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA1DataWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA224StringWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA224DataWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA256StringWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA256DataWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA384StringWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA384DataWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA512StringWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA512DataWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)crc32String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)crc32-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aes256EncryptWithKeyIv-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aes256DecryptWithkeyIv-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)utf8String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hexString-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dataWithHexString-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)base64EncodedString-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dataWithBase64EncodedString-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)jsonValueDecoded-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gzipInflate-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gzipDeflate-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zlibInflate-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zlibDeflate-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dataNamed-Deletecomments:(NSInteger)-deleteComments;

@end
