#import <Foundation/Foundation.h>
#import "NSData+YYAdd.h"
#import "YYCategoriesMacro.h"
#import "NSData+YYAddBm.h"
#import "NSData+YYAddBmBm.h"

@interface NSData (YYAddBmBm-Deletecomments)
+ (BOOL)md2StringBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)md2DataBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)md4StringBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)md4DataBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)md5StringBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)md5DataBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha1StringBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha1DataBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha224StringBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha224DataBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha256StringBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha256DataBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha384StringBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha384DataBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha512StringBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha512DataBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacStringUsingAlgWithkeyBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacDataUsingAlgWithkeyBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacMD5StringWithKeyBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacMD5DataWithKeyBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA1StringWithKeyBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA1DataWithKeyBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA224StringWithKeyBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA224DataWithKeyBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA256StringWithKeyBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA256DataWithKeyBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA384StringWithKeyBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA384DataWithKeyBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA512StringWithKeyBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA512DataWithKeyBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)crc32StringBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)crc32BmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aes256EncryptWithKeyIvBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aes256DecryptWithkeyIvBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)utf8StringBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hexStringBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dataWithHexStringBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)base64EncodedStringBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dataWithBase64EncodedStringBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)jsonValueDecodedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gzipInflateBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gzipDeflateBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zlibInflateBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)zlibDeflateBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dataNamedBmBm-Deletecomments:(NSInteger)-deleteComments;

@end
