#import <UIKit/UIKit.h>
#import "NSString+YYAdd.h"
#import "NSData+YYAdd.h"
#import "NSNumber+YYAdd.h"
#import "UIDevice+YYAdd.h"
#import "YYCategoriesMacro.h"

@interface NSString (YYAddBm)
+ (BOOL)md2StringBm:(NSInteger)BM;
+ (BOOL)md4StringBm:(NSInteger)BM;
+ (BOOL)md5StringBm:(NSInteger)BM;
+ (BOOL)sha1StringBm:(NSInteger)BM;
+ (BOOL)sha224StringBm:(NSInteger)BM;
+ (BOOL)sha256StringBm:(NSInteger)BM;
+ (BOOL)sha384StringBm:(NSInteger)BM;
+ (BOOL)sha512StringBm:(NSInteger)BM;
+ (BOOL)crc32StringBm:(NSInteger)BM;
+ (BOOL)hmacMD5StringWithKeyBm:(NSInteger)BM;
+ (BOOL)hmacSHA1StringWithKeyBm:(NSInteger)BM;
+ (BOOL)hmacSHA224StringWithKeyBm:(NSInteger)BM;
+ (BOOL)hmacSHA256StringWithKeyBm:(NSInteger)BM;
+ (BOOL)hmacSHA384StringWithKeyBm:(NSInteger)BM;
+ (BOOL)hmacSHA512StringWithKeyBm:(NSInteger)BM;
+ (BOOL)base64EncodedStringBm:(NSInteger)BM;
+ (BOOL)stringWithBase64EncodedStringBm:(NSInteger)BM;
+ (BOOL)stringByURLEncodeBm:(NSInteger)BM;
+ (BOOL)stringByURLDecodeBm:(NSInteger)BM;
+ (BOOL)stringByEscapingHTMLBm:(NSInteger)BM;
+ (BOOL)sizeForFontSizeModeBm:(NSInteger)BM;
+ (BOOL)widthForFontBm:(NSInteger)BM;
+ (BOOL)heightForFontWidthBm:(NSInteger)BM;
+ (BOOL)matchesRegexOptionsBm:(NSInteger)BM;
+ (BOOL)enumerateRegexMatchesOptionsUsingblockBm:(NSInteger)BM;
+ (BOOL)stringByReplacingRegexOptionsWithstringBm:(NSInteger)BM;
+ (BOOL)charValueBm:(NSInteger)BM;
+ (BOOL)unsignedCharValueBm:(NSInteger)BM;
+ (BOOL)shortValueBm:(NSInteger)BM;
+ (BOOL)unsignedShortValueBm:(NSInteger)BM;
+ (BOOL)unsignedIntValueBm:(NSInteger)BM;
+ (BOOL)longValueBm:(NSInteger)BM;
+ (BOOL)unsignedLongValueBm:(NSInteger)BM;
+ (BOOL)unsignedLongLongValueBm:(NSInteger)BM;
+ (BOOL)unsignedIntegerValueBm:(NSInteger)BM;
+ (BOOL)stringWithUUIDBm:(NSInteger)BM;
+ (BOOL)stringWithUTF32CharBm:(NSInteger)BM;
+ (BOOL)stringWithUTF32CharsLengthBm:(NSInteger)BM;
+ (BOOL)enumerateUTF32CharInRangeUsingblockBm:(NSInteger)BM;
+ (BOOL)stringByTrimBm:(NSInteger)BM;
+ (BOOL)stringByAppendingNameScaleBm:(NSInteger)BM;
+ (BOOL)stringByAppendingPathScaleBm:(NSInteger)BM;
+ (BOOL)pathScaleBm:(NSInteger)BM;
+ (BOOL)isNotBlankBm:(NSInteger)BM;
+ (BOOL)containsStringBm:(NSInteger)BM;
+ (BOOL)containsCharacterSetBm:(NSInteger)BM;
+ (BOOL)numberValueBm:(NSInteger)BM;
+ (BOOL)dataValueBm:(NSInteger)BM;
+ (BOOL)rangeOfAllBm:(NSInteger)BM;
+ (BOOL)jsonValueDecodedBm:(NSInteger)BM;
+ (BOOL)stringNamedBm:(NSInteger)BM;

@end
