#import <UIKit/UIKit.h>
#import "NSString+YYAdd.h"
#import "NSData+YYAdd.h"
#import "NSNumber+YYAdd.h"
#import "UIDevice+YYAdd.h"
#import "YYCategoriesMacro.h"

@interface NSString (YYAdd-Deletecomments)
+ (BOOL)md2String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)md4String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)md5String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha1String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha224String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha256String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha384String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sha512String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)crc32String-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacMD5StringWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA1StringWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA224StringWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA256StringWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA384StringWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hmacSHA512StringWithKey-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)base64EncodedString-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stringWithBase64EncodedString-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stringByURLEncode-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stringByURLDecode-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stringByEscapingHTML-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sizeForFontSizeMode-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)widthForFont-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)heightForFontWidth-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)matchesRegexOptions-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)enumerateRegexMatchesOptionsUsingblock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stringByReplacingRegexOptionsWithstring-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)charValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)unsignedCharValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)shortValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)unsignedShortValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)unsignedIntValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)longValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)unsignedLongValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)unsignedLongLongValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)unsignedIntegerValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stringWithUUID-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stringWithUTF32Char-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stringWithUTF32CharsLength-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)enumerateUTF32CharInRangeUsingblock-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stringByTrim-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stringByAppendingNameScale-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stringByAppendingPathScale-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)pathScale-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)isNotBlank-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)containsString-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)containsCharacterSet-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)numberValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dataValue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rangeOfAll-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)jsonValueDecoded-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)stringNamed-Deletecomments:(NSInteger)-deleteComments;

@end
