#import <UIKit/UIKit.h>
#import "NSString+YYAdd.h"
#import "NSData+YYAdd.h"
#import "NSNumber+YYAdd.h"
#import "UIDevice+YYAdd.h"
#import "YYCategoriesMacro.h"
#import "NSString+YYAddBm.h"
#import "NSString+YYAddBmBm.h"

@interface NSString (YYAddBmBmBm)
+ (BOOL)md2StringBmBmBm:(NSInteger)BM;
+ (BOOL)md4StringBmBmBm:(NSInteger)BM;
+ (BOOL)md5StringBmBmBm:(NSInteger)BM;
+ (BOOL)sha1StringBmBmBm:(NSInteger)BM;
+ (BOOL)sha224StringBmBmBm:(NSInteger)BM;
+ (BOOL)sha256StringBmBmBm:(NSInteger)BM;
+ (BOOL)sha384StringBmBmBm:(NSInteger)BM;
+ (BOOL)sha512StringBmBmBm:(NSInteger)BM;
+ (BOOL)crc32StringBmBmBm:(NSInteger)BM;
+ (BOOL)hmacMD5StringWithKeyBmBmBm:(NSInteger)BM;
+ (BOOL)hmacSHA1StringWithKeyBmBmBm:(NSInteger)BM;
+ (BOOL)hmacSHA224StringWithKeyBmBmBm:(NSInteger)BM;
+ (BOOL)hmacSHA256StringWithKeyBmBmBm:(NSInteger)BM;
+ (BOOL)hmacSHA384StringWithKeyBmBmBm:(NSInteger)BM;
+ (BOOL)hmacSHA512StringWithKeyBmBmBm:(NSInteger)BM;
+ (BOOL)base64EncodedStringBmBmBm:(NSInteger)BM;
+ (BOOL)stringWithBase64EncodedStringBmBmBm:(NSInteger)BM;
+ (BOOL)stringByURLEncodeBmBmBm:(NSInteger)BM;
+ (BOOL)stringByURLDecodeBmBmBm:(NSInteger)BM;
+ (BOOL)stringByEscapingHTMLBmBmBm:(NSInteger)BM;
+ (BOOL)sizeForFontSizeModeBmBmBm:(NSInteger)BM;
+ (BOOL)widthForFontBmBmBm:(NSInteger)BM;
+ (BOOL)heightForFontWidthBmBmBm:(NSInteger)BM;
+ (BOOL)matchesRegexOptionsBmBmBm:(NSInteger)BM;
+ (BOOL)enumerateRegexMatchesOptionsUsingblockBmBmBm:(NSInteger)BM;
+ (BOOL)stringByReplacingRegexOptionsWithstringBmBmBm:(NSInteger)BM;
+ (BOOL)charValueBmBmBm:(NSInteger)BM;
+ (BOOL)unsignedCharValueBmBmBm:(NSInteger)BM;
+ (BOOL)shortValueBmBmBm:(NSInteger)BM;
+ (BOOL)unsignedShortValueBmBmBm:(NSInteger)BM;
+ (BOOL)unsignedIntValueBmBmBm:(NSInteger)BM;
+ (BOOL)longValueBmBmBm:(NSInteger)BM;
+ (BOOL)unsignedLongValueBmBmBm:(NSInteger)BM;
+ (BOOL)unsignedLongLongValueBmBmBm:(NSInteger)BM;
+ (BOOL)unsignedIntegerValueBmBmBm:(NSInteger)BM;
+ (BOOL)stringWithUUIDBmBmBm:(NSInteger)BM;
+ (BOOL)stringWithUTF32CharBmBmBm:(NSInteger)BM;
+ (BOOL)stringWithUTF32CharsLengthBmBmBm:(NSInteger)BM;
+ (BOOL)enumerateUTF32CharInRangeUsingblockBmBmBm:(NSInteger)BM;
+ (BOOL)stringByTrimBmBmBm:(NSInteger)BM;
+ (BOOL)stringByAppendingNameScaleBmBmBm:(NSInteger)BM;
+ (BOOL)stringByAppendingPathScaleBmBmBm:(NSInteger)BM;
+ (BOOL)pathScaleBmBmBm:(NSInteger)BM;
+ (BOOL)isNotBlankBmBmBm:(NSInteger)BM;
+ (BOOL)containsStringBmBmBm:(NSInteger)BM;
+ (BOOL)containsCharacterSetBmBmBm:(NSInteger)BM;
+ (BOOL)numberValueBmBmBm:(NSInteger)BM;
+ (BOOL)dataValueBmBmBm:(NSInteger)BM;
+ (BOOL)rangeOfAllBmBmBm:(NSInteger)BM;
+ (BOOL)jsonValueDecodedBmBmBm:(NSInteger)BM;
+ (BOOL)stringNamedBmBmBm:(NSInteger)BM;

@end
