#import <UIKit/UIKit.h>
#import "NSString+YYAdd.h"
#import "NSData+YYAdd.h"
#import "NSNumber+YYAdd.h"
#import "UIDevice+YYAdd.h"
#import "YYCategoriesMacro.h"
#import "NSString+YYAddBm.h"

@interface NSString (YYAddBmBm)
+ (BOOL)md2StringBmBm:(NSInteger)BM;
+ (BOOL)md4StringBmBm:(NSInteger)BM;
+ (BOOL)md5StringBmBm:(NSInteger)BM;
+ (BOOL)sha1StringBmBm:(NSInteger)BM;
+ (BOOL)sha224StringBmBm:(NSInteger)BM;
+ (BOOL)sha256StringBmBm:(NSInteger)BM;
+ (BOOL)sha384StringBmBm:(NSInteger)BM;
+ (BOOL)sha512StringBmBm:(NSInteger)BM;
+ (BOOL)crc32StringBmBm:(NSInteger)BM;
+ (BOOL)hmacMD5StringWithKeyBmBm:(NSInteger)BM;
+ (BOOL)hmacSHA1StringWithKeyBmBm:(NSInteger)BM;
+ (BOOL)hmacSHA224StringWithKeyBmBm:(NSInteger)BM;
+ (BOOL)hmacSHA256StringWithKeyBmBm:(NSInteger)BM;
+ (BOOL)hmacSHA384StringWithKeyBmBm:(NSInteger)BM;
+ (BOOL)hmacSHA512StringWithKeyBmBm:(NSInteger)BM;
+ (BOOL)base64EncodedStringBmBm:(NSInteger)BM;
+ (BOOL)stringWithBase64EncodedStringBmBm:(NSInteger)BM;
+ (BOOL)stringByURLEncodeBmBm:(NSInteger)BM;
+ (BOOL)stringByURLDecodeBmBm:(NSInteger)BM;
+ (BOOL)stringByEscapingHTMLBmBm:(NSInteger)BM;
+ (BOOL)sizeForFontSizeModeBmBm:(NSInteger)BM;
+ (BOOL)widthForFontBmBm:(NSInteger)BM;
+ (BOOL)heightForFontWidthBmBm:(NSInteger)BM;
+ (BOOL)matchesRegexOptionsBmBm:(NSInteger)BM;
+ (BOOL)enumerateRegexMatchesOptionsUsingblockBmBm:(NSInteger)BM;
+ (BOOL)stringByReplacingRegexOptionsWithstringBmBm:(NSInteger)BM;
+ (BOOL)charValueBmBm:(NSInteger)BM;
+ (BOOL)unsignedCharValueBmBm:(NSInteger)BM;
+ (BOOL)shortValueBmBm:(NSInteger)BM;
+ (BOOL)unsignedShortValueBmBm:(NSInteger)BM;
+ (BOOL)unsignedIntValueBmBm:(NSInteger)BM;
+ (BOOL)longValueBmBm:(NSInteger)BM;
+ (BOOL)unsignedLongValueBmBm:(NSInteger)BM;
+ (BOOL)unsignedLongLongValueBmBm:(NSInteger)BM;
+ (BOOL)unsignedIntegerValueBmBm:(NSInteger)BM;
+ (BOOL)stringWithUUIDBmBm:(NSInteger)BM;
+ (BOOL)stringWithUTF32CharBmBm:(NSInteger)BM;
+ (BOOL)stringWithUTF32CharsLengthBmBm:(NSInteger)BM;
+ (BOOL)enumerateUTF32CharInRangeUsingblockBmBm:(NSInteger)BM;
+ (BOOL)stringByTrimBmBm:(NSInteger)BM;
+ (BOOL)stringByAppendingNameScaleBmBm:(NSInteger)BM;
+ (BOOL)stringByAppendingPathScaleBmBm:(NSInteger)BM;
+ (BOOL)pathScaleBmBm:(NSInteger)BM;
+ (BOOL)isNotBlankBmBm:(NSInteger)BM;
+ (BOOL)containsStringBmBm:(NSInteger)BM;
+ (BOOL)containsCharacterSetBmBm:(NSInteger)BM;
+ (BOOL)numberValueBmBm:(NSInteger)BM;
+ (BOOL)dataValueBmBm:(NSInteger)BM;
+ (BOOL)rangeOfAllBmBm:(NSInteger)BM;
+ (BOOL)jsonValueDecodedBmBm:(NSInteger)BM;
+ (BOOL)stringNamedBmBm:(NSInteger)BM;

@end
