#import <UIKit/UIKit.h>
#import "NSString+YYAdd.h"
#import "NSData+YYAdd.h"
#import "NSNumber+YYAdd.h"
#import "UIDevice+YYAdd.h"
#import "YYCategoriesMacro.h"
#import "NSString+YYAddHb.h"

@interface NSString (YYAddHbHb)
+ (BOOL)md2StringHbHb:(NSInteger)hb;
+ (BOOL)md4StringHbHb:(NSInteger)hb;
+ (BOOL)md5StringHbHb:(NSInteger)hb;
+ (BOOL)sha1StringHbHb:(NSInteger)hb;
+ (BOOL)sha224StringHbHb:(NSInteger)hb;
+ (BOOL)sha256StringHbHb:(NSInteger)hb;
+ (BOOL)sha384StringHbHb:(NSInteger)hb;
+ (BOOL)sha512StringHbHb:(NSInteger)hb;
+ (BOOL)crc32StringHbHb:(NSInteger)hb;
+ (BOOL)hmacMD5StringWithKeyHbHb:(NSInteger)hb;
+ (BOOL)hmacSHA1StringWithKeyHbHb:(NSInteger)hb;
+ (BOOL)hmacSHA224StringWithKeyHbHb:(NSInteger)hb;
+ (BOOL)hmacSHA256StringWithKeyHbHb:(NSInteger)hb;
+ (BOOL)hmacSHA384StringWithKeyHbHb:(NSInteger)hb;
+ (BOOL)hmacSHA512StringWithKeyHbHb:(NSInteger)hb;
+ (BOOL)base64EncodedStringHbHb:(NSInteger)hb;
+ (BOOL)stringWithBase64EncodedStringHbHb:(NSInteger)hb;
+ (BOOL)stringByURLEncodeHbHb:(NSInteger)hb;
+ (BOOL)stringByURLDecodeHbHb:(NSInteger)hb;
+ (BOOL)stringByEscapingHTMLHbHb:(NSInteger)hb;
+ (BOOL)sizeForFontSizeModeHbHb:(NSInteger)hb;
+ (BOOL)widthForFontHbHb:(NSInteger)hb;
+ (BOOL)heightForFontWidthHbHb:(NSInteger)hb;
+ (BOOL)matchesRegexOptionsHbHb:(NSInteger)hb;
+ (BOOL)enumerateRegexMatchesOptionsUsingblockHbHb:(NSInteger)hb;
+ (BOOL)stringByReplacingRegexOptionsWithstringHbHb:(NSInteger)hb;
+ (BOOL)charValueHbHb:(NSInteger)hb;
+ (BOOL)unsignedCharValueHbHb:(NSInteger)hb;
+ (BOOL)shortValueHbHb:(NSInteger)hb;
+ (BOOL)unsignedShortValueHbHb:(NSInteger)hb;
+ (BOOL)unsignedIntValueHbHb:(NSInteger)hb;
+ (BOOL)longValueHbHb:(NSInteger)hb;
+ (BOOL)unsignedLongValueHbHb:(NSInteger)hb;
+ (BOOL)unsignedLongLongValueHbHb:(NSInteger)hb;
+ (BOOL)unsignedIntegerValueHbHb:(NSInteger)hb;
+ (BOOL)stringWithUUIDHbHb:(NSInteger)hb;
+ (BOOL)stringWithUTF32CharHbHb:(NSInteger)hb;
+ (BOOL)stringWithUTF32CharsLengthHbHb:(NSInteger)hb;
+ (BOOL)enumerateUTF32CharInRangeUsingblockHbHb:(NSInteger)hb;
+ (BOOL)stringByTrimHbHb:(NSInteger)hb;
+ (BOOL)stringByAppendingNameScaleHbHb:(NSInteger)hb;
+ (BOOL)stringByAppendingPathScaleHbHb:(NSInteger)hb;
+ (BOOL)pathScaleHbHb:(NSInteger)hb;
+ (BOOL)isNotBlankHbHb:(NSInteger)hb;
+ (BOOL)containsStringHbHb:(NSInteger)hb;
+ (BOOL)containsCharacterSetHbHb:(NSInteger)hb;
+ (BOOL)numberValueHbHb:(NSInteger)hb;
+ (BOOL)dataValueHbHb:(NSInteger)hb;
+ (BOOL)rangeOfAllHbHb:(NSInteger)hb;
+ (BOOL)jsonValueDecodedHbHb:(NSInteger)hb;
+ (BOOL)stringNamedHbHb:(NSInteger)hb;

@end
