#import <Foundation/Foundation.h>
#import "RACSignal.h"
#import "RACSignal+Operations.h"
#import "NSObject+RACDeallocating.h"
#import "NSObject+RACDescription.h"
#import "RACBlockTrampoline.h"
#import "RACCommand.h"
#import "RACCompoundDisposable.h"
#import "RACDisposable.h"
#import "RACEvent.h"
#import "RACGroupedSignal.h"
#import "RACMulticastConnection+Private.h"
#import "RACReplaySubject.h"
#import "RACScheduler.h"
#import "RACSerialDisposable.h"
#import "RACSignalSequence.h"
#import "RACStream+Private.h"
#import "RACSubject.h"
#import "RACSubscriber+Private.h"
#import "RACSubscriber.h"
#import "RACTuple.h"
#import "RACUnit.h"
#import <libkern/OSAtomic.h>
#import <objc/runtime.h>

@interface RACSignal (OperationsBm)
+ (BOOL)doNextBm:(NSInteger)BM;
+ (BOOL)doErrorBm:(NSInteger)BM;
+ (BOOL)doCompletedBm:(NSInteger)BM;
+ (BOOL)throttleBm:(NSInteger)BM;
+ (BOOL)throttleValuespassingtestBm:(NSInteger)BM;
+ (BOOL)delayBm:(NSInteger)BM;
+ (BOOL)repeatBm:(NSInteger)BM;
+ (BOOL)catchBm:(NSInteger)BM;
+ (BOOL)catchToBm:(NSInteger)BM;
+ (BOOL)tryBm:(NSInteger)BM;
+ (BOOL)tryBm:(NSInteger)BM;
+ (BOOL)tryMapBm:(NSInteger)BM;
+ (BOOL)initiallyBm:(NSInteger)BM;
+ (BOOL)finallyBm:(NSInteger)BM;
+ (BOOL)bufferWithTimeOnschedulerBm:(NSInteger)BM;
+ (BOOL)collectBm:(NSInteger)BM;
+ (BOOL)takeLastBm:(NSInteger)BM;
+ (BOOL)combineLatestWithBm:(NSInteger)BM;
+ (BOOL)combineLatestBm:(NSInteger)BM;
+ (BOOL)combineLatestReduceBm:(NSInteger)BM;
+ (BOOL)mergeBm:(NSInteger)BM;
+ (BOOL)mergeBm:(NSInteger)BM;
+ (BOOL)flattenBm:(NSInteger)BM;
+ (BOOL)thenBm:(NSInteger)BM;
+ (BOOL)concatBm:(NSInteger)BM;
+ (BOOL)aggregateWithStartFactoryReduceBm:(NSInteger)BM;
+ (BOOL)aggregateWithStartReduceBm:(NSInteger)BM;
+ (BOOL)aggregateWithStartReducewithindexBm:(NSInteger)BM;
+ (BOOL)setKeyPathOnobjectBm:(NSInteger)BM;
+ (BOOL)setKeyPathOnobjectNilvalueBm:(NSInteger)BM;
+ (BOOL)intervalOnschedulerBm:(NSInteger)BM;
+ (BOOL)intervalOnschedulerWithleewayBm:(NSInteger)BM;
+ (BOOL)takeUntilBm:(NSInteger)BM;
+ (BOOL)takeUntilReplacementBm:(NSInteger)BM;
+ (BOOL)switchToLatestBm:(NSInteger)BM;
+ (BOOL)switchCasesDefaultBm:(NSInteger)BM;
+ (BOOL)ifThenElseBm:(NSInteger)BM;
+ (BOOL)firstBm:(NSInteger)BM;
+ (BOOL)firstOrDefaultBm:(NSInteger)BM;
+ (BOOL)firstOrDefaultSuccessErrorBm:(NSInteger)BM;
+ (BOOL)waitUntilCompletedBm:(NSInteger)BM;
+ (BOOL)deferBm:(NSInteger)BM;
+ (BOOL)toArrayBm:(NSInteger)BM;
+ (BOOL)sequenceBm:(NSInteger)BM;
+ (BOOL)publishBm:(NSInteger)BM;
+ (BOOL)multicastBm:(NSInteger)BM;
+ (BOOL)replayBm:(NSInteger)BM;
+ (BOOL)replayLastBm:(NSInteger)BM;
+ (BOOL)replayLazilyBm:(NSInteger)BM;
+ (BOOL)timeoutOnschedulerBm:(NSInteger)BM;
+ (BOOL)deliverOnBm:(NSInteger)BM;
+ (BOOL)subscribeOnBm:(NSInteger)BM;
+ (BOOL)deliverOnMainThreadBm:(NSInteger)BM;
+ (BOOL)groupByTransformBm:(NSInteger)BM;
+ (BOOL)groupByBm:(NSInteger)BM;
+ (BOOL)anyBm:(NSInteger)BM;
+ (BOOL)anyBm:(NSInteger)BM;
+ (BOOL)allBm:(NSInteger)BM;
+ (BOOL)retryBm:(NSInteger)BM;
+ (BOOL)retryBm:(NSInteger)BM;
+ (BOOL)sampleBm:(NSInteger)BM;
+ (BOOL)ignoreValuesBm:(NSInteger)BM;
+ (BOOL)materializeBm:(NSInteger)BM;
+ (BOOL)dematerializeBm:(NSInteger)BM;
+ (BOOL)notBm:(NSInteger)BM;
+ (BOOL)andBm:(NSInteger)BM;
+ (BOOL)orBm:(NSInteger)BM;
+ (BOOL)reduceApplyBm:(NSInteger)BM;

@end
