#import <Foundation/Foundation.h>
#import "RACSignal.h"
#import "RACSignal+Operations.h"
#import "NSObject+RACDeallocating.h"
#import "NSObject+RACDescription.h"
#import "RACBlockTrampoline.h"
#import "RACCommand.h"
#import "RACCompoundDisposable.h"
#import "RACDisposable.h"
#import "RACEvent.h"
#import "RACGroupedSignal.h"
#import "RACMulticastConnection+Private.h"
#import "RACReplaySubject.h"
#import "RACScheduler.h"
#import "RACSerialDisposable.h"
#import "RACSignalSequence.h"
#import "RACStream+Private.h"
#import "RACSubject.h"
#import "RACSubscriber+Private.h"
#import "RACSubscriber.h"
#import "RACTuple.h"
#import "RACUnit.h"
#import <libkern/OSAtomic.h>
#import <objc/runtime.h>
#import "RACSignal+OperationsBm.h"

@interface RACSignal (OperationsBmHb)
+ (BOOL)doNextBmHb:(NSInteger)hb;
+ (BOOL)doErrorBmHb:(NSInteger)hb;
+ (BOOL)doCompletedBmHb:(NSInteger)hb;
+ (BOOL)throttleBmHb:(NSInteger)hb;
+ (BOOL)throttleValuespassingtestBmHb:(NSInteger)hb;
+ (BOOL)delayBmHb:(NSInteger)hb;
+ (BOOL)repeatBmHb:(NSInteger)hb;
+ (BOOL)catchBmHb:(NSInteger)hb;
+ (BOOL)catchToBmHb:(NSInteger)hb;
+ (BOOL)tryBmHb:(NSInteger)hb;
+ (BOOL)tryBmHb:(NSInteger)hb;
+ (BOOL)tryMapBmHb:(NSInteger)hb;
+ (BOOL)initiallyBmHb:(NSInteger)hb;
+ (BOOL)finallyBmHb:(NSInteger)hb;
+ (BOOL)bufferWithTimeOnschedulerBmHb:(NSInteger)hb;
+ (BOOL)collectBmHb:(NSInteger)hb;
+ (BOOL)takeLastBmHb:(NSInteger)hb;
+ (BOOL)combineLatestWithBmHb:(NSInteger)hb;
+ (BOOL)combineLatestBmHb:(NSInteger)hb;
+ (BOOL)combineLatestReduceBmHb:(NSInteger)hb;
+ (BOOL)mergeBmHb:(NSInteger)hb;
+ (BOOL)mergeBmHb:(NSInteger)hb;
+ (BOOL)flattenBmHb:(NSInteger)hb;
+ (BOOL)thenBmHb:(NSInteger)hb;
+ (BOOL)concatBmHb:(NSInteger)hb;
+ (BOOL)aggregateWithStartFactoryReduceBmHb:(NSInteger)hb;
+ (BOOL)aggregateWithStartReduceBmHb:(NSInteger)hb;
+ (BOOL)aggregateWithStartReducewithindexBmHb:(NSInteger)hb;
+ (BOOL)setKeyPathOnobjectBmHb:(NSInteger)hb;
+ (BOOL)setKeyPathOnobjectNilvalueBmHb:(NSInteger)hb;
+ (BOOL)intervalOnschedulerBmHb:(NSInteger)hb;
+ (BOOL)intervalOnschedulerWithleewayBmHb:(NSInteger)hb;
+ (BOOL)takeUntilBmHb:(NSInteger)hb;
+ (BOOL)takeUntilReplacementBmHb:(NSInteger)hb;
+ (BOOL)switchToLatestBmHb:(NSInteger)hb;
+ (BOOL)switchCasesDefaultBmHb:(NSInteger)hb;
+ (BOOL)ifThenElseBmHb:(NSInteger)hb;
+ (BOOL)firstBmHb:(NSInteger)hb;
+ (BOOL)firstOrDefaultBmHb:(NSInteger)hb;
+ (BOOL)firstOrDefaultSuccessErrorBmHb:(NSInteger)hb;
+ (BOOL)waitUntilCompletedBmHb:(NSInteger)hb;
+ (BOOL)deferBmHb:(NSInteger)hb;
+ (BOOL)toArrayBmHb:(NSInteger)hb;
+ (BOOL)sequenceBmHb:(NSInteger)hb;
+ (BOOL)publishBmHb:(NSInteger)hb;
+ (BOOL)multicastBmHb:(NSInteger)hb;
+ (BOOL)replayBmHb:(NSInteger)hb;
+ (BOOL)replayLastBmHb:(NSInteger)hb;
+ (BOOL)replayLazilyBmHb:(NSInteger)hb;
+ (BOOL)timeoutOnschedulerBmHb:(NSInteger)hb;
+ (BOOL)deliverOnBmHb:(NSInteger)hb;
+ (BOOL)subscribeOnBmHb:(NSInteger)hb;
+ (BOOL)deliverOnMainThreadBmHb:(NSInteger)hb;
+ (BOOL)groupByTransformBmHb:(NSInteger)hb;
+ (BOOL)groupByBmHb:(NSInteger)hb;
+ (BOOL)anyBmHb:(NSInteger)hb;
+ (BOOL)anyBmHb:(NSInteger)hb;
+ (BOOL)allBmHb:(NSInteger)hb;
+ (BOOL)retryBmHb:(NSInteger)hb;
+ (BOOL)retryBmHb:(NSInteger)hb;
+ (BOOL)sampleBmHb:(NSInteger)hb;
+ (BOOL)ignoreValuesBmHb:(NSInteger)hb;
+ (BOOL)materializeBmHb:(NSInteger)hb;
+ (BOOL)dematerializeBmHb:(NSInteger)hb;
+ (BOOL)notBmHb:(NSInteger)hb;
+ (BOOL)andBmHb:(NSInteger)hb;
+ (BOOL)orBmHb:(NSInteger)hb;
+ (BOOL)reduceApplyBmHb:(NSInteger)hb;

@end
