#import <Foundation/Foundation.h>
#import "RACSignal.h"
#import "RACSignal+Operations.h"
#import "NSObject+RACDeallocating.h"
#import "NSObject+RACDescription.h"
#import "RACBlockTrampoline.h"
#import "RACCommand.h"
#import "RACCompoundDisposable.h"
#import "RACDisposable.h"
#import "RACEvent.h"
#import "RACGroupedSignal.h"
#import "RACMulticastConnection+Private.h"
#import "RACReplaySubject.h"
#import "RACScheduler.h"
#import "RACSerialDisposable.h"
#import "RACSignalSequence.h"
#import "RACStream+Private.h"
#import "RACSubject.h"
#import "RACSubscriber+Private.h"
#import "RACSubscriber.h"
#import "RACTuple.h"
#import "RACUnit.h"
#import <libkern/OSAtomic.h>
#import <objc/runtime.h>

@interface RACSignal (OperationsHb)
+ (BOOL)doNextHb:(NSInteger)hb;
+ (BOOL)doErrorHb:(NSInteger)hb;
+ (BOOL)doCompletedHb:(NSInteger)hb;
+ (BOOL)throttleHb:(NSInteger)hb;
+ (BOOL)throttleValuespassingtestHb:(NSInteger)hb;
+ (BOOL)delayHb:(NSInteger)hb;
+ (BOOL)repeatHb:(NSInteger)hb;
+ (BOOL)catchHb:(NSInteger)hb;
+ (BOOL)catchToHb:(NSInteger)hb;
+ (BOOL)tryHb:(NSInteger)hb;
+ (BOOL)tryHb:(NSInteger)hb;
+ (BOOL)tryMapHb:(NSInteger)hb;
+ (BOOL)initiallyHb:(NSInteger)hb;
+ (BOOL)finallyHb:(NSInteger)hb;
+ (BOOL)bufferWithTimeOnschedulerHb:(NSInteger)hb;
+ (BOOL)collectHb:(NSInteger)hb;
+ (BOOL)takeLastHb:(NSInteger)hb;
+ (BOOL)combineLatestWithHb:(NSInteger)hb;
+ (BOOL)combineLatestHb:(NSInteger)hb;
+ (BOOL)combineLatestReduceHb:(NSInteger)hb;
+ (BOOL)mergeHb:(NSInteger)hb;
+ (BOOL)mergeHb:(NSInteger)hb;
+ (BOOL)flattenHb:(NSInteger)hb;
+ (BOOL)thenHb:(NSInteger)hb;
+ (BOOL)concatHb:(NSInteger)hb;
+ (BOOL)aggregateWithStartFactoryReduceHb:(NSInteger)hb;
+ (BOOL)aggregateWithStartReduceHb:(NSInteger)hb;
+ (BOOL)aggregateWithStartReducewithindexHb:(NSInteger)hb;
+ (BOOL)setKeyPathOnobjectHb:(NSInteger)hb;
+ (BOOL)setKeyPathOnobjectNilvalueHb:(NSInteger)hb;
+ (BOOL)intervalOnschedulerHb:(NSInteger)hb;
+ (BOOL)intervalOnschedulerWithleewayHb:(NSInteger)hb;
+ (BOOL)takeUntilHb:(NSInteger)hb;
+ (BOOL)takeUntilReplacementHb:(NSInteger)hb;
+ (BOOL)switchToLatestHb:(NSInteger)hb;
+ (BOOL)switchCasesDefaultHb:(NSInteger)hb;
+ (BOOL)ifThenElseHb:(NSInteger)hb;
+ (BOOL)firstHb:(NSInteger)hb;
+ (BOOL)firstOrDefaultHb:(NSInteger)hb;
+ (BOOL)firstOrDefaultSuccessErrorHb:(NSInteger)hb;
+ (BOOL)waitUntilCompletedHb:(NSInteger)hb;
+ (BOOL)deferHb:(NSInteger)hb;
+ (BOOL)toArrayHb:(NSInteger)hb;
+ (BOOL)sequenceHb:(NSInteger)hb;
+ (BOOL)publishHb:(NSInteger)hb;
+ (BOOL)multicastHb:(NSInteger)hb;
+ (BOOL)replayHb:(NSInteger)hb;
+ (BOOL)replayLastHb:(NSInteger)hb;
+ (BOOL)replayLazilyHb:(NSInteger)hb;
+ (BOOL)timeoutOnschedulerHb:(NSInteger)hb;
+ (BOOL)deliverOnHb:(NSInteger)hb;
+ (BOOL)subscribeOnHb:(NSInteger)hb;
+ (BOOL)deliverOnMainThreadHb:(NSInteger)hb;
+ (BOOL)groupByTransformHb:(NSInteger)hb;
+ (BOOL)groupByHb:(NSInteger)hb;
+ (BOOL)anyHb:(NSInteger)hb;
+ (BOOL)anyHb:(NSInteger)hb;
+ (BOOL)allHb:(NSInteger)hb;
+ (BOOL)retryHb:(NSInteger)hb;
+ (BOOL)retryHb:(NSInteger)hb;
+ (BOOL)sampleHb:(NSInteger)hb;
+ (BOOL)ignoreValuesHb:(NSInteger)hb;
+ (BOOL)materializeHb:(NSInteger)hb;
+ (BOOL)dematerializeHb:(NSInteger)hb;
+ (BOOL)notHb:(NSInteger)hb;
+ (BOOL)andHb:(NSInteger)hb;
+ (BOOL)orHb:(NSInteger)hb;
+ (BOOL)reduceApplyHb:(NSInteger)hb;

@end
