#import <Foundation/Foundation.h>
#import "RACSignal.h"
#import "RACSignal+Operations.h"
#import "NSObject+RACDeallocating.h"
#import "NSObject+RACDescription.h"
#import "RACBlockTrampoline.h"
#import "RACCommand.h"
#import "RACCompoundDisposable.h"
#import "RACDisposable.h"
#import "RACEvent.h"
#import "RACGroupedSignal.h"
#import "RACMulticastConnection+Private.h"
#import "RACReplaySubject.h"
#import "RACScheduler.h"
#import "RACSerialDisposable.h"
#import "RACSignalSequence.h"
#import "RACStream+Private.h"
#import "RACSubject.h"
#import "RACSubscriber+Private.h"
#import "RACSubscriber.h"
#import "RACTuple.h"
#import "RACUnit.h"
#import <libkern/OSAtomic.h>
#import <objc/runtime.h>
#import "RACSignal+OperationsBm.h"

@interface RACSignal (OperationsBm-Deletecomments)
+ (BOOL)doNextBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)doErrorBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)doCompletedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)throttleBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)throttleValuespassingtestBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)delayBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)repeatBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)catchBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)catchToBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tryBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tryBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tryMapBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initiallyBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)finallyBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bufferWithTimeOnschedulerBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)collectBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)takeLastBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)combineLatestWithBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)combineLatestBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)combineLatestReduceBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)mergeBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)mergeBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)flattenBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)thenBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)concatBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aggregateWithStartFactoryReduceBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aggregateWithStartReduceBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aggregateWithStartReducewithindexBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setKeyPathOnobjectBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setKeyPathOnobjectNilvalueBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)intervalOnschedulerBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)intervalOnschedulerWithleewayBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)takeUntilBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)takeUntilReplacementBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)switchToLatestBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)switchCasesDefaultBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ifThenElseBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)firstBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)firstOrDefaultBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)firstOrDefaultSuccessErrorBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)waitUntilCompletedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)deferBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)toArrayBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sequenceBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)publishBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)multicastBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)replayBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)replayLastBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)replayLazilyBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)timeoutOnschedulerBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)deliverOnBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)subscribeOnBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)deliverOnMainThreadBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)groupByTransformBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)groupByBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)anyBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)anyBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)allBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)retryBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)retryBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sampleBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ignoreValuesBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)materializeBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dematerializeBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)notBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)andBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)orBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)reduceApplyBm-Deletecomments:(NSInteger)-deleteComments;

@end
