#import <Foundation/Foundation.h>
#import "RACSignal.h"
#import "RACSignal+Operations.h"
#import "NSObject+RACDeallocating.h"
#import "NSObject+RACDescription.h"
#import "RACBlockTrampoline.h"
#import "RACCommand.h"
#import "RACCompoundDisposable.h"
#import "RACDisposable.h"
#import "RACEvent.h"
#import "RACGroupedSignal.h"
#import "RACMulticastConnection+Private.h"
#import "RACReplaySubject.h"
#import "RACScheduler.h"
#import "RACSerialDisposable.h"
#import "RACSignalSequence.h"
#import "RACStream+Private.h"
#import "RACSubject.h"
#import "RACSubscriber+Private.h"
#import "RACSubscriber.h"
#import "RACTuple.h"
#import "RACUnit.h"
#import <libkern/OSAtomic.h>
#import <objc/runtime.h>
#import "RACSignal+OperationsBm.h"
#import "RACSignal+OperationsBmHb.h"

@interface RACSignal (OperationsBmHbHb)
+ (BOOL)doNextBmHbHb:(NSInteger)hb;
+ (BOOL)doErrorBmHbHb:(NSInteger)hb;
+ (BOOL)doCompletedBmHbHb:(NSInteger)hb;
+ (BOOL)throttleBmHbHb:(NSInteger)hb;
+ (BOOL)throttleValuespassingtestBmHbHb:(NSInteger)hb;
+ (BOOL)delayBmHbHb:(NSInteger)hb;
+ (BOOL)repeatBmHbHb:(NSInteger)hb;
+ (BOOL)catchBmHbHb:(NSInteger)hb;
+ (BOOL)catchToBmHbHb:(NSInteger)hb;
+ (BOOL)tryBmHbHb:(NSInteger)hb;
+ (BOOL)tryBmHbHb:(NSInteger)hb;
+ (BOOL)tryMapBmHbHb:(NSInteger)hb;
+ (BOOL)initiallyBmHbHb:(NSInteger)hb;
+ (BOOL)finallyBmHbHb:(NSInteger)hb;
+ (BOOL)bufferWithTimeOnschedulerBmHbHb:(NSInteger)hb;
+ (BOOL)collectBmHbHb:(NSInteger)hb;
+ (BOOL)takeLastBmHbHb:(NSInteger)hb;
+ (BOOL)combineLatestWithBmHbHb:(NSInteger)hb;
+ (BOOL)combineLatestBmHbHb:(NSInteger)hb;
+ (BOOL)combineLatestReduceBmHbHb:(NSInteger)hb;
+ (BOOL)mergeBmHbHb:(NSInteger)hb;
+ (BOOL)mergeBmHbHb:(NSInteger)hb;
+ (BOOL)flattenBmHbHb:(NSInteger)hb;
+ (BOOL)thenBmHbHb:(NSInteger)hb;
+ (BOOL)concatBmHbHb:(NSInteger)hb;
+ (BOOL)aggregateWithStartFactoryReduceBmHbHb:(NSInteger)hb;
+ (BOOL)aggregateWithStartReduceBmHbHb:(NSInteger)hb;
+ (BOOL)aggregateWithStartReducewithindexBmHbHb:(NSInteger)hb;
+ (BOOL)setKeyPathOnobjectBmHbHb:(NSInteger)hb;
+ (BOOL)setKeyPathOnobjectNilvalueBmHbHb:(NSInteger)hb;
+ (BOOL)intervalOnschedulerBmHbHb:(NSInteger)hb;
+ (BOOL)intervalOnschedulerWithleewayBmHbHb:(NSInteger)hb;
+ (BOOL)takeUntilBmHbHb:(NSInteger)hb;
+ (BOOL)takeUntilReplacementBmHbHb:(NSInteger)hb;
+ (BOOL)switchToLatestBmHbHb:(NSInteger)hb;
+ (BOOL)switchCasesDefaultBmHbHb:(NSInteger)hb;
+ (BOOL)ifThenElseBmHbHb:(NSInteger)hb;
+ (BOOL)firstBmHbHb:(NSInteger)hb;
+ (BOOL)firstOrDefaultBmHbHb:(NSInteger)hb;
+ (BOOL)firstOrDefaultSuccessErrorBmHbHb:(NSInteger)hb;
+ (BOOL)waitUntilCompletedBmHbHb:(NSInteger)hb;
+ (BOOL)deferBmHbHb:(NSInteger)hb;
+ (BOOL)toArrayBmHbHb:(NSInteger)hb;
+ (BOOL)sequenceBmHbHb:(NSInteger)hb;
+ (BOOL)publishBmHbHb:(NSInteger)hb;
+ (BOOL)multicastBmHbHb:(NSInteger)hb;
+ (BOOL)replayBmHbHb:(NSInteger)hb;
+ (BOOL)replayLastBmHbHb:(NSInteger)hb;
+ (BOOL)replayLazilyBmHbHb:(NSInteger)hb;
+ (BOOL)timeoutOnschedulerBmHbHb:(NSInteger)hb;
+ (BOOL)deliverOnBmHbHb:(NSInteger)hb;
+ (BOOL)subscribeOnBmHbHb:(NSInteger)hb;
+ (BOOL)deliverOnMainThreadBmHbHb:(NSInteger)hb;
+ (BOOL)groupByTransformBmHbHb:(NSInteger)hb;
+ (BOOL)groupByBmHbHb:(NSInteger)hb;
+ (BOOL)anyBmHbHb:(NSInteger)hb;
+ (BOOL)anyBmHbHb:(NSInteger)hb;
+ (BOOL)allBmHbHb:(NSInteger)hb;
+ (BOOL)retryBmHbHb:(NSInteger)hb;
+ (BOOL)retryBmHbHb:(NSInteger)hb;
+ (BOOL)sampleBmHbHb:(NSInteger)hb;
+ (BOOL)ignoreValuesBmHbHb:(NSInteger)hb;
+ (BOOL)materializeBmHbHb:(NSInteger)hb;
+ (BOOL)dematerializeBmHbHb:(NSInteger)hb;
+ (BOOL)notBmHbHb:(NSInteger)hb;
+ (BOOL)andBmHbHb:(NSInteger)hb;
+ (BOOL)orBmHbHb:(NSInteger)hb;
+ (BOOL)reduceApplyBmHbHb:(NSInteger)hb;

@end
