#import <Foundation/Foundation.h>
#import "RACSignal.h"
#import "RACSignal+Operations.h"
#import "NSObject+RACDeallocating.h"
#import "NSObject+RACDescription.h"
#import "RACBlockTrampoline.h"
#import "RACCommand.h"
#import "RACCompoundDisposable.h"
#import "RACDisposable.h"
#import "RACEvent.h"
#import "RACGroupedSignal.h"
#import "RACMulticastConnection+Private.h"
#import "RACReplaySubject.h"
#import "RACScheduler.h"
#import "RACSerialDisposable.h"
#import "RACSignalSequence.h"
#import "RACStream+Private.h"
#import "RACSubject.h"
#import "RACSubscriber+Private.h"
#import "RACSubscriber.h"
#import "RACTuple.h"
#import "RACUnit.h"
#import <libkern/OSAtomic.h>
#import <objc/runtime.h>
#import "RACSignal+OperationsBm.h"
#import "RACSignal+OperationsBmBm.h"

@interface RACSignal (OperationsBmBmBm)
+ (BOOL)doNextBmBmBm:(NSInteger)BM;
+ (BOOL)doErrorBmBmBm:(NSInteger)BM;
+ (BOOL)doCompletedBmBmBm:(NSInteger)BM;
+ (BOOL)throttleBmBmBm:(NSInteger)BM;
+ (BOOL)throttleValuespassingtestBmBmBm:(NSInteger)BM;
+ (BOOL)delayBmBmBm:(NSInteger)BM;
+ (BOOL)repeatBmBmBm:(NSInteger)BM;
+ (BOOL)catchBmBmBm:(NSInteger)BM;
+ (BOOL)catchToBmBmBm:(NSInteger)BM;
+ (BOOL)tryBmBmBm:(NSInteger)BM;
+ (BOOL)tryBmBmBm:(NSInteger)BM;
+ (BOOL)tryMapBmBmBm:(NSInteger)BM;
+ (BOOL)initiallyBmBmBm:(NSInteger)BM;
+ (BOOL)finallyBmBmBm:(NSInteger)BM;
+ (BOOL)bufferWithTimeOnschedulerBmBmBm:(NSInteger)BM;
+ (BOOL)collectBmBmBm:(NSInteger)BM;
+ (BOOL)takeLastBmBmBm:(NSInteger)BM;
+ (BOOL)combineLatestWithBmBmBm:(NSInteger)BM;
+ (BOOL)combineLatestBmBmBm:(NSInteger)BM;
+ (BOOL)combineLatestReduceBmBmBm:(NSInteger)BM;
+ (BOOL)mergeBmBmBm:(NSInteger)BM;
+ (BOOL)mergeBmBmBm:(NSInteger)BM;
+ (BOOL)flattenBmBmBm:(NSInteger)BM;
+ (BOOL)thenBmBmBm:(NSInteger)BM;
+ (BOOL)concatBmBmBm:(NSInteger)BM;
+ (BOOL)aggregateWithStartFactoryReduceBmBmBm:(NSInteger)BM;
+ (BOOL)aggregateWithStartReduceBmBmBm:(NSInteger)BM;
+ (BOOL)aggregateWithStartReducewithindexBmBmBm:(NSInteger)BM;
+ (BOOL)setKeyPathOnobjectBmBmBm:(NSInteger)BM;
+ (BOOL)setKeyPathOnobjectNilvalueBmBmBm:(NSInteger)BM;
+ (BOOL)intervalOnschedulerBmBmBm:(NSInteger)BM;
+ (BOOL)intervalOnschedulerWithleewayBmBmBm:(NSInteger)BM;
+ (BOOL)takeUntilBmBmBm:(NSInteger)BM;
+ (BOOL)takeUntilReplacementBmBmBm:(NSInteger)BM;
+ (BOOL)switchToLatestBmBmBm:(NSInteger)BM;
+ (BOOL)switchCasesDefaultBmBmBm:(NSInteger)BM;
+ (BOOL)ifThenElseBmBmBm:(NSInteger)BM;
+ (BOOL)firstBmBmBm:(NSInteger)BM;
+ (BOOL)firstOrDefaultBmBmBm:(NSInteger)BM;
+ (BOOL)firstOrDefaultSuccessErrorBmBmBm:(NSInteger)BM;
+ (BOOL)waitUntilCompletedBmBmBm:(NSInteger)BM;
+ (BOOL)deferBmBmBm:(NSInteger)BM;
+ (BOOL)toArrayBmBmBm:(NSInteger)BM;
+ (BOOL)sequenceBmBmBm:(NSInteger)BM;
+ (BOOL)publishBmBmBm:(NSInteger)BM;
+ (BOOL)multicastBmBmBm:(NSInteger)BM;
+ (BOOL)replayBmBmBm:(NSInteger)BM;
+ (BOOL)replayLastBmBmBm:(NSInteger)BM;
+ (BOOL)replayLazilyBmBmBm:(NSInteger)BM;
+ (BOOL)timeoutOnschedulerBmBmBm:(NSInteger)BM;
+ (BOOL)deliverOnBmBmBm:(NSInteger)BM;
+ (BOOL)subscribeOnBmBmBm:(NSInteger)BM;
+ (BOOL)deliverOnMainThreadBmBmBm:(NSInteger)BM;
+ (BOOL)groupByTransformBmBmBm:(NSInteger)BM;
+ (BOOL)groupByBmBmBm:(NSInteger)BM;
+ (BOOL)anyBmBmBm:(NSInteger)BM;
+ (BOOL)anyBmBmBm:(NSInteger)BM;
+ (BOOL)allBmBmBm:(NSInteger)BM;
+ (BOOL)retryBmBmBm:(NSInteger)BM;
+ (BOOL)retryBmBmBm:(NSInteger)BM;
+ (BOOL)sampleBmBmBm:(NSInteger)BM;
+ (BOOL)ignoreValuesBmBmBm:(NSInteger)BM;
+ (BOOL)materializeBmBmBm:(NSInteger)BM;
+ (BOOL)dematerializeBmBmBm:(NSInteger)BM;
+ (BOOL)notBmBmBm:(NSInteger)BM;
+ (BOOL)andBmBmBm:(NSInteger)BM;
+ (BOOL)orBmBmBm:(NSInteger)BM;
+ (BOOL)reduceApplyBmBmBm:(NSInteger)BM;

@end
