#import <Foundation/Foundation.h>
#import "RACSignal.h"
#import "RACSignal+Operations.h"
#import "NSObject+RACDeallocating.h"
#import "NSObject+RACDescription.h"
#import "RACBlockTrampoline.h"
#import "RACCommand.h"
#import "RACCompoundDisposable.h"
#import "RACDisposable.h"
#import "RACEvent.h"
#import "RACGroupedSignal.h"
#import "RACMulticastConnection+Private.h"
#import "RACReplaySubject.h"
#import "RACScheduler.h"
#import "RACSerialDisposable.h"
#import "RACSignalSequence.h"
#import "RACStream+Private.h"
#import "RACSubject.h"
#import "RACSubscriber+Private.h"
#import "RACSubscriber.h"
#import "RACTuple.h"
#import "RACUnit.h"
#import <libkern/OSAtomic.h>
#import <objc/runtime.h>

@interface RACSignal (Operations-Deletecomments)
+ (BOOL)doNext-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)doError-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)doCompleted-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)throttle-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)throttleValuespassingtest-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)delay-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)repeat-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)catch-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)catchTo-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)try-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)try-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)tryMap-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initially-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)finally-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)bufferWithTimeOnscheduler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)collect-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)takeLast-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)combineLatestWith-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)combineLatest-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)combineLatestReduce-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)merge-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)merge-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)flatten-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)then-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)concat-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aggregateWithStartFactoryReduce-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aggregateWithStartReduce-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aggregateWithStartReducewithindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setKeyPathOnobject-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setKeyPathOnobjectNilvalue-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)intervalOnscheduler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)intervalOnschedulerWithleeway-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)takeUntil-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)takeUntilReplacement-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)switchToLatest-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)switchCasesDefault-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ifThenElse-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)first-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)firstOrDefault-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)firstOrDefaultSuccessError-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)waitUntilCompleted-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)defer-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)toArray-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sequence-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)publish-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)multicast-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)replay-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)replayLast-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)replayLazily-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)timeoutOnscheduler-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)deliverOn-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)subscribeOn-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)deliverOnMainThread-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)groupByTransform-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)groupBy-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)any-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)any-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)all-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)retry-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)retry-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)sample-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)ignoreValues-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)materialize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dematerialize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)not-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)and-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)or-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)reduceApply-Deletecomments:(NSInteger)-deleteComments;

@end
