#import <Foundation/Foundation.h>
#import "RACSignal.h"
#import "RACSignal+Operations.h"
#import "NSObject+RACDeallocating.h"
#import "NSObject+RACDescription.h"
#import "RACBlockTrampoline.h"
#import "RACCommand.h"
#import "RACCompoundDisposable.h"
#import "RACDisposable.h"
#import "RACEvent.h"
#import "RACGroupedSignal.h"
#import "RACMulticastConnection+Private.h"
#import "RACReplaySubject.h"
#import "RACScheduler.h"
#import "RACSerialDisposable.h"
#import "RACSignalSequence.h"
#import "RACStream+Private.h"
#import "RACSubject.h"
#import "RACSubscriber+Private.h"
#import "RACSubscriber.h"
#import "RACTuple.h"
#import "RACUnit.h"
#import <libkern/OSAtomic.h>
#import <objc/runtime.h>
#import "RACSignal+OperationsBm.h"

@interface RACSignal (OperationsBmBm)
+ (BOOL)doNextBmBm:(NSInteger)BM;
+ (BOOL)doErrorBmBm:(NSInteger)BM;
+ (BOOL)doCompletedBmBm:(NSInteger)BM;
+ (BOOL)throttleBmBm:(NSInteger)BM;
+ (BOOL)throttleValuespassingtestBmBm:(NSInteger)BM;
+ (BOOL)delayBmBm:(NSInteger)BM;
+ (BOOL)repeatBmBm:(NSInteger)BM;
+ (BOOL)catchBmBm:(NSInteger)BM;
+ (BOOL)catchToBmBm:(NSInteger)BM;
+ (BOOL)tryBmBm:(NSInteger)BM;
+ (BOOL)tryBmBm:(NSInteger)BM;
+ (BOOL)tryMapBmBm:(NSInteger)BM;
+ (BOOL)initiallyBmBm:(NSInteger)BM;
+ (BOOL)finallyBmBm:(NSInteger)BM;
+ (BOOL)bufferWithTimeOnschedulerBmBm:(NSInteger)BM;
+ (BOOL)collectBmBm:(NSInteger)BM;
+ (BOOL)takeLastBmBm:(NSInteger)BM;
+ (BOOL)combineLatestWithBmBm:(NSInteger)BM;
+ (BOOL)combineLatestBmBm:(NSInteger)BM;
+ (BOOL)combineLatestReduceBmBm:(NSInteger)BM;
+ (BOOL)mergeBmBm:(NSInteger)BM;
+ (BOOL)mergeBmBm:(NSInteger)BM;
+ (BOOL)flattenBmBm:(NSInteger)BM;
+ (BOOL)thenBmBm:(NSInteger)BM;
+ (BOOL)concatBmBm:(NSInteger)BM;
+ (BOOL)aggregateWithStartFactoryReduceBmBm:(NSInteger)BM;
+ (BOOL)aggregateWithStartReduceBmBm:(NSInteger)BM;
+ (BOOL)aggregateWithStartReducewithindexBmBm:(NSInteger)BM;
+ (BOOL)setKeyPathOnobjectBmBm:(NSInteger)BM;
+ (BOOL)setKeyPathOnobjectNilvalueBmBm:(NSInteger)BM;
+ (BOOL)intervalOnschedulerBmBm:(NSInteger)BM;
+ (BOOL)intervalOnschedulerWithleewayBmBm:(NSInteger)BM;
+ (BOOL)takeUntilBmBm:(NSInteger)BM;
+ (BOOL)takeUntilReplacementBmBm:(NSInteger)BM;
+ (BOOL)switchToLatestBmBm:(NSInteger)BM;
+ (BOOL)switchCasesDefaultBmBm:(NSInteger)BM;
+ (BOOL)ifThenElseBmBm:(NSInteger)BM;
+ (BOOL)firstBmBm:(NSInteger)BM;
+ (BOOL)firstOrDefaultBmBm:(NSInteger)BM;
+ (BOOL)firstOrDefaultSuccessErrorBmBm:(NSInteger)BM;
+ (BOOL)waitUntilCompletedBmBm:(NSInteger)BM;
+ (BOOL)deferBmBm:(NSInteger)BM;
+ (BOOL)toArrayBmBm:(NSInteger)BM;
+ (BOOL)sequenceBmBm:(NSInteger)BM;
+ (BOOL)publishBmBm:(NSInteger)BM;
+ (BOOL)multicastBmBm:(NSInteger)BM;
+ (BOOL)replayBmBm:(NSInteger)BM;
+ (BOOL)replayLastBmBm:(NSInteger)BM;
+ (BOOL)replayLazilyBmBm:(NSInteger)BM;
+ (BOOL)timeoutOnschedulerBmBm:(NSInteger)BM;
+ (BOOL)deliverOnBmBm:(NSInteger)BM;
+ (BOOL)subscribeOnBmBm:(NSInteger)BM;
+ (BOOL)deliverOnMainThreadBmBm:(NSInteger)BM;
+ (BOOL)groupByTransformBmBm:(NSInteger)BM;
+ (BOOL)groupByBmBm:(NSInteger)BM;
+ (BOOL)anyBmBm:(NSInteger)BM;
+ (BOOL)anyBmBm:(NSInteger)BM;
+ (BOOL)allBmBm:(NSInteger)BM;
+ (BOOL)retryBmBm:(NSInteger)BM;
+ (BOOL)retryBmBm:(NSInteger)BM;
+ (BOOL)sampleBmBm:(NSInteger)BM;
+ (BOOL)ignoreValuesBmBm:(NSInteger)BM;
+ (BOOL)materializeBmBm:(NSInteger)BM;
+ (BOOL)dematerializeBmBm:(NSInteger)BM;
+ (BOOL)notBmBm:(NSInteger)BM;
+ (BOOL)andBmBm:(NSInteger)BM;
+ (BOOL)orBmBm:(NSInteger)BM;
+ (BOOL)reduceApplyBmBm:(NSInteger)BM;

@end
