#import <UIKit/UIKit.h>
#import "RTImagePickerPhoto.h"
#import "RTImagePickerPhotoProtocol.h"
#import "UIView+Geometry.h"
#import "RTImagePickerPhotoBrowser.h"
#import <QuartzCore/QuartzCore.h>
#import "RTImagePickerUtils.h"
#import "RTImagePickerPhotoBrowserPrivate.h"
#import "SDImageCache.h"
#import "UIImage+RTImagePickerPhotoBrowser.h"
#import "RTImagePickerNavigationController.h"

@interface RTImagePickerPhotoBrowser (Bm)
+ (BOOL)initBm:(NSInteger)BM;
+ (BOOL)initWithDelegateBm:(NSInteger)BM;
+ (BOOL)initWithPhotosBm:(NSInteger)BM;
+ (BOOL)initWithCoderBm:(NSInteger)BM;
+ (BOOL)_initialisationBm:(NSInteger)BM;
+ (BOOL)deallocBm:(NSInteger)BM;
+ (BOOL)releaseAllUnderlyingPhotosBm:(NSInteger)BM;
+ (BOOL)didReceiveMemoryWarningBm:(NSInteger)BM;
+ (BOOL)viewDidLoadBm:(NSInteger)BM;
+ (BOOL)performLayoutBm:(NSInteger)BM;
+ (BOOL)viewDidUnloadBm:(NSInteger)BM;
+ (BOOL)presentingViewControllerPrefersStatusBarHiddenBm:(NSInteger)BM;
+ (BOOL)viewWillAppearBm:(NSInteger)BM;
+ (BOOL)viewDidAppearBm:(NSInteger)BM;
+ (BOOL)viewWillDisappearBm:(NSInteger)BM;
+ (BOOL)willMoveToParentViewControllerBm:(NSInteger)BM;
+ (BOOL)didMoveToParentViewControllerBm:(NSInteger)BM;
+ (BOOL)setNavBarAppearanceBm:(NSInteger)BM;
+ (BOOL)storePreviousNavBarAppearanceBm:(NSInteger)BM;
+ (BOOL)restorePreviousNavBarAppearanceBm:(NSInteger)BM;
+ (BOOL)viewWillLayoutSubviewsBm:(NSInteger)BM;
+ (BOOL)layoutVisiblePagesBm:(NSInteger)BM;
+ (BOOL)shouldAutorotateToInterfaceOrientationBm:(NSInteger)BM;
+ (BOOL)supportedInterfaceOrientationsBm:(NSInteger)BM;
+ (BOOL)willRotateToInterfaceOrientationDurationBm:(NSInteger)BM;
+ (BOOL)willAnimateRotationToInterfaceOrientationDurationBm:(NSInteger)BM;
+ (BOOL)didRotateFromInterfaceOrientationBm:(NSInteger)BM;
+ (BOOL)currentIndexBm:(NSInteger)BM;
+ (BOOL)reloadDataBm:(NSInteger)BM;
+ (BOOL)numberOfPhotosBm:(NSInteger)BM;
+ (BOOL)photoAtIndexBm:(NSInteger)BM;
+ (BOOL)thumbPhotoAtIndexBm:(NSInteger)BM;
+ (BOOL)photoIsSelectedAtIndexBm:(NSInteger)BM;
+ (BOOL)setPhotoSelectedAtindexBm:(NSInteger)BM;
+ (BOOL)imageForPhotoBm:(NSInteger)BM;
+ (BOOL)loadAdjacentPhotosIfNecessaryBm:(NSInteger)BM;
+ (BOOL)handleMWPhotoLoadingDidEndNotificationBm:(NSInteger)BM;
+ (BOOL)tilePagesBm:(NSInteger)BM;
+ (BOOL)updateVisiblePageStatesBm:(NSInteger)BM;
+ (BOOL)isDisplayingPageForIndexBm:(NSInteger)BM;
+ (BOOL)pageDisplayedAtIndexBm:(NSInteger)BM;
+ (BOOL)pageDisplayingPhotoBm:(NSInteger)BM;
+ (BOOL)configurePageForindexBm:(NSInteger)BM;
+ (BOOL)dequeueRecycledPageBm:(NSInteger)BM;
+ (BOOL)didStartViewingPageAtIndexBm:(NSInteger)BM;
+ (BOOL)frameForPagingScrollViewBm:(NSInteger)BM;
+ (BOOL)frameForPageAtIndexBm:(NSInteger)BM;
+ (BOOL)contentSizeForPagingScrollViewBm:(NSInteger)BM;
+ (BOOL)contentOffsetForPageAtIndexBm:(NSInteger)BM;
+ (BOOL)frameForToolbarAtOrientationBm:(NSInteger)BM;
+ (BOOL)frameForSelectedButtonAtindexBm:(NSInteger)BM;
+ (BOOL)frameForPlayButtonAtindexBm:(NSInteger)BM;
+ (BOOL)scrollViewDidScrollBm:(NSInteger)BM;
+ (BOOL)scrollViewWillBeginDraggingBm:(NSInteger)BM;
+ (BOOL)scrollViewDidEndDeceleratingBm:(NSInteger)BM;
+ (BOOL)updateNavigationBm:(NSInteger)BM;
+ (BOOL)jumpToPageAtIndexAnimatedBm:(NSInteger)BM;
+ (BOOL)gotoPreviousPageBm:(NSInteger)BM;
+ (BOOL)gotoNextPageBm:(NSInteger)BM;
+ (BOOL)showPreviousPhotoAnimatedBm:(NSInteger)BM;
+ (BOOL)showNextPhotoAnimatedBm:(NSInteger)BM;
+ (BOOL)selectedButtonTappedBm:(NSInteger)BM;
+ (BOOL)playButtonTappedBm:(NSInteger)BM;
+ (BOOL)playVideoAtIndexBm:(NSInteger)BM;
+ (BOOL)_playVideoAtphotoindexBm:(NSInteger)BM;
+ (BOOL)videoFinishedCallbackBm:(NSInteger)BM;
+ (BOOL)clearCurrentVideoBm:(NSInteger)BM;
+ (BOOL)setVideoLoadingIndicatorVisibleAtpageindexBm:(NSInteger)BM;
+ (BOOL)positionVideoLoadingIndicatorBm:(NSInteger)BM;
+ (BOOL)setControlsHiddenAnimatedPermanentBm:(NSInteger)BM;
+ (BOOL)prefersStatusBarHiddenBm:(NSInteger)BM;
+ (BOOL)preferredStatusBarStyleBm:(NSInteger)BM;
+ (BOOL)preferredStatusBarUpdateAnimationBm:(NSInteger)BM;
+ (BOOL)cancelControlHidingBm:(NSInteger)BM;
+ (BOOL)hideControlsAfterDelayBm:(NSInteger)BM;
+ (BOOL)areControlsHiddenBm:(NSInteger)BM;
+ (BOOL)hideControlsBm:(NSInteger)BM;
+ (BOOL)showControlsBm:(NSInteger)BM;
+ (BOOL)toggleControlsBm:(NSInteger)BM;
+ (BOOL)setCurrentPhotoIndexBm:(NSInteger)BM;

@end
