#import <UIKit/UIKit.h>
#import "RTImagePickerPhoto.h"
#import "RTImagePickerPhotoProtocol.h"
#import "UIView+Geometry.h"
#import "RTImagePickerPhotoBrowser.h"
#import <QuartzCore/QuartzCore.h>
#import "RTImagePickerUtils.h"
#import "RTImagePickerPhotoBrowserPrivate.h"
#import "SDImageCache.h"
#import "UIImage+RTImagePickerPhotoBrowser.h"
#import "RTImagePickerNavigationController.h"
#import "RTImagePickerPhotoBrowser+Bm.h"

@interface RTImagePickerPhotoBrowser (BmBm)
+ (BOOL)initBmBm:(NSInteger)BM;
+ (BOOL)initWithDelegateBmBm:(NSInteger)BM;
+ (BOOL)initWithPhotosBmBm:(NSInteger)BM;
+ (BOOL)initWithCoderBmBm:(NSInteger)BM;
+ (BOOL)_initialisationBmBm:(NSInteger)BM;
+ (BOOL)deallocBmBm:(NSInteger)BM;
+ (BOOL)releaseAllUnderlyingPhotosBmBm:(NSInteger)BM;
+ (BOOL)didReceiveMemoryWarningBmBm:(NSInteger)BM;
+ (BOOL)viewDidLoadBmBm:(NSInteger)BM;
+ (BOOL)performLayoutBmBm:(NSInteger)BM;
+ (BOOL)viewDidUnloadBmBm:(NSInteger)BM;
+ (BOOL)presentingViewControllerPrefersStatusBarHiddenBmBm:(NSInteger)BM;
+ (BOOL)viewWillAppearBmBm:(NSInteger)BM;
+ (BOOL)viewDidAppearBmBm:(NSInteger)BM;
+ (BOOL)viewWillDisappearBmBm:(NSInteger)BM;
+ (BOOL)willMoveToParentViewControllerBmBm:(NSInteger)BM;
+ (BOOL)didMoveToParentViewControllerBmBm:(NSInteger)BM;
+ (BOOL)setNavBarAppearanceBmBm:(NSInteger)BM;
+ (BOOL)storePreviousNavBarAppearanceBmBm:(NSInteger)BM;
+ (BOOL)restorePreviousNavBarAppearanceBmBm:(NSInteger)BM;
+ (BOOL)viewWillLayoutSubviewsBmBm:(NSInteger)BM;
+ (BOOL)layoutVisiblePagesBmBm:(NSInteger)BM;
+ (BOOL)shouldAutorotateToInterfaceOrientationBmBm:(NSInteger)BM;
+ (BOOL)supportedInterfaceOrientationsBmBm:(NSInteger)BM;
+ (BOOL)willRotateToInterfaceOrientationDurationBmBm:(NSInteger)BM;
+ (BOOL)willAnimateRotationToInterfaceOrientationDurationBmBm:(NSInteger)BM;
+ (BOOL)didRotateFromInterfaceOrientationBmBm:(NSInteger)BM;
+ (BOOL)currentIndexBmBm:(NSInteger)BM;
+ (BOOL)reloadDataBmBm:(NSInteger)BM;
+ (BOOL)numberOfPhotosBmBm:(NSInteger)BM;
+ (BOOL)photoAtIndexBmBm:(NSInteger)BM;
+ (BOOL)thumbPhotoAtIndexBmBm:(NSInteger)BM;
+ (BOOL)photoIsSelectedAtIndexBmBm:(NSInteger)BM;
+ (BOOL)setPhotoSelectedAtindexBmBm:(NSInteger)BM;
+ (BOOL)imageForPhotoBmBm:(NSInteger)BM;
+ (BOOL)loadAdjacentPhotosIfNecessaryBmBm:(NSInteger)BM;
+ (BOOL)handleMWPhotoLoadingDidEndNotificationBmBm:(NSInteger)BM;
+ (BOOL)tilePagesBmBm:(NSInteger)BM;
+ (BOOL)updateVisiblePageStatesBmBm:(NSInteger)BM;
+ (BOOL)isDisplayingPageForIndexBmBm:(NSInteger)BM;
+ (BOOL)pageDisplayedAtIndexBmBm:(NSInteger)BM;
+ (BOOL)pageDisplayingPhotoBmBm:(NSInteger)BM;
+ (BOOL)configurePageForindexBmBm:(NSInteger)BM;
+ (BOOL)dequeueRecycledPageBmBm:(NSInteger)BM;
+ (BOOL)didStartViewingPageAtIndexBmBm:(NSInteger)BM;
+ (BOOL)frameForPagingScrollViewBmBm:(NSInteger)BM;
+ (BOOL)frameForPageAtIndexBmBm:(NSInteger)BM;
+ (BOOL)contentSizeForPagingScrollViewBmBm:(NSInteger)BM;
+ (BOOL)contentOffsetForPageAtIndexBmBm:(NSInteger)BM;
+ (BOOL)frameForToolbarAtOrientationBmBm:(NSInteger)BM;
+ (BOOL)frameForSelectedButtonAtindexBmBm:(NSInteger)BM;
+ (BOOL)frameForPlayButtonAtindexBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidScrollBmBm:(NSInteger)BM;
+ (BOOL)scrollViewWillBeginDraggingBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidEndDeceleratingBmBm:(NSInteger)BM;
+ (BOOL)updateNavigationBmBm:(NSInteger)BM;
+ (BOOL)jumpToPageAtIndexAnimatedBmBm:(NSInteger)BM;
+ (BOOL)gotoPreviousPageBmBm:(NSInteger)BM;
+ (BOOL)gotoNextPageBmBm:(NSInteger)BM;
+ (BOOL)showPreviousPhotoAnimatedBmBm:(NSInteger)BM;
+ (BOOL)showNextPhotoAnimatedBmBm:(NSInteger)BM;
+ (BOOL)selectedButtonTappedBmBm:(NSInteger)BM;
+ (BOOL)playButtonTappedBmBm:(NSInteger)BM;
+ (BOOL)playVideoAtIndexBmBm:(NSInteger)BM;
+ (BOOL)_playVideoAtphotoindexBmBm:(NSInteger)BM;
+ (BOOL)videoFinishedCallbackBmBm:(NSInteger)BM;
+ (BOOL)clearCurrentVideoBmBm:(NSInteger)BM;
+ (BOOL)setVideoLoadingIndicatorVisibleAtpageindexBmBm:(NSInteger)BM;
+ (BOOL)positionVideoLoadingIndicatorBmBm:(NSInteger)BM;
+ (BOOL)setControlsHiddenAnimatedPermanentBmBm:(NSInteger)BM;
+ (BOOL)prefersStatusBarHiddenBmBm:(NSInteger)BM;
+ (BOOL)preferredStatusBarStyleBmBm:(NSInteger)BM;
+ (BOOL)preferredStatusBarUpdateAnimationBmBm:(NSInteger)BM;
+ (BOOL)cancelControlHidingBmBm:(NSInteger)BM;
+ (BOOL)hideControlsAfterDelayBmBm:(NSInteger)BM;
+ (BOOL)areControlsHiddenBmBm:(NSInteger)BM;
+ (BOOL)hideControlsBmBm:(NSInteger)BM;
+ (BOOL)showControlsBmBm:(NSInteger)BM;
+ (BOOL)toggleControlsBmBm:(NSInteger)BM;
+ (BOOL)setCurrentPhotoIndexBmBm:(NSInteger)BM;

@end
