#import <UIKit/UIKit.h>
#import "SDCycleScrollView.h"
#import "SDCollectionViewCell.h"
#import "UIView+SDExtension.h"
#import "TAPageControl.h"
#import "SDWebImageManager.h"
#import "UIImageView+WebCache.h"

@interface SDCycleScrollView (Bm)
+ (BOOL)initWithFrameBm:(NSInteger)BM;
+ (BOOL)awakeFromNibBm:(NSInteger)BM;
+ (BOOL)initializationBm:(NSInteger)BM;
+ (BOOL)cycleScrollViewWithFrameImagenamesgroupBm:(NSInteger)BM;
+ (BOOL)cycleScrollViewWithFrameShouldinfiniteloopImagenamesgroupBm:(NSInteger)BM;
+ (BOOL)cycleScrollViewWithFrameImageurlstringsgroupBm:(NSInteger)BM;
+ (BOOL)cycleScrollViewWithFrameDelegatePlaceholderimageBm:(NSInteger)BM;
+ (BOOL)setupMainViewBm:(NSInteger)BM;
+ (BOOL)setDelegateBm:(NSInteger)BM;
+ (BOOL)setPlaceholderImageBm:(NSInteger)BM;
+ (BOOL)setPageControlDotSizeBm:(NSInteger)BM;
+ (BOOL)setShowPageControlBm:(NSInteger)BM;
+ (BOOL)setCurrentPageDotColorBm:(NSInteger)BM;
+ (BOOL)setPageDotColorBm:(NSInteger)BM;
+ (BOOL)setCurrentPageDotImageBm:(NSInteger)BM;
+ (BOOL)setPageDotImageBm:(NSInteger)BM;
+ (BOOL)setCustomPageControlDotImageIscurrentpagedotBm:(NSInteger)BM;
+ (BOOL)setInfiniteLoopBm:(NSInteger)BM;
+ (BOOL)setAutoScrollBm:(NSInteger)BM;
+ (BOOL)setScrollDirectionBm:(NSInteger)BM;
+ (BOOL)setAutoScrollTimeIntervalBm:(NSInteger)BM;
+ (BOOL)setPageControlStyleBm:(NSInteger)BM;
+ (BOOL)setImagePathsGroupBm:(NSInteger)BM;
+ (BOOL)setImageURLStringsGroupBm:(NSInteger)BM;
+ (BOOL)setLocalizationImageNamesGroupBm:(NSInteger)BM;
+ (BOOL)setTitlesGroupBm:(NSInteger)BM;
+ (BOOL)disableScrollGestureBm:(NSInteger)BM;
+ (BOOL)setupTimerBm:(NSInteger)BM;
+ (BOOL)invalidateTimerBm:(NSInteger)BM;
+ (BOOL)setupPageControlBm:(NSInteger)BM;
+ (BOOL)automaticScrollBm:(NSInteger)BM;
+ (BOOL)scrollToIndexBm:(NSInteger)BM;
+ (BOOL)currentIndexBm:(NSInteger)BM;
+ (BOOL)pageControlIndexWithCurrentCellIndexBm:(NSInteger)BM;
+ (BOOL)clearCacheBm:(NSInteger)BM;
+ (BOOL)clearImagesCacheBm:(NSInteger)BM;
+ (BOOL)layoutSubviewsBm:(NSInteger)BM;
+ (BOOL)willMoveToSuperviewBm:(NSInteger)BM;
+ (BOOL)deallocBm:(NSInteger)BM;
+ (BOOL)adjustWhenControllerViewWillApperaBm:(NSInteger)BM;
+ (BOOL)collectionViewNumberofitemsinsectionBm:(NSInteger)BM;
+ (BOOL)collectionViewCellforitematindexpathBm:(NSInteger)BM;
+ (BOOL)collectionViewDidselectitematindexpathBm:(NSInteger)BM;
+ (BOOL)scrollViewDidScrollBm:(NSInteger)BM;
+ (BOOL)scrollViewWillBeginDraggingBm:(NSInteger)BM;
+ (BOOL)scrollViewDidEndDraggingWilldecelerateBm:(NSInteger)BM;
+ (BOOL)scrollViewDidEndDeceleratingBm:(NSInteger)BM;
+ (BOOL)scrollViewDidEndScrollingAnimationBm:(NSInteger)BM;
+ (BOOL)makeScrollViewScrollToIndexBm:(NSInteger)BM;

@end
