#import <UIKit/UIKit.h>
#import "SDCycleScrollView.h"
#import "SDCollectionViewCell.h"
#import "UIView+SDExtension.h"
#import "TAPageControl.h"
#import "SDWebImageManager.h"
#import "UIImageView+WebCache.h"

@interface SDCycleScrollView (-Deletecomments)
+ (BOOL)initWithFrame-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)awakeFromNib-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initialization-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cycleScrollViewWithFrameImagenamesgroup-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cycleScrollViewWithFrameShouldinfiniteloopImagenamesgroup-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cycleScrollViewWithFrameImageurlstringsgroup-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cycleScrollViewWithFrameDelegatePlaceholderimage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setupMainView-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setDelegate-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setPlaceholderImage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setPageControlDotSize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setShowPageControl-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCurrentPageDotColor-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setPageDotColor-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCurrentPageDotImage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setPageDotImage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCustomPageControlDotImageIscurrentpagedot-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setInfiniteLoop-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAutoScroll-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setScrollDirection-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAutoScrollTimeInterval-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setPageControlStyle-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setImagePathsGroup-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setImageURLStringsGroup-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setLocalizationImageNamesGroup-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTitlesGroup-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)disableScrollGesture-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setupTimer-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)invalidateTimer-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setupPageControl-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)automaticScroll-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollToIndex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)currentIndex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)pageControlIndexWithCurrentCellIndex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)clearCache-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)clearImagesCache-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)layoutSubviews-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)willMoveToSuperview-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dealloc-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)adjustWhenControllerViewWillAppera-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)collectionViewNumberofitemsinsection-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)collectionViewCellforitematindexpath-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)collectionViewDidselectitematindexpath-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidScroll-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewWillBeginDragging-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidEndDraggingWilldecelerate-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidEndDecelerating-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidEndScrollingAnimation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)makeScrollViewScrollToIndex-Deletecomments:(NSInteger)-deleteComments;

@end
