#import <UIKit/UIKit.h>
#import "SDCycleScrollView.h"
#import "SDCollectionViewCell.h"
#import "UIView+SDExtension.h"
#import "TAPageControl.h"
#import "SDWebImageManager.h"
#import "UIImageView+WebCache.h"
#import "SDCycleScrollView+Bm.h"

@interface SDCycleScrollView (BmBm)
+ (BOOL)initWithFrameBmBm:(NSInteger)BM;
+ (BOOL)awakeFromNibBmBm:(NSInteger)BM;
+ (BOOL)initializationBmBm:(NSInteger)BM;
+ (BOOL)cycleScrollViewWithFrameImagenamesgroupBmBm:(NSInteger)BM;
+ (BOOL)cycleScrollViewWithFrameShouldinfiniteloopImagenamesgroupBmBm:(NSInteger)BM;
+ (BOOL)cycleScrollViewWithFrameImageurlstringsgroupBmBm:(NSInteger)BM;
+ (BOOL)cycleScrollViewWithFrameDelegatePlaceholderimageBmBm:(NSInteger)BM;
+ (BOOL)setupMainViewBmBm:(NSInteger)BM;
+ (BOOL)setDelegateBmBm:(NSInteger)BM;
+ (BOOL)setPlaceholderImageBmBm:(NSInteger)BM;
+ (BOOL)setPageControlDotSizeBmBm:(NSInteger)BM;
+ (BOOL)setShowPageControlBmBm:(NSInteger)BM;
+ (BOOL)setCurrentPageDotColorBmBm:(NSInteger)BM;
+ (BOOL)setPageDotColorBmBm:(NSInteger)BM;
+ (BOOL)setCurrentPageDotImageBmBm:(NSInteger)BM;
+ (BOOL)setPageDotImageBmBm:(NSInteger)BM;
+ (BOOL)setCustomPageControlDotImageIscurrentpagedotBmBm:(NSInteger)BM;
+ (BOOL)setInfiniteLoopBmBm:(NSInteger)BM;
+ (BOOL)setAutoScrollBmBm:(NSInteger)BM;
+ (BOOL)setScrollDirectionBmBm:(NSInteger)BM;
+ (BOOL)setAutoScrollTimeIntervalBmBm:(NSInteger)BM;
+ (BOOL)setPageControlStyleBmBm:(NSInteger)BM;
+ (BOOL)setImagePathsGroupBmBm:(NSInteger)BM;
+ (BOOL)setImageURLStringsGroupBmBm:(NSInteger)BM;
+ (BOOL)setLocalizationImageNamesGroupBmBm:(NSInteger)BM;
+ (BOOL)setTitlesGroupBmBm:(NSInteger)BM;
+ (BOOL)disableScrollGestureBmBm:(NSInteger)BM;
+ (BOOL)setupTimerBmBm:(NSInteger)BM;
+ (BOOL)invalidateTimerBmBm:(NSInteger)BM;
+ (BOOL)setupPageControlBmBm:(NSInteger)BM;
+ (BOOL)automaticScrollBmBm:(NSInteger)BM;
+ (BOOL)scrollToIndexBmBm:(NSInteger)BM;
+ (BOOL)currentIndexBmBm:(NSInteger)BM;
+ (BOOL)pageControlIndexWithCurrentCellIndexBmBm:(NSInteger)BM;
+ (BOOL)clearCacheBmBm:(NSInteger)BM;
+ (BOOL)clearImagesCacheBmBm:(NSInteger)BM;
+ (BOOL)layoutSubviewsBmBm:(NSInteger)BM;
+ (BOOL)willMoveToSuperviewBmBm:(NSInteger)BM;
+ (BOOL)deallocBmBm:(NSInteger)BM;
+ (BOOL)adjustWhenControllerViewWillApperaBmBm:(NSInteger)BM;
+ (BOOL)collectionViewNumberofitemsinsectionBmBm:(NSInteger)BM;
+ (BOOL)collectionViewCellforitematindexpathBmBm:(NSInteger)BM;
+ (BOOL)collectionViewDidselectitematindexpathBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidScrollBmBm:(NSInteger)BM;
+ (BOOL)scrollViewWillBeginDraggingBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidEndDraggingWilldecelerateBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidEndDeceleratingBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidEndScrollingAnimationBmBm:(NSInteger)BM;
+ (BOOL)makeScrollViewScrollToIndexBmBm:(NSInteger)BM;

@end
