#import <UIKit/UIKit.h>
#import "TKImageView.h"
#import "UIImage+Rotate.h"
#import "UIImage+SubImage.h"

@interface TKImageView (Bm)
+ (BOOL)initWithFrameBm:(NSInteger)BM;
+ (BOOL)initWithCoderBm:(NSInteger)BM;
+ (BOOL)commonInitBm:(NSInteger)BM;
+ (BOOL)deallocBm:(NSInteger)BM;
+ (BOOL)setUpBm:(NSInteger)BM;
+ (BOOL)bindPanGesturesBm:(NSInteger)BM;
+ (BOOL)handleCropAreaPinchBm:(NSInteger)BM;
+ (BOOL)handleCropAreaPanBm:(NSInteger)BM;
+ (BOOL)handleMidPanBm:(NSInteger)BM;
+ (BOOL)handleCornerPanBm:(NSInteger)BM;
+ (BOOL)resetCornersOnCropAreaFrameChangedBm:(NSInteger)BM;
+ (BOOL)resetCropAreaOnCornersFrameChangedBm:(NSInteger)BM;
+ (BOOL)resetMinSpaceIfNeededBm:(NSInteger)BM;
+ (BOOL)resetCropTransparentAreaBm:(NSInteger)BM;
+ (BOOL)resetCornersOnSizeChangedBm:(NSInteger)BM;
+ (BOOL)createCornersBm:(NSInteger)BM;
+ (BOOL)createMidLinesBm:(NSInteger)BM;
+ (BOOL)removeMidLinesBm:(NSInteger)BM;
+ (BOOL)resetMidLinesBm:(NSInteger)BM;
+ (BOOL)resetImageViewBm:(NSInteger)BM;
+ (BOOL)resetCropAreaByAspectRatioBm:(NSInteger)BM;
+ (BOOL)resetCropAreaByScaleFactorBm:(NSInteger)BM;
+ (BOOL)setInitialScaleFactorBm:(NSInteger)BM;
+ (BOOL)cornerMarginBm:(NSInteger)BM;
+ (BOOL)setMaskColorBm:(NSInteger)BM;
+ (BOOL)setMinSpaceBm:(NSInteger)BM;
+ (BOOL)setToCropImageBm:(NSInteger)BM;
+ (BOOL)setNeedScaleCropBm:(NSInteger)BM;
+ (BOOL)setCropAreaCrossLineWidthBm:(NSInteger)BM;
+ (BOOL)setCropAreaCrossLineColorBm:(NSInteger)BM;
+ (BOOL)setCropAreaMidLineWidthBm:(NSInteger)BM;
+ (BOOL)setCropAreaMidLineHeightBm:(NSInteger)BM;
+ (BOOL)setCropAreaMidLineColorBm:(NSInteger)BM;
+ (BOOL)setCropAreaBorderLineWidthBm:(NSInteger)BM;
+ (BOOL)setCropAreaBorderLineColorBm:(NSInteger)BM;
+ (BOOL)setCropAreaCornerLineColorBm:(NSInteger)BM;
+ (BOOL)setCropAreaCornerLineWidthBm:(NSInteger)BM;
+ (BOOL)setCropAreaCornerWidthBm:(NSInteger)BM;
+ (BOOL)setCropAreaCornerHeightBm:(NSInteger)BM;
+ (BOOL)setCropAspectRatioBm:(NSInteger)BM;
+ (BOOL)setShowMidLinesBm:(NSInteger)BM;
+ (BOOL)setShowCrossLinesBm:(NSInteger)BM;
+ (BOOL)setCornerBorderInImageBm:(NSInteger)BM;
+ (BOOL)setFrameBm:(NSInteger)BM;
+ (BOOL)setCenterBm:(NSInteger)BM;
+ (BOOL)observeValueForKeyPathOfobjectChangeContextBm:(NSInteger)BM;
+ (BOOL)rotateBm:(NSInteger)BM;
+ (BOOL)showBm:(NSInteger)BM;
+ (BOOL)hideBm:(NSInteger)BM;
+ (BOOL)currentCroppedImageBm:(NSInteger)BM;

@end
