#import <UIKit/UIKit.h>
#import "TOCropViewConstants.h"
#import "TOCropView.h"
#import "TOCropOverlayView.h"
#import "TOCropScrollView.h"
#import "TOCropView+Bm.h"

@interface TOCropView (Bm-Deletecomments)
+ (BOOL)initWithImageBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithCroppingStyleImageBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setupBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)performInitialSetupBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)layoutInitialImageBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)prepareforRotationBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)performRelayoutForRotationBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)matchForegroundToBackgroundBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)updateCropBoxFrameWithGesturePointBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)resetLayoutToDefaultAnimatedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)toggleTranslucencyViewVisibleBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)updateToImageCropFrameBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gridPanGestureRecognizedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)longPressGestureRecognizedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gestureRecognizerShouldBeginBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gestureRecognizerShouldreceivetouchBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)startResetTimerBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)timerTriggeredBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cancelResetTimerBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cropEdgeForPointBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewForZoomingInScrollViewBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidScrollBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewWillBeginDraggingBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewWillBeginZoomingWithviewBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidEndDeceleratingBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidEndZoomingWithviewAtscaleBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidZoomBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidEndDraggingWilldecelerateBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCropBoxResizeEnabledBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCropBoxFrameBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setEditingBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setSimpleRenderModeBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cropBoxAspectRatioIsPortraitBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)imageCropFrameBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setImageCropFrameBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCroppingViewsHiddenBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCroppingViewsHiddenAnimatedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setBackgroundImageViewHiddenAnimatedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setGridOverlayHiddenBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setGridOverlayHiddenAnimatedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)imageViewFrameBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCanBeResetBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAngleBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)startEditingBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setEditingResetcropboxAnimatedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)moveCroppedContentToCenterAnimatedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setSimpleRenderModeAnimatedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAspectRatioBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAspectRatioAnimatedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rotateImageNinetyDegreesAnimatedBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rotateImageNinetyDegreesAnimatedClockwiseBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)captureStateForImageRotationBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)checkForCanResetBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)contentBoundsBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)imageSizeBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hasAspectRatioBm-Deletecomments:(NSInteger)-deleteComments;

@end
