#import <UIKit/UIKit.h>
#import "TOCropViewConstants.h"
#import "TOCropView.h"
#import "TOCropToolbar.h"
#import "TOCropViewController.h"
#import "TOCropViewControllerTransitioning.h"
#import "TOActivityCroppedImageProvider.h"
#import "UIImage+CropRotate.h"
#import "TOCroppedImageAttributes.h"

@interface TOCropViewController (-Deletecomments)
+ (BOOL)initWithCroppingStyleImage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithImage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewDidLoad-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewWillAppear-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewDidAppear-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewWillDisappear-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewDidDisappear-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)preferredStatusBarStyle-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)prefersStatusBarHidden-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)preferredScreenEdgesDeferringSystemGestures-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)frameForToolbarWithVerticalLayout-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)frameForCropViewWithVerticalLayout-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)frameForTitleLabelWithSizeVerticallayout-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)adjustCropViewInsets-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)adjustToolbarInsets-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewSafeAreaInsetsDidChange-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewDidLayoutSubviews-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)willRotateToInterfaceOrientationDuration-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)willAnimateRotationToInterfaceOrientationDuration-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)didRotateFromInterfaceOrientation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewWillTransitionToSizeWithtransitioncoordinator-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)resetCropViewLayout-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)showAspectRatioDialog-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)actionSheetDiddismisswithbuttonindex-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAspectRatioPresetAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rotateCropViewClockwise-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rotateCropViewCounterclockwise-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cropViewDidBecomeResettable-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cropViewDidBecomeNonResettable-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)presentAnimatedFromParentViewControllerFromviewFromframeSetupCompletion-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)presentAnimatedFromParentViewControllerFromimageFromviewFromframeAngleToimageframeSetupCompletion-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dismissAnimatedFromParentViewControllerToviewToframeSetupCompletion-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)dismissAnimatedFromParentViewControllerWithcroppedimageToviewToframeSetupCompletion-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)animationControllerForPresentedControllerPresentingcontrollerSourcecontroller-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)animationControllerForDismissedController-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cancelButtonTapped-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)doneButtonTapped-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setTitle-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setDoneButtonTitle-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCancelButtonTitle-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cropView-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)toolbar-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)titleLabel-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAspectRatioLockEnabled-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAspectRatioLockDimensionSwapEnabled-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aspectRatioLockEnabled-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setRotateButtonsHidden-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rotateButtonsHidden-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setRotateClockwiseButtonHidden-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rotateClockwiseButtonHidden-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAspectRatioPickerButtonHidden-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)aspectRatioPickerButtonHidden-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setResetAspectRatioEnabled-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCustomAspectRatio-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)resetAspectRatioEnabled-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAngle-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)angle-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setImageCropFrame-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)imageCropFrame-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)verticalLayout-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)overrideStatusBar-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)statusBarHidden-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)statusBarHeight-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)statusBarSafeInsets-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setMinimumAspectRatio-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)minimumAspectRatio-Deletecomments:(NSInteger)-deleteComments;

@end
