#import <UIKit/UIKit.h>
#import "TOCropViewConstants.h"
#import "TOCropView.h"
#import "TOCropOverlayView.h"
#import "TOCropScrollView.h"
#import "TOCropView+Bm.h"

@interface TOCropView (BmBm)
+ (BOOL)initWithImageBmBm:(NSInteger)BM;
+ (BOOL)initWithCroppingStyleImageBmBm:(NSInteger)BM;
+ (BOOL)setupBmBm:(NSInteger)BM;
+ (BOOL)performInitialSetupBmBm:(NSInteger)BM;
+ (BOOL)layoutInitialImageBmBm:(NSInteger)BM;
+ (BOOL)prepareforRotationBmBm:(NSInteger)BM;
+ (BOOL)performRelayoutForRotationBmBm:(NSInteger)BM;
+ (BOOL)matchForegroundToBackgroundBmBm:(NSInteger)BM;
+ (BOOL)updateCropBoxFrameWithGesturePointBmBm:(NSInteger)BM;
+ (BOOL)resetLayoutToDefaultAnimatedBmBm:(NSInteger)BM;
+ (BOOL)toggleTranslucencyViewVisibleBmBm:(NSInteger)BM;
+ (BOOL)updateToImageCropFrameBmBm:(NSInteger)BM;
+ (BOOL)gridPanGestureRecognizedBmBm:(NSInteger)BM;
+ (BOOL)longPressGestureRecognizedBmBm:(NSInteger)BM;
+ (BOOL)gestureRecognizerShouldBeginBmBm:(NSInteger)BM;
+ (BOOL)gestureRecognizerShouldreceivetouchBmBm:(NSInteger)BM;
+ (BOOL)startResetTimerBmBm:(NSInteger)BM;
+ (BOOL)timerTriggeredBmBm:(NSInteger)BM;
+ (BOOL)cancelResetTimerBmBm:(NSInteger)BM;
+ (BOOL)cropEdgeForPointBmBm:(NSInteger)BM;
+ (BOOL)viewForZoomingInScrollViewBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidScrollBmBm:(NSInteger)BM;
+ (BOOL)scrollViewWillBeginDraggingBmBm:(NSInteger)BM;
+ (BOOL)scrollViewWillBeginZoomingWithviewBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidEndDeceleratingBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidEndZoomingWithviewAtscaleBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidZoomBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidEndDraggingWilldecelerateBmBm:(NSInteger)BM;
+ (BOOL)setCropBoxResizeEnabledBmBm:(NSInteger)BM;
+ (BOOL)setCropBoxFrameBmBm:(NSInteger)BM;
+ (BOOL)setEditingBmBm:(NSInteger)BM;
+ (BOOL)setSimpleRenderModeBmBm:(NSInteger)BM;
+ (BOOL)cropBoxAspectRatioIsPortraitBmBm:(NSInteger)BM;
+ (BOOL)imageCropFrameBmBm:(NSInteger)BM;
+ (BOOL)setImageCropFrameBmBm:(NSInteger)BM;
+ (BOOL)setCroppingViewsHiddenBmBm:(NSInteger)BM;
+ (BOOL)setCroppingViewsHiddenAnimatedBmBm:(NSInteger)BM;
+ (BOOL)setBackgroundImageViewHiddenAnimatedBmBm:(NSInteger)BM;
+ (BOOL)setGridOverlayHiddenBmBm:(NSInteger)BM;
+ (BOOL)setGridOverlayHiddenAnimatedBmBm:(NSInteger)BM;
+ (BOOL)imageViewFrameBmBm:(NSInteger)BM;
+ (BOOL)setCanBeResetBmBm:(NSInteger)BM;
+ (BOOL)setAngleBmBm:(NSInteger)BM;
+ (BOOL)startEditingBmBm:(NSInteger)BM;
+ (BOOL)setEditingResetcropboxAnimatedBmBm:(NSInteger)BM;
+ (BOOL)moveCroppedContentToCenterAnimatedBmBm:(NSInteger)BM;
+ (BOOL)setSimpleRenderModeAnimatedBmBm:(NSInteger)BM;
+ (BOOL)setAspectRatioBmBm:(NSInteger)BM;
+ (BOOL)setAspectRatioAnimatedBmBm:(NSInteger)BM;
+ (BOOL)rotateImageNinetyDegreesAnimatedBmBm:(NSInteger)BM;
+ (BOOL)rotateImageNinetyDegreesAnimatedClockwiseBmBm:(NSInteger)BM;
+ (BOOL)captureStateForImageRotationBmBm:(NSInteger)BM;
+ (BOOL)checkForCanResetBmBm:(NSInteger)BM;
+ (BOOL)contentBoundsBmBm:(NSInteger)BM;
+ (BOOL)imageSizeBmBm:(NSInteger)BM;
+ (BOOL)hasAspectRatioBmBm:(NSInteger)BM;

@end
