#import <UIKit/UIKit.h>
#import "TOCropViewConstants.h"
#import "TOCropView.h"
#import "TOCropToolbar.h"
#import "TOCropViewController.h"
#import "TOCropViewControllerTransitioning.h"
#import "TOActivityCroppedImageProvider.h"
#import "UIImage+CropRotate.h"
#import "TOCroppedImageAttributes.h"
#import "TOCropViewController+Bm.h"

@interface TOCropViewController (BmBm)
+ (BOOL)initWithCroppingStyleImageBmBm:(NSInteger)BM;
+ (BOOL)initWithImageBmBm:(NSInteger)BM;
+ (BOOL)viewDidLoadBmBm:(NSInteger)BM;
+ (BOOL)viewWillAppearBmBm:(NSInteger)BM;
+ (BOOL)viewDidAppearBmBm:(NSInteger)BM;
+ (BOOL)viewWillDisappearBmBm:(NSInteger)BM;
+ (BOOL)viewDidDisappearBmBm:(NSInteger)BM;
+ (BOOL)preferredStatusBarStyleBmBm:(NSInteger)BM;
+ (BOOL)prefersStatusBarHiddenBmBm:(NSInteger)BM;
+ (BOOL)preferredScreenEdgesDeferringSystemGesturesBmBm:(NSInteger)BM;
+ (BOOL)frameForToolbarWithVerticalLayoutBmBm:(NSInteger)BM;
+ (BOOL)frameForCropViewWithVerticalLayoutBmBm:(NSInteger)BM;
+ (BOOL)frameForTitleLabelWithSizeVerticallayoutBmBm:(NSInteger)BM;
+ (BOOL)adjustCropViewInsetsBmBm:(NSInteger)BM;
+ (BOOL)adjustToolbarInsetsBmBm:(NSInteger)BM;
+ (BOOL)viewSafeAreaInsetsDidChangeBmBm:(NSInteger)BM;
+ (BOOL)viewDidLayoutSubviewsBmBm:(NSInteger)BM;
+ (BOOL)willRotateToInterfaceOrientationDurationBmBm:(NSInteger)BM;
+ (BOOL)willAnimateRotationToInterfaceOrientationDurationBmBm:(NSInteger)BM;
+ (BOOL)didRotateFromInterfaceOrientationBmBm:(NSInteger)BM;
+ (BOOL)viewWillTransitionToSizeWithtransitioncoordinatorBmBm:(NSInteger)BM;
+ (BOOL)resetCropViewLayoutBmBm:(NSInteger)BM;
+ (BOOL)showAspectRatioDialogBmBm:(NSInteger)BM;
+ (BOOL)actionSheetDiddismisswithbuttonindexBmBm:(NSInteger)BM;
+ (BOOL)setAspectRatioPresetAnimatedBmBm:(NSInteger)BM;
+ (BOOL)rotateCropViewClockwiseBmBm:(NSInteger)BM;
+ (BOOL)rotateCropViewCounterclockwiseBmBm:(NSInteger)BM;
+ (BOOL)cropViewDidBecomeResettableBmBm:(NSInteger)BM;
+ (BOOL)cropViewDidBecomeNonResettableBmBm:(NSInteger)BM;
+ (BOOL)presentAnimatedFromParentViewControllerFromviewFromframeSetupCompletionBmBm:(NSInteger)BM;
+ (BOOL)presentAnimatedFromParentViewControllerFromimageFromviewFromframeAngleToimageframeSetupCompletionBmBm:(NSInteger)BM;
+ (BOOL)dismissAnimatedFromParentViewControllerToviewToframeSetupCompletionBmBm:(NSInteger)BM;
+ (BOOL)dismissAnimatedFromParentViewControllerWithcroppedimageToviewToframeSetupCompletionBmBm:(NSInteger)BM;
+ (BOOL)animationControllerForPresentedControllerPresentingcontrollerSourcecontrollerBmBm:(NSInteger)BM;
+ (BOOL)animationControllerForDismissedControllerBmBm:(NSInteger)BM;
+ (BOOL)cancelButtonTappedBmBm:(NSInteger)BM;
+ (BOOL)doneButtonTappedBmBm:(NSInteger)BM;
+ (BOOL)setTitleBmBm:(NSInteger)BM;
+ (BOOL)setDoneButtonTitleBmBm:(NSInteger)BM;
+ (BOOL)setCancelButtonTitleBmBm:(NSInteger)BM;
+ (BOOL)cropViewBmBm:(NSInteger)BM;
+ (BOOL)toolbarBmBm:(NSInteger)BM;
+ (BOOL)titleLabelBmBm:(NSInteger)BM;
+ (BOOL)setAspectRatioLockEnabledBmBm:(NSInteger)BM;
+ (BOOL)setAspectRatioLockDimensionSwapEnabledBmBm:(NSInteger)BM;
+ (BOOL)aspectRatioLockEnabledBmBm:(NSInteger)BM;
+ (BOOL)setRotateButtonsHiddenBmBm:(NSInteger)BM;
+ (BOOL)rotateButtonsHiddenBmBm:(NSInteger)BM;
+ (BOOL)setRotateClockwiseButtonHiddenBmBm:(NSInteger)BM;
+ (BOOL)rotateClockwiseButtonHiddenBmBm:(NSInteger)BM;
+ (BOOL)setAspectRatioPickerButtonHiddenBmBm:(NSInteger)BM;
+ (BOOL)aspectRatioPickerButtonHiddenBmBm:(NSInteger)BM;
+ (BOOL)setResetAspectRatioEnabledBmBm:(NSInteger)BM;
+ (BOOL)setCustomAspectRatioBmBm:(NSInteger)BM;
+ (BOOL)resetAspectRatioEnabledBmBm:(NSInteger)BM;
+ (BOOL)setAngleBmBm:(NSInteger)BM;
+ (BOOL)angleBmBm:(NSInteger)BM;
+ (BOOL)setImageCropFrameBmBm:(NSInteger)BM;
+ (BOOL)imageCropFrameBmBm:(NSInteger)BM;
+ (BOOL)verticalLayoutBmBm:(NSInteger)BM;
+ (BOOL)overrideStatusBarBmBm:(NSInteger)BM;
+ (BOOL)statusBarHiddenBmBm:(NSInteger)BM;
+ (BOOL)statusBarHeightBmBm:(NSInteger)BM;
+ (BOOL)statusBarSafeInsetsBmBm:(NSInteger)BM;
+ (BOOL)setMinimumAspectRatioBmBm:(NSInteger)BM;
+ (BOOL)minimumAspectRatioBmBm:(NSInteger)BM;

@end
