#import <UIKit/UIKit.h>
#import "TOCropViewConstants.h"
#import "TOCropView.h"
#import "TOCropOverlayView.h"
#import "TOCropScrollView.h"
#import "TOCropView+Bm.h"
#import "TOCropView+BmBm.h"

@interface TOCropView (BmBmBm)
+ (BOOL)initWithImageBmBmBm:(NSInteger)BM;
+ (BOOL)initWithCroppingStyleImageBmBmBm:(NSInteger)BM;
+ (BOOL)setupBmBmBm:(NSInteger)BM;
+ (BOOL)performInitialSetupBmBmBm:(NSInteger)BM;
+ (BOOL)layoutInitialImageBmBmBm:(NSInteger)BM;
+ (BOOL)prepareforRotationBmBmBm:(NSInteger)BM;
+ (BOOL)performRelayoutForRotationBmBmBm:(NSInteger)BM;
+ (BOOL)matchForegroundToBackgroundBmBmBm:(NSInteger)BM;
+ (BOOL)updateCropBoxFrameWithGesturePointBmBmBm:(NSInteger)BM;
+ (BOOL)resetLayoutToDefaultAnimatedBmBmBm:(NSInteger)BM;
+ (BOOL)toggleTranslucencyViewVisibleBmBmBm:(NSInteger)BM;
+ (BOOL)updateToImageCropFrameBmBmBm:(NSInteger)BM;
+ (BOOL)gridPanGestureRecognizedBmBmBm:(NSInteger)BM;
+ (BOOL)longPressGestureRecognizedBmBmBm:(NSInteger)BM;
+ (BOOL)gestureRecognizerShouldBeginBmBmBm:(NSInteger)BM;
+ (BOOL)gestureRecognizerShouldreceivetouchBmBmBm:(NSInteger)BM;
+ (BOOL)startResetTimerBmBmBm:(NSInteger)BM;
+ (BOOL)timerTriggeredBmBmBm:(NSInteger)BM;
+ (BOOL)cancelResetTimerBmBmBm:(NSInteger)BM;
+ (BOOL)cropEdgeForPointBmBmBm:(NSInteger)BM;
+ (BOOL)viewForZoomingInScrollViewBmBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidScrollBmBmBm:(NSInteger)BM;
+ (BOOL)scrollViewWillBeginDraggingBmBmBm:(NSInteger)BM;
+ (BOOL)scrollViewWillBeginZoomingWithviewBmBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidEndDeceleratingBmBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidEndZoomingWithviewAtscaleBmBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidZoomBmBmBm:(NSInteger)BM;
+ (BOOL)scrollViewDidEndDraggingWilldecelerateBmBmBm:(NSInteger)BM;
+ (BOOL)setCropBoxResizeEnabledBmBmBm:(NSInteger)BM;
+ (BOOL)setCropBoxFrameBmBmBm:(NSInteger)BM;
+ (BOOL)setEditingBmBmBm:(NSInteger)BM;
+ (BOOL)setSimpleRenderModeBmBmBm:(NSInteger)BM;
+ (BOOL)cropBoxAspectRatioIsPortraitBmBmBm:(NSInteger)BM;
+ (BOOL)imageCropFrameBmBmBm:(NSInteger)BM;
+ (BOOL)setImageCropFrameBmBmBm:(NSInteger)BM;
+ (BOOL)setCroppingViewsHiddenBmBmBm:(NSInteger)BM;
+ (BOOL)setCroppingViewsHiddenAnimatedBmBmBm:(NSInteger)BM;
+ (BOOL)setBackgroundImageViewHiddenAnimatedBmBmBm:(NSInteger)BM;
+ (BOOL)setGridOverlayHiddenBmBmBm:(NSInteger)BM;
+ (BOOL)setGridOverlayHiddenAnimatedBmBmBm:(NSInteger)BM;
+ (BOOL)imageViewFrameBmBmBm:(NSInteger)BM;
+ (BOOL)setCanBeResetBmBmBm:(NSInteger)BM;
+ (BOOL)setAngleBmBmBm:(NSInteger)BM;
+ (BOOL)startEditingBmBmBm:(NSInteger)BM;
+ (BOOL)setEditingResetcropboxAnimatedBmBmBm:(NSInteger)BM;
+ (BOOL)moveCroppedContentToCenterAnimatedBmBmBm:(NSInteger)BM;
+ (BOOL)setSimpleRenderModeAnimatedBmBmBm:(NSInteger)BM;
+ (BOOL)setAspectRatioBmBmBm:(NSInteger)BM;
+ (BOOL)setAspectRatioAnimatedBmBmBm:(NSInteger)BM;
+ (BOOL)rotateImageNinetyDegreesAnimatedBmBmBm:(NSInteger)BM;
+ (BOOL)rotateImageNinetyDegreesAnimatedClockwiseBmBmBm:(NSInteger)BM;
+ (BOOL)captureStateForImageRotationBmBmBm:(NSInteger)BM;
+ (BOOL)checkForCanResetBmBmBm:(NSInteger)BM;
+ (BOOL)contentBoundsBmBmBm:(NSInteger)BM;
+ (BOOL)imageSizeBmBmBm:(NSInteger)BM;
+ (BOOL)hasAspectRatioBmBmBm:(NSInteger)BM;

@end
