#import <UIKit/UIKit.h>
#import "TOCropViewConstants.h"
#import "TOCropView.h"
#import "TOCropOverlayView.h"
#import "TOCropScrollView.h"

@interface TOCropView (-Deletecomments)
+ (BOOL)initWithImage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithCroppingStyleImage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setup-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)performInitialSetup-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)layoutInitialImage-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)prepareforRotation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)performRelayoutForRotation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)matchForegroundToBackground-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)updateCropBoxFrameWithGesturePoint-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)resetLayoutToDefaultAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)toggleTranslucencyViewVisible-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)updateToImageCropFrame-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gridPanGestureRecognized-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)longPressGestureRecognized-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gestureRecognizerShouldBegin-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gestureRecognizerShouldreceivetouch-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)startResetTimer-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)timerTriggered-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cancelResetTimer-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cropEdgeForPoint-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewForZoomingInScrollView-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidScroll-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewWillBeginDragging-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewWillBeginZoomingWithview-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidEndDecelerating-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidEndZoomingWithviewAtscale-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidZoom-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidEndDraggingWilldecelerate-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCropBoxResizeEnabled-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCropBoxFrame-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setEditing-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setSimpleRenderMode-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cropBoxAspectRatioIsPortrait-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)imageCropFrame-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setImageCropFrame-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCroppingViewsHidden-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCroppingViewsHiddenAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setBackgroundImageViewHiddenAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setGridOverlayHidden-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setGridOverlayHiddenAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)imageViewFrame-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCanBeReset-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAngle-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)startEditing-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setEditingResetcropboxAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)moveCroppedContentToCenterAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setSimpleRenderModeAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAspectRatio-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAspectRatioAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rotateImageNinetyDegreesAnimated-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rotateImageNinetyDegreesAnimatedClockwise-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)captureStateForImageRotation-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)checkForCanReset-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)contentBounds-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)imageSize-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hasAspectRatio-Deletecomments:(NSInteger)-deleteComments;

@end
