#import <UIKit/UIKit.h>
#import "TOCropViewConstants.h"
#import "TOCropView.h"
#import "TOCropOverlayView.h"
#import "TOCropScrollView.h"
#import "TOCropView+Bm.h"
#import "TOCropView+BmBm.h"
#import "TOCropView+BmBmBm.h"

@interface TOCropView (BmBmBmHb)
+ (BOOL)initWithImageBmBmBmHb:(NSInteger)hb;
+ (BOOL)initWithCroppingStyleImageBmBmBmHb:(NSInteger)hb;
+ (BOOL)setupBmBmBmHb:(NSInteger)hb;
+ (BOOL)performInitialSetupBmBmBmHb:(NSInteger)hb;
+ (BOOL)layoutInitialImageBmBmBmHb:(NSInteger)hb;
+ (BOOL)prepareforRotationBmBmBmHb:(NSInteger)hb;
+ (BOOL)performRelayoutForRotationBmBmBmHb:(NSInteger)hb;
+ (BOOL)matchForegroundToBackgroundBmBmBmHb:(NSInteger)hb;
+ (BOOL)updateCropBoxFrameWithGesturePointBmBmBmHb:(NSInteger)hb;
+ (BOOL)resetLayoutToDefaultAnimatedBmBmBmHb:(NSInteger)hb;
+ (BOOL)toggleTranslucencyViewVisibleBmBmBmHb:(NSInteger)hb;
+ (BOOL)updateToImageCropFrameBmBmBmHb:(NSInteger)hb;
+ (BOOL)gridPanGestureRecognizedBmBmBmHb:(NSInteger)hb;
+ (BOOL)longPressGestureRecognizedBmBmBmHb:(NSInteger)hb;
+ (BOOL)gestureRecognizerShouldBeginBmBmBmHb:(NSInteger)hb;
+ (BOOL)gestureRecognizerShouldreceivetouchBmBmBmHb:(NSInteger)hb;
+ (BOOL)startResetTimerBmBmBmHb:(NSInteger)hb;
+ (BOOL)timerTriggeredBmBmBmHb:(NSInteger)hb;
+ (BOOL)cancelResetTimerBmBmBmHb:(NSInteger)hb;
+ (BOOL)cropEdgeForPointBmBmBmHb:(NSInteger)hb;
+ (BOOL)viewForZoomingInScrollViewBmBmBmHb:(NSInteger)hb;
+ (BOOL)scrollViewDidScrollBmBmBmHb:(NSInteger)hb;
+ (BOOL)scrollViewWillBeginDraggingBmBmBmHb:(NSInteger)hb;
+ (BOOL)scrollViewWillBeginZoomingWithviewBmBmBmHb:(NSInteger)hb;
+ (BOOL)scrollViewDidEndDeceleratingBmBmBmHb:(NSInteger)hb;
+ (BOOL)scrollViewDidEndZoomingWithviewAtscaleBmBmBmHb:(NSInteger)hb;
+ (BOOL)scrollViewDidZoomBmBmBmHb:(NSInteger)hb;
+ (BOOL)scrollViewDidEndDraggingWilldecelerateBmBmBmHb:(NSInteger)hb;
+ (BOOL)setCropBoxResizeEnabledBmBmBmHb:(NSInteger)hb;
+ (BOOL)setCropBoxFrameBmBmBmHb:(NSInteger)hb;
+ (BOOL)setEditingBmBmBmHb:(NSInteger)hb;
+ (BOOL)setSimpleRenderModeBmBmBmHb:(NSInteger)hb;
+ (BOOL)cropBoxAspectRatioIsPortraitBmBmBmHb:(NSInteger)hb;
+ (BOOL)imageCropFrameBmBmBmHb:(NSInteger)hb;
+ (BOOL)setImageCropFrameBmBmBmHb:(NSInteger)hb;
+ (BOOL)setCroppingViewsHiddenBmBmBmHb:(NSInteger)hb;
+ (BOOL)setCroppingViewsHiddenAnimatedBmBmBmHb:(NSInteger)hb;
+ (BOOL)setBackgroundImageViewHiddenAnimatedBmBmBmHb:(NSInteger)hb;
+ (BOOL)setGridOverlayHiddenBmBmBmHb:(NSInteger)hb;
+ (BOOL)setGridOverlayHiddenAnimatedBmBmBmHb:(NSInteger)hb;
+ (BOOL)imageViewFrameBmBmBmHb:(NSInteger)hb;
+ (BOOL)setCanBeResetBmBmBmHb:(NSInteger)hb;
+ (BOOL)setAngleBmBmBmHb:(NSInteger)hb;
+ (BOOL)startEditingBmBmBmHb:(NSInteger)hb;
+ (BOOL)setEditingResetcropboxAnimatedBmBmBmHb:(NSInteger)hb;
+ (BOOL)moveCroppedContentToCenterAnimatedBmBmBmHb:(NSInteger)hb;
+ (BOOL)setSimpleRenderModeAnimatedBmBmBmHb:(NSInteger)hb;
+ (BOOL)setAspectRatioBmBmBmHb:(NSInteger)hb;
+ (BOOL)setAspectRatioAnimatedBmBmBmHb:(NSInteger)hb;
+ (BOOL)rotateImageNinetyDegreesAnimatedBmBmBmHb:(NSInteger)hb;
+ (BOOL)rotateImageNinetyDegreesAnimatedClockwiseBmBmBmHb:(NSInteger)hb;
+ (BOOL)captureStateForImageRotationBmBmBmHb:(NSInteger)hb;
+ (BOOL)checkForCanResetBmBmBmHb:(NSInteger)hb;
+ (BOOL)contentBoundsBmBmBmHb:(NSInteger)hb;
+ (BOOL)imageSizeBmBmBmHb:(NSInteger)hb;
+ (BOOL)hasAspectRatioBmBmBmHb:(NSInteger)hb;

@end
