#import <UIKit/UIKit.h>
#import "TOCropViewConstants.h"
#import "TOCropView.h"
#import "TOCropOverlayView.h"
#import "TOCropScrollView.h"
#import "TOCropView+Bm.h"
#import "TOCropView+BmBm.h"

@interface TOCropView (BmBmHb)
+ (BOOL)initWithImageBmBmHb:(NSInteger)hb;
+ (BOOL)initWithCroppingStyleImageBmBmHb:(NSInteger)hb;
+ (BOOL)setupBmBmHb:(NSInteger)hb;
+ (BOOL)performInitialSetupBmBmHb:(NSInteger)hb;
+ (BOOL)layoutInitialImageBmBmHb:(NSInteger)hb;
+ (BOOL)prepareforRotationBmBmHb:(NSInteger)hb;
+ (BOOL)performRelayoutForRotationBmBmHb:(NSInteger)hb;
+ (BOOL)matchForegroundToBackgroundBmBmHb:(NSInteger)hb;
+ (BOOL)updateCropBoxFrameWithGesturePointBmBmHb:(NSInteger)hb;
+ (BOOL)resetLayoutToDefaultAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)toggleTranslucencyViewVisibleBmBmHb:(NSInteger)hb;
+ (BOOL)updateToImageCropFrameBmBmHb:(NSInteger)hb;
+ (BOOL)gridPanGestureRecognizedBmBmHb:(NSInteger)hb;
+ (BOOL)longPressGestureRecognizedBmBmHb:(NSInteger)hb;
+ (BOOL)gestureRecognizerShouldBeginBmBmHb:(NSInteger)hb;
+ (BOOL)gestureRecognizerShouldreceivetouchBmBmHb:(NSInteger)hb;
+ (BOOL)startResetTimerBmBmHb:(NSInteger)hb;
+ (BOOL)timerTriggeredBmBmHb:(NSInteger)hb;
+ (BOOL)cancelResetTimerBmBmHb:(NSInteger)hb;
+ (BOOL)cropEdgeForPointBmBmHb:(NSInteger)hb;
+ (BOOL)viewForZoomingInScrollViewBmBmHb:(NSInteger)hb;
+ (BOOL)scrollViewDidScrollBmBmHb:(NSInteger)hb;
+ (BOOL)scrollViewWillBeginDraggingBmBmHb:(NSInteger)hb;
+ (BOOL)scrollViewWillBeginZoomingWithviewBmBmHb:(NSInteger)hb;
+ (BOOL)scrollViewDidEndDeceleratingBmBmHb:(NSInteger)hb;
+ (BOOL)scrollViewDidEndZoomingWithviewAtscaleBmBmHb:(NSInteger)hb;
+ (BOOL)scrollViewDidZoomBmBmHb:(NSInteger)hb;
+ (BOOL)scrollViewDidEndDraggingWilldecelerateBmBmHb:(NSInteger)hb;
+ (BOOL)setCropBoxResizeEnabledBmBmHb:(NSInteger)hb;
+ (BOOL)setCropBoxFrameBmBmHb:(NSInteger)hb;
+ (BOOL)setEditingBmBmHb:(NSInteger)hb;
+ (BOOL)setSimpleRenderModeBmBmHb:(NSInteger)hb;
+ (BOOL)cropBoxAspectRatioIsPortraitBmBmHb:(NSInteger)hb;
+ (BOOL)imageCropFrameBmBmHb:(NSInteger)hb;
+ (BOOL)setImageCropFrameBmBmHb:(NSInteger)hb;
+ (BOOL)setCroppingViewsHiddenBmBmHb:(NSInteger)hb;
+ (BOOL)setCroppingViewsHiddenAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)setBackgroundImageViewHiddenAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)setGridOverlayHiddenBmBmHb:(NSInteger)hb;
+ (BOOL)setGridOverlayHiddenAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)imageViewFrameBmBmHb:(NSInteger)hb;
+ (BOOL)setCanBeResetBmBmHb:(NSInteger)hb;
+ (BOOL)setAngleBmBmHb:(NSInteger)hb;
+ (BOOL)startEditingBmBmHb:(NSInteger)hb;
+ (BOOL)setEditingResetcropboxAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)moveCroppedContentToCenterAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)setSimpleRenderModeAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)setAspectRatioBmBmHb:(NSInteger)hb;
+ (BOOL)setAspectRatioAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)rotateImageNinetyDegreesAnimatedBmBmHb:(NSInteger)hb;
+ (BOOL)rotateImageNinetyDegreesAnimatedClockwiseBmBmHb:(NSInteger)hb;
+ (BOOL)captureStateForImageRotationBmBmHb:(NSInteger)hb;
+ (BOOL)checkForCanResetBmBmHb:(NSInteger)hb;
+ (BOOL)contentBoundsBmBmHb:(NSInteger)hb;
+ (BOOL)imageSizeBmBmHb:(NSInteger)hb;
+ (BOOL)hasAspectRatioBmBmHb:(NSInteger)hb;

@end
