#import <UIKit/UIKit.h>
#import "TOCropViewConstants.h"
#import "TOCropView.h"
#import "TOCropOverlayView.h"
#import "TOCropScrollView.h"
#import "TOCropView+Bm.h"
#import "TOCropView+BmBm.h"
#import "TOCropView+BmBmBm.h"

@interface TOCropView (BmBmBm-Deletecomments)
+ (BOOL)initWithImageBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithCroppingStyleImageBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setupBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)performInitialSetupBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)layoutInitialImageBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)prepareforRotationBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)performRelayoutForRotationBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)matchForegroundToBackgroundBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)updateCropBoxFrameWithGesturePointBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)resetLayoutToDefaultAnimatedBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)toggleTranslucencyViewVisibleBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)updateToImageCropFrameBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gridPanGestureRecognizedBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)longPressGestureRecognizedBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gestureRecognizerShouldBeginBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gestureRecognizerShouldreceivetouchBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)startResetTimerBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)timerTriggeredBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cancelResetTimerBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cropEdgeForPointBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewForZoomingInScrollViewBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidScrollBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewWillBeginDraggingBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewWillBeginZoomingWithviewBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidEndDeceleratingBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidEndZoomingWithviewAtscaleBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidZoomBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidEndDraggingWilldecelerateBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCropBoxResizeEnabledBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCropBoxFrameBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setEditingBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setSimpleRenderModeBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cropBoxAspectRatioIsPortraitBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)imageCropFrameBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setImageCropFrameBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCroppingViewsHiddenBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCroppingViewsHiddenAnimatedBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setBackgroundImageViewHiddenAnimatedBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setGridOverlayHiddenBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setGridOverlayHiddenAnimatedBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)imageViewFrameBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCanBeResetBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAngleBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)startEditingBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setEditingResetcropboxAnimatedBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)moveCroppedContentToCenterAnimatedBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setSimpleRenderModeAnimatedBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAspectRatioBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAspectRatioAnimatedBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rotateImageNinetyDegreesAnimatedBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rotateImageNinetyDegreesAnimatedClockwiseBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)captureStateForImageRotationBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)checkForCanResetBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)contentBoundsBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)imageSizeBmBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hasAspectRatioBmBmBm-Deletecomments:(NSInteger)-deleteComments;

@end
