#import <UIKit/UIKit.h>
#import "TOCropViewConstants.h"
#import "TOCropView.h"
#import "TOCropOverlayView.h"
#import "TOCropScrollView.h"
#import "TOCropView+Bm.h"
#import "TOCropView+BmBm.h"

@interface TOCropView (BmBm-Deletecomments)
+ (BOOL)initWithImageBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)initWithCroppingStyleImageBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setupBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)performInitialSetupBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)layoutInitialImageBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)prepareforRotationBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)performRelayoutForRotationBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)matchForegroundToBackgroundBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)updateCropBoxFrameWithGesturePointBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)resetLayoutToDefaultAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)toggleTranslucencyViewVisibleBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)updateToImageCropFrameBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gridPanGestureRecognizedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)longPressGestureRecognizedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gestureRecognizerShouldBeginBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)gestureRecognizerShouldreceivetouchBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)startResetTimerBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)timerTriggeredBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cancelResetTimerBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cropEdgeForPointBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)viewForZoomingInScrollViewBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidScrollBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewWillBeginDraggingBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewWillBeginZoomingWithviewBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidEndDeceleratingBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidEndZoomingWithviewAtscaleBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidZoomBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)scrollViewDidEndDraggingWilldecelerateBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCropBoxResizeEnabledBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCropBoxFrameBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setEditingBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setSimpleRenderModeBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)cropBoxAspectRatioIsPortraitBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)imageCropFrameBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setImageCropFrameBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCroppingViewsHiddenBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCroppingViewsHiddenAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setBackgroundImageViewHiddenAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setGridOverlayHiddenBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setGridOverlayHiddenAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)imageViewFrameBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setCanBeResetBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAngleBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)startEditingBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setEditingResetcropboxAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)moveCroppedContentToCenterAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setSimpleRenderModeAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAspectRatioBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)setAspectRatioAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rotateImageNinetyDegreesAnimatedBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)rotateImageNinetyDegreesAnimatedClockwiseBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)captureStateForImageRotationBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)checkForCanResetBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)contentBoundsBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)imageSizeBmBm-Deletecomments:(NSInteger)-deleteComments;
+ (BOOL)hasAspectRatioBmBm-Deletecomments:(NSInteger)-deleteComments;

@end
