#import <UIKit/UIKit.h>
#import "TOCropViewConstants.h"
#import "TOCropView.h"
#import "TOCropToolbar.h"
#import "TOCropViewController.h"
#import "TOCropViewControllerTransitioning.h"
#import "TOActivityCroppedImageProvider.h"
#import "UIImage+CropRotate.h"
#import "TOCroppedImageAttributes.h"

@interface TOCropViewController (Hb)
+ (BOOL)initWithCroppingStyleImageHb:(NSInteger)hb;
+ (BOOL)initWithImageHb:(NSInteger)hb;
+ (BOOL)viewDidLoadHb:(NSInteger)hb;
+ (BOOL)viewWillAppearHb:(NSInteger)hb;
+ (BOOL)viewDidAppearHb:(NSInteger)hb;
+ (BOOL)viewWillDisappearHb:(NSInteger)hb;
+ (BOOL)viewDidDisappearHb:(NSInteger)hb;
+ (BOOL)preferredStatusBarStyleHb:(NSInteger)hb;
+ (BOOL)prefersStatusBarHiddenHb:(NSInteger)hb;
+ (BOOL)preferredScreenEdgesDeferringSystemGesturesHb:(NSInteger)hb;
+ (BOOL)frameForToolbarWithVerticalLayoutHb:(NSInteger)hb;
+ (BOOL)frameForCropViewWithVerticalLayoutHb:(NSInteger)hb;
+ (BOOL)frameForTitleLabelWithSizeVerticallayoutHb:(NSInteger)hb;
+ (BOOL)adjustCropViewInsetsHb:(NSInteger)hb;
+ (BOOL)adjustToolbarInsetsHb:(NSInteger)hb;
+ (BOOL)viewSafeAreaInsetsDidChangeHb:(NSInteger)hb;
+ (BOOL)viewDidLayoutSubviewsHb:(NSInteger)hb;
+ (BOOL)willRotateToInterfaceOrientationDurationHb:(NSInteger)hb;
+ (BOOL)willAnimateRotationToInterfaceOrientationDurationHb:(NSInteger)hb;
+ (BOOL)didRotateFromInterfaceOrientationHb:(NSInteger)hb;
+ (BOOL)viewWillTransitionToSizeWithtransitioncoordinatorHb:(NSInteger)hb;
+ (BOOL)resetCropViewLayoutHb:(NSInteger)hb;
+ (BOOL)showAspectRatioDialogHb:(NSInteger)hb;
+ (BOOL)actionSheetDiddismisswithbuttonindexHb:(NSInteger)hb;
+ (BOOL)setAspectRatioPresetAnimatedHb:(NSInteger)hb;
+ (BOOL)rotateCropViewClockwiseHb:(NSInteger)hb;
+ (BOOL)rotateCropViewCounterclockwiseHb:(NSInteger)hb;
+ (BOOL)cropViewDidBecomeResettableHb:(NSInteger)hb;
+ (BOOL)cropViewDidBecomeNonResettableHb:(NSInteger)hb;
+ (BOOL)presentAnimatedFromParentViewControllerFromviewFromframeSetupCompletionHb:(NSInteger)hb;
+ (BOOL)presentAnimatedFromParentViewControllerFromimageFromviewFromframeAngleToimageframeSetupCompletionHb:(NSInteger)hb;
+ (BOOL)dismissAnimatedFromParentViewControllerToviewToframeSetupCompletionHb:(NSInteger)hb;
+ (BOOL)dismissAnimatedFromParentViewControllerWithcroppedimageToviewToframeSetupCompletionHb:(NSInteger)hb;
+ (BOOL)animationControllerForPresentedControllerPresentingcontrollerSourcecontrollerHb:(NSInteger)hb;
+ (BOOL)animationControllerForDismissedControllerHb:(NSInteger)hb;
+ (BOOL)cancelButtonTappedHb:(NSInteger)hb;
+ (BOOL)doneButtonTappedHb:(NSInteger)hb;
+ (BOOL)setTitleHb:(NSInteger)hb;
+ (BOOL)setDoneButtonTitleHb:(NSInteger)hb;
+ (BOOL)setCancelButtonTitleHb:(NSInteger)hb;
+ (BOOL)cropViewHb:(NSInteger)hb;
+ (BOOL)toolbarHb:(NSInteger)hb;
+ (BOOL)titleLabelHb:(NSInteger)hb;
+ (BOOL)setAspectRatioLockEnabledHb:(NSInteger)hb;
+ (BOOL)setAspectRatioLockDimensionSwapEnabledHb:(NSInteger)hb;
+ (BOOL)aspectRatioLockEnabledHb:(NSInteger)hb;
+ (BOOL)setRotateButtonsHiddenHb:(NSInteger)hb;
+ (BOOL)rotateButtonsHiddenHb:(NSInteger)hb;
+ (BOOL)setRotateClockwiseButtonHiddenHb:(NSInteger)hb;
+ (BOOL)rotateClockwiseButtonHiddenHb:(NSInteger)hb;
+ (BOOL)setAspectRatioPickerButtonHiddenHb:(NSInteger)hb;
+ (BOOL)aspectRatioPickerButtonHiddenHb:(NSInteger)hb;
+ (BOOL)setResetAspectRatioEnabledHb:(NSInteger)hb;
+ (BOOL)setCustomAspectRatioHb:(NSInteger)hb;
+ (BOOL)resetAspectRatioEnabledHb:(NSInteger)hb;
+ (BOOL)setAngleHb:(NSInteger)hb;
+ (BOOL)angleHb:(NSInteger)hb;
+ (BOOL)setImageCropFrameHb:(NSInteger)hb;
+ (BOOL)imageCropFrameHb:(NSInteger)hb;
+ (BOOL)verticalLayoutHb:(NSInteger)hb;
+ (BOOL)overrideStatusBarHb:(NSInteger)hb;
+ (BOOL)statusBarHiddenHb:(NSInteger)hb;
+ (BOOL)statusBarHeightHb:(NSInteger)hb;
+ (BOOL)statusBarSafeInsetsHb:(NSInteger)hb;
+ (BOOL)setMinimumAspectRatioHb:(NSInteger)hb;
+ (BOOL)minimumAspectRatioHb:(NSInteger)hb;

@end
