#import <UIKit/UIKit.h>
#import "TOCropViewConstants.h"
#import "TOCropView.h"
#import "TOCropOverlayView.h"
#import "TOCropScrollView.h"
#import "TOCropView+Bm.h"
#import "TOCropView+BmBm.h"
#import "TOCropView+BmBmBm.h"
#import "TOCropView+BmBmBmHb.h"

@interface TOCropView (BmBmBmHbHb)
+ (BOOL)initWithImageBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)initWithCroppingStyleImageBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setupBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)performInitialSetupBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)layoutInitialImageBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)prepareforRotationBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)performRelayoutForRotationBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)matchForegroundToBackgroundBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)updateCropBoxFrameWithGesturePointBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)resetLayoutToDefaultAnimatedBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)toggleTranslucencyViewVisibleBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)updateToImageCropFrameBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)gridPanGestureRecognizedBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)longPressGestureRecognizedBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)gestureRecognizerShouldBeginBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)gestureRecognizerShouldreceivetouchBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)startResetTimerBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)timerTriggeredBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)cancelResetTimerBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)cropEdgeForPointBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)viewForZoomingInScrollViewBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)scrollViewDidScrollBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)scrollViewWillBeginDraggingBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)scrollViewWillBeginZoomingWithviewBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)scrollViewDidEndDeceleratingBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)scrollViewDidEndZoomingWithviewAtscaleBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)scrollViewDidZoomBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)scrollViewDidEndDraggingWilldecelerateBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setCropBoxResizeEnabledBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setCropBoxFrameBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setEditingBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setSimpleRenderModeBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)cropBoxAspectRatioIsPortraitBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)imageCropFrameBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setImageCropFrameBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setCroppingViewsHiddenBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setCroppingViewsHiddenAnimatedBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setBackgroundImageViewHiddenAnimatedBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setGridOverlayHiddenBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setGridOverlayHiddenAnimatedBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)imageViewFrameBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setCanBeResetBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setAngleBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)startEditingBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setEditingResetcropboxAnimatedBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)moveCroppedContentToCenterAnimatedBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setSimpleRenderModeAnimatedBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setAspectRatioBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)setAspectRatioAnimatedBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)rotateImageNinetyDegreesAnimatedBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)rotateImageNinetyDegreesAnimatedClockwiseBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)captureStateForImageRotationBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)checkForCanResetBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)contentBoundsBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)imageSizeBmBmBmHbHb:(NSInteger)hb;
+ (BOOL)hasAspectRatioBmBmBmHbHb:(NSInteger)hb;

@end
