#import <UIKit/UIKit.h>
#import "TOCropViewConstants.h"
#import "TOCropView.h"
#import "TOCropOverlayView.h"
#import "TOCropScrollView.h"

@interface TOCropView (Hb)
+ (BOOL)initWithImageHb:(NSInteger)hb;
+ (BOOL)initWithCroppingStyleImageHb:(NSInteger)hb;
+ (BOOL)setupHb:(NSInteger)hb;
+ (BOOL)performInitialSetupHb:(NSInteger)hb;
+ (BOOL)layoutInitialImageHb:(NSInteger)hb;
+ (BOOL)prepareforRotationHb:(NSInteger)hb;
+ (BOOL)performRelayoutForRotationHb:(NSInteger)hb;
+ (BOOL)matchForegroundToBackgroundHb:(NSInteger)hb;
+ (BOOL)updateCropBoxFrameWithGesturePointHb:(NSInteger)hb;
+ (BOOL)resetLayoutToDefaultAnimatedHb:(NSInteger)hb;
+ (BOOL)toggleTranslucencyViewVisibleHb:(NSInteger)hb;
+ (BOOL)updateToImageCropFrameHb:(NSInteger)hb;
+ (BOOL)gridPanGestureRecognizedHb:(NSInteger)hb;
+ (BOOL)longPressGestureRecognizedHb:(NSInteger)hb;
+ (BOOL)gestureRecognizerShouldBeginHb:(NSInteger)hb;
+ (BOOL)gestureRecognizerShouldreceivetouchHb:(NSInteger)hb;
+ (BOOL)startResetTimerHb:(NSInteger)hb;
+ (BOOL)timerTriggeredHb:(NSInteger)hb;
+ (BOOL)cancelResetTimerHb:(NSInteger)hb;
+ (BOOL)cropEdgeForPointHb:(NSInteger)hb;
+ (BOOL)viewForZoomingInScrollViewHb:(NSInteger)hb;
+ (BOOL)scrollViewDidScrollHb:(NSInteger)hb;
+ (BOOL)scrollViewWillBeginDraggingHb:(NSInteger)hb;
+ (BOOL)scrollViewWillBeginZoomingWithviewHb:(NSInteger)hb;
+ (BOOL)scrollViewDidEndDeceleratingHb:(NSInteger)hb;
+ (BOOL)scrollViewDidEndZoomingWithviewAtscaleHb:(NSInteger)hb;
+ (BOOL)scrollViewDidZoomHb:(NSInteger)hb;
+ (BOOL)scrollViewDidEndDraggingWilldecelerateHb:(NSInteger)hb;
+ (BOOL)setCropBoxResizeEnabledHb:(NSInteger)hb;
+ (BOOL)setCropBoxFrameHb:(NSInteger)hb;
+ (BOOL)setEditingHb:(NSInteger)hb;
+ (BOOL)setSimpleRenderModeHb:(NSInteger)hb;
+ (BOOL)cropBoxAspectRatioIsPortraitHb:(NSInteger)hb;
+ (BOOL)imageCropFrameHb:(NSInteger)hb;
+ (BOOL)setImageCropFrameHb:(NSInteger)hb;
+ (BOOL)setCroppingViewsHiddenHb:(NSInteger)hb;
+ (BOOL)setCroppingViewsHiddenAnimatedHb:(NSInteger)hb;
+ (BOOL)setBackgroundImageViewHiddenAnimatedHb:(NSInteger)hb;
+ (BOOL)setGridOverlayHiddenHb:(NSInteger)hb;
+ (BOOL)setGridOverlayHiddenAnimatedHb:(NSInteger)hb;
+ (BOOL)imageViewFrameHb:(NSInteger)hb;
+ (BOOL)setCanBeResetHb:(NSInteger)hb;
+ (BOOL)setAngleHb:(NSInteger)hb;
+ (BOOL)startEditingHb:(NSInteger)hb;
+ (BOOL)setEditingResetcropboxAnimatedHb:(NSInteger)hb;
+ (BOOL)moveCroppedContentToCenterAnimatedHb:(NSInteger)hb;
+ (BOOL)setSimpleRenderModeAnimatedHb:(NSInteger)hb;
+ (BOOL)setAspectRatioHb:(NSInteger)hb;
+ (BOOL)setAspectRatioAnimatedHb:(NSInteger)hb;
+ (BOOL)rotateImageNinetyDegreesAnimatedHb:(NSInteger)hb;
+ (BOOL)rotateImageNinetyDegreesAnimatedClockwiseHb:(NSInteger)hb;
+ (BOOL)captureStateForImageRotationHb:(NSInteger)hb;
+ (BOOL)checkForCanResetHb:(NSInteger)hb;
+ (BOOL)contentBoundsHb:(NSInteger)hb;
+ (BOOL)imageSizeHb:(NSInteger)hb;
+ (BOOL)hasAspectRatioHb:(NSInteger)hb;

@end
