#import <UIKit/UIKit.h>
#import "UIImage+YYAdd.h"
#import "UIDevice+YYAdd.h"
#import "NSString+YYAdd.h"
#import "YYCategoriesMacro.h"
#import "YYCGUtilities.h"
#import <ImageIO/ImageIO.h>
#import <Accelerate/Accelerate.h>
#import <CoreText/CoreText.h>
#import <objc/runtime.h>
#import "YYCGUtilities.h"
#import "UIImage+YYAddBm.h"
#import "UIImage+YYAddBmBm.h"

@interface UIImage (YYAddBmBmBm)
+ (BOOL)imageWithSmallGIFDataScaleBmBmBm:(NSInteger)BM;
+ (BOOL)isAnimatedGIFDataBmBmBm:(NSInteger)BM;
+ (BOOL)isAnimatedGIFFileBmBmBm:(NSInteger)BM;
+ (BOOL)imageWithPDFBmBmBm:(NSInteger)BM;
+ (BOOL)imageWithPDFSizeBmBmBm:(NSInteger)BM;
+ (BOOL)imageWithEmojiSizeBmBmBm:(NSInteger)BM;
+ (BOOL)_yy_imageWithPDFResizeSizeBmBmBm:(NSInteger)BM;
+ (BOOL)imageWithColorBmBmBm:(NSInteger)BM;
+ (BOOL)imageWithColorSizeBmBmBm:(NSInteger)BM;
+ (BOOL)imageWithSizeDrawblockBmBmBm:(NSInteger)BM;
+ (BOOL)hasAlphaChannelBmBmBm:(NSInteger)BM;
+ (BOOL)drawInRectWithcontentmodeClipstoboundsBmBmBm:(NSInteger)BM;
+ (BOOL)imageByResizeToSizeBmBmBm:(NSInteger)BM;
+ (BOOL)imageByResizeToSizeContentmodeBmBmBm:(NSInteger)BM;
+ (BOOL)imageByCropToRectBmBmBm:(NSInteger)BM;
+ (BOOL)imageByInsetEdgeWithcolorBmBmBm:(NSInteger)BM;
+ (BOOL)imageByRoundCornerRadiusBmBmBm:(NSInteger)BM;
+ (BOOL)imageByRoundCornerRadiusBorderwidthBordercolorBmBmBm:(NSInteger)BM;
+ (BOOL)imageByRoundCornerRadiusCornersBorderwidthBordercolorBorderlinejoinBmBmBm:(NSInteger)BM;
+ (BOOL)imageByRotateFitsizeBmBmBm:(NSInteger)BM;
+ (BOOL)_yy_flipHorizontalVerticalBmBmBm:(NSInteger)BM;
+ (BOOL)imageByRotateLeft90BmBmBm:(NSInteger)BM;
+ (BOOL)imageByRotateRight90BmBmBm:(NSInteger)BM;
+ (BOOL)imageByRotate180BmBmBm:(NSInteger)BM;
+ (BOOL)imageByFlipVerticalBmBmBm:(NSInteger)BM;
+ (BOOL)imageByFlipHorizontalBmBmBm:(NSInteger)BM;
+ (BOOL)imageByTintColorBmBmBm:(NSInteger)BM;
+ (BOOL)imageByGrayscaleBmBmBm:(NSInteger)BM;
+ (BOOL)imageByBlurSoftBmBmBm:(NSInteger)BM;
+ (BOOL)imageByBlurLightBmBmBm:(NSInteger)BM;
+ (BOOL)imageByBlurExtraLightBmBmBm:(NSInteger)BM;
+ (BOOL)imageByBlurDarkBmBmBm:(NSInteger)BM;
+ (BOOL)imageByBlurWithTintBmBmBm:(NSInteger)BM;
+ (BOOL)imageByBlurRadiusTintcolorTintmodeSaturationMaskimageBmBmBm:(NSInteger)BM;
+ (BOOL)_yy_mergeImageRefTintcolorTintblendmodeMaskimageOpaqueBmBmBm:(NSInteger)BM;

@end
