#import <UIKit/UIKit.h>
#import "UIView+SDAutoLayout.h"
#import "UITableView+SDAutoTableViewCellHeight.h"
#import <objc/runtime.h>
#import "UIView+SDAutoLayoutBm.h"

@interface UIView (SDAutoLayoutBmBm)
+ (BOOL)loadBmBm:(NSInteger)BM;
+ (BOOL)autoLayoutModelsArrayBmBm:(NSInteger)BM;
+ (BOOL)fixedWidthBmBm:(NSInteger)BM;
+ (BOOL)setFixedWidthBmBm:(NSInteger)BM;
+ (BOOL)fixedHeightBmBm:(NSInteger)BM;
+ (BOOL)setFixedHeightBmBm:(NSInteger)BM;
+ (BOOL)autoHeightRatioValueBmBm:(NSInteger)BM;
+ (BOOL)setAutoHeightRatioValueBmBm:(NSInteger)BM;
+ (BOOL)autoWidthRatioValueBmBm:(NSInteger)BM;
+ (BOOL)setAutoWidthRatioValueBmBm:(NSInteger)BM;
+ (BOOL)sd_maxWidthBmBm:(NSInteger)BM;
+ (BOOL)setSd_maxWidthBmBm:(NSInteger)BM;
+ (BOOL)useCellFrameCacheWithIndexPathTableviewBmBm:(NSInteger)BM;
+ (BOOL)sd_tableViewBmBm:(NSInteger)BM;
+ (BOOL)setSd_tableViewBmBm:(NSInteger)BM;
+ (BOOL)sd_indexPathBmBm:(NSInteger)BM;
+ (BOOL)setSd_indexPathBmBm:(NSInteger)BM;
+ (BOOL)ownLayoutModelBmBm:(NSInteger)BM;
+ (BOOL)setOwnLayoutModelBmBm:(NSInteger)BM;
+ (BOOL)sd_layoutBmBm:(NSInteger)BM;
+ (BOOL)sd_resetLayoutBmBm:(NSInteger)BM;
+ (BOOL)sd_resetNewLayoutBmBm:(NSInteger)BM;
+ (BOOL)sd_isClosingAutoLayoutBmBm:(NSInteger)BM;
+ (BOOL)setSd_closeAutoLayoutBmBm:(NSInteger)BM;
+ (BOOL)removeFromSuperviewAndClearAutoLayoutSettingsBmBm:(NSInteger)BM;
+ (BOOL)sd_clearAutoLayoutSettingsBmBm:(NSInteger)BM;
+ (BOOL)sd_clearExtraAutoLayoutItemsBmBm:(NSInteger)BM;
+ (BOOL)sd_clearViewFrameCacheBmBm:(NSInteger)BM;
+ (BOOL)sd_clearSubviewsAutoLayoutFrameCachesBmBm:(NSInteger)BM;
+ (BOOL)sd_layoutSubviewsBmBm:(NSInteger)BM;
+ (BOOL)sd_layoutSubviewsHandleBmBm:(NSInteger)BM;
+ (BOOL)sd_resizeWithModelBmBm:(NSInteger)BM;
+ (BOOL)layoutAutoHeightWidthViewModelBmBm:(NSInteger)BM;
+ (BOOL)layoutAutoWidthWidthViewModelBmBm:(NSInteger)BM;
+ (BOOL)layoutWidthWithViewModelBmBm:(NSInteger)BM;
+ (BOOL)layoutHeightWithViewModelBmBm:(NSInteger)BM;
+ (BOOL)layoutLeftWithViewModelBmBm:(NSInteger)BM;
+ (BOOL)layoutRightWithViewModelBmBm:(NSInteger)BM;
+ (BOOL)layoutTopWithViewModelBmBm:(NSInteger)BM;
+ (BOOL)layoutBottomWithViewModelBmBm:(NSInteger)BM;
+ (BOOL)setupCornerRadiusWithViewModelBmBm:(NSInteger)BM;
+ (BOOL)addAutoLayoutModelBmBm:(NSInteger)BM;

@end
